/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2025 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

--
-- Populates the countries table with ISO 3166-1 country data
--

SET search_path TO ores;

-- ISO 3166-1 Countries
-- Columns: alpha2_code, version, alpha3_code, numeric_code, name, official_name, modified_by, change_reason_code, change_commentary
INSERT INTO countries (alpha2_code, version, alpha3_code, numeric_code, name, official_name, modified_by, change_reason_code, change_commentary)
VALUES
-- A
('AD', 0, 'AND', '020', 'Andorra', 'Principality of Andorra', 'system', 'system.new_record', 'System seed data'),
('AE', 0, 'ARE', '784', 'United Arab Emirates', 'United Arab Emirates', 'system', 'system.new_record', 'System seed data'),
('AF', 0, 'AFG', '004', 'Afghanistan', 'Islamic Republic of Afghanistan', 'system', 'system.new_record', 'System seed data'),
('AG', 0, 'ATG', '028', 'Antigua and Barbuda', 'Antigua and Barbuda', 'system', 'system.new_record', 'System seed data'),
('AI', 0, 'AIA', '660', 'Anguilla', 'Anguilla', 'system', 'system.new_record', 'System seed data'),
('AL', 0, 'ALB', '008', 'Albania', 'Republic of Albania', 'system', 'system.new_record', 'System seed data'),
('AM', 0, 'ARM', '051', 'Armenia', 'Republic of Armenia', 'system', 'system.new_record', 'System seed data'),
('AO', 0, 'AGO', '024', 'Angola', 'Republic of Angola', 'system', 'system.new_record', 'System seed data'),
('AQ', 0, 'ATA', '010', 'Antarctica', 'Antarctica', 'system', 'system.new_record', 'System seed data'),
('AR', 0, 'ARG', '032', 'Argentina', 'Argentine Republic', 'system', 'system.new_record', 'System seed data'),
('AS', 0, 'ASM', '016', 'American Samoa', 'American Samoa', 'system', 'system.new_record', 'System seed data'),
('AT', 0, 'AUT', '040', 'Austria', 'Republic of Austria', 'system', 'system.new_record', 'System seed data'),
('AU', 0, 'AUS', '036', 'Australia', 'Commonwealth of Australia', 'system', 'system.new_record', 'System seed data'),
('AW', 0, 'ABW', '533', 'Aruba', 'Aruba', 'system', 'system.new_record', 'System seed data'),
('AX', 0, 'ALA', '248', 'Åland Islands', 'Åland Islands', 'system', 'system.new_record', 'System seed data'),
('AZ', 0, 'AZE', '031', 'Azerbaijan', 'Republic of Azerbaijan', 'system', 'system.new_record', 'System seed data'),
-- B
('BA', 0, 'BIH', '070', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'system', 'system.new_record', 'System seed data'),
('BB', 0, 'BRB', '052', 'Barbados', 'Barbados', 'system', 'system.new_record', 'System seed data'),
('BD', 0, 'BGD', '050', 'Bangladesh', 'People''s Republic of Bangladesh', 'system', 'system.new_record', 'System seed data'),
('BE', 0, 'BEL', '056', 'Belgium', 'Kingdom of Belgium', 'system', 'system.new_record', 'System seed data'),
('BF', 0, 'BFA', '854', 'Burkina Faso', 'Burkina Faso', 'system', 'system.new_record', 'System seed data'),
('BG', 0, 'BGR', '100', 'Bulgaria', 'Republic of Bulgaria', 'system', 'system.new_record', 'System seed data'),
('BH', 0, 'BHR', '048', 'Bahrain', 'Kingdom of Bahrain', 'system', 'system.new_record', 'System seed data'),
('BI', 0, 'BDI', '108', 'Burundi', 'Republic of Burundi', 'system', 'system.new_record', 'System seed data'),
('BJ', 0, 'BEN', '204', 'Benin', 'Republic of Benin', 'system', 'system.new_record', 'System seed data'),
('BL', 0, 'BLM', '652', 'Saint Barthélemy', 'Saint Barthélemy', 'system', 'system.new_record', 'System seed data'),
('BM', 0, 'BMU', '060', 'Bermuda', 'Bermuda', 'system', 'system.new_record', 'System seed data'),
('BN', 0, 'BRN', '096', 'Brunei', 'Brunei Darussalam', 'system', 'system.new_record', 'System seed data'),
('BO', 0, 'BOL', '068', 'Bolivia', 'Plurinational State of Bolivia', 'system', 'system.new_record', 'System seed data'),
('BQ', 0, 'BES', '535', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba', 'system', 'system.new_record', 'System seed data'),
('BR', 0, 'BRA', '076', 'Brazil', 'Federative Republic of Brazil', 'system', 'system.new_record', 'System seed data'),
('BS', 0, 'BHS', '044', 'Bahamas', 'Commonwealth of The Bahamas', 'system', 'system.new_record', 'System seed data'),
('BT', 0, 'BTN', '064', 'Bhutan', 'Kingdom of Bhutan', 'system', 'system.new_record', 'System seed data'),
('BV', 0, 'BVT', '074', 'Bouvet Island', 'Bouvet Island', 'system', 'system.new_record', 'System seed data'),
('BW', 0, 'BWA', '072', 'Botswana', 'Republic of Botswana', 'system', 'system.new_record', 'System seed data'),
('BY', 0, 'BLR', '112', 'Belarus', 'Republic of Belarus', 'system', 'system.new_record', 'System seed data'),
('BZ', 0, 'BLZ', '084', 'Belize', 'Belize', 'system', 'system.new_record', 'System seed data'),
-- C
('CA', 0, 'CAN', '124', 'Canada', 'Canada', 'system', 'system.new_record', 'System seed data'),
('CC', 0, 'CCK', '166', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'system', 'system.new_record', 'System seed data'),
('CD', 0, 'COD', '180', 'DR Congo', 'Democratic Republic of the Congo', 'system', 'system.new_record', 'System seed data'),
('CF', 0, 'CAF', '140', 'Central African Republic', 'Central African Republic', 'system', 'system.new_record', 'System seed data'),
('CG', 0, 'COG', '178', 'Congo', 'Republic of the Congo', 'system', 'system.new_record', 'System seed data'),
('CH', 0, 'CHE', '756', 'Switzerland', 'Swiss Confederation', 'system', 'system.new_record', 'System seed data'),
('CI', 0, 'CIV', '384', 'Côte d''Ivoire', 'Republic of Côte d''Ivoire', 'system', 'system.new_record', 'System seed data'),
('CK', 0, 'COK', '184', 'Cook Islands', 'Cook Islands', 'system', 'system.new_record', 'System seed data'),
('CL', 0, 'CHL', '152', 'Chile', 'Republic of Chile', 'system', 'system.new_record', 'System seed data'),
('CM', 0, 'CMR', '120', 'Cameroon', 'Republic of Cameroon', 'system', 'system.new_record', 'System seed data'),
('CN', 0, 'CHN', '156', 'China', 'People''s Republic of China', 'system', 'system.new_record', 'System seed data'),
('CO', 0, 'COL', '170', 'Colombia', 'Republic of Colombia', 'system', 'system.new_record', 'System seed data'),
('CR', 0, 'CRI', '188', 'Costa Rica', 'Republic of Costa Rica', 'system', 'system.new_record', 'System seed data'),
('CU', 0, 'CUB', '192', 'Cuba', 'Republic of Cuba', 'system', 'system.new_record', 'System seed data'),
('CV', 0, 'CPV', '132', 'Cape Verde', 'Republic of Cabo Verde', 'system', 'system.new_record', 'System seed data'),
('CW', 0, 'CUW', '531', 'Curaçao', 'Curaçao', 'system', 'system.new_record', 'System seed data'),
('CX', 0, 'CXR', '162', 'Christmas Island', 'Christmas Island', 'system', 'system.new_record', 'System seed data'),
('CY', 0, 'CYP', '196', 'Cyprus', 'Republic of Cyprus', 'system', 'system.new_record', 'System seed data'),
('CZ', 0, 'CZE', '203', 'Czechia', 'Czech Republic', 'system', 'system.new_record', 'System seed data'),
-- D
('DE', 0, 'DEU', '276', 'Germany', 'Federal Republic of Germany', 'system', 'system.new_record', 'System seed data'),
('DJ', 0, 'DJI', '262', 'Djibouti', 'Republic of Djibouti', 'system', 'system.new_record', 'System seed data'),
('DK', 0, 'DNK', '208', 'Denmark', 'Kingdom of Denmark', 'system', 'system.new_record', 'System seed data'),
('DM', 0, 'DMA', '212', 'Dominica', 'Commonwealth of Dominica', 'system', 'system.new_record', 'System seed data'),
('DO', 0, 'DOM', '214', 'Dominican Republic', 'Dominican Republic', 'system', 'system.new_record', 'System seed data'),
('DZ', 0, 'DZA', '012', 'Algeria', 'People''s Democratic Republic of Algeria', 'system', 'system.new_record', 'System seed data'),
-- E
('EC', 0, 'ECU', '218', 'Ecuador', 'Republic of Ecuador', 'system', 'system.new_record', 'System seed data'),
('EE', 0, 'EST', '233', 'Estonia', 'Republic of Estonia', 'system', 'system.new_record', 'System seed data'),
('EG', 0, 'EGY', '818', 'Egypt', 'Arab Republic of Egypt', 'system', 'system.new_record', 'System seed data'),
('EH', 0, 'ESH', '732', 'Western Sahara', 'Western Sahara', 'system', 'system.new_record', 'System seed data'),
('ER', 0, 'ERI', '232', 'Eritrea', 'State of Eritrea', 'system', 'system.new_record', 'System seed data'),
('ES', 0, 'ESP', '724', 'Spain', 'Kingdom of Spain', 'system', 'system.new_record', 'System seed data'),
('ET', 0, 'ETH', '231', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', 'system', 'system.new_record', 'System seed data'),
-- F
('FI', 0, 'FIN', '246', 'Finland', 'Republic of Finland', 'system', 'system.new_record', 'System seed data'),
('FJ', 0, 'FJI', '242', 'Fiji', 'Republic of Fiji', 'system', 'system.new_record', 'System seed data'),
('FK', 0, 'FLK', '238', 'Falkland Islands', 'Falkland Islands', 'system', 'system.new_record', 'System seed data'),
('FM', 0, 'FSM', '583', 'Micronesia', 'Federated States of Micronesia', 'system', 'system.new_record', 'System seed data'),
('FO', 0, 'FRO', '234', 'Faroe Islands', 'Faroe Islands', 'system', 'system.new_record', 'System seed data'),
('FR', 0, 'FRA', '250', 'France', 'French Republic', 'system', 'system.new_record', 'System seed data'),
-- G
('GA', 0, 'GAB', '266', 'Gabon', 'Gabonese Republic', 'system', 'system.new_record', 'System seed data'),
('GB', 0, 'GBR', '826', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', 'system', 'system.new_record', 'System seed data'),
('GD', 0, 'GRD', '308', 'Grenada', 'Grenada', 'system', 'system.new_record', 'System seed data'),
('GE', 0, 'GEO', '268', 'Georgia', 'Georgia', 'system', 'system.new_record', 'System seed data'),
('GF', 0, 'GUF', '254', 'French Guiana', 'French Guiana', 'system', 'system.new_record', 'System seed data'),
('GG', 0, 'GGY', '831', 'Guernsey', 'Bailiwick of Guernsey', 'system', 'system.new_record', 'System seed data'),
('GH', 0, 'GHA', '288', 'Ghana', 'Republic of Ghana', 'system', 'system.new_record', 'System seed data'),
('GI', 0, 'GIB', '292', 'Gibraltar', 'Gibraltar', 'system', 'system.new_record', 'System seed data'),
('GL', 0, 'GRL', '304', 'Greenland', 'Greenland', 'system', 'system.new_record', 'System seed data'),
('GM', 0, 'GMB', '270', 'Gambia', 'Republic of The Gambia', 'system', 'system.new_record', 'System seed data'),
('GN', 0, 'GIN', '324', 'Guinea', 'Republic of Guinea', 'system', 'system.new_record', 'System seed data'),
('GP', 0, 'GLP', '312', 'Guadeloupe', 'Guadeloupe', 'system', 'system.new_record', 'System seed data'),
('GQ', 0, 'GNQ', '226', 'Equatorial Guinea', 'Republic of Equatorial Guinea', 'system', 'system.new_record', 'System seed data'),
('GR', 0, 'GRC', '300', 'Greece', 'Hellenic Republic', 'system', 'system.new_record', 'System seed data'),
('GS', 0, 'SGS', '239', 'South Georgia', 'South Georgia and the South Sandwich Islands', 'system', 'system.new_record', 'System seed data'),
('GT', 0, 'GTM', '320', 'Guatemala', 'Republic of Guatemala', 'system', 'system.new_record', 'System seed data'),
('GU', 0, 'GUM', '316', 'Guam', 'Guam', 'system', 'system.new_record', 'System seed data'),
('GW', 0, 'GNB', '624', 'Guinea-Bissau', 'Republic of Guinea-Bissau', 'system', 'system.new_record', 'System seed data'),
('GY', 0, 'GUY', '328', 'Guyana', 'Co-operative Republic of Guyana', 'system', 'system.new_record', 'System seed data'),
-- H
('HK', 0, 'HKG', '344', 'Hong Kong', 'Hong Kong Special Administrative Region of the People''s Republic of China', 'system', 'system.new_record', 'System seed data'),
('HM', 0, 'HMD', '334', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'system', 'system.new_record', 'System seed data'),
('HN', 0, 'HND', '340', 'Honduras', 'Republic of Honduras', 'system', 'system.new_record', 'System seed data'),
('HR', 0, 'HRV', '191', 'Croatia', 'Republic of Croatia', 'system', 'system.new_record', 'System seed data'),
('HT', 0, 'HTI', '332', 'Haiti', 'Republic of Haiti', 'system', 'system.new_record', 'System seed data'),
('HU', 0, 'HUN', '348', 'Hungary', 'Hungary', 'system', 'system.new_record', 'System seed data'),
-- I
('ID', 0, 'IDN', '360', 'Indonesia', 'Republic of Indonesia', 'system', 'system.new_record', 'System seed data'),
('IE', 0, 'IRL', '372', 'Ireland', 'Ireland', 'system', 'system.new_record', 'System seed data'),
('IL', 0, 'ISR', '376', 'Israel', 'State of Israel', 'system', 'system.new_record', 'System seed data'),
('IM', 0, 'IMN', '833', 'Isle of Man', 'Isle of Man', 'system', 'system.new_record', 'System seed data'),
('IN', 0, 'IND', '356', 'India', 'Republic of India', 'system', 'system.new_record', 'System seed data'),
('IO', 0, 'IOT', '086', 'British Indian Ocean Territory', 'British Indian Ocean Territory', 'system', 'system.new_record', 'System seed data'),
('IQ', 0, 'IRQ', '368', 'Iraq', 'Republic of Iraq', 'system', 'system.new_record', 'System seed data'),
('IR', 0, 'IRN', '364', 'Iran', 'Islamic Republic of Iran', 'system', 'system.new_record', 'System seed data'),
('IS', 0, 'ISL', '352', 'Iceland', 'Iceland', 'system', 'system.new_record', 'System seed data'),
('IT', 0, 'ITA', '380', 'Italy', 'Italian Republic', 'system', 'system.new_record', 'System seed data'),
-- J
('JE', 0, 'JEY', '832', 'Jersey', 'Bailiwick of Jersey', 'system', 'system.new_record', 'System seed data'),
('JM', 0, 'JAM', '388', 'Jamaica', 'Jamaica', 'system', 'system.new_record', 'System seed data'),
('JO', 0, 'JOR', '400', 'Jordan', 'Hashemite Kingdom of Jordan', 'system', 'system.new_record', 'System seed data'),
('JP', 0, 'JPN', '392', 'Japan', 'Japan', 'system', 'system.new_record', 'System seed data'),
-- K
('KE', 0, 'KEN', '404', 'Kenya', 'Republic of Kenya', 'system', 'system.new_record', 'System seed data'),
('KG', 0, 'KGZ', '417', 'Kyrgyzstan', 'Kyrgyz Republic', 'system', 'system.new_record', 'System seed data'),
('KH', 0, 'KHM', '116', 'Cambodia', 'Kingdom of Cambodia', 'system', 'system.new_record', 'System seed data'),
('KI', 0, 'KIR', '296', 'Kiribati', 'Republic of Kiribati', 'system', 'system.new_record', 'System seed data'),
('KM', 0, 'COM', '174', 'Comoros', 'Union of the Comoros', 'system', 'system.new_record', 'System seed data'),
('KN', 0, 'KNA', '659', 'Saint Kitts and Nevis', 'Federation of Saint Christopher and Nevis', 'system', 'system.new_record', 'System seed data'),
('KP', 0, 'PRK', '408', 'North Korea', 'Democratic People''s Republic of Korea', 'system', 'system.new_record', 'System seed data'),
('KR', 0, 'KOR', '410', 'South Korea', 'Republic of Korea', 'system', 'system.new_record', 'System seed data'),
('KW', 0, 'KWT', '414', 'Kuwait', 'State of Kuwait', 'system', 'system.new_record', 'System seed data'),
('KY', 0, 'CYM', '136', 'Cayman Islands', 'Cayman Islands', 'system', 'system.new_record', 'System seed data'),
('KZ', 0, 'KAZ', '398', 'Kazakhstan', 'Republic of Kazakhstan', 'system', 'system.new_record', 'System seed data'),
-- L
('LA', 0, 'LAO', '418', 'Laos', 'Lao People''s Democratic Republic', 'system', 'system.new_record', 'System seed data'),
('LB', 0, 'LBN', '422', 'Lebanon', 'Lebanese Republic', 'system', 'system.new_record', 'System seed data'),
('LC', 0, 'LCA', '662', 'Saint Lucia', 'Saint Lucia', 'system', 'system.new_record', 'System seed data'),
('LI', 0, 'LIE', '438', 'Liechtenstein', 'Principality of Liechtenstein', 'system', 'system.new_record', 'System seed data'),
('LK', 0, 'LKA', '144', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'system', 'system.new_record', 'System seed data'),
('LR', 0, 'LBR', '430', 'Liberia', 'Republic of Liberia', 'system', 'system.new_record', 'System seed data'),
('LS', 0, 'LSO', '426', 'Lesotho', 'Kingdom of Lesotho', 'system', 'system.new_record', 'System seed data'),
('LT', 0, 'LTU', '440', 'Lithuania', 'Republic of Lithuania', 'system', 'system.new_record', 'System seed data'),
('LU', 0, 'LUX', '442', 'Luxembourg', 'Grand Duchy of Luxembourg', 'system', 'system.new_record', 'System seed data'),
('LV', 0, 'LVA', '428', 'Latvia', 'Republic of Latvia', 'system', 'system.new_record', 'System seed data'),
('LY', 0, 'LBY', '434', 'Libya', 'State of Libya', 'system', 'system.new_record', 'System seed data'),
-- M
('MA', 0, 'MAR', '504', 'Morocco', 'Kingdom of Morocco', 'system', 'system.new_record', 'System seed data'),
('MC', 0, 'MCO', '492', 'Monaco', 'Principality of Monaco', 'system', 'system.new_record', 'System seed data'),
('MD', 0, 'MDA', '498', 'Moldova', 'Republic of Moldova', 'system', 'system.new_record', 'System seed data'),
('ME', 0, 'MNE', '499', 'Montenegro', 'Montenegro', 'system', 'system.new_record', 'System seed data'),
('MF', 0, 'MAF', '663', 'Saint Martin', 'Saint Martin (French part)', 'system', 'system.new_record', 'System seed data'),
('MG', 0, 'MDG', '450', 'Madagascar', 'Republic of Madagascar', 'system', 'system.new_record', 'System seed data'),
('MH', 0, 'MHL', '584', 'Marshall Islands', 'Republic of the Marshall Islands', 'system', 'system.new_record', 'System seed data'),
('MK', 0, 'MKD', '807', 'North Macedonia', 'Republic of North Macedonia', 'system', 'system.new_record', 'System seed data'),
('ML', 0, 'MLI', '466', 'Mali', 'Republic of Mali', 'system', 'system.new_record', 'System seed data'),
('MM', 0, 'MMR', '104', 'Myanmar', 'Republic of the Union of Myanmar', 'system', 'system.new_record', 'System seed data'),
('MN', 0, 'MNG', '496', 'Mongolia', 'Mongolia', 'system', 'system.new_record', 'System seed data'),
('MO', 0, 'MAC', '446', 'Macau', 'Macao Special Administrative Region of the People''s Republic of China', 'system', 'system.new_record', 'System seed data'),
('MP', 0, 'MNP', '580', 'Northern Mariana Islands', 'Commonwealth of the Northern Mariana Islands', 'system', 'system.new_record', 'System seed data'),
('MQ', 0, 'MTQ', '474', 'Martinique', 'Martinique', 'system', 'system.new_record', 'System seed data'),
('MR', 0, 'MRT', '478', 'Mauritania', 'Islamic Republic of Mauritania', 'system', 'system.new_record', 'System seed data'),
('MS', 0, 'MSR', '500', 'Montserrat', 'Montserrat', 'system', 'system.new_record', 'System seed data'),
('MT', 0, 'MLT', '470', 'Malta', 'Republic of Malta', 'system', 'system.new_record', 'System seed data'),
('MU', 0, 'MUS', '480', 'Mauritius', 'Republic of Mauritius', 'system', 'system.new_record', 'System seed data'),
('MV', 0, 'MDV', '462', 'Maldives', 'Republic of Maldives', 'system', 'system.new_record', 'System seed data'),
('MW', 0, 'MWI', '454', 'Malawi', 'Republic of Malawi', 'system', 'system.new_record', 'System seed data'),
('MX', 0, 'MEX', '484', 'Mexico', 'United Mexican States', 'system', 'system.new_record', 'System seed data'),
('MY', 0, 'MYS', '458', 'Malaysia', 'Malaysia', 'system', 'system.new_record', 'System seed data'),
('MZ', 0, 'MOZ', '508', 'Mozambique', 'Republic of Mozambique', 'system', 'system.new_record', 'System seed data'),
-- N
('NA', 0, 'NAM', '516', 'Namibia', 'Republic of Namibia', 'system', 'system.new_record', 'System seed data'),
('NC', 0, 'NCL', '540', 'New Caledonia', 'New Caledonia', 'system', 'system.new_record', 'System seed data'),
('NE', 0, 'NER', '562', 'Niger', 'Republic of the Niger', 'system', 'system.new_record', 'System seed data'),
('NF', 0, 'NFK', '574', 'Norfolk Island', 'Norfolk Island', 'system', 'system.new_record', 'System seed data'),
('NG', 0, 'NGA', '566', 'Nigeria', 'Federal Republic of Nigeria', 'system', 'system.new_record', 'System seed data'),
('NI', 0, 'NIC', '558', 'Nicaragua', 'Republic of Nicaragua', 'system', 'system.new_record', 'System seed data'),
('NL', 0, 'NLD', '528', 'Netherlands', 'Kingdom of the Netherlands', 'system', 'system.new_record', 'System seed data'),
('NO', 0, 'NOR', '578', 'Norway', 'Kingdom of Norway', 'system', 'system.new_record', 'System seed data'),
('NP', 0, 'NPL', '524', 'Nepal', 'Federal Democratic Republic of Nepal', 'system', 'system.new_record', 'System seed data'),
('NR', 0, 'NRU', '520', 'Nauru', 'Republic of Nauru', 'system', 'system.new_record', 'System seed data'),
('NU', 0, 'NIU', '570', 'Niue', 'Niue', 'system', 'system.new_record', 'System seed data'),
('NZ', 0, 'NZL', '554', 'New Zealand', 'New Zealand', 'system', 'system.new_record', 'System seed data'),
-- O
('OM', 0, 'OMN', '512', 'Oman', 'Sultanate of Oman', 'system', 'system.new_record', 'System seed data'),
-- P
('PA', 0, 'PAN', '591', 'Panama', 'Republic of Panama', 'system', 'system.new_record', 'System seed data'),
('PE', 0, 'PER', '604', 'Peru', 'Republic of Peru', 'system', 'system.new_record', 'System seed data'),
('PF', 0, 'PYF', '258', 'French Polynesia', 'French Polynesia', 'system', 'system.new_record', 'System seed data'),
('PG', 0, 'PNG', '598', 'Papua New Guinea', 'Independent State of Papua New Guinea', 'system', 'system.new_record', 'System seed data'),
('PH', 0, 'PHL', '608', 'Philippines', 'Republic of the Philippines', 'system', 'system.new_record', 'System seed data'),
('PK', 0, 'PAK', '586', 'Pakistan', 'Islamic Republic of Pakistan', 'system', 'system.new_record', 'System seed data'),
('PL', 0, 'POL', '616', 'Poland', 'Republic of Poland', 'system', 'system.new_record', 'System seed data'),
('PM', 0, 'SPM', '666', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'system', 'system.new_record', 'System seed data'),
('PN', 0, 'PCN', '612', 'Pitcairn Islands', 'Pitcairn Islands', 'system', 'system.new_record', 'System seed data'),
('PR', 0, 'PRI', '630', 'Puerto Rico', 'Commonwealth of Puerto Rico', 'system', 'system.new_record', 'System seed data'),
('PS', 0, 'PSE', '275', 'Palestine', 'State of Palestine', 'system', 'system.new_record', 'System seed data'),
('PT', 0, 'PRT', '620', 'Portugal', 'Portuguese Republic', 'system', 'system.new_record', 'System seed data'),
('PW', 0, 'PLW', '585', 'Palau', 'Republic of Palau', 'system', 'system.new_record', 'System seed data'),
('PY', 0, 'PRY', '600', 'Paraguay', 'Republic of Paraguay', 'system', 'system.new_record', 'System seed data'),
-- Q
('QA', 0, 'QAT', '634', 'Qatar', 'State of Qatar', 'system', 'system.new_record', 'System seed data'),
-- R
('RE', 0, 'REU', '638', 'Réunion', 'Réunion', 'system', 'system.new_record', 'System seed data'),
('RO', 0, 'ROU', '642', 'Romania', 'Romania', 'system', 'system.new_record', 'System seed data'),
('RS', 0, 'SRB', '688', 'Serbia', 'Republic of Serbia', 'system', 'system.new_record', 'System seed data'),
('RU', 0, 'RUS', '643', 'Russia', 'Russian Federation', 'system', 'system.new_record', 'System seed data'),
('RW', 0, 'RWA', '646', 'Rwanda', 'Republic of Rwanda', 'system', 'system.new_record', 'System seed data'),
-- S
('SA', 0, 'SAU', '682', 'Saudi Arabia', 'Kingdom of Saudi Arabia', 'system', 'system.new_record', 'System seed data'),
('SB', 0, 'SLB', '090', 'Solomon Islands', 'Solomon Islands', 'system', 'system.new_record', 'System seed data'),
('SC', 0, 'SYC', '690', 'Seychelles', 'Republic of Seychelles', 'system', 'system.new_record', 'System seed data'),
('SD', 0, 'SDN', '729', 'Sudan', 'Republic of the Sudan', 'system', 'system.new_record', 'System seed data'),
('SE', 0, 'SWE', '752', 'Sweden', 'Kingdom of Sweden', 'system', 'system.new_record', 'System seed data'),
('SG', 0, 'SGP', '702', 'Singapore', 'Republic of Singapore', 'system', 'system.new_record', 'System seed data'),
('SH', 0, 'SHN', '654', 'Saint Helena', 'Saint Helena, Ascension and Tristan da Cunha', 'system', 'system.new_record', 'System seed data'),
('SI', 0, 'SVN', '705', 'Slovenia', 'Republic of Slovenia', 'system', 'system.new_record', 'System seed data'),
('SJ', 0, 'SJM', '744', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen', 'system', 'system.new_record', 'System seed data'),
('SK', 0, 'SVK', '703', 'Slovakia', 'Slovak Republic', 'system', 'system.new_record', 'System seed data'),
('SL', 0, 'SLE', '694', 'Sierra Leone', 'Republic of Sierra Leone', 'system', 'system.new_record', 'System seed data'),
('SM', 0, 'SMR', '674', 'San Marino', 'Republic of San Marino', 'system', 'system.new_record', 'System seed data'),
('SN', 0, 'SEN', '686', 'Senegal', 'Republic of Senegal', 'system', 'system.new_record', 'System seed data'),
('SO', 0, 'SOM', '706', 'Somalia', 'Federal Republic of Somalia', 'system', 'system.new_record', 'System seed data'),
('SR', 0, 'SUR', '740', 'Suriname', 'Republic of Suriname', 'system', 'system.new_record', 'System seed data'),
('SS', 0, 'SSD', '728', 'South Sudan', 'Republic of South Sudan', 'system', 'system.new_record', 'System seed data'),
('ST', 0, 'STP', '678', 'São Tomé and Príncipe', 'Democratic Republic of São Tomé and Príncipe', 'system', 'system.new_record', 'System seed data'),
('SV', 0, 'SLV', '222', 'El Salvador', 'Republic of El Salvador', 'system', 'system.new_record', 'System seed data'),
('SX', 0, 'SXM', '534', 'Sint Maarten', 'Sint Maarten (Dutch part)', 'system', 'system.new_record', 'System seed data'),
('SY', 0, 'SYR', '760', 'Syria', 'Syrian Arab Republic', 'system', 'system.new_record', 'System seed data'),
('SZ', 0, 'SWZ', '748', 'Eswatini', 'Kingdom of Eswatini', 'system', 'system.new_record', 'System seed data'),
-- T
('TC', 0, 'TCA', '796', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'system', 'system.new_record', 'System seed data'),
('TD', 0, 'TCD', '148', 'Chad', 'Republic of Chad', 'system', 'system.new_record', 'System seed data'),
('TF', 0, 'ATF', '260', 'French Southern Territories', 'French Southern and Antarctic Lands', 'system', 'system.new_record', 'System seed data'),
('TG', 0, 'TGO', '768', 'Togo', 'Togolese Republic', 'system', 'system.new_record', 'System seed data'),
('TH', 0, 'THA', '764', 'Thailand', 'Kingdom of Thailand', 'system', 'system.new_record', 'System seed data'),
('TJ', 0, 'TJK', '762', 'Tajikistan', 'Republic of Tajikistan', 'system', 'system.new_record', 'System seed data'),
('TK', 0, 'TKL', '772', 'Tokelau', 'Tokelau', 'system', 'system.new_record', 'System seed data'),
('TL', 0, 'TLS', '626', 'Timor-Leste', 'Democratic Republic of Timor-Leste', 'system', 'system.new_record', 'System seed data'),
('TM', 0, 'TKM', '795', 'Turkmenistan', 'Turkmenistan', 'system', 'system.new_record', 'System seed data'),
('TN', 0, 'TUN', '788', 'Tunisia', 'Republic of Tunisia', 'system', 'system.new_record', 'System seed data'),
('TO', 0, 'TON', '776', 'Tonga', 'Kingdom of Tonga', 'system', 'system.new_record', 'System seed data'),
('TR', 0, 'TUR', '792', 'Turkey', 'Republic of Turkey', 'system', 'system.new_record', 'System seed data'),
('TT', 0, 'TTO', '780', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'system', 'system.new_record', 'System seed data'),
('TV', 0, 'TUV', '798', 'Tuvalu', 'Tuvalu', 'system', 'system.new_record', 'System seed data'),
('TW', 0, 'TWN', '158', 'Taiwan', 'Republic of China (Taiwan)', 'system', 'system.new_record', 'System seed data'),
('TZ', 0, 'TZA', '834', 'Tanzania', 'United Republic of Tanzania', 'system', 'system.new_record', 'System seed data'),
-- U
('UA', 0, 'UKR', '804', 'Ukraine', 'Ukraine', 'system', 'system.new_record', 'System seed data'),
('UG', 0, 'UGA', '800', 'Uganda', 'Republic of Uganda', 'system', 'system.new_record', 'System seed data'),
('UM', 0, 'UMI', '581', 'U.S. Minor Outlying Islands', 'United States Minor Outlying Islands', 'system', 'system.new_record', 'System seed data'),
('US', 0, 'USA', '840', 'United States', 'United States of America', 'system', 'system.new_record', 'System seed data'),
('UY', 0, 'URY', '858', 'Uruguay', 'Oriental Republic of Uruguay', 'system', 'system.new_record', 'System seed data'),
('UZ', 0, 'UZB', '860', 'Uzbekistan', 'Republic of Uzbekistan', 'system', 'system.new_record', 'System seed data'),
-- V
('VA', 0, 'VAT', '336', 'Vatican City', 'Vatican City State', 'system', 'system.new_record', 'System seed data'),
('VC', 0, 'VCT', '670', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'system', 'system.new_record', 'System seed data'),
('VE', 0, 'VEN', '862', 'Venezuela', 'Bolivarian Republic of Venezuela', 'system', 'system.new_record', 'System seed data'),
('VG', 0, 'VGB', '092', 'British Virgin Islands', 'Virgin Islands (British)', 'system', 'system.new_record', 'System seed data'),
('VI', 0, 'VIR', '850', 'U.S. Virgin Islands', 'Virgin Islands (U.S.)', 'system', 'system.new_record', 'System seed data'),
('VN', 0, 'VNM', '704', 'Vietnam', 'Socialist Republic of Vietnam', 'system', 'system.new_record', 'System seed data'),
('VU', 0, 'VUT', '548', 'Vanuatu', 'Republic of Vanuatu', 'system', 'system.new_record', 'System seed data'),
-- W
('WF', 0, 'WLF', '876', 'Wallis and Futuna', 'Wallis and Futuna', 'system', 'system.new_record', 'System seed data'),
('WS', 0, 'WSM', '882', 'Samoa', 'Independent State of Samoa', 'system', 'system.new_record', 'System seed data'),
-- X (no standard ISO 3166-1 countries)
-- Y
('YE', 0, 'YEM', '887', 'Yemen', 'Republic of Yemen', 'system', 'system.new_record', 'System seed data'),
('YT', 0, 'MYT', '175', 'Mayotte', 'Department of Mayotte', 'system', 'system.new_record', 'System seed data'),
-- Z
('ZA', 0, 'ZAF', '710', 'South Africa', 'Republic of South Africa', 'system', 'system.new_record', 'System seed data'),
('ZM', 0, 'ZMB', '894', 'Zambia', 'Republic of Zambia', 'system', 'system.new_record', 'System seed data'),
('ZW', 0, 'ZWE', '716', 'Zimbabwe', 'Republic of Zimbabwe', 'system', 'system.new_record', 'System seed data');
