/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2025 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

--
-- Populates the countries table with ISO 3166-1 country data
--

SET search_path TO ores;

-- ISO 3166-1 Countries
-- Columns: alpha2_code, version, alpha3_code, numeric_code, name, official_name, modified_by
INSERT INTO countries (alpha2_code, version, alpha3_code, numeric_code, name, official_name, modified_by)
VALUES
-- A
('AD', 0, 'AND', '020', 'Andorra', 'Principality of Andorra', 'system'),
('AE', 0, 'ARE', '784', 'United Arab Emirates', 'United Arab Emirates', 'system'),
('AF', 0, 'AFG', '004', 'Afghanistan', 'Islamic Republic of Afghanistan', 'system'),
('AG', 0, 'ATG', '028', 'Antigua and Barbuda', 'Antigua and Barbuda', 'system'),
('AI', 0, 'AIA', '660', 'Anguilla', 'Anguilla', 'system'),
('AL', 0, 'ALB', '008', 'Albania', 'Republic of Albania', 'system'),
('AM', 0, 'ARM', '051', 'Armenia', 'Republic of Armenia', 'system'),
('AO', 0, 'AGO', '024', 'Angola', 'Republic of Angola', 'system'),
('AQ', 0, 'ATA', '010', 'Antarctica', 'Antarctica', 'system'),
('AR', 0, 'ARG', '032', 'Argentina', 'Argentine Republic', 'system'),
('AS', 0, 'ASM', '016', 'American Samoa', 'American Samoa', 'system'),
('AT', 0, 'AUT', '040', 'Austria', 'Republic of Austria', 'system'),
('AU', 0, 'AUS', '036', 'Australia', 'Commonwealth of Australia', 'system'),
('AW', 0, 'ABW', '533', 'Aruba', 'Aruba', 'system'),
('AX', 0, 'ALA', '248', 'Åland Islands', 'Åland Islands', 'system'),
('AZ', 0, 'AZE', '031', 'Azerbaijan', 'Republic of Azerbaijan', 'system'),
-- B
('BA', 0, 'BIH', '070', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'system'),
('BB', 0, 'BRB', '052', 'Barbados', 'Barbados', 'system'),
('BD', 0, 'BGD', '050', 'Bangladesh', 'People''s Republic of Bangladesh', 'system'),
('BE', 0, 'BEL', '056', 'Belgium', 'Kingdom of Belgium', 'system'),
('BF', 0, 'BFA', '854', 'Burkina Faso', 'Burkina Faso', 'system'),
('BG', 0, 'BGR', '100', 'Bulgaria', 'Republic of Bulgaria', 'system'),
('BH', 0, 'BHR', '048', 'Bahrain', 'Kingdom of Bahrain', 'system'),
('BI', 0, 'BDI', '108', 'Burundi', 'Republic of Burundi', 'system'),
('BJ', 0, 'BEN', '204', 'Benin', 'Republic of Benin', 'system'),
('BL', 0, 'BLM', '652', 'Saint Barthélemy', 'Saint Barthélemy', 'system'),
('BM', 0, 'BMU', '060', 'Bermuda', 'Bermuda', 'system'),
('BN', 0, 'BRN', '096', 'Brunei', 'Brunei Darussalam', 'system'),
('BO', 0, 'BOL', '068', 'Bolivia', 'Plurinational State of Bolivia', 'system'),
('BQ', 0, 'BES', '535', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba', 'system'),
('BR', 0, 'BRA', '076', 'Brazil', 'Federative Republic of Brazil', 'system'),
('BS', 0, 'BHS', '044', 'Bahamas', 'Commonwealth of The Bahamas', 'system'),
('BT', 0, 'BTN', '064', 'Bhutan', 'Kingdom of Bhutan', 'system'),
('BV', 0, 'BVT', '074', 'Bouvet Island', 'Bouvet Island', 'system'),
('BW', 0, 'BWA', '072', 'Botswana', 'Republic of Botswana', 'system'),
('BY', 0, 'BLR', '112', 'Belarus', 'Republic of Belarus', 'system'),
('BZ', 0, 'BLZ', '084', 'Belize', 'Belize', 'system'),
-- C
('CA', 0, 'CAN', '124', 'Canada', 'Canada', 'system'),
('CC', 0, 'CCK', '166', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'system'),
('CD', 0, 'COD', '180', 'DR Congo', 'Democratic Republic of the Congo', 'system'),
('CF', 0, 'CAF', '140', 'Central African Republic', 'Central African Republic', 'system'),
('CG', 0, 'COG', '178', 'Congo', 'Republic of the Congo', 'system'),
('CH', 0, 'CHE', '756', 'Switzerland', 'Swiss Confederation', 'system'),
('CI', 0, 'CIV', '384', 'Côte d''Ivoire', 'Republic of Côte d''Ivoire', 'system'),
('CK', 0, 'COK', '184', 'Cook Islands', 'Cook Islands', 'system'),
('CL', 0, 'CHL', '152', 'Chile', 'Republic of Chile', 'system'),
('CM', 0, 'CMR', '120', 'Cameroon', 'Republic of Cameroon', 'system'),
('CN', 0, 'CHN', '156', 'China', 'People''s Republic of China', 'system'),
('CO', 0, 'COL', '170', 'Colombia', 'Republic of Colombia', 'system'),
('CR', 0, 'CRI', '188', 'Costa Rica', 'Republic of Costa Rica', 'system'),
('CU', 0, 'CUB', '192', 'Cuba', 'Republic of Cuba', 'system'),
('CV', 0, 'CPV', '132', 'Cape Verde', 'Republic of Cabo Verde', 'system'),
('CW', 0, 'CUW', '531', 'Curaçao', 'Curaçao', 'system'),
('CX', 0, 'CXR', '162', 'Christmas Island', 'Christmas Island', 'system'),
('CY', 0, 'CYP', '196', 'Cyprus', 'Republic of Cyprus', 'system'),
('CZ', 0, 'CZE', '203', 'Czechia', 'Czech Republic', 'system'),
-- D
('DE', 0, 'DEU', '276', 'Germany', 'Federal Republic of Germany', 'system'),
('DJ', 0, 'DJI', '262', 'Djibouti', 'Republic of Djibouti', 'system'),
('DK', 0, 'DNK', '208', 'Denmark', 'Kingdom of Denmark', 'system'),
('DM', 0, 'DMA', '212', 'Dominica', 'Commonwealth of Dominica', 'system'),
('DO', 0, 'DOM', '214', 'Dominican Republic', 'Dominican Republic', 'system'),
('DZ', 0, 'DZA', '012', 'Algeria', 'People''s Democratic Republic of Algeria', 'system'),
-- E
('EC', 0, 'ECU', '218', 'Ecuador', 'Republic of Ecuador', 'system'),
('EE', 0, 'EST', '233', 'Estonia', 'Republic of Estonia', 'system'),
('EG', 0, 'EGY', '818', 'Egypt', 'Arab Republic of Egypt', 'system'),
('EH', 0, 'ESH', '732', 'Western Sahara', 'Western Sahara', 'system'),
('ER', 0, 'ERI', '232', 'Eritrea', 'State of Eritrea', 'system'),
('ES', 0, 'ESP', '724', 'Spain', 'Kingdom of Spain', 'system'),
('ET', 0, 'ETH', '231', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', 'system'),
-- F
('FI', 0, 'FIN', '246', 'Finland', 'Republic of Finland', 'system'),
('FJ', 0, 'FJI', '242', 'Fiji', 'Republic of Fiji', 'system'),
('FK', 0, 'FLK', '238', 'Falkland Islands', 'Falkland Islands', 'system'),
('FM', 0, 'FSM', '583', 'Micronesia', 'Federated States of Micronesia', 'system'),
('FO', 0, 'FRO', '234', 'Faroe Islands', 'Faroe Islands', 'system'),
('FR', 0, 'FRA', '250', 'France', 'French Republic', 'system'),
-- G
('GA', 0, 'GAB', '266', 'Gabon', 'Gabonese Republic', 'system'),
('GB', 0, 'GBR', '826', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', 'system'),
('GD', 0, 'GRD', '308', 'Grenada', 'Grenada', 'system'),
('GE', 0, 'GEO', '268', 'Georgia', 'Georgia', 'system'),
('GF', 0, 'GUF', '254', 'French Guiana', 'French Guiana', 'system'),
('GG', 0, 'GGY', '831', 'Guernsey', 'Bailiwick of Guernsey', 'system'),
('GH', 0, 'GHA', '288', 'Ghana', 'Republic of Ghana', 'system'),
('GI', 0, 'GIB', '292', 'Gibraltar', 'Gibraltar', 'system'),
('GL', 0, 'GRL', '304', 'Greenland', 'Greenland', 'system'),
('GM', 0, 'GMB', '270', 'Gambia', 'Republic of The Gambia', 'system'),
('GN', 0, 'GIN', '324', 'Guinea', 'Republic of Guinea', 'system'),
('GP', 0, 'GLP', '312', 'Guadeloupe', 'Guadeloupe', 'system'),
('GQ', 0, 'GNQ', '226', 'Equatorial Guinea', 'Republic of Equatorial Guinea', 'system'),
('GR', 0, 'GRC', '300', 'Greece', 'Hellenic Republic', 'system'),
('GS', 0, 'SGS', '239', 'South Georgia', 'South Georgia and the South Sandwich Islands', 'system'),
('GT', 0, 'GTM', '320', 'Guatemala', 'Republic of Guatemala', 'system'),
('GU', 0, 'GUM', '316', 'Guam', 'Guam', 'system'),
('GW', 0, 'GNB', '624', 'Guinea-Bissau', 'Republic of Guinea-Bissau', 'system'),
('GY', 0, 'GUY', '328', 'Guyana', 'Co-operative Republic of Guyana', 'system'),
-- H
('HK', 0, 'HKG', '344', 'Hong Kong', 'Hong Kong Special Administrative Region of the People''s Republic of China', 'system'),
('HM', 0, 'HMD', '334', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'system'),
('HN', 0, 'HND', '340', 'Honduras', 'Republic of Honduras', 'system'),
('HR', 0, 'HRV', '191', 'Croatia', 'Republic of Croatia', 'system'),
('HT', 0, 'HTI', '332', 'Haiti', 'Republic of Haiti', 'system'),
('HU', 0, 'HUN', '348', 'Hungary', 'Hungary', 'system'),
-- I
('ID', 0, 'IDN', '360', 'Indonesia', 'Republic of Indonesia', 'system'),
('IE', 0, 'IRL', '372', 'Ireland', 'Ireland', 'system'),
('IL', 0, 'ISR', '376', 'Israel', 'State of Israel', 'system'),
('IM', 0, 'IMN', '833', 'Isle of Man', 'Isle of Man', 'system'),
('IN', 0, 'IND', '356', 'India', 'Republic of India', 'system'),
('IO', 0, 'IOT', '086', 'British Indian Ocean Territory', 'British Indian Ocean Territory', 'system'),
('IQ', 0, 'IRQ', '368', 'Iraq', 'Republic of Iraq', 'system'),
('IR', 0, 'IRN', '364', 'Iran', 'Islamic Republic of Iran', 'system'),
('IS', 0, 'ISL', '352', 'Iceland', 'Iceland', 'system'),
('IT', 0, 'ITA', '380', 'Italy', 'Italian Republic', 'system'),
-- J
('JE', 0, 'JEY', '832', 'Jersey', 'Bailiwick of Jersey', 'system'),
('JM', 0, 'JAM', '388', 'Jamaica', 'Jamaica', 'system'),
('JO', 0, 'JOR', '400', 'Jordan', 'Hashemite Kingdom of Jordan', 'system'),
('JP', 0, 'JPN', '392', 'Japan', 'Japan', 'system'),
-- K
('KE', 0, 'KEN', '404', 'Kenya', 'Republic of Kenya', 'system'),
('KG', 0, 'KGZ', '417', 'Kyrgyzstan', 'Kyrgyz Republic', 'system'),
('KH', 0, 'KHM', '116', 'Cambodia', 'Kingdom of Cambodia', 'system'),
('KI', 0, 'KIR', '296', 'Kiribati', 'Republic of Kiribati', 'system'),
('KM', 0, 'COM', '174', 'Comoros', 'Union of the Comoros', 'system'),
('KN', 0, 'KNA', '659', 'Saint Kitts and Nevis', 'Federation of Saint Christopher and Nevis', 'system'),
('KP', 0, 'PRK', '408', 'North Korea', 'Democratic People''s Republic of Korea', 'system'),
('KR', 0, 'KOR', '410', 'South Korea', 'Republic of Korea', 'system'),
('KW', 0, 'KWT', '414', 'Kuwait', 'State of Kuwait', 'system'),
('KY', 0, 'CYM', '136', 'Cayman Islands', 'Cayman Islands', 'system'),
('KZ', 0, 'KAZ', '398', 'Kazakhstan', 'Republic of Kazakhstan', 'system'),
-- L
('LA', 0, 'LAO', '418', 'Laos', 'Lao People''s Democratic Republic', 'system'),
('LB', 0, 'LBN', '422', 'Lebanon', 'Lebanese Republic', 'system'),
('LC', 0, 'LCA', '662', 'Saint Lucia', 'Saint Lucia', 'system'),
('LI', 0, 'LIE', '438', 'Liechtenstein', 'Principality of Liechtenstein', 'system'),
('LK', 0, 'LKA', '144', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'system'),
('LR', 0, 'LBR', '430', 'Liberia', 'Republic of Liberia', 'system'),
('LS', 0, 'LSO', '426', 'Lesotho', 'Kingdom of Lesotho', 'system'),
('LT', 0, 'LTU', '440', 'Lithuania', 'Republic of Lithuania', 'system'),
('LU', 0, 'LUX', '442', 'Luxembourg', 'Grand Duchy of Luxembourg', 'system'),
('LV', 0, 'LVA', '428', 'Latvia', 'Republic of Latvia', 'system'),
('LY', 0, 'LBY', '434', 'Libya', 'State of Libya', 'system'),
-- M
('MA', 0, 'MAR', '504', 'Morocco', 'Kingdom of Morocco', 'system'),
('MC', 0, 'MCO', '492', 'Monaco', 'Principality of Monaco', 'system'),
('MD', 0, 'MDA', '498', 'Moldova', 'Republic of Moldova', 'system'),
('ME', 0, 'MNE', '499', 'Montenegro', 'Montenegro', 'system'),
('MF', 0, 'MAF', '663', 'Saint Martin', 'Saint Martin (French part)', 'system'),
('MG', 0, 'MDG', '450', 'Madagascar', 'Republic of Madagascar', 'system'),
('MH', 0, 'MHL', '584', 'Marshall Islands', 'Republic of the Marshall Islands', 'system'),
('MK', 0, 'MKD', '807', 'North Macedonia', 'Republic of North Macedonia', 'system'),
('ML', 0, 'MLI', '466', 'Mali', 'Republic of Mali', 'system'),
('MM', 0, 'MMR', '104', 'Myanmar', 'Republic of the Union of Myanmar', 'system'),
('MN', 0, 'MNG', '496', 'Mongolia', 'Mongolia', 'system'),
('MO', 0, 'MAC', '446', 'Macau', 'Macao Special Administrative Region of the People''s Republic of China', 'system'),
('MP', 0, 'MNP', '580', 'Northern Mariana Islands', 'Commonwealth of the Northern Mariana Islands', 'system'),
('MQ', 0, 'MTQ', '474', 'Martinique', 'Martinique', 'system'),
('MR', 0, 'MRT', '478', 'Mauritania', 'Islamic Republic of Mauritania', 'system'),
('MS', 0, 'MSR', '500', 'Montserrat', 'Montserrat', 'system'),
('MT', 0, 'MLT', '470', 'Malta', 'Republic of Malta', 'system'),
('MU', 0, 'MUS', '480', 'Mauritius', 'Republic of Mauritius', 'system'),
('MV', 0, 'MDV', '462', 'Maldives', 'Republic of Maldives', 'system'),
('MW', 0, 'MWI', '454', 'Malawi', 'Republic of Malawi', 'system'),
('MX', 0, 'MEX', '484', 'Mexico', 'United Mexican States', 'system'),
('MY', 0, 'MYS', '458', 'Malaysia', 'Malaysia', 'system'),
('MZ', 0, 'MOZ', '508', 'Mozambique', 'Republic of Mozambique', 'system'),
-- N
('NA', 0, 'NAM', '516', 'Namibia', 'Republic of Namibia', 'system'),
('NC', 0, 'NCL', '540', 'New Caledonia', 'New Caledonia', 'system'),
('NE', 0, 'NER', '562', 'Niger', 'Republic of the Niger', 'system'),
('NF', 0, 'NFK', '574', 'Norfolk Island', 'Norfolk Island', 'system'),
('NG', 0, 'NGA', '566', 'Nigeria', 'Federal Republic of Nigeria', 'system'),
('NI', 0, 'NIC', '558', 'Nicaragua', 'Republic of Nicaragua', 'system'),
('NL', 0, 'NLD', '528', 'Netherlands', 'Kingdom of the Netherlands', 'system'),
('NO', 0, 'NOR', '578', 'Norway', 'Kingdom of Norway', 'system'),
('NP', 0, 'NPL', '524', 'Nepal', 'Federal Democratic Republic of Nepal', 'system'),
('NR', 0, 'NRU', '520', 'Nauru', 'Republic of Nauru', 'system'),
('NU', 0, 'NIU', '570', 'Niue', 'Niue', 'system'),
('NZ', 0, 'NZL', '554', 'New Zealand', 'New Zealand', 'system'),
-- O
('OM', 0, 'OMN', '512', 'Oman', 'Sultanate of Oman', 'system'),
-- P
('PA', 0, 'PAN', '591', 'Panama', 'Republic of Panama', 'system'),
('PE', 0, 'PER', '604', 'Peru', 'Republic of Peru', 'system'),
('PF', 0, 'PYF', '258', 'French Polynesia', 'French Polynesia', 'system'),
('PG', 0, 'PNG', '598', 'Papua New Guinea', 'Independent State of Papua New Guinea', 'system'),
('PH', 0, 'PHL', '608', 'Philippines', 'Republic of the Philippines', 'system'),
('PK', 0, 'PAK', '586', 'Pakistan', 'Islamic Republic of Pakistan', 'system'),
('PL', 0, 'POL', '616', 'Poland', 'Republic of Poland', 'system'),
('PM', 0, 'SPM', '666', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'system'),
('PN', 0, 'PCN', '612', 'Pitcairn Islands', 'Pitcairn Islands', 'system'),
('PR', 0, 'PRI', '630', 'Puerto Rico', 'Commonwealth of Puerto Rico', 'system'),
('PS', 0, 'PSE', '275', 'Palestine', 'State of Palestine', 'system'),
('PT', 0, 'PRT', '620', 'Portugal', 'Portuguese Republic', 'system'),
('PW', 0, 'PLW', '585', 'Palau', 'Republic of Palau', 'system'),
('PY', 0, 'PRY', '600', 'Paraguay', 'Republic of Paraguay', 'system'),
-- Q
('QA', 0, 'QAT', '634', 'Qatar', 'State of Qatar', 'system'),
-- R
('RE', 0, 'REU', '638', 'Réunion', 'Réunion', 'system'),
('RO', 0, 'ROU', '642', 'Romania', 'Romania', 'system'),
('RS', 0, 'SRB', '688', 'Serbia', 'Republic of Serbia', 'system'),
('RU', 0, 'RUS', '643', 'Russia', 'Russian Federation', 'system'),
('RW', 0, 'RWA', '646', 'Rwanda', 'Republic of Rwanda', 'system'),
-- S
('SA', 0, 'SAU', '682', 'Saudi Arabia', 'Kingdom of Saudi Arabia', 'system'),
('SB', 0, 'SLB', '090', 'Solomon Islands', 'Solomon Islands', 'system'),
('SC', 0, 'SYC', '690', 'Seychelles', 'Republic of Seychelles', 'system'),
('SD', 0, 'SDN', '729', 'Sudan', 'Republic of the Sudan', 'system'),
('SE', 0, 'SWE', '752', 'Sweden', 'Kingdom of Sweden', 'system'),
('SG', 0, 'SGP', '702', 'Singapore', 'Republic of Singapore', 'system'),
('SH', 0, 'SHN', '654', 'Saint Helena', 'Saint Helena, Ascension and Tristan da Cunha', 'system'),
('SI', 0, 'SVN', '705', 'Slovenia', 'Republic of Slovenia', 'system'),
('SJ', 0, 'SJM', '744', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen', 'system'),
('SK', 0, 'SVK', '703', 'Slovakia', 'Slovak Republic', 'system'),
('SL', 0, 'SLE', '694', 'Sierra Leone', 'Republic of Sierra Leone', 'system'),
('SM', 0, 'SMR', '674', 'San Marino', 'Republic of San Marino', 'system'),
('SN', 0, 'SEN', '686', 'Senegal', 'Republic of Senegal', 'system'),
('SO', 0, 'SOM', '706', 'Somalia', 'Federal Republic of Somalia', 'system'),
('SR', 0, 'SUR', '740', 'Suriname', 'Republic of Suriname', 'system'),
('SS', 0, 'SSD', '728', 'South Sudan', 'Republic of South Sudan', 'system'),
('ST', 0, 'STP', '678', 'São Tomé and Príncipe', 'Democratic Republic of São Tomé and Príncipe', 'system'),
('SV', 0, 'SLV', '222', 'El Salvador', 'Republic of El Salvador', 'system'),
('SX', 0, 'SXM', '534', 'Sint Maarten', 'Sint Maarten (Dutch part)', 'system'),
('SY', 0, 'SYR', '760', 'Syria', 'Syrian Arab Republic', 'system'),
('SZ', 0, 'SWZ', '748', 'Eswatini', 'Kingdom of Eswatini', 'system'),
-- T
('TC', 0, 'TCA', '796', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'system'),
('TD', 0, 'TCD', '148', 'Chad', 'Republic of Chad', 'system'),
('TF', 0, 'ATF', '260', 'French Southern Territories', 'French Southern and Antarctic Lands', 'system'),
('TG', 0, 'TGO', '768', 'Togo', 'Togolese Republic', 'system'),
('TH', 0, 'THA', '764', 'Thailand', 'Kingdom of Thailand', 'system'),
('TJ', 0, 'TJK', '762', 'Tajikistan', 'Republic of Tajikistan', 'system'),
('TK', 0, 'TKL', '772', 'Tokelau', 'Tokelau', 'system'),
('TL', 0, 'TLS', '626', 'Timor-Leste', 'Democratic Republic of Timor-Leste', 'system'),
('TM', 0, 'TKM', '795', 'Turkmenistan', 'Turkmenistan', 'system'),
('TN', 0, 'TUN', '788', 'Tunisia', 'Republic of Tunisia', 'system'),
('TO', 0, 'TON', '776', 'Tonga', 'Kingdom of Tonga', 'system'),
('TR', 0, 'TUR', '792', 'Turkey', 'Republic of Turkey', 'system'),
('TT', 0, 'TTO', '780', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'system'),
('TV', 0, 'TUV', '798', 'Tuvalu', 'Tuvalu', 'system'),
('TW', 0, 'TWN', '158', 'Taiwan', 'Republic of China (Taiwan)', 'system'),
('TZ', 0, 'TZA', '834', 'Tanzania', 'United Republic of Tanzania', 'system'),
-- U
('UA', 0, 'UKR', '804', 'Ukraine', 'Ukraine', 'system'),
('UG', 0, 'UGA', '800', 'Uganda', 'Republic of Uganda', 'system'),
('UM', 0, 'UMI', '581', 'U.S. Minor Outlying Islands', 'United States Minor Outlying Islands', 'system'),
('US', 0, 'USA', '840', 'United States', 'United States of America', 'system'),
('UY', 0, 'URY', '858', 'Uruguay', 'Oriental Republic of Uruguay', 'system'),
('UZ', 0, 'UZB', '860', 'Uzbekistan', 'Republic of Uzbekistan', 'system'),
-- V
('VA', 0, 'VAT', '336', 'Vatican City', 'Vatican City State', 'system'),
('VC', 0, 'VCT', '670', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'system'),
('VE', 0, 'VEN', '862', 'Venezuela', 'Bolivarian Republic of Venezuela', 'system'),
('VG', 0, 'VGB', '092', 'British Virgin Islands', 'Virgin Islands (British)', 'system'),
('VI', 0, 'VIR', '850', 'U.S. Virgin Islands', 'Virgin Islands (U.S.)', 'system'),
('VN', 0, 'VNM', '704', 'Vietnam', 'Socialist Republic of Vietnam', 'system'),
('VU', 0, 'VUT', '548', 'Vanuatu', 'Republic of Vanuatu', 'system'),
-- W
('WF', 0, 'WLF', '876', 'Wallis and Futuna', 'Wallis and Futuna', 'system'),
('WS', 0, 'WSM', '882', 'Samoa', 'Independent State of Samoa', 'system'),
-- X (no standard ISO 3166-1 countries)
-- Y
('YE', 0, 'YEM', '887', 'Yemen', 'Republic of Yemen', 'system'),
('YT', 0, 'MYT', '175', 'Mayotte', 'Department of Mayotte', 'system'),
-- Z
('ZA', 0, 'ZAF', '710', 'South Africa', 'Republic of South Africa', 'system'),
('ZM', 0, 'ZMB', '894', 'Zambia', 'Republic of Zambia', 'system'),
('ZW', 0, 'ZWE', '716', 'Zimbabwe', 'Republic of Zimbabwe', 'system');
