/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * FPML Reference Data Master Include File
 *
 * Auto-generated by generate_fpml_refdata.sh
 * Includes all FPML SQL files in the correct dependency order.
 */

-- =============================================================================
-- FPML Methodology (must come first)
-- =============================================================================

\echo '--- FPML Methodology ---'
\ir fpml_methodology_populate.sql

-- =============================================================================
-- FPML Coding Schemes
-- =============================================================================

\echo '--- FPML Coding Schemes ---'
\ir fpml_coding_schemes_populate.sql

-- =============================================================================
-- FPML Datasets
-- =============================================================================

\echo '--- FPML Datasets ---'
\ir fpml_non_iso_currency_dataset_populate.sql

-- =============================================================================
-- FPML Artefacts
-- =============================================================================

\echo '--- FPML Artefacts ---'
\ir dq_non_iso_currency_artefact_populate.sql
