/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * FPML Reference Data Master Include File
 *
 * Auto-generated by generate_fpml_refdata.sh
 * Includes all FPML SQL files in the correct dependency order.
 */

-- =============================================================================
-- FPML Methodology (must come first)
-- =============================================================================

\echo '--- FPML Methodology ---'
\ir fpml_methodology_populate.sql

-- =============================================================================
-- FPML Coding Schemes
-- =============================================================================

\echo '--- FPML Coding Schemes ---'
\ir fpml_coding_schemes_populate.sql

-- =============================================================================
-- FPML Datasets
-- =============================================================================

\echo '--- FPML Datasets ---'
\ir fpml_account_type_dataset_populate.sql
\ir fpml_asset_class_dataset_populate.sql
\ir fpml_asset_measure_dataset_populate.sql
\ir fpml_benchmark_rate_dataset_populate.sql
\ir fpml_business_center_dataset_populate.sql
\ir fpml_business_process_dataset_populate.sql
\ir fpml_cashflow_type_dataset_populate.sql
\ir fpml_cftc_entity_classification_dataset_populate.sql
\ir fpml_cftc_organization_type_dataset_populate.sql
\ir fpml_entity_type_dataset_populate.sql
\ir fpml_hkma_rewrite_party_relationship_type_dataset_populate.sql
\ir fpml_hkma_rewrite_regulatory_corporate_sector_dataset_populate.sql
\ir fpml_local_jurisdiction_dataset_populate.sql
\ir fpml_non_iso_currency_dataset_populate.sql
\ir fpml_party_relationship_type_dataset_populate.sql
\ir fpml_party_role_dataset_populate.sql
\ir fpml_party_role_type_dataset_populate.sql
\ir fpml_person_role_dataset_populate.sql
\ir fpml_regulatory_corporate_sector_dataset_populate.sql
\ir fpml_reporting_regime_dataset_populate.sql
\ir fpml_supervisory_body_dataset_populate.sql

-- =============================================================================
-- FPML Artefacts
-- =============================================================================

\echo '--- FPML Artefacts ---'
\ir dq_account_type_artefact_populate.sql
\ir dq_asset_class_artefact_populate.sql
\ir dq_asset_measure_artefact_populate.sql
\ir dq_benchmark_rate_artefact_populate.sql
\ir dq_business_center_artefact_populate.sql
\ir dq_business_process_artefact_populate.sql
\ir dq_cashflow_type_artefact_populate.sql
\ir dq_cftc_entity_classification_artefact_populate.sql
\ir dq_cftc_organization_type_artefact_populate.sql
\ir dq_entity_type_artefact_populate.sql
\ir dq_hkma_rewrite_party_relationship_type_artefact_populate.sql
\ir dq_hkma_rewrite_regulatory_corporate_sector_artefact_populate.sql
\ir dq_local_jurisdiction_artefact_populate.sql
\ir dq_non_iso_currency_artefact_populate.sql
\ir dq_party_relationship_type_artefact_populate.sql
\ir dq_party_role_artefact_populate.sql
\ir dq_party_role_type_artefact_populate.sql
\ir dq_person_role_artefact_populate.sql
\ir dq_regulatory_corporate_sector_artefact_populate.sql
\ir dq_reporting_regime_artefact_populate.sql
\ir dq_supervisory_body_artefact_populate.sql
