' -*- mode: plantuml; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
'
' Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
'
' This program is free software; you can redistribute it and/or modify it under
' the terms of the GNU General Public License as published by the Free Software
' Foundation; either version 3 of the License, or (at your option) any later
' version.
'
' This program is distributed in the hope that it will be useful, but WITHOUT
' ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
' FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with
' this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
' Street, Fifth Floor, Boston, MA 02110-1301, USA.
'
@startuml
@startuml

salt
{
  <b>ORE STUDIO - SYSTEM ADMINISTRATION: TENANTS</b>
  --
  <b>ACME CORPORATION</b> | [ Back to tenants ]
  --
  <b>DETAILS</b>
  --
  {
    Code | acme_corporation
    Name | Acme Corporation
    Hostname | acme_corporation
    Type | (Evaluation)
    Status | (Active)
    Description | Acme's evaluation tenant
    Registration default | No
  }
  --
  {
    Version | 3
    Changed by | admin
    Written by | ores.iam.service
    Reason | system.initial_load
    Recorded | 2026-10-02 21:39
  }
  --
  <b>SETUP</b>
  --
  {
    Run | (Failed) | Step 4 of 7 | Seeding failed. | [ Resume setup ]
  }
  --
  <b>PARTIES</b>
  --
  {#
    Code | Name | Category | Type | Status | Parent
    system | Acme Corporation System | System | | Active | -
    acme_group | Acme Group | Operational | Legal entity | Active | -
    acme_london | Acme London | Operational | Branch | Active | Acme Group
  }
  --
  <b>NO SUCH TENANT</b>
  --
  No tenant has this identifier.
  [ Back to tenants ]
}

@enduml
