' -*- mode: plantuml; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
'
' Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
'
' This program is free software; you can redistribute it and/or modify it under
' the terms of the GNU General Public License as published by the Free Software
' Foundation; either version 3 of the License, or (at your option) any later
' version.
'
' This program is distributed in the hope that it will be useful, but WITHOUT
' ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
' FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with
' this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
' Street, Fifth Floor, Boston, MA 02110-1301, USA.
'
@startuml

title ores.assets.api Component

set namespaceSeparator ::

namespace ores #F2F2F2 {
    namespace assets #F2F2F2 {
        namespace domain #F2F2F2 {
            class image <<struct>> {
                +version : int
                +image_id : boost::uuids::uuid
                +key : string
                +description : string
                +mime_type : string
                +data : vector<uint8_t>
                +modified_by : string
                +change_reason_code : string
                +change_commentary : string
                +performed_by : string
                +recorded_at : chrono::system_clock::time_point
            }
            class image_tag <<struct>> {
                +image_id : boost::uuids::uuid
                +tag_id : boost::uuids::uuid
                +assigned_by : string
                +assigned_at : chrono::system_clock::time_point
            }
            class tag <<struct>> {
                +version : int
                +tenant_id : string
                +tag_id : string
                +name : string
                +description : string
                +modified_by : string
                +change_reason_code : string
                +change_commentary : string
                +performed_by : string
                +recorded_at : string
            }
        }
        namespace eventing #F2F2F2 {
            class assets_changed_event <<struct>> {
                +timestamp : chrono::system_clock::time_point
                +iso_codes : vector<string>
                +tenant_id : string
            }
        }
        namespace messaging #F2F2F2 {
            class image_info <<struct>> {
                +image_id : string
                +key : string
                +description : string
            }
            class get_images_request <<struct>> {
                +image_ids : vector<string>
            }
            class get_images_response <<struct>> {
                +success : bool
                +message : string
                +images : vector<ores::assets::domain::image>
            }
            class list_images_request <<struct>> {
                +modified_since : optional<chrono::system_clock::time_point>
            }
            class list_images_response <<struct>> {
                +success : bool
                +message : string
                +images : vector<image_info>
            }
            class save_image_request <<struct>> {
                +data : ores::assets::domain::image
            }
            class save_image_response <<struct>> {
                +success : bool
                +message : string
            }
        }
    }
}

' --- manual: everything below this line is hand-authored; the script preserves it ---

' Local Variables:
' compile-command: "java -Djava.awt.headless=true -DPLANTUML_SECURITY_PROFILE=UNSECURE -DPLANTUML_LIMIT_SIZE=65535 -jar /usr/share/plantuml/plantuml.jar ores.assets.api.puml"
' End:
@enduml
