# -*- mode: cmake; cmake-tab-width: 4; indent-tabs-mode: nil -*-
#
# Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
set(files
    "app/application.cpp"
    "app/host.cpp"
    "config/add_account_options.cpp"
    "config/add_change_reason_category_options.cpp"
    "config/add_change_reason_options.cpp"
    "config/add_compute_app_options.cpp"
    "config/add_compute_app_version_options.cpp"
    "config/add_compute_batch_options.cpp"
    "config/add_compute_host_options.cpp"
    "config/add_compute_workunit_options.cpp"
    "config/add_country_options.cpp"
    "config/add_currency_options.cpp"
    "config/add_floating_index_type_options.cpp"
    "config/add_leg_type_options.cpp"
    "config/add_login_info_options.cpp"
    "config/add_options.cpp"
    "config/add_permission_options.cpp"
    "config/add_role_options.cpp"
    "config/add_system_setting_options.cpp"
    "config/delete_options.cpp"
    "config/domain_parsers/compute_parser.cpp"
    "config/domain_parsers/dq_parser.cpp"
    "config/domain_parsers/iam_parser.cpp"
    "config/domain_parsers/ore_parser.cpp"
    "config/domain_parsers/refdata_parser.cpp"
    "config/domain_parsers/trading_parser.cpp"
    "config/domain_parsers/variability_parser.cpp"
    "config/entity_parsers/accounts_parser.cpp"
    "config/entity_parsers/change_reason_categories_parser.cpp"
    "config/entity_parsers/change_reasons_parser.cpp"
    "config/entity_parsers/compute_app_versions_parser.cpp"
    "config/entity_parsers/compute_apps_parser.cpp"
    "config/entity_parsers/compute_batches_parser.cpp"
    "config/entity_parsers/compute_hosts_parser.cpp"
    "config/entity_parsers/compute_results_parser.cpp"
    "config/entity_parsers/compute_workunits_parser.cpp"
    "config/entity_parsers/countries_parser.cpp"
    "config/entity_parsers/currencies_parser.cpp"
    "config/entity_parsers/floating_index_types_parser.cpp"
    "config/entity_parsers/leg_types_parser.cpp"
    "config/entity_parsers/login_info_parser.cpp"
    "config/entity_parsers/permissions_parser.cpp"
    "config/entity_parsers/roles_parser.cpp"
    "config/entity_parsers/system_settings_parser.cpp"
    "config/export_options.cpp"
    "config/import_options.cpp"
    "config/list_options.cpp"
    "config/options.cpp"
    "config/ore_roundtrip_options.cpp"
    "config/parser.cpp"
    "config/parser_helpers.cpp"
    "main.cpp"
)

# Headers must be listed for AUTOMOC to find Q_OBJECT declarations.
set(HEADERS
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/app/application.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/app/application_exception.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/app/host.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/app/ores.cli.app.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_account_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_change_reason_category_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_change_reason_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_compute_app_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_compute_app_version_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_compute_batch_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_compute_host_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_compute_workunit_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_country_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_currency_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_floating_index_type_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_leg_type_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_login_info_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_permission_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_role_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/add_system_setting_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/delete_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/domain.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/domain_parsers/compute_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/domain_parsers/dq_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/domain_parsers/iam_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/domain_parsers/ore_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/domain_parsers/refdata_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/domain_parsers/trading_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/domain_parsers/variability_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/accounts_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/change_reason_categories_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/change_reasons_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/compute_app_versions_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/compute_apps_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/compute_batches_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/compute_hosts_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/compute_results_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/compute_workunits_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/countries_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/currencies_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/floating_index_types_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/leg_types_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/login_info_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/permissions_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/roles_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/entity_parsers/system_settings_parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/export_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/format.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/import_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/list_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/operation.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/ore_roundtrip_options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/ores.cli.config.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/parser_exception.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/config/parser_helpers.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/export.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.cli/ores.cli.hpp"
)
