#!/usr/bin/env python3
"""Report which SQL files codegen produces, which another tool produces, and
which are written by hand.

A "generated" comment in a file cannot answer this. No drop template writes
one, and some files keep one after the input that generated them was deleted.
So this asks the generator instead: it renders every catalogue component at
the whole ``ores`` address into a scratch root, with the same functions
``check_component_drift.py --sweep`` uses. A file under ``projects/ores.sql``
is entity codegen output exactly when that root contains it. A file the root
does not contain but that carries a generated marker comes from another
generator (a dataset or FpML script, the service templates). Everything else
is hand-written.

Renders into a temporary directory and writes nothing into the repository.

Run::

    python3 projects/ores.codegen/scripts/census_sql_origin.py
    python3 projects/ores.codegen/scripts/census_sql_origin.py --csv origin.csv
"""
import argparse
import csv
import re
import sys
import tempfile
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(Path(__file__).resolve().parent))

import check_component_drift as drift  # noqa: E402

SQL_ROOT = Path("projects") / "ores.sql"
TREES = ("create", "drop", "populate")
MARKER = re.compile(r"GENERATED FILE|DO NOT EDIT|AUTO-GENERATED|Generated by",
                    re.IGNORECASE)


def rendered_sql(tmp_root: Path) -> set[Path]:
    """Render every catalogue component and return the SQL paths produced."""
    drift._seed_clang_format(tmp_root)
    rc = drift._render_components(drift._catalogue_components(), "ores",
                                  tmp_root, whole_address=True)
    if rc != 0:
        raise SystemExit(rc)
    return {p.relative_to(tmp_root) for p in (tmp_root / SQL_ROOT).rglob("*.sql")}


def classify(generated: set[Path]) -> list[tuple[str, str, str]]:
    """Label every SQL file in the three trees by origin."""
    rows = []
    for tree in TREES:
        for path in sorted((REPO_ROOT / SQL_ROOT / tree).rglob("*.sql")):
            rel = path.relative_to(REPO_ROOT)
            head = path.read_text(encoding="utf-8", errors="replace")[:3000]
            if rel in generated:
                origin = "codegen"
            elif MARKER.search(head):
                origin = "other-generator"
            else:
                origin = "hand"
            rows.append((tree, str(rel), origin))
    return rows


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--csv", metavar="PATH",
                    help="write one row per file: tree, path, origin")
    args = ap.parse_args()

    with tempfile.TemporaryDirectory(prefix="ores-sql-census-") as tmpdir:
        generated = rendered_sql(Path(tmpdir))
    rows = classify(generated)

    if args.csv:
        with open(args.csv, "w", newline="") as out:
            writer = csv.writer(out)
            writer.writerow(["tree", "path", "origin"])
            writer.writerows(rows)

    counts = Counter((tree, origin) for tree, _, origin in rows)
    origins = ("codegen", "other-generator", "hand")
    print(f"{'tree':10} " + " ".join(f"{o:>16}" for o in origins) + f" {'total':>7}")
    for tree in TREES:
        line = [counts[(tree, o)] for o in origins]
        print(f"{tree:10} " + " ".join(f"{n:16}" for n in line) + f" {sum(line):7}")
    totals = [sum(counts[(t, o)] for t in TREES) for o in origins]
    print(f"{'all':10} " + " ".join(f"{n:16}" for n in totals) + f" {sum(totals):7}")

    absent = sorted(g for g in generated if not (REPO_ROOT / g).exists())
    if absent:
        print(f"\n{len(absent)} rendered file(s) are not in the tree:")
        for rel in absent:
            print(f"  {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
