#!/usr/bin/env python3
"""
Regenerate the product-backlog index pages.

Walks doc/agile/product_backlog/{near,far}/ and rewrites the
auto-generated section of near.org and far.org with the current set of
captures. Each capture's row carries Title (id-linked), Tags, and
Description.

Modes:
  (default)   Rewrite the two index files in place.
  --check     Exit non-zero if either index is stale (CI gate).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
BACKLOG_ROOT = REPO_ROOT / "doc/agile/product_backlog"
GLOSS_CAPTURE = "671f18e4-e09c-4b3b-bd24-d33df8ae38a6"

BEGIN_MARK = "# BEGIN AUTOGENERATED — regenerate_backlog_indexes.py"
END_MARK = "# END AUTOGENERATED"

INDEX_HEADER = {
    "near": """:PROPERTIES:
:ID: {id}
:END:
#+title: Product backlog — near
#+description: Index of pre-sprint captures we may pull into the next version.
#+type: knowledge
#+version: 2
#+level: cross
#+filetags: :backlog:near:capture:index:knowledge:
#+created: 2026-05-21
#+updated: 2026-05-21

The /near/ bucket of the [[id:d4219199-7b17-4a89-b4bc-6019738642da][product backlog]]. Captures here are
[[id:{gloss}][captures]] — pre-sprint ideas considered candidate work for the
next version. When a sprint pulls one in, it becomes a story.

#+begin_note
The table below is regenerated by
=projects/ores.codegen/scripts/regenerate_backlog_indexes.py= — do not
edit the rows by hand. To add a capture, run
=generate_v2_doc.sh --type capture --parent-dir doc/agile/product_backlog/near=
and re-run the script.
#+end_note

* Captures

""",
    "far": """:PROPERTIES:
:ID: {id}
:END:
#+title: Product backlog — far
#+description: Index of pre-sprint captures kept for the longer-term wishlist.
#+type: knowledge
#+version: 2
#+level: cross
#+filetags: :backlog:far:capture:index:knowledge:
#+created: 2026-05-21
#+updated: 2026-05-21

The /far/ bucket of the [[id:d4219199-7b17-4a89-b4bc-6019738642da][product backlog]]. Captures here are
[[id:{gloss}][captures]] — ideas worth keeping but not yet attached to any
near-term version. Things may live here for a long time.

#+begin_note
The table below is regenerated by
=projects/ores.codegen/scripts/regenerate_backlog_indexes.py= — do not
edit the rows by hand. To add a capture, run
=generate_v2_doc.sh --type capture --parent-dir doc/agile/product_backlog/far=
and re-run the script.
#+end_note

* Captures

""",
}

# Stable IDs for the two index pages, so agile.org can link to them.
INDEX_IDS = {
    "near": "9a17e8df-7e94-4f55-8a14-bcb7d9a16d6b",
    "far":  "c1bf2c4f-2db3-49c1-94e9-7d2b3e4f1ab8",
}


def read_frontmatter(path: Path) -> dict[str, str]:
    """Extract :ID:, title, description, filetags from a capture .org file."""
    text = path.read_text(encoding="utf-8")
    info: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not info.get("id") and stripped.startswith(":ID:"):
            info["id"] = stripped.split(":ID:", 1)[1].strip()
        elif not info.get("title") and stripped.lower().startswith("#+title:"):
            info["title"] = stripped.split(":", 1)[1].strip()
        elif not info.get("description") and stripped.lower().startswith("#+description:"):
            info["description"] = stripped.split(":", 1)[1].strip()
        elif not info.get("filetags") and stripped.lower().startswith("#+filetags:"):
            info["filetags"] = stripped.split(":", 1)[1].strip()
        if all(k in info for k in ("id", "title", "description", "filetags")):
            break
    return info


def gather_captures(bucket: str) -> list[dict[str, str]]:
    captures = []
    bucket_dir = BACKLOG_ROOT / bucket
    if not bucket_dir.is_dir():
        return captures
    for path in sorted(bucket_dir.glob("*.org")):
        fm = read_frontmatter(path)
        if not fm.get("id") or not fm.get("title"):
            continue
        captures.append(fm)
    # Sort alphabetically by title (case-insensitive).
    captures.sort(key=lambda c: c["title"].lower())
    return captures


def display_tags(filetags: str) -> str:
    """Strip the boilerplate :capture: / :near: / :far: tags from the display."""
    raw = [t for t in filetags.strip().strip(":").split(":") if t]
    boilerplate = {"capture", "near", "far"}
    keep = [t for t in raw if t not in boilerplate]
    return " ".join(f"={t}=" for t in keep)


def render_table(captures: list[dict[str, str]]) -> str:
    if not captures:
        return "(No captures in this bucket yet.)\n"

    rows = []
    for c in captures:
        title_link = f"[[id:{c['id']}][{c['title']}]]"
        tags = display_tags(c.get("filetags", ""))
        desc = c.get("description", "").strip()
        rows.append((title_link, tags, desc))

    title_w = max(len("Capture"), max(len(r[0]) for r in rows))
    tags_w  = max(len("Tags"),    max(len(r[1]) for r in rows), 1)
    desc_w  = max(len("Description"), max(len(r[2]) for r in rows), 50)

    sep = "|" + "+".join("-" * (w + 2) for w in (title_w, tags_w, desc_w)) + "|"
    out = [
        "#+ATTR_HTML: :class hug-leading",
        "| " + "Capture".ljust(title_w) + " | " + "Tags".ljust(tags_w)
            + " | " + "Description".ljust(desc_w) + " |",
        sep,
    ]
    for link, tags, desc in rows:
        out.append("| " + link.ljust(title_w) + " | " + tags.ljust(tags_w)
                   + " | " + desc.ljust(desc_w) + " |")
    return "\n".join(out) + "\n"


def build_index(bucket: str) -> str:
    captures = gather_captures(bucket)
    header = INDEX_HEADER[bucket].format(
        id=INDEX_IDS[bucket], gloss=GLOSS_CAPTURE,
    )
    table = render_table(captures)
    body = (
        header
        + f"{BEGIN_MARK}\n"
        + table
        + f"{END_MARK}\n"
    )
    return body


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Exit non-zero if either index is stale.")
    args = parser.parse_args()

    stale: list[str] = []
    for bucket in ("near", "far"):
        target = BACKLOG_ROOT / f"{bucket}.org"
        desired = build_index(bucket)
        if args.check:
            current = target.read_text(encoding="utf-8") if target.exists() else ""
            if current != desired:
                stale.append(str(target.relative_to(REPO_ROOT)))
        else:
            target.write_text(desired, encoding="utf-8", newline="\n")
            print(f"wrote {target.relative_to(REPO_ROOT)} ({len(gather_captures(bucket))} captures)")

    if args.check:
        if stale:
            print("stale backlog index(es):", file=sys.stderr)
            for s in stale:
                print(f"  {s}", file=sys.stderr)
            print("\nrun: python3 projects/ores.codegen/scripts/regenerate_backlog_indexes.py",
                  file=sys.stderr)
            return 1
        return 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
