# -*- mode: cmake; cmake-tab-width: 4; indent-tabs-mode: nil -*-
#
# Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# Template: cmake_component_files_src.mustache
# To modify, update the template and regenerate.
set(files
    "app/commands/trading/activity_category_commands.cpp"
    "app/commands/trading/activity_type_commands.cpp"
    "app/commands/trading/amortization_type_commands.cpp"
    "app/commands/trading/average_type_commands.cpp"
    "app/commands/trading/balance_guaranteed_swap_instrument_commands.cpp"
    "app/commands/trading/barrier_type_commands.cpp"
    "app/commands/trading/bond_instrument_commands.cpp"
    "app/commands/trading/bond_issue_commands.cpp"
    "app/commands/trading/callable_swap_instrument_commands.cpp"
    "app/commands/trading/cap_floor_instrument_commands.cpp"
    "app/commands/trading/commodity_basket_constituent_commands.cpp"
    "app/commands/trading/commodity_instrument_commands.cpp"
    "app/commands/trading/composite_instrument_commands.cpp"
    "app/commands/trading/composite_leg_commands.cpp"
    "app/commands/trading/credit_instrument_commands.cpp"
    "app/commands/trading/equity_accumulator_instrument_commands.cpp"
    "app/commands/trading/equity_asian_option_instrument_commands.cpp"
    "app/commands/trading/equity_barrier_option_instrument_commands.cpp"
    "app/commands/trading/equity_digital_option_instrument_commands.cpp"
    "app/commands/trading/equity_forward_instrument_commands.cpp"
    "app/commands/trading/equity_option_instrument_commands.cpp"
    "app/commands/trading/equity_position_instrument_commands.cpp"
    "app/commands/trading/equity_position_option_underlying_commands.cpp"
    "app/commands/trading/equity_swap_instrument_commands.cpp"
    "app/commands/trading/equity_variance_swap_instrument_commands.cpp"
    "app/commands/trading/exercise_type_commands.cpp"
    "app/commands/trading/fpml_event_type_commands.cpp"
    "app/commands/trading/fra_instrument_commands.cpp"
    "app/commands/trading/fx_accumulator_instrument_commands.cpp"
    "app/commands/trading/fx_asian_forward_instrument_commands.cpp"
    "app/commands/trading/fx_barrier_option_instrument_commands.cpp"
    "app/commands/trading/fx_digital_option_instrument_commands.cpp"
    "app/commands/trading/fx_forward_instrument_commands.cpp"
    "app/commands/trading/fx_vanilla_option_instrument_commands.cpp"
    "app/commands/trading/fx_variance_swap_instrument_commands.cpp"
    "app/commands/trading/inflation_swap_instrument_commands.cpp"
    "app/commands/trading/knock_out_swap_instrument_commands.cpp"
    "app/commands/trading/lifecycle_event_commands.cpp"
    "app/commands/trading/long_short_type_commands.cpp"
    "app/commands/trading/moment_type_commands.cpp"
    "app/commands/trading/option_type_commands.cpp"
    "app/commands/trading/party_role_type_commands.cpp"
    "app/commands/trading/payoff_type_commands.cpp"
    "app/commands/trading/price_type_commands.cpp"
    "app/commands/trading/rate_instrument_commands.cpp"
    "app/commands/trading/return_type_commands.cpp"
    "app/commands/trading/rpa_instrument_commands.cpp"
    "app/commands/trading/scripted_instrument_commands.cpp"
    "app/commands/trading/settlement_type_commands.cpp"
    "app/commands/trading/structure_commands.cpp"
    "app/commands/trading/structure_kind_commands.cpp"
    "app/commands/trading/structure_member_commands.cpp"
    "app/commands/trading/structure_template_commands.cpp"
    "app/commands/trading/structure_template_role_commands.cpp"
    "app/commands/trading/swap_leg_commands.cpp"
    "app/commands/trading/swaption_instrument_commands.cpp"
    "app/commands/trading/trade_booking_commands.cpp"
    "app/commands/trading/trade_id_type_commands.cpp"
    "app/commands/trading/trade_identifier_commands.cpp"
    "app/commands/trading/trade_link_commands.cpp"
    "app/commands/trading/trade_link_type_commands.cpp"
    "app/commands/trading/trade_party_role_commands.cpp"
    "app/commands/trading/trade_state_commands.cpp"
    "app/commands/trading/trade_type_commands.cpp"
    "app/commands/trading/vanilla_swap_instrument_commands.cpp"
)

# The headers are listed for the install and IDE targets.
set(HEADERS
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/activity_category_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/activity_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/amortization_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/average_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/balance_guaranteed_swap_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/barrier_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/bond_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/bond_issue_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/callable_swap_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/cap_floor_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/commodity_basket_constituent_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/commodity_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/composite_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/composite_leg_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/credit_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/equity_accumulator_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/equity_asian_option_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/equity_barrier_option_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/equity_digital_option_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/equity_forward_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/equity_option_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/equity_position_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/equity_position_option_underlying_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/equity_swap_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/equity_variance_swap_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/exercise_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/fpml_event_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/fra_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/fx_accumulator_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/fx_asian_forward_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/fx_barrier_option_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/fx_digital_option_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/fx_forward_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/fx_vanilla_option_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/fx_variance_swap_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/inflation_swap_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/knock_out_swap_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/lifecycle_event_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/long_short_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/moment_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/option_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/party_role_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/payoff_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/price_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/rate_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/return_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/rpa_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/scripted_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/settlement_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/structure_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/structure_kind_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/structure_member_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/structure_template_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/structure_template_role_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/swap_leg_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/swaption_instrument_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/trade_booking_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/trade_id_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/trade_identifier_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/trade_link_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/trade_link_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/trade_party_role_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/trade_state_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/trade_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/trading/vanilla_swap_instrument_commands.hpp"
)
