# -*- mode: cmake; cmake-tab-width: 4; indent-tabs-mode: nil -*-
#
# Copyright (C) 2024 Marco Craveiro <marco.craveiro@gmail.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
# Street, Fifth Floor, Boston, MA 02110-1301, USA.
#

# File sourced from here:
# - https://github.com/alisw/AliRoot/blob/master/CTestCustom.cmake
# - https://github.com/Slicer/Slicer/blob/main/CMake/CTestCustom.cmake.in


# number of warnings to display
set(CTEST_CUSTOM_MAXIMUM_NUMBER_OF_WARNINGS "500")

# number of errors to display
set(CTEST_CUSTOM_MAXIMUM_NUMBER_OF_ERRORS "50")

# Set limits for test output
set(CTEST_CUSTOM_MAXIMUM_PASSED_TEST_OUTPUT_SIZE 0)
set(CTEST_CUSTOM_MAXIMUM_FAILED_TEST_OUTPUT_SIZE 0)

# warning exceptions
list(APPEND CTEST_CUSTOM_WARNING_EXCEPTION
    #
    # vcpkg-related warnings (configure phase - may not filter during configure)
    #
    # RPath in OSX (install_name_tool can't be redone)
    "z_vcpkg_fixup_rpath_macho"
    "fixup_rpath_macho"
    # boost-system's buildsystem uses very long paths
    "vcpkg_buildpath_length_warning"
    # could not find a matching pdb file (Windows)
    "vcpkg_copy_pdbs"
    "could not find a matching pdb"
    # vcpkg unused variable warnings (e.g. PCRE2_STATIC_RUNTIME)
    "MAYBE_UNUSED_VARIABLES"
    # vcpkg portfile warnings
    "ports/.*portfile\\.cmake"
    "scripts/cmake/vcpkg"

    #
    # Windows-specific warnings
    #
    # MSVC deprecation warnings in external headers
    "This function or variable may be unsafe"
    "Please define _CRT_SECURE_NO_WARNINGS"
    # DLL export warnings
    "needs to have dll-interface"
    # Windows SDK warnings
    "Windows SDK"
    # Linker warnings about missing PDBs (common in vcpkg builds)
    "LNK4099"
    # Code analysis warnings we can ignore
    "C26.*"
    # vcpkg installed headers
    "vcpkg_installed"

    #
    # macOS-specific warnings
    #
    # install_name_tool warnings
    "install_name_tool"
    # Code signing warnings
    "codesign"
    # Framework warnings
    "framework"
    # Deprecation warnings in system headers
    "is deprecated"
    # macOS SDK warnings
    "MacOSX.*\\.sdk"

    #
    # Common third-party library warnings to ignore
    #
    # Boost
    "boost/"
    "BOOST_"
    # Qt (moc, uic generated)
    "moc_.*\\.cpp"
    "ui_.*\\.h"
    "qrc_.*\\.cpp"
    # ICU
    "ports/icu"
    # qtbase
    "ports/qtbase"

    #
    # CMake-generated warnings
    #
    "CMake Warning \\(dev\\)"
    "Policy CMP"
)

# warning addons
set(CTEST_CUSTOM_WARNING_MATCH ${CTEST_CUSTOM_WARNING_MATCH})
set(CTEST_CUSTOM_COVERAGE_EXCLUDE
  # exclude try_compile sources from coverage results:
  "/CMakeFiles/CMakeTmp/"
  # exclude files generated by the moc pre-compiler
  ".*/moc_.*"
  # exclude files generated by the uic pre-compiler
  ".*/ui_.*"
  # exclude files generated by the resource pre-compiler
  ".*/qrc_.*"
  # exclude files from the testing directories
  ".*/Tests/.*"
  # exclude qt designer plugins
  ".*/DesignerPlugins/.*"
  # exclude qt designer plugins
  ".*/DesignerPlugins/.*"
  # exclude VCPKG headers
  "vcpkg_installed/.*"
)

# error execptions:
# get rid of boost warnings which are misinterpreted as errors
# set(CTEST_CUSTOM_ERROR_EXCEPTION ${CTEST_CUSTOM_ERROR_EXCEPTION}
# "/include/boost/")
