' -*- mode: plantuml; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
'
' Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
'
' This program is free software; you can redistribute it and/or modify it under
' the terms of the GNU General Public License as published by the Free Software
' Foundation; either version 3 of the License, or (at your option) any later
' version.
'
' This program is distributed in the hope that it will be useful, but WITHOUT
' ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
' FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with
' this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
' Street, Fifth Floor, Boston, MA 02110-1301, USA.
'
@startuml

title Codegen org-entity meta-model

skinparam backgroundColor #FEFEFE
skinparam classAttributeIconSize 0

class CommonFrontmatter <<segment>>
class EntityFrontmatter <<segment>>
CommonFrontmatter <|-- EntityFrontmatter

abstract class Base <<metaclass>> {
  +frontmatter : CommonFrontmatter
}
Base "1" *-- "1" CommonFrontmatter

class Entity <<metaclass>> {
  +frontmatter : EntityFrontmatter
  +keysAndColumns : KeysAndColumns
  +sql : SQL
  +cppDomain : CppDomain
  +cppRepository : CppRepository
  +cppService : CppService
  +cppProtocol : CppProtocol
  +cppNats : CppNats
  +cppQt : CppQt
  +cppGenerator : CppGenerator
  +cppPresentation : CppPresentation
}
Base <|-- Entity

class KeysAndColumns <<segment>>
class SQL <<segment>>
class CppDomain <<segment>>
class CppRepository <<segment>>
class CppService <<segment>>
class CppProtocol <<segment>>
class CppNats <<segment>>
class CppQt <<segment>>
class CppGenerator <<segment>>
class CppPresentation <<segment>>

Entity "1" *-- "1" KeysAndColumns
Entity "1" *-- "1" SQL
Entity "1" *-- "1" CppDomain
Entity "1" *-- "1" CppRepository
Entity "1" *-- "1" CppService
Entity "1" *-- "1" CppProtocol
Entity "1" *-- "1" CppNats
Entity "1" *-- "1" CppQt
Entity "1" *-- "1" CppGenerator
Entity "1" *-- "1" CppPresentation

@enduml
