' -*- mode: plantuml; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
'
' Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
'
' This program is free software; you can redistribute it and/or modify it under
' the terms of the GNU General Public License as published by the Free Software
' Foundation; either version 3 of the License, or (at your option) any later
' version.
'
' This program is distributed in the hope that it will be useful, but WITHOUT
' ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
' FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with
' this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
' Street, Fifth Floor, Boston, MA 02110-1301, USA.
'
@startuml

title ores.qt Component

set namespaceSeparator ::

namespace ores #F2F2F2 {
    namespace qt #F2F2F2 {
        class AboutDialog {
            +parent : QWidget*
            -ui_ : unique_ptr<Ui::AboutDialog>
            -logoLabel_ : LogoLabel*
            -clientManager_ : ClientManager*
        }
        enum ItemType {
            Folder
            Environment
            Connection
        }
        class AddItemDialog {
            +parent : QWidget*
            -manager_ : connections::service::connection_manager*
            -saveButton_ : QPushButton*
            -cancelButton_ : QPushButton*
            -testButton_ : QPushButton*
            -typeCombo_ : QComboBox*
            -nameEdit_ : QLineEdit*
            -folderCombo_ : QComboBox*
            -descriptionEdit_ : QTextEdit*
            -environmentLabel_ : QLabel*
            -environmentCombo_ : QComboBox*
            -hostLabel_ : QLabel*
            -hostEdit_ : QLineEdit*
            -portLabel_ : QLabel*
            -portSpinBox_ : QSpinBox*
            -httpPortLabel_ : QLabel*
            -httpPortSpinBox_ : QSpinBox*
            -namespaceLabel_ : QLabel*
            -namespaceEdit_ : QLineEdit*
            -usernameLabel_ : QLabel*
            -usernameEdit_ : QLineEdit*
            -passwordLabel_ : QLabel*
            -passwordEdit_ : QLineEdit*
            -showPasswordCheckbox_ : QCheckBox*
            -passwordWidget_ : QWidget*
            -tagLabel_ : QLabel*
            -tagSelector_ : TagSelectorWidget*
            -folderId_ : boost::uuids::uuid
            -pureEnvironmentId_ : boost::uuids::uuid
            -connectionId_ : boost::uuids::uuid
            -linkedEnvironmentId_ : optional<boost::uuids::uuid>
            -testCallback_ : TestConnectionCallback
        }
        class ChangePasswordDialog {
            -new_password_edit_ : QLineEdit*
            -confirm_password_edit_ : QLineEdit*
            -change_button_ : QPushButton*
            -cancel_button_ : QPushButton*
            -status_label_ : QLabel*
            -info_label_ : QLabel*
            -clientManager_ : ClientManager*
        }
        class ClientTelemetryLogModel {
            +parent : QObject*
            +role : int
            -clientManager_ : ClientManager*
            -entries_ : vector<telemetry::domain::telemetry_log_entry>
            -watcher_ : QFutureWatcher<FetchResult>*
            -current_session_id_ : optional<boost::uuids::uuid>
            -start_time_ : chrono::system_clock::time_point
            -end_time_ : chrono::system_clock::time_point
            -min_level_ : optional<string>
            -message_filter_ : optional<string>
            -tag_filter_ : optional<string>
            -component_filter_ : optional<string>
        }
        class CommandLineParser {
            -parser_ : QCommandLineParser
        }
        class ConnectionBrowserMdiWindow {
            +parent : QWidget*
            -layout_ : QVBoxLayout*
            -splitter_ : QSplitter*
            -treeView_ : QTreeView*
            -detailPanel_ : ConnectionDetailPanel*
            -toolBar_ : QToolBar*
            -addAction_ : QAction*
            -editAction_ : QAction*
            -copyAction_ : QAction*
            -deleteAction_ : QAction*
            -connectAction_ : QAction*
            -refreshAction_ : QAction*
            -changeMasterPasswordAction_ : QAction*
            -purgeDatabaseAction_ : QAction*
            -model_ : unique_ptr<ConnectionTreeModel>
            -manager_ : connections::service::connection_manager*
            -testCallback_ : TestConnectionCallback
            -mdiArea_ : QMdiArea*
            -mainWindow_ : QMainWindow*
            -allDetachableWindows_ : QList<QPointer<DetachableMdiSubWindow>>*
            -savedWindowSize_ : QSize
        }
        class ConnectionDetailPanel {
            +parent : QWidget*
            -manager_ : connections::service::connection_manager*
            -stackedWidget_ : QStackedWidget*
            -emptyPage_ : QWidget*
            -folderPage_ : QWidget*
            -folderNameLabel_ : QLabel*
            -folderItemCountLabel_ : QLabel*
            -folderDescriptionLabel_ : QLabel*
            -environmentPage_ : QWidget*
            -envNameLabel_ : QLabel*
            -envHostLabel_ : QLabel*
            -envPortLabel_ : QLabel*
            -envHttpPortLabel_ : QLabel*
            -envNamespaceLabel_ : QLabel*
            -envDescriptionLabel_ : QLabel*
            -envTagsContainer_ : QWidget*
            -connectionPage_ : QWidget*
            -connNameLabel_ : QLabel*
            -connHostLabel_ : QLabel*
            -connPortLabel_ : QLabel*
            -connNamespaceLabel_ : QLabel*
            -connUsernameLabel_ : QLabel*
            -connDescriptionLabel_ : QLabel*
            -connTagsContainer_ : QWidget*
        }
        class ConnectionItemDelegate {
        }
        class ConnectionTreeNode <<struct>> {
            +name : QString
            +parent_id : optional<boost::uuids::uuid>
            +host : QString
            +username : QString
            +description : QString
            +environment_id : optional<boost::uuids::uuid>
            +children : vector<unique_ptr<ConnectionTreeNode>>
        }
        class ConnectionTreeModel {
            +parent : QObject*
            +role : int
            +role : int
            -manager_ : connections::service::connection_manager*
            -rootNode_ : unique_ptr<ConnectionTreeNode>
            -folderIcon_ : QIcon
            -folderOpenIcon_ : QIcon
            -serverIcon_ : QIcon
            -plugIcon_ : QIcon
            -expandedFolders_ : unordered_set<boost::uuids::uuid>
        }
        class EventRecord <<struct>> {
            +timestamp : QDateTime
            +eventType : QString
            +source : QString
            +summary : QString
            +jsonPayload : QString
        }
        class EventTableModel {
            +role : int
            +role : int
            -events_ : deque<EventRecord>
        }
        class EventViewerWindow {
            +parent : QWidget*
            -eventBus_ : shared_ptr<eventing::service::event_bus>
            -clientManager_ : ClientManager*
            -tableView_ : QTableView*
            -model_ : EventTableModel*
            -statusLabel_ : QLabel*
            -clearButton_ : QPushButton*
            -subscriptions_ : vector<eventing::service::subscription>
        }
        class LoginDialog {
            -loginTitleLabel_ : QLabel*
            -usernameEdit_ : QLineEdit*
            -passwordEdit_ : QLineEdit*
            -showPasswordCheck_ : QCheckBox*
            -rememberMeCheck_ : QCheckBox*
            -loginButton_ : QPushButton*
            -signUpButton_ : QPushButton*
            -signUpLabel_ : QLabel*
            -statusLabel_ : QLabel*
            -hostEdit_ : QLineEdit*
            -portSpinBox_ : QSpinBox*
            -subjectPrefixEdit_ : QLineEdit*
            -allItems_ : QList<QuickConnectItem>
        }
        class LogoLabel {
            -overlayText_ : QString
        }
        class MainWindow {
            -ui_ : Ui::MainWindow*
            -mdiArea_ : MdiAreaWithBackground*
            -connectionStatusIconLabel_ : QLabel*
            -userStatusWidget_ : QWidget*
            -userStatusNameLabel_ : QLabel*
            -serverStatusWidget_ : QWidget*
            -serverStatusNameLabel_ : QLabel*
            -tenantStatusWidget_ : QWidget*
            -tenantStatusNameLabel_ : QLabel*
            -partyStatusWidget_ : QWidget*
            -partyStatusNameLabel_ : QLabel*
            -envLabelWidget_ : QWidget*
            -envLabelNameLabel_ : QLabel*
            -allDetachableWindows_ : QList<QPointer<DetachableMdiSubWindow>>
            -connectedIcon_ : QIcon
            -disconnectedIcon_ : QIcon
            -reconnectingIcon_ : QIcon
            -recordOffIcon_ : QIcon
            -recordOnIcon_ : QIcon
            -plugin_menus_ : QList<QMenu*>
            -plugin_toolbar_actions_ : QList<QAction*>
            -eventBus_ : shared_ptr<eventing::service::event_bus>
            -clientManager_ : ClientManager*
            -imageCache_ : ImageCache*
            -changeReasonCache_ : ChangeReasonCache*
            -badgeCache_ : BadgeCache*
            -username_ : string
            -httpBaseUrl_ : string
            -party_name_ : QString
            -systemTrayIcon_ : QSystemTrayIcon*
            -trayContextMenu_ : QMenu*
            -eventSubscriptions_ : vector<eventing::service::subscription>
            -instanceName_ : QString
            -instanceColor_ : QColor
            -instanceColorIndicator_ : QLabel*
            -eventViewerWindow_ : DetachableMdiSubWindow*
            -telemetryViewerWindow_ : DetachableMdiSubWindow*
            -connectionManager_ : unique_ptr<connections::service::connection_manager>
            -activeConnectionName_ : QString
            -masterPassword_ : QString
        }
        class MasterPasswordDialog {
            -mode_ : Mode
            -infoLabel_ : QLabel*
            -currentPasswordEdit_ : QLineEdit*
            -newPasswordEdit_ : QLineEdit*
            -confirmPasswordEdit_ : QLineEdit*
            -showPasswordCheck_ : QCheckBox*
            -buttonBox_ : QDialogButtonBox*
        }
        class MyAccountDialog {
            -toolbar_ : QToolBar*
            -tabWidget_ : QTabWidget*
            -username_edit_ : QLineEdit*
            -email_edit_ : QLineEdit*
            -save_email_button_ : QPushButton*
            -email_status_label_ : QLabel*
            -active_sessions_label_ : QLabel*
            -current_session_label_ : QLabel*
            -view_sessions_button_ : QPushButton*
            -new_password_edit_ : QLineEdit*
            -confirm_password_edit_ : QLineEdit*
            -change_password_button_ : QPushButton*
            -password_status_label_ : QLabel*
            -clientManager_ : ClientManager*
        }
        class OreLogViewerWidget {
            +parent : QWidget*
            -client_manager_ : ClientManager*
            -current_result_id_ : QString
            -model_ : unique_ptr<ClientTelemetryLogModel>
        }
        class PartyProvisioningWizard {
            +parent : QWidget*
            -clientManager_ : ClientManager*
            -selectedBundleCode_ : QString
            -leiDatasetSize_ : QString
            -organisationPublished_ : bool
            -selectedReports_ : vector<ReportSpec>
        }
        class PartyWelcomePage {
            -wizard_ : PartyProvisioningWizard*
        }
        class PartyCounterpartySetupPage {
            -wizard_ : PartyProvisioningWizard*
            -datasetSizeCombo_ : QComboBox*
        }
        class PartyOrganisationSetupPage {
            -wizard_ : PartyProvisioningWizard*
            -statusLabel_ : QLabel*
            -progressBar_ : QProgressBar*
            -logOutput_ : QTextEdit*
            -publishComplete_ : bool
            -publishSuccess_ : bool
        }
        class PartyReportSetupPage {
            -wizard_ : PartyProvisioningWizard*
            -loadingLabel_ : QLabel*
            -errorLabel_ : QLabel*
            -reportList_ : QListWidget*
        }
        class PartyReportInstallPage {
            -wizard_ : PartyProvisioningWizard*
            -statusLabel_ : QLabel*
            -progressBar_ : QProgressBar*
            -logOutput_ : QTextEdit*
            -installComplete_ : bool
            -installSuccess_ : bool
        }
        class PartyApplyAndSummaryPage {
            -wizard_ : PartyProvisioningWizard*
            -summaryLabel_ : QLabel*
        }
        class SessionAuditModel {
            +role : int
            -sessions_ : vector<iam::domain::session>
            -activeIcon_ : QIcon
            -historyIcon_ : QIcon
        }
        class SessionAuditDialog {
            +parent : QWidget*
            -tableView_ : QTableView*
            -model_ : SessionAuditModel*
            -splitter_ : QSplitter*
            -chartView_ : QChartView*
            -clientManager_ : ClientManager*
            -accountId_ : boost::uuids::uuid
            -username_ : QString
            -watcher_ : QFutureWatcher<FetchResult>*
            -samplesWatcher_ : QFutureWatcher<FetchSamplesResult>*
            -sampleRefreshTimer_ : QTimer*
            -hasSelectedSession_ : bool
            -selectedSessionLabel_ : QString
            -selectedSessionActive_ : bool
        }
        class qt_output_streambuf {
            -mutex_ : mutex
            -buffer_ : string
        }
        class qt_input_streambuf {
            -mutex_ : mutex
            -cv_ : condition_variable
            -pending_ : deque<string>
            -current_ : string
        }
        class ShellMdiWindow {
            +parent : QWidget*
            -client_manager_ : ClientManager*
            -toolbar_ : QToolBar*
            -output_area_ : QPlainTextEdit*
            -input_line_ : QLineEdit*
            -output_buf_ : unique_ptr<qt_output_streambuf>
            -input_buf_ : unique_ptr<qt_input_streambuf>
            -out_stream_ : unique_ptr<ostream>
            -in_stream_ : unique_ptr<istream>
            -shell_session_ : ores::nats::service::nats_client
            -shell_repl_ : unique_ptr<shell::app::repl>
            -worker_thread_ : unique_ptr<thread>
            -command_history_ : vector<string>
        }
        class SignUpDialog {
            -titleLabel_ : QLabel*
            -usernameEdit_ : QLineEdit*
            -emailEdit_ : QLineEdit*
            -passwordEdit_ : QLineEdit*
            -confirmPasswordEdit_ : QLineEdit*
            -showPasswordCheck_ : QCheckBox*
            -signUpButton_ : QPushButton*
            -loginButton_ : QPushButton*
            -loginLabel_ : QLabel*
            -statusLabel_ : QLabel*
            -hostEdit_ : QLineEdit*
            -portSpinBox_ : QSpinBox*
            -registeredUsername_ : QString
        }
        class SystemProvisionerWizard {
            +parent : QWidget*
            -clientManager_ : ClientManager*
            -adminUsername_ : QString
            -adminEmail_ : QString
            -adminPassword_ : QString
            -adminAccountId_ : string
            -multiTenantMode_ : bool
            -tenantCode_ : QString
            -tenantName_ : QString
            -tenantHostname_ : QString
            -tenantDescription_ : QString
            -tenantAdminUsername_ : QString
            -tenantAdminPassword_ : QString
            -tenantAdminEmail_ : QString
            -provisionedTenantId_ : QString
        }
        class WelcomePage {
            -wizard_ : SystemProvisionerWizard*
        }
        class AdminAccountPage {
            -wizard_ : SystemProvisionerWizard*
            -usernameEdit_ : QLineEdit*
            -emailEdit_ : QLineEdit*
            -passwordEdit_ : QLineEdit*
            -confirmPasswordEdit_ : QLineEdit*
            -showPasswordCheckbox_ : QCheckBox*
            -validationLabel_ : QLabel*
            -accountCreated_ : bool
        }
        class SetupModePage {
            -wizard_ : SystemProvisionerWizard*
            -singleTenantRadio_ : QRadioButton*
            -multiTenantRadio_ : QRadioButton*
        }
        class ProvisionerTenantDetailsPage {
            -wizard_ : SystemProvisionerWizard*
            -codeEdit_ : QLineEdit*
            -editCodeButton_ : QPushButton*
            -nameEdit_ : QLineEdit*
            -typeCombo_ : QComboBox*
            -hostnameEdit_ : QLineEdit*
            -descriptionEdit_ : QLineEdit*
            -validationLabel_ : QLabel*
            -hostnameManuallyEdited_ : bool
            -codeManuallyEdited_ : bool
        }
        class ProvisionerTenantAdminPage {
            -wizard_ : SystemProvisionerWizard*
            -usernameEdit_ : QLineEdit*
            -emailEdit_ : QLineEdit*
            -passwordEdit_ : QLineEdit*
            -confirmPasswordEdit_ : QLineEdit*
            -showPasswordCheck_ : QCheckBox*
            -validationLabel_ : QLabel*
        }
        class ProvisionerApplyPage {
            -wizard_ : SystemProvisionerWizard*
            -statusLabel_ : QLabel*
            -progressBar_ : QProgressBar*
            -logOutput_ : QTextEdit*
            -provisioningComplete_ : bool
            -provisioningSuccess_ : bool
        }
        class ProvisionerCompletePage {
            -wizard_ : SystemProvisionerWizard*
            -summaryLabel_ : QLabel*
            -nextStepsLabel_ : QLabel*
        }
        class TagSelectorWidget {
            +parent : QWidget*
            -manager_ : connections::service::connection_manager*
            -layout_ : QHBoxLayout*
            -addButton_ : QToolButton*
            -tagMenu_ : QMenu*
            -selectedTags_ : vector<connections::domain::tag>
        }
        class TelemetryLogDelegate {
            -monospaceFont_ : QFont
            -badgeFont_ : QFont
        }
        class TelemetryMdiWindow {
            +parent : QWidget*
            -mainSplitter_ : QSplitter*
            -leftPanel_ : QWidget*
            -rightPanel_ : QWidget*
            -leftSplitter_ : QSplitter*
            -sessionTree_ : QTreeWidget*
            -sessionDetailsGroup_ : QGroupBox*
            -sessionDetailsTable_ : QTableWidget*
            -rightLayout_ : QVBoxLayout*
            -toolBar_ : QToolBar*
            -logTableView_ : QTableView*
            -paginationWidget_ : PaginationWidget*
            -logDetailGroup_ : QGroupBox*
            -logMessageEdit_ : QTextEdit*
            -filterTraceBtn_ : QPushButton*
            -filterDebugBtn_ : QPushButton*
            -filterInfoBtn_ : QPushButton*
            -filterWarnBtn_ : QPushButton*
            -filterErrorBtn_ : QPushButton*
            -reloadAction_ : QAction*
            -normalReloadIcon_ : QIcon
            -staleReloadIcon_ : QIcon
            -pulseTimer_ : QTimer*
            -logModel_ : unique_ptr<ClientTelemetryLogModel>
            -proxyModel_ : QSortFilterProxyModel*
            -clientManager_ : ClientManager*
            -username_ : QString
            -sessionCache_ : unordered_map<string, iam::domain::session>
            -selectedSessionId_ : optional<boost::uuids::uuid>
        }
        class TelemetrySettingsDialog {
            -tab_widget_ : QTabWidget*
            -logging_enabled_checkbox_ : QCheckBox*
            -log_level_combo_ : QComboBox*
            -console_output_checkbox_ : QCheckBox*
            -log_directory_edit_ : QLineEdit*
            -log_directory_browse_ : QPushButton*
            -log_filename_edit_ : QLineEdit*
            -include_pid_checkbox_ : QCheckBox*
            -tag_filter_edit_ : QLineEdit*
            -telemetry_enabled_checkbox_ : QCheckBox*
            -telemetry_output_file_edit_ : QLineEdit*
            -telemetry_directory_edit_ : QLineEdit*
            -telemetry_directory_browse_ : QPushButton*
            -streaming_enabled_checkbox_ : QCheckBox*
            -batch_size_spin_ : QSpinBox*
            -flush_interval_spin_ : QSpinBox*
            -compression_enabled_checkbox_ : QCheckBox*
            -compression_algorithm_combo_ : QComboBox*
            -apply_button_ : QPushButton*
            -cancel_button_ : QPushButton*
        }
        class TenantProvisioningWizard {
            +parent : QWidget*
            -clientManager_ : ClientManager*
            -selectedBundleCode_ : QString
            -selectedBundleName_ : QString
            -dataSourceMode_ : DataSourceMode
            -rootLei_ : QString
            -rootLeiName_ : QString
            -leiDatasetSize_ : QString
            -syntheticCountry_ : QString
            -syntheticPartyCount_ : int
            -syntheticPartyMaxDepth_ : int
            -syntheticCounterpartyCount_ : int
            -syntheticCounterpartyMaxDepth_ : int
            -syntheticPortfolioLeafCount_ : int
            -syntheticPortfolioMaxDepth_ : int
            -syntheticBooksPerPortfolio_ : int
            -syntheticBusinessUnitCount_ : int
            -syntheticBusinessUnitMaxDepth_ : int
            -syntheticGenerateAddresses_ : bool
            -syntheticContactsPerParty_ : int
            -syntheticContactsPerCounterparty_ : int
            -syntheticGenerateIdentifiers_ : bool
            -syntheticSeed_ : optional<uint64_t>
            -partiesLinkedCount_ : int
        }
        class ProvisioningWelcomePage {
            -wizard_ : TenantProvisioningWizard*
        }
        class BundleSelectionPage {
            -wizard_ : TenantProvisioningWizard*
            -bundleModel_ : ClientDatasetBundleModel*
            -bundleCombo_ : QComboBox*
            -descriptionLabel_ : QLabel*
            -statusLabel_ : QLabel*
        }
        class BundleInstallPage {
            -wizard_ : TenantProvisioningWizard*
            -statusLabel_ : QLabel*
            -progressBar_ : QProgressBar*
            -logOutput_ : QTextEdit*
            -publishComplete_ : bool
            -publishSuccess_ : bool
        }
        class TenantDataSourceSelectionPage {
            -wizard_ : TenantProvisioningWizard*
            -gleifRadio_ : QRadioButton*
            -syntheticRadio_ : QRadioButton*
            -syntheticOptions_ : QWidget*
            -countryCombo_ : QComboBox*
            -partyCountSpin_ : QSpinBox*
            -partyMaxDepthSpin_ : QSpinBox*
            -counterpartyCountSpin_ : QSpinBox*
            -counterpartyMaxDepthSpin_ : QSpinBox*
            -portfolioLeafCountSpin_ : QSpinBox*
            -portfolioMaxDepthSpin_ : QSpinBox*
            -booksPerPortfolioSpin_ : QSpinBox*
            -businessUnitCountSpin_ : QSpinBox*
            -businessUnitMaxDepthSpin_ : QSpinBox*
            -contactsPerPartySpin_ : QSpinBox*
            -contactsPerCounterpartySpin_ : QSpinBox*
            -generateAddressesCheck_ : QCheckBox*
            -generateIdentifiersCheck_ : QCheckBox*
            -seedEdit_ : QLineEdit*
        }
        class TenantPartySetupPage {
            -wizard_ : TenantProvisioningWizard*
            -instructionLabel_ : QLabel*
            -datasetSizeCombo_ : QComboBox*
            -leiPicker_ : LeiEntityPicker*
            -leiLoaded_ : bool
        }
        class TenantPartyOrganisationPage {
            -wizard_ : TenantProvisioningWizard*
            -statusLabel_ : QLabel*
            -progressBar_ : QProgressBar*
            -logOutput_ : QTextEdit*
            -publishComplete_ : bool
            -publishSuccess_ : bool
        }
        class TenantApplyAndSummaryPage {
            -wizard_ : TenantProvisioningWizard*
            -summaryLabel_ : QLabel*
        }
    }
}

' --- manual: everything below this line is hand-authored; the script preserves it ---

' Local Variables:
' compile-command: "java -Djava.awt.headless=true -DPLANTUML_SECURITY_PROFILE=UNSECURE -DPLANTUML_LIMIT_SIZE=65535 -jar /usr/share/plantuml/plantuml.jar ores.qt.puml"
' End:
@enduml
