/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

/**
 * ORE Application Seed Script
 *
 * Seeds the ORE (Open Source Risk Engine) application and its standard app
 * version in the compute grid. Idempotent: guarded by name/version lookups
 * so it is safe to run on every database recreation. UUIDs are generated by
 * PostgreSQL on first insert and looked up on subsequent runs.
 *
 * The system tenant (ffffffff-ffff-ffff-ffff-ffffffffffff) owns these
 * records so they are visible to all tenants through RLS.
 */

\echo '--- ORE Application Seed ---'

-- -------------------------------------------------------------------------
-- ORE Application
-- -------------------------------------------------------------------------
insert into ores_compute_apps_tbl (
    id,
    tenant_id,
    version,
    name,
    description,
    modified_by,
    performed_by,
    change_reason_code,
    change_commentary,
    valid_from,
    valid_to
)
select
    gen_random_uuid(),
    ores_iam_system_tenant_id_fn(),
    1,
    'ORE',
    'Open Source Risk Engine — QuantLib-based risk analytics engine for '
    'market risk, counterparty credit risk, XVA, and sensitivity analysis.',
    current_user,
    current_user,
    'system.new_record',
    '',
    current_timestamp,
    ores_utility_infinity_timestamp_fn()
where not exists (
    select 1 from ores_compute_apps_tbl
    where name = 'ORE'
      and tenant_id = ores_iam_system_tenant_id_fn()
      and valid_to = ores_utility_infinity_timestamp_fn()
);

-- -------------------------------------------------------------------------
-- ORE App Version 1.8.15.0 (linux-x86_64)
-- -------------------------------------------------------------------------
with ore_app as (
    select id from ores_compute_apps_tbl
    where name = 'ORE'
      and tenant_id = ores_iam_system_tenant_id_fn()
      and valid_to = ores_utility_infinity_timestamp_fn()
),
new_version_id as (
    select gen_random_uuid() as uuid
),
inserted_version as (
    insert into ores_compute_app_versions_tbl (
        id,
        tenant_id,
        version,
        app_id,
        wrapper_version,
        engine_version,
        package_uri,
        min_ram_mb,
        modified_by,
        performed_by,
        change_reason_code,
        change_commentary,
        valid_from,
        valid_to
    )
    select
        new_version_id.uuid,
        ores_iam_system_tenant_id_fn(),
        1,
        ore_app.id,
        '1.0.0',
        '1.8.15.0',
        '/api/v1/storage/compute/packages/' || new_version_id.uuid::text,
        512,
        current_user,
        current_user,
        'system.new_record',
        '',
        current_timestamp,
        ores_utility_infinity_timestamp_fn()
    from ore_app
    cross join new_version_id
    where not exists (
        select 1 from ores_compute_app_versions_tbl av
        join ore_app on av.app_id = ore_app.id
        where av.engine_version = '1.8.15.0'
          and av.wrapper_version = '1.0.0'
          and av.tenant_id = ores_iam_system_tenant_id_fn()
          and av.valid_to = ores_utility_infinity_timestamp_fn()
    )
    returning id
),
app_version_id as (
    select id from inserted_version
    union all
    select av.id
    from ores_compute_app_versions_tbl av
    join ore_app on av.app_id = ore_app.id
    where av.engine_version = '1.8.15.0'
      and av.wrapper_version = '1.0.0'
      and av.tenant_id = ores_iam_system_tenant_id_fn()
      and av.valid_to = ores_utility_infinity_timestamp_fn()
    limit 1
)
-- -------------------------------------------------------------------------
-- ORE App Version Platform (x86_64-unknown-linux-gnu)
-- -------------------------------------------------------------------------
insert into ores_compute_app_version_platforms_tbl (
    tenant_id,
    app_version_id,
    platform_id,
    modified_by,
    performed_by,
    change_reason_code,
    change_commentary,
    valid_from,
    valid_to
)
select
    ores_iam_system_tenant_id_fn(),
    app_version_id.id,
    p.id,
    current_user,
    current_user,
    'system.new_record',
    '',
    current_timestamp,
    ores_utility_infinity_timestamp_fn()
from app_version_id
join ores_compute_platforms_tbl p
    on p.code = 'x86_64-unknown-linux-gnu'
   and p.valid_to = ores_utility_infinity_timestamp_fn()
where not exists (
    select 1 from ores_compute_app_version_platforms_tbl avp
    join ores_compute_platforms_tbl pl
        on pl.id = avp.platform_id
       and pl.code = 'x86_64-unknown-linux-gnu'
       and pl.valid_to = ores_utility_infinity_timestamp_fn()
    where avp.app_version_id = app_version_id.id
      and avp.tenant_id = ores_iam_system_tenant_id_fn()
      and avp.valid_to = ores_utility_infinity_timestamp_fn()
);
