/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * IP to Country Reference Data Master Include File
 *
 * Auto-generated by ip2country_generate_metadata_sql.py
 * Includes all IP to country SQL files in the correct dependency order.
 */

-- =============================================================================
-- IP Geolocation Catalog (must come first)
-- =============================================================================

\echo '--- IP Geolocation Catalog ---'
\ir ip2country_catalog_populate.sql

-- =============================================================================
-- IP Geolocation Methodology
-- =============================================================================

\echo '--- IP Geolocation Methodology ---'
\ir ip2country_methodology_populate.sql

-- =============================================================================
-- IP Geolocation Datasets
-- =============================================================================

\echo '--- IP Geolocation Datasets ---'
\ir ip2country_dataset_populate.sql

-- =============================================================================
-- IP Geolocation Dataset Tags
-- =============================================================================

\echo '--- IP Geolocation Dataset Tags ---'
\ir ip2country_dataset_tag_populate.sql

-- =============================================================================
-- IP Geolocation Dataset Dependencies
-- =============================================================================

\echo '--- IP Geolocation Dataset Dependencies ---'
\ir ip2country_dataset_dependency_populate.sql

-- =============================================================================
-- IP to Country Artefacts
-- =============================================================================

\echo '--- IP to Country Artefacts ---'
\ir ip2country_artefact_populate.sql
