/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

/**
 * GLEIF LEI Methodology Population Script
 *
 * Auto-generated from external/lei/manifest.json
 * This script is idempotent.
 */

-- =============================================================================
-- GLEIF LEI Methodology
-- =============================================================================

\echo '--- GLEIF LEI Methodology ---'

select ores_dq_methodologies_upsert_fn(ores_iam_system_tenant_id_fn(),
    'GLEIF Golden Copy Extraction',
    'Data sourced from GLEIF golden copy, published daily at https://www.gleif.org/en/lei-data/gleif-golden-copy. Two CSV file types are used:

1. LEI2 (lei2-golden-copy): Legal entity master data containing ~3.2M records with 338 columns covering identity (LEI code, legal name), classification (entity category, legal form, jurisdiction), addresses (legal and headquarters), and registration metadata. Mapped to ores_dq_lei_entities_artefact_tbl.

2. RR (rr-golden-copy): Corporate hierarchy relationship records containing ~463K records with 54 columns covering parent-child consolidation relationships (IS_DIRECTLY_CONSOLIDATED_BY, IS_ULTIMATELY_CONSOLIDATED_BY), fund management, and branch relationships. Mapped to ores_dq_lei_relationships_artefact_tbl.

Diverse subsets (small ~6K entities, large ~15K entities) are extracted using lei_extract_subset.py which selects entities across countries, sectors, entity categories, fund types, and relationship depths. SQL populate scripts are generated by lei_generate_metadata_sql.py which reads the CSV subsets and produces PL/pgSQL blocks with VALUES clauses for idempotent bulk insertion.',
    'https://www.gleif.org/en/lei-data/gleif-golden-copy',
    'Data sourced from https://www.gleif.org/en/lei-data/gleif-golden-copy

See methodology documentation for detailed steps.'
);
