# -*- mode: cmake; cmake-tab-width: 4; indent-tabs-mode: nil -*-
#
# Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# Template: cmake_component_files_tests.mustache
# To modify, update the template and regenerate.
set(files
    "asset_class_code_commands_tests.cpp"
    "average_ois_convention_commands_tests.cpp"
    "base_correlation_config_commands_tests.cpp"
    "bma_basis_swap_convention_commands_tests.cpp"
    "bond_future_volatility_config_commands_tests.cpp"
    "bond_yield_convention_commands_tests.cpp"
    "book_change_commands_tests.cpp"
    "book_commands_tests.cpp"
    "book_purpose_type_commands_tests.cpp"
    "book_status_commands_tests.cpp"
    "business_centre_commands_tests.cpp"
    "business_day_convention_type_commands_tests.cpp"
    "business_unit_commands_tests.cpp"
    "business_unit_type_commands_tests.cpp"
    "calendar_commands_tests.cpp"
    "calendar_date_commands_tests.cpp"
    "calendar_event_commands_tests.cpp"
    "calendar_exception_commands_tests.cpp"
    "calendar_name_commands_tests.cpp"
    "calendar_rule_commands_tests.cpp"
    "calendar_type_commands_tests.cpp"
    "cap_floor_volatility_config_commands_tests.cpp"
    "cds_convention_commands_tests.cpp"
    "cds_volatility_config_commands_tests.cpp"
    "cds_volatility_term_commands_tests.cpp"
    "cms_spread_option_convention_commands_tests.cpp"
    "commodity_curve_config_commands_tests.cpp"
    "commodity_forward_convention_commands_tests.cpp"
    "commodity_future_convention_commands_tests.cpp"
    "commodity_price_segment_commands_tests.cpp"
    "commodity_volatility_config_commands_tests.cpp"
    "contact_type_commands_tests.cpp"
    "counterparty_business_centre_commands_tests.cpp"
    "counterparty_commands_tests.cpp"
    "counterparty_contact_information_commands_tests.cpp"
    "counterparty_identifier_commands_tests.cpp"
    "country_commands_tests.cpp"
    "crm_driver_pair_commands_tests.cpp"
    "crm_enabled_derived_pair_commands_tests.cpp"
    "crm_topology_config_commands_tests.cpp"
    "cross_currency_basis_convention_commands_tests.cpp"
    "cross_currency_fix_float_convention_commands_tests.cpp"
    "csa_commands_tests.cpp"
    "csa_eligible_currency_commands_tests.cpp"
    "currency_calendar_commands_tests.cpp"
    "currency_commands_tests.cpp"
    "currency_country_commands_tests.cpp"
    "currency_currency_group_commands_tests.cpp"
    "currency_group_commands_tests.cpp"
    "currency_market_tier_commands_tests.cpp"
    "currency_pair_classification_commands_tests.cpp"
    "currency_pair_commands_tests.cpp"
    "currency_pair_convention_calendar_commands_tests.cpp"
    "currency_pair_convention_commands_tests.cpp"
    "curve_bootstrap_config_commands_tests.cpp"
    "curve_configuration_commands_tests.cpp"
    "curve_configuration_section_commands_tests.cpp"
    "curve_correlation_config_commands_tests.cpp"
    "curve_definition_commands_tests.cpp"
    "curve_global_report_commands_tests.cpp"
    "curve_parametric_smile_commands_tests.cpp"
    "curve_parametric_smile_parameter_commands_tests.cpp"
    "curve_quote_commands_tests.cpp"
    "curve_report_configuration_commands_tests.cpp"
    "curve_role_commands_tests.cpp"
    "curve_section_commands_tests.cpp"
    "curve_security_config_commands_tests.cpp"
    "curve_segment_commands_tests.cpp"
    "curve_segment_curve_commands_tests.cpp"
    "curve_segment_type_commands_tests.cpp"
    "curve_volatility_config_commands_tests.cpp"
    "day_count_fraction_type_commands_tests.cpp"
    "day_counter_commands_tests.cpp"
    "default_curve_config_commands_tests.cpp"
    "default_curve_configuration_commands_tests.cpp"
    "deposit_convention_commands_tests.cpp"
    "derivation_kind_commands_tests.cpp"
    "diary_entry_type_commands_tests.cpp"
    "equity_curve_config_commands_tests.cpp"
    "equity_volatility_config_commands_tests.cpp"
    "floating_index_type_commands_tests.cpp"
    "fra_convention_commands_tests.cpp"
    "future_convention_commands_tests.cpp"
    "fx_option_convention_commands_tests.cpp"
    "fx_volatility_config_commands_tests.cpp"
    "ibor_index_convention_commands_tests.cpp"
    "inflation_cap_floor_volatility_config_commands_tests.cpp"
    "inflation_curve_config_commands_tests.cpp"
    "inflation_seasonality_factor_commands_tests.cpp"
    "inflation_swap_convention_commands_tests.cpp"
    "instrument_code_commands_tests.cpp"
    "intraday_power_curve_config_commands_tests.cpp"
    "intraday_power_load_convention_commands_tests.cpp"
    "ir_curve_bootstrap_config_commands_tests.cpp"
    "ir_curve_bootstrap_pillar_commands_tests.cpp"
    "ledger_feed_type_commands_tests.cpp"
    "leg_type_commands_tests.cpp"
    "main.cpp"
    "monetary_nature_commands_tests.cpp"
    "netting_agreement_commands_tests.cpp"
    "netting_set_commands_tests.cpp"
    "netting_set_identifier_commands_tests.cpp"
    "ois_convention_commands_tests.cpp"
    "overnight_index_convention_commands_tests.cpp"
    "party_commands_tests.cpp"
    "party_contact_information_commands_tests.cpp"
    "party_counterparty_commands_tests.cpp"
    "party_country_commands_tests.cpp"
    "party_currency_commands_tests.cpp"
    "party_id_scheme_commands_tests.cpp"
    "party_identifier_commands_tests.cpp"
    "party_status_commands_tests.cpp"
    "party_type_commands_tests.cpp"
    "payment_frequency_commands_tests.cpp"
    "portfolio_commands_tests.cpp"
    "portfolio_right_commands_tests.cpp"
    "producer_kind_commands_tests.cpp"
    "purpose_type_commands_tests.cpp"
    "regulatory_book_type_commands_tests.cpp"
    "rounding_type_commands_tests.cpp"
    "sandbox_commands_tests.cpp"
    "sandbox_member_commands_tests.cpp"
    "series_subclass_code_commands_tests.cpp"
    "sub_periods_coupon_type_commands_tests.cpp"
    "swap_convention_commands_tests.cpp"
    "swap_index_convention_commands_tests.cpp"
    "swaption_volatility_config_commands_tests.cpp"
    "tenor_anchor_commands_tests.cpp"
    "tenor_basis_swap_convention_commands_tests.cpp"
    "tenor_basis_two_swap_convention_commands_tests.cpp"
    "tenor_commands_tests.cpp"
    "tenor_convention_commands_tests.cpp"
    "tenor_convention_resolution_commands_tests.cpp"
    "tenor_kind_commands_tests.cpp"
    "tenor_resolution_algorithm_commands_tests.cpp"
    "tenor_schedule_commands_tests.cpp"
    "tenor_unit_commands_tests.cpp"
    "yield_curve_config_commands_tests.cpp"
    "yield_volatility_config_commands_tests.cpp"
    "zero_convention_commands_tests.cpp"
    "zero_inflation_index_convention_commands_tests.cpp"
)
