# -*- mode: cmake; cmake-tab-width: 4; indent-tabs-mode: nil -*-
#
# Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
set(files
    "app/application.cpp"
    "app/host.cpp"
    "config/options.cpp"
    "config/parser.cpp"
    "main.cpp"
    "messaging/ascot_event_registrar.cpp"
    "messaging/balance_guaranteed_swap_instrument_event_registrar.cpp"
    "messaging/bond_future_event_registrar.cpp"
    "messaging/bond_instrument_event_registrar.cpp"
    "messaging/bond_issue_call_date_event_registrar.cpp"
    "messaging/bond_issue_conversion_target_event_registrar.cpp"
    "messaging/bond_issue_event_registrar.cpp"
    "messaging/bond_leg_amortization_event_registrar.cpp"
    "messaging/bond_leg_amount_event_registrar.cpp"
    "messaging/bond_leg_event_registrar.cpp"
    "messaging/bond_leg_rate_event_registrar.cpp"
    "messaging/bond_option_event_registrar.cpp"
    "messaging/bond_repo_event_registrar.cpp"
    "messaging/bond_trs_event_registrar.cpp"
    "messaging/callable_swap_instrument_event_registrar.cpp"
    "messaging/cap_floor_instrument_event_registrar.cpp"
    "messaging/commodity_instrument_event_registrar.cpp"
    "messaging/composite_instrument_event_registrar.cpp"
    "messaging/credit_instrument_event_registrar.cpp"
    "messaging/equity_accumulator_instrument_event_registrar.cpp"
    "messaging/equity_asian_option_instrument_event_registrar.cpp"
    "messaging/equity_barrier_option_instrument_event_registrar.cpp"
    "messaging/equity_digital_option_instrument_event_registrar.cpp"
    "messaging/equity_forward_instrument_event_registrar.cpp"
    "messaging/equity_option_instrument_event_registrar.cpp"
    "messaging/equity_position_instrument_event_registrar.cpp"
    "messaging/equity_swap_instrument_event_registrar.cpp"
    "messaging/equity_variance_swap_instrument_event_registrar.cpp"
    "messaging/fra_instrument_event_registrar.cpp"
    "messaging/fx_accumulator_instrument_event_registrar.cpp"
    "messaging/fx_asian_forward_instrument_event_registrar.cpp"
    "messaging/fx_barrier_option_instrument_event_registrar.cpp"
    "messaging/fx_digital_option_instrument_event_registrar.cpp"
    "messaging/fx_forward_instrument_event_registrar.cpp"
    "messaging/fx_vanilla_option_instrument_event_registrar.cpp"
    "messaging/fx_variance_swap_instrument_event_registrar.cpp"
    "messaging/inflation_swap_instrument_event_registrar.cpp"
    "messaging/instrument_schedule_date_event_registrar.cpp"
    "messaging/instrument_schedule_event_registrar.cpp"
    "messaging/knock_out_swap_instrument_event_registrar.cpp"
    "messaging/lifecycle_event_event_registrar.cpp"
    "messaging/party_role_type_event_registrar.cpp"
    "messaging/rpa_instrument_event_registrar.cpp"
    "messaging/scripted_instrument_event_registrar.cpp"
    "messaging/swaption_instrument_event_registrar.cpp"
    "messaging/trade_id_type_event_registrar.cpp"
    "messaging/trade_identifier_event_registrar.cpp"
    "messaging/trade_party_role_event_registrar.cpp"
    "messaging/trade_type_event_registrar.cpp"
    "messaging/vanilla_swap_instrument_event_registrar.cpp"
)

# Headers must be listed for AUTOMOC to find Q_OBJECT declarations.
set(HEADERS
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/app/application.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/app/application_exception.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/app/host.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/config/options.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/config/parser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/config/parser_exception.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/export.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/ascot_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/balance_guaranteed_swap_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/bond_future_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/bond_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/bond_issue_call_date_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/bond_issue_conversion_target_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/bond_issue_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/bond_leg_amortization_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/bond_leg_amount_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/bond_leg_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/bond_leg_rate_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/bond_option_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/bond_repo_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/bond_trs_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/callable_swap_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/cap_floor_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/commodity_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/composite_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/credit_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/equity_accumulator_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/equity_asian_option_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/equity_barrier_option_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/equity_digital_option_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/equity_forward_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/equity_option_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/equity_position_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/equity_swap_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/equity_variance_swap_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/fra_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/fx_accumulator_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/fx_asian_forward_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/fx_barrier_option_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/fx_digital_option_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/fx_forward_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/fx_vanilla_option_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/fx_variance_swap_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/inflation_swap_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/instrument_schedule_date_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/instrument_schedule_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/knock_out_swap_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/lifecycle_event_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/party_role_type_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/rpa_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/scripted_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/swaption_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/trade_id_type_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/trade_identifier_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/trade_party_role_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/trade_type_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/messaging/vanilla_swap_instrument_event_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.trading.service/ores.trading.service.hpp"
)
