' -*- mode: plantuml; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
'
' Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
'
' This program is free software; you can redistribute it and/or modify it under
' the terms of the GNU General Public License as published by the Free Software
' Foundation; either version 3 of the License, or (at your option) any later
' version.
'
' This program is distributed in the hope that it will be useful, but WITHOUT
' ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
' FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with
' this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
' Street, Fifth Floor, Boston, MA 02110-1301, USA.
'
@startuml

salt
{
  {#
    <b>NEW TENANT</b>
    --
    <b>(1) Choose a starting point</b>
    (2) Describe the tenant
    (3) Review
    (4) Provisioning
    (5) Hand off
  } | {
    <b>Choose a starting point</b>
    Choose a starting point for the new tenant.
    --
    {#
      <b>Operational</b> | <b>ACME demo</b>
      For real use | For demos and testing
      Production-ready setup | Pre-configured sandbox
      - Standard reference data | - 4 legal entities, books, desks
      - Your parties, from their LEI | - 45 staff to sign in as
      - No test data | - Live synthetic market data
      2 settings, 6 steps | 0 settings, 9 steps
    }
    --
    [ Continue ]
  }
}

@enduml
