' -*- mode: plantuml; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
'
' Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
'
' This program is free software; you can redistribute it and/or modify it under
' the terms of the GNU General Public License as published by the Free Software
' Foundation; either version 3 of the License, or (at your option) any later
' version.
'
' This program is distributed in the hope that it will be useful, but WITHOUT
' ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
' FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with
' this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
' Street, Fifth Floor, Boston, MA 02110-1301, USA.
'
@startuml

salt
{
  {#
    <b>SET UP ORE STUDIO</b>
    --
    <b>(1) Create the administrator</b>
    (2) Choose a starting point
    (3) Describe the tenant
    (4) Review
    (5) Provisioning
    (6) Hand off
    (7) First sign-in
    (8) Ready
  } | {
    <b>Create the administrator</b>
    This account sets up ORE Studio and creates its tenants.
    --
    {#
      Username | super_admin
      Email | admin@example.com
      Password | ************
      Strength | strong
    }
    --
    [ Create administrator ]
  }
}

@enduml
