/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_bank/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * Acme Bank ACME_US Books Artefact Population Script
 *
 * parent_portfolio_id is the artefact-space id (uuid) of the owning row
 * in the matching portfolios dataset, resolved by name at publish time
 * (see ores_refdata_publish_books_from_dq_fn). This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_us.books'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_us.books. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_books_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_books_artefact_tbl (
        dataset_id, tenant_id, id, version, name,
        parent_portfolio_id, functional_currency, gl_account_ref, cost_center,
        book_status, regulatory_book_type, is_sweepable, rates_centre_code
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '7587dbc4-6099-5efd-b6b3-5e3f15fac2c6', 0, 'IR Swaps New York Book', 'c6826c25-9de0-5d23-b39b-96f53c714d65', 'USD', null, null, 'Active', 'Trading', false, null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '35400c12-2a43-5b5c-934e-96f09f406887', 0, 'Credit Trading New York Book', '840f7ff0-f868-5c63-98d4-91fb24180e51', 'USD', null, null, 'Active', 'Trading', false, null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'b60bea04-a671-5dcb-8fb4-9fea97d7d9e6', 0, 'FX Rates New York Book', 'e1b393f8-d984-5ae7-b3ae-0c16ac371aa7', 'USD', null, null, 'Active', 'Trading', false, null);
end $$;
