/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_corporation/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * ACME Corporation ACME_UK Books Artefact Population Script
 *
 * parent_portfolio_id is the artefact-space id (uuid) of the owning row
 * in the matching portfolios dataset, resolved by name at publish time
 * (see ores_refdata_publish_books_from_dq_fn). This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_uk.books'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_uk.books. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_books_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_books_artefact_tbl (
        dataset_id, tenant_id, id, version, name,
        parent_portfolio_id, functional_currency, gl_account_ref, cost_center,
        book_status, regulatory_book_type, is_sweepable, rates_centre_code
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '3be9e09c-a418-591a-8936-8a331733c511', 0, 'GBP Nostro Sweep', '421f5d6a-bdf1-529a-a686-11b3b414a34e', 'GBP', 'GL-TREAS-001', 'CC-EMEA-TREASURY', 'Active', 'Trading', true, 'GBLO'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '323956c4-76f2-5dd2-a73b-a8e0d251ec9b', 0, 'GBP Vanilla Swaps', '421f5d6a-bdf1-529a-a686-11b3b414a34e', 'GBP', 'GL-RATES-001', 'CC-EMEA-RATES', 'Active', 'Trading', false, 'GBLO'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'b0ae6a6e-fe68-5dca-a0e1-151b9d78bc26', 0, 'GBP Rates Options', '421f5d6a-bdf1-529a-a686-11b3b414a34e', 'GBP', 'GL-RATES-002', 'CC-EMEA-RATES', 'Active', 'Trading', false, 'GBLO'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '4128c4c3-6f7d-53bb-b28a-ae141afa9299', 0, 'EUR Vanilla Swaps', '07a2e6f7-3f5e-5156-a151-a994fb301ffb', 'EUR', 'GL-RATES-003', 'CC-EMEA-RATES', 'Active', 'Trading', false, 'FRPA'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '797bddb4-fc67-5ce9-b4e4-60643f3bc5e5', 0, 'EUR Exotic Rates', '07a2e6f7-3f5e-5156-a151-a994fb301ffb', 'EUR', 'GL-RATES-004', 'CC-EMEA-RATES', 'Active', 'Trading', false, 'FRPA'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '5293ecff-2b19-504a-a561-f537ce72058d', 0, 'IG CDS EMEA', '4a188fa2-8a12-5dc7-9e0c-b638f7eb334d', 'EUR', 'GL-CREDIT-001', 'CC-EMEA-CREDIT', 'Active', 'Trading', false, 'GBLO'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '0ad90f7f-9f73-5092-ac67-3849f65b3c0f', 0, 'IG Bonds EMEA', '4a188fa2-8a12-5dc7-9e0c-b638f7eb334d', 'EUR', 'GL-CREDIT-002', 'CC-EMEA-CREDIT', 'Active', 'Banking', false, 'GBLO'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '3569df9c-65e6-5d01-a9b1-12aaf3c1df9e', 0, 'G10 FX Spot Forward', 'fc30df52-0d2f-531e-b53f-77819db78b5a', 'EUR', 'GL-FX-001', 'CC-EMEA-FX', 'Active', 'Trading', false, 'GBLO'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '4fddf104-79e1-5e9e-9055-e8994e6f0f48', 0, 'G10 FX Options', 'fc30df52-0d2f-531e-b53f-77819db78b5a', 'EUR', 'GL-FX-002', 'CC-EMEA-FX', 'Active', 'Trading', false, 'GBLO'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '2ad85813-2de7-5bd7-88be-c1c63d2a492b', 0, 'USD Cash Management Sweep', 'b1c0b37a-3745-53dd-849f-288dbeac9b00', 'USD', 'GL-TREAS-002', 'CC-AMER-TREASURY', 'Active', 'Trading', true, 'USNY'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '9d14e014-26fc-5806-94dd-2cf2b641fbcb', 0, 'USD Vanilla Swaps', 'b1c0b37a-3745-53dd-849f-288dbeac9b00', 'USD', 'GL-RATES-005', 'CC-AMER-RATES', 'Active', 'Trading', false, 'USNY'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '0f50789b-6f05-5950-8849-6eab4060da16', 0, 'USD Rates Options', 'b1c0b37a-3745-53dd-849f-288dbeac9b00', 'USD', 'GL-RATES-006', 'CC-AMER-RATES', 'Active', 'Trading', false, 'USNY'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '76cda48f-6543-51e7-b646-db4d16ab01d3', 0, 'CAD Swaps', '13fdfe0b-69b2-50af-bdc2-095060012170', 'CAD', 'GL-RATES-007', 'CC-AMER-RATES', 'Active', 'Trading', false, 'CATO'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '9c58634b-30c6-546e-ae19-fb4d398290b9', 0, 'IG CDS Americas', '31fe7c73-fd4b-5b4a-ab6d-ad19264a9f14', 'USD', 'GL-CREDIT-003', 'CC-AMER-CREDIT', 'Active', 'Trading', false, 'USNY'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ac0e02e6-4794-5248-8820-1cbf6d4294d8', 0, 'IG Bonds Americas', '31fe7c73-fd4b-5b4a-ab6d-ad19264a9f14', 'USD', 'GL-CREDIT-004', 'CC-AMER-CREDIT', 'Active', 'Banking', false, 'USNY'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '71cb0035-9dc3-5994-bfc6-e17c2d9d1f72', 0, 'JPY Vanilla Swaps', '382e9f13-0613-5ac1-84a2-447b14c894dd', 'JPY', 'GL-RATES-008', 'CC-APAC-RATES', 'Active', 'Trading', false, 'JPTO'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ad45207c-9388-5f1a-953e-256e7d6219ec', 0, 'JPY Rates Options', '382e9f13-0613-5ac1-84a2-447b14c894dd', 'JPY', 'GL-RATES-009', 'CC-APAC-RATES', 'Active', 'Trading', false, 'JPTO'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '84a4e576-00a2-567c-85e6-c748914e1986', 0, 'APAC FX Spot Forward', 'ccaa774f-83c5-58fe-971b-144577697bb6', 'JPY', 'GL-FX-003', 'CC-APAC-FX', 'Active', 'Trading', false, 'SGSI'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '57d1be33-d5e3-545b-a805-823586f1f641', 0, 'APAC FX NDF', 'ccaa774f-83c5-58fe-971b-144577697bb6', 'JPY', 'GL-FX-004', 'CC-APAC-FX', 'Active', 'Trading', false, 'SGSI'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '36f1c8d8-0d82-5bd3-8a44-621341ff5663', 0, 'Regulatory Banking Book', 'bf123dce-5374-575c-9a6f-f671fcbbbf2f', 'USD', 'GL-REG-001', 'CC-RISK', 'Active', 'Banking', false, null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '0eaaa504-6e74-5b97-927f-53ed81b125dc', 0, 'Regulatory Trading Book', 'bf123dce-5374-575c-9a6f-f671fcbbbf2f', 'USD', 'GL-REG-002', 'CC-RISK', 'Active', 'Trading', false, null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '27a86d5a-ef42-571d-96e1-f774255395e7', 0, 'Regulatory CVA Book', 'bf123dce-5374-575c-9a6f-f671fcbbbf2f', 'USD', 'GL-REG-003', 'CC-RISK', 'Closed', 'Trading', false, null);
end $$;
