/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_bank/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * Acme Bank ACME_US Account Contact Informations Artefact
 * Population Script
 *
 * account_username identifies the owning account by username, resolved
 * to an account id by the publish function once the account itself has
 * been published (see the server-side-orchestration follow-up task).
 * This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_us.account_contact_informations'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_us.account_contact_informations. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_account_contact_informations_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_account_contact_informations_artefact_tbl (
        dataset_id, tenant_id, id, version, account_username, full_name,
        street_line_1, street_line_2, city, state, country_code,
        postal_code, phone, email, web_page
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'a01deae1-855c-5c90-a1fe-7079ee4b16ae', 0, 'jennifer.adams.acme_us.0', 'Jennifer Adams', null, null, null, null, null, null, null, 'jennifer.adams.0@acme_us.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '3f054eb0-c1b3-5fc8-89f8-ee3bcd34e62f', 0, 'john.reeves.acme_us.1', 'John Reeves', null, null, null, null, null, null, null, 'john.reeves.1@acme_us.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '6ccbc504-1335-5304-ad3f-477bba83e6a3', 0, 'lance.sanford.acme_us.2', 'Lance Sanford', null, null, null, null, null, null, null, 'lance.sanford.2@acme_us.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'f1b8a368-c0e7-5aef-a020-e4583f4f6a4f', 0, 'karen.armstrong.acme_us.3', 'Karen Armstrong', null, null, null, null, null, null, null, 'karen.armstrong.3@acme_us.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '152ef943-46f6-59ca-b412-02fbcc1f5d42', 0, 'wendy.choi.acme_us.4', 'Wendy Choi', null, null, null, null, null, null, null, 'wendy.choi.4@acme_us.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'c9e94664-94e8-5832-81d3-29d3623287ec', 0, 'sharon.adams.acme_us.5', 'Sharon Adams', null, null, null, null, null, null, null, 'sharon.adams.5@acme_us.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '6bb6c84e-265d-5129-afd0-c0e6218b08b3', 0, 'kevin.barrett.acme_us.6', 'Kevin Barrett', null, null, null, null, null, null, null, 'kevin.barrett.6@acme_us.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ae776572-a805-5925-9d61-84dfb7c1eb29', 0, 'tracy.robinson.acme_us.7', 'Tracy Robinson', null, null, null, null, null, null, null, 'tracy.robinson.7@acme_us.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'd5c77395-1bb7-5c2e-af7d-c92ba48b0378', 0, 'marissa.green.acme_us.8', 'Marissa Green', null, null, null, null, null, null, null, 'marissa.green.8@acme_us.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '9381770b-4924-5077-b587-4ff9cef31d74', 0, 'michael.jones.acme_us.9', 'Michael Jones', null, null, null, null, null, null, null, 'michael.jones.9@acme_us.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'de796cfa-8832-50c7-a51f-5ea932b121c8', 0, 'ashley.carlson.acme_us.10', 'Ashley Carlson', null, null, null, null, null, null, null, 'ashley.carlson.10@acme_us.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'e5c585f7-ad22-55d1-b982-9afdab9bddf0', 0, 'james.gross.acme_us.11', 'James Gross', null, null, null, null, null, null, null, 'james.gross.11@acme_us.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '21e6aea2-5e8d-59ed-b0da-48de6b8f35bf', 0, 'nicole.stevens.acme_us.12', 'Nicole Stevens', null, null, null, null, null, null, null, 'nicole.stevens.12@acme_us.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '20324ca8-1553-5d74-9ecb-53dc4ee64bac', 0, 'connie.reid.acme_us.13', 'Connie Reid', null, null, null, null, null, null, null, 'connie.reid.13@acme_us.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'b07bc142-19f0-56ad-b32e-1c29dd20b6b1', 0, 'kevin.franklin.acme_us.14', 'Kevin Franklin', null, null, null, null, null, null, null, 'kevin.franklin.14@acme_us.acmebank.example', null);
end $$;
