/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_corporation/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * ACME Corporation ACME_UK Business Units Artefact Population Script
 *
 * parent_business_unit_id is the artefact-space id (uuid) of the parent
 * unit's own row in this same dataset -- ores_refdata_publish_business_
 * units_from_dq_fn walks this self-referential chain breadth-first and
 * remaps it to newly-published ids. This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_uk.business_units'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_uk.business_units. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_business_units_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_business_units_artefact_tbl (
        dataset_id, tenant_id, id, version, unit_name,
        parent_business_unit_id, unit_code, business_centre_code, unit_type_code
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '57e8e604-dcb6-515a-a6bd-38f0be805480', 0, 'Global Markets', null, 'acme_uk.global_markets', 'GBLO', 'DIVISION'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '477f84a7-7edf-50a7-a96f-559dc2778b8b', 0, 'EMEA Trading', '57e8e604-dcb6-515a-a6bd-38f0be805480', 'acme_uk.emea_trading', 'GBLO', 'BUSINESS_AREA'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '087d2259-9228-57a4-b0d4-5e5c6b4a687d', 0, 'Rates Trading EMEA', '477f84a7-7edf-50a7-a96f-559dc2778b8b', 'acme_uk.rates_trading_emea', 'GBLO', 'DESK'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '40966335-f572-55ea-8df4-6734d990b94c', 0, 'Credit Trading EMEA', '477f84a7-7edf-50a7-a96f-559dc2778b8b', 'acme_uk.credit_trading_emea', 'GBLO', 'DESK'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '89fef41b-1c7d-54db-843b-bf06df71a15b', 0, 'FX Trading EMEA', '477f84a7-7edf-50a7-a96f-559dc2778b8b', 'acme_uk.fx_trading_emea', 'GBLO', 'DESK'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'a5d09e78-0f28-5528-b041-f153061b63fb', 0, 'Americas Trading', '57e8e604-dcb6-515a-a6bd-38f0be805480', 'acme_uk.americas_trading', 'USNY', 'BUSINESS_AREA'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '9532cb35-6a65-5992-a787-00b8c95555fd', 0, 'Rates Trading Americas', 'a5d09e78-0f28-5528-b041-f153061b63fb', 'acme_uk.rates_trading_americas', 'USNY', 'DESK'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'cab78299-7de2-5213-b534-5d1f4556cc95', 0, 'Credit Trading Americas', 'a5d09e78-0f28-5528-b041-f153061b63fb', 'acme_uk.credit_trading_americas', 'USNY', 'DESK'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '0ba311e9-77e6-5f6d-9f7b-40e431865917', 0, 'APAC Trading', '57e8e604-dcb6-515a-a6bd-38f0be805480', 'acme_uk.apac_trading', 'JPTO', 'BUSINESS_AREA'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'aca9bec4-2b34-5093-8505-9e34830cd0c7', 0, 'Rates Trading APAC', '0ba311e9-77e6-5f6d-9f7b-40e431865917', 'acme_uk.rates_trading_apac', 'JPTO', 'DESK'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '7078caf2-d53a-5066-9bb7-2a7fcec74d13', 0, 'FX Trading APAC', '0ba311e9-77e6-5f6d-9f7b-40e431865917', 'acme_uk.fx_trading_apac', 'HKHK', 'DESK'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ee639085-d4a7-5855-bb58-c94d9a6b21f1', 0, 'Risk Management', null, 'acme_uk.risk_management', 'GBLO', 'DIVISION'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '2fcd2ca5-15b5-52f5-8a2c-a808faf3a381', 0, 'Counterparty Risk', 'ee639085-d4a7-5855-bb58-c94d9a6b21f1', 'acme_uk.counterparty_risk', 'GBLO', 'BUSINESS_AREA'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'a3c5e2ae-d25f-5f39-b334-e59d76ceff31', 0, 'Middle Office London', null, 'acme_uk.middle_office', 'GBLO', 'COST_CENTRE'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '648136b1-4548-59e8-80c7-2eb7639c4a89', 0, 'Market Risk London', null, 'acme_uk.market_risk', 'GBLO', 'COST_CENTRE');
end $$;
