/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_corporation/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * ACME Corporation HK Netting Sets Artefact Population Script
 *
 * Each set names its agreement by number; the agreement is found among the same entity's agreements at publish time. This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_hk.netting_sets'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_hk.netting_sets. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_netting_sets_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_netting_sets_artefact_tbl (
        dataset_id, tenant_id, code, version, agreement_number, description
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACHK-HBAP-VM', 0, 'ACHK-HBAP-ISDA-2017', 'OTC derivatives with The Hongkong and Shanghai Banking Corporation Limited under the 2016 Credit Support Annex for Variation Margin (English law, title transfer), variation margin only, margined daily'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACHK-SCB-VM', 0, 'ACHK-SCB-ISDA-2018', 'OTC derivatives with Standard Chartered Bank under the 2016 Credit Support Annex for Variation Margin (English law, title transfer), variation margin only, margined daily'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACHK-CITI-VM', 0, 'ACHK-CITI-ISDA-2019', 'OTC derivatives with Citibank, National Association under the 2016 Credit Support Annex for Variation Margin (English law, title transfer), variation margin only, margined daily'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACHK-ACGR-IC-UNC', 0, 'ACGR-ACHK-ISDA-2018', 'Intragroup derivatives with Acme Corporation Plc, uncollateralised');
end $$;
