/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- Acme Corporation Reference Data Publication
--
-- Promotes Acme's staged DQ artefacts into the refdata tables the rest of the
-- system reads. Without this step the artefact tables hold Acme's parties,
-- business units, portfolios and books, and ores_refdata_books_tbl is empty,
-- so no trade can be booked: ores_trading_trades_insert_fn validates book_id
-- against ores_refdata_books_tbl and rejects every row.
--
-- This calls the same ores_refdata_publish_*_from_dq_fn functions that
-- ores.iam.core's Acme provisioner drives over dq.v1.bundles.publish. It is a
-- second trigger of one implementation, not a second implementation. The
-- provisioner remains the path for a running system; this exists so a freshly
-- created database is usable before any service starts.
--
-- Order matters and is not arbitrary. Business centres are validated when a
-- party is written. Business units, portfolios and books each resolve their
-- parent from what the previous step published.
--
-- Each office publishes under its own party. The publish functions skip when
-- the target party already owns rows of that kind, so without an explicit
-- party_id every office after the first resolves to the group party and is
-- skipped, publishing 2 books instead of 31.
--
-- Idempotent: re-running skips what is already published.
-- =============================================================================

do $$
declare
    v_tenant_id uuid := ores_utility_system_tenant_id_fn();
    v_office record;
    v_party_id uuid;
    v_dataset_id uuid;
    v_result record;
begin
    -- Countries, read when a business centre is written.
    select id into v_dataset_id from ores_dq_datasets_tbl
    where code = 'iso.countries'
      and valid_to = ores_utility_infinity_timestamp_fn();
    if v_dataset_id is not null then
        select * into v_result from
            ores_refdata_publish_countries_from_dq_fn(v_dataset_id, v_tenant_id);
        raise notice 'countries: % %', v_result.action, v_result.record_count;
    end if;

    -- Business centres, validated when a party is written.
    select id into v_dataset_id from ores_dq_datasets_tbl
    where code = 'fpml.business_center'
      and valid_to = ores_utility_infinity_timestamp_fn();
    if v_dataset_id is null then
        -- fpml_populate.sql is generated by ores.codegen but is not included in
        -- this orchestrator, so the dataset can be absent on a fresh database.
        -- Publishing parties then fails on an unknown business centre, which is
        -- confusing far from its cause. Say so here instead.
        raise warning 'fpml.business_center dataset absent; parties will fail '
            'to publish. Load populate/fpml/fpml_populate.sql first.';
    else
        select * into v_result from
            ores_refdata_publish_business_centres_from_dq_fn(v_dataset_id, v_tenant_id);
        raise notice 'business_centres: % %', v_result.action, v_result.record_count;
    end if;

    -- Acme's four legal entities as parties, rooted at the group LEI.
    select id into v_dataset_id from ores_dq_datasets_tbl
    where code = 'acme.lei_parties'
      and valid_to = ores_utility_infinity_timestamp_fn();
    if v_dataset_id is not null then
        select * into v_result from ores_refdata_publish_lei_parties_from_dq_fn(
            v_dataset_id, v_tenant_id, 'upsert',
            jsonb_build_object('root_lei', '9695ACMEGROUP0000030'));
        raise notice 'lei_parties: % %', v_result.action, v_result.record_count;
    end if;

    -- The same entities as counterparties, so a trade has someone to face.
    select id into v_dataset_id from ores_dq_datasets_tbl
    where code = 'acme.lei_entities'
      and valid_to = ores_utility_infinity_timestamp_fn();
    if v_dataset_id is not null then
        select * into v_result from
            ores_refdata_publish_lei_counterparties_from_dq_fn(v_dataset_id, v_tenant_id);
        raise notice 'lei_counterparties: % %', v_result.action, v_result.record_count;
    end if;

    -- Trading structure, per office, under that office's own party.
    for v_office in
        select * from (values
            ('acme_group', 'ACMCOR'),
            ('acme_uk',    'ACCOUK'),
            ('acme_us',    'ACCOUS'),
            ('acme_hk',    'ACCOHK')
        ) as t(dataset_prefix, party_short_code)
    loop
        select id into v_party_id from ores_refdata_parties_tbl
        where short_code = v_office.party_short_code
          and tenant_id = v_tenant_id
          and valid_to = ores_utility_infinity_timestamp_fn();

        if v_party_id is null then
            raise notice 'no party %; skipping %',
                v_office.party_short_code, v_office.dataset_prefix;
            continue;
        end if;

        select id into v_dataset_id from ores_dq_datasets_tbl
        where code = 'acme.' || v_office.dataset_prefix || '.business_units'
          and valid_to = ores_utility_infinity_timestamp_fn();
        if v_dataset_id is not null then
            select * into v_result from ores_refdata_publish_business_units_from_dq_fn(
                v_dataset_id, v_tenant_id, 'upsert',
                jsonb_build_object('party_id', v_party_id));
            raise notice '% business_units: % %',
                v_office.dataset_prefix, v_result.action, v_result.record_count;
        end if;

        select id into v_dataset_id from ores_dq_datasets_tbl
        where code = 'acme.' || v_office.dataset_prefix || '.portfolios'
          and valid_to = ores_utility_infinity_timestamp_fn();
        if v_dataset_id is not null then
            select * into v_result from ores_refdata_publish_portfolios_from_dq_fn(
                v_dataset_id, v_tenant_id, 'upsert',
                jsonb_build_object('party_id', v_party_id));
            raise notice '% portfolios: % %',
                v_office.dataset_prefix, v_result.action, v_result.record_count;
        end if;

        select id into v_dataset_id from ores_dq_datasets_tbl
        where code = 'acme.' || v_office.dataset_prefix || '.books'
          and valid_to = ores_utility_infinity_timestamp_fn();
        if v_dataset_id is not null then
            select * into v_result from ores_refdata_publish_books_from_dq_fn(
                v_dataset_id, v_tenant_id, 'upsert',
                jsonb_build_object('party_id', v_party_id));
            raise notice '% books: % %',
                v_office.dataset_prefix, v_result.action, v_result.record_count;
        end if;
    end loop;
end
$$;
