/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_bank/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * Acme Bank ACME_US Accounts Artefact Population Script
 *
 * business_unit_code is a natural-key code, resolved to a business unit
 * id by the publish function (see the server-side-orchestration
 * follow-up task). This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_us.accounts'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_us.accounts. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_accounts_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_accounts_artefact_tbl (
        dataset_id, tenant_id, id, version, username,
        email, password_hash, account_type, business_unit_code, role
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'f5bf3574-ed9e-58b4-ba34-606dc5342580', 0, 'jennifer.adams.acme_us.0', 'jennifer.adams.0@acme_us.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.ir_swaps', 'Desk Head'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '2fa85391-04db-5c08-9633-4b104421b3e9', 0, 'john.reeves.acme_us.1', 'john.reeves.1@acme_us.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.ir_swaps', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '8388f569-834c-5554-b831-ff038c0025fc', 0, 'lance.sanford.acme_us.2', 'lance.sanford.2@acme_us.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.ir_swaps', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'f2e9ceb0-8b20-55cd-865c-b2f8f5720424', 0, 'karen.armstrong.acme_us.3', 'karen.armstrong.3@acme_us.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.credit_trading', 'Desk Head'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '7947ba31-e702-58a9-af7d-1e1a1c9f6d8c', 0, 'wendy.choi.acme_us.4', 'wendy.choi.4@acme_us.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.credit_trading', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'df18c448-d797-525a-8a74-6bca02ace814', 0, 'sharon.adams.acme_us.5', 'sharon.adams.5@acme_us.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.credit_trading', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ba7feaf0-77d7-55d5-b0ff-034ed6a76370', 0, 'kevin.barrett.acme_us.6', 'kevin.barrett.6@acme_us.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.fx_rates', 'Desk Head'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'e5eff069-2c98-5f15-89c5-ba02a8da82c9', 0, 'tracy.robinson.acme_us.7', 'tracy.robinson.7@acme_us.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.fx_rates', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '9d3d5fdc-b2e0-5afe-b368-dedccee93952', 0, 'marissa.green.acme_us.8', 'marissa.green.8@acme_us.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.fx_rates', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'b1ea4241-72e5-5cf4-809d-75518f0c2407', 0, 'michael.jones.acme_us.9', 'michael.jones.9@acme_us.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.middle_office', 'Manager'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '875d7405-9458-54f8-ac09-2b776a6cc798', 0, 'ashley.carlson.acme_us.10', 'ashley.carlson.10@acme_us.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.middle_office', 'Analyst'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '4a7644a2-3fd3-585e-ae75-4a337929053c', 0, 'james.gross.acme_us.11', 'james.gross.11@acme_us.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.middle_office', 'Analyst'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '0aa5e542-43f1-5a07-9fcc-ca9577fedbf1', 0, 'nicole.stevens.acme_us.12', 'nicole.stevens.12@acme_us.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.market_risk', 'Manager'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '10a34815-297e-5b29-8b2c-5a29a0e47139', 0, 'connie.reid.acme_us.13', 'connie.reid.13@acme_us.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.market_risk', 'Analyst'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '79979b95-8e4c-5170-9b08-ee56b4a86fa9', 0, 'kevin.franklin.acme_us.14', 'kevin.franklin.14@acme_us.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.market_risk', 'Analyst');
end $$;
