/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_corporation/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * ACME Corporation ACME_US Accounts Artefact Population Script
 *
 * business_unit_code is a natural-key code, resolved to a business unit
 * id by the publish function (see the server-side-orchestration
 * follow-up task). This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_us.accounts'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_us.accounts. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_accounts_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_accounts_artefact_tbl (
        dataset_id, tenant_id, id, version, username, full_name,
        email, password_hash, account_type, business_unit_code, role,
        job_title, reports_to_username, photo_key
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '7af4c356-125a-532c-a45b-65d2c6d86ff4', 0, 'mindy.adams', 'Mindy Adams', 'mindy.adams@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.global_markets', 'Operations', 'Country Head', 'adrian.vance', 'acme_staff_photo:female_age30_european_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '30ed8136-2c92-5661-b438-e1cdf21c5ab7', 0, 'david.reeves', 'David Reeves', 'david.reeves@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.global_markets', 'Operations', 'COO', 'mindy.adams', 'acme_staff_photo:male_age20_african_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '96766b8d-0ea2-574b-86cd-da9a8cda967c', 0, 'emily.sanford', 'Emily Sanford', 'emily.sanford@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.global_markets', 'Operations', 'Head of Risk', 'mindy.adams', 'acme_staff_photo:female_age20_latin_american_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '45737efa-2dd5-5105-a81f-ca9e90d76cf9', 0, 'paul.armstrong', 'Paul Armstrong', 'paul.armstrong@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.global_markets', 'Trading', 'Head of Trading', 'mindy.adams', 'acme_staff_photo:male_age20_east_asian_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '50a1a661-d252-5ded-9d80-12caa3c39d27', 0, 'yesenia.choi', 'Yesenia Choi', 'yesenia.choi@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.ir_swaps', 'Trading', 'Head of Desk', 'paul.armstrong', 'acme_staff_photo:female_age20_south_asian_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'd08732c9-13c9-5616-88f4-b43007e792ab', 0, 'timothy.adams', 'Timothy Adams', 'timothy.adams@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.ir_swaps', 'Trading', 'Senior Trader', 'yesenia.choi', 'acme_staff_photo:male_age20_european_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '1cd62629-f5b5-58fd-97d1-806d7e5e2a93', 0, 'elizabeth.barrett', 'Elizabeth Barrett', 'elizabeth.barrett@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.ir_swaps', 'Trading', 'Junior Trader', 'yesenia.choi', 'acme_staff_photo:female_age30_african_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '99bc8d7e-3b15-576a-b7cd-adcb5f52720d', 0, 'john.robinson', 'John Robinson', 'john.robinson@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.credit_trading', 'Trading', 'Head of Desk', 'paul.armstrong', 'acme_staff_photo:male_age20_latin_american_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'e329300a-80d5-5443-9aa0-90a6bda88daa', 0, 'sandra.green', 'Sandra Green', 'sandra.green@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.credit_trading', 'Trading', 'Senior Trader', 'john.robinson', 'acme_staff_photo:female_age20_east_asian_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ff024727-e600-5d68-9aec-d0d17562b782', 0, 'henry.jones', 'Henry Jones', 'henry.jones@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.credit_trading', 'Trading', 'Junior Trader', 'john.robinson', 'acme_staff_photo:male_age25_south_asian_03'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '82b638e8-0d5e-5846-8217-14ac2dd3c198', 0, 'laura.carlson', 'Laura Carlson', 'laura.carlson@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.fx_rates', 'Trading', 'Head of Desk', 'paul.armstrong', 'acme_staff_photo:female_age30_european_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '565a224f-5517-5e5f-96ee-b5d365dc1dc0', 0, 'corey.gross', 'Corey Gross', 'corey.gross@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.fx_rates', 'Trading', 'Senior Trader', 'laura.carlson', 'acme_staff_photo:male_age20_african_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '19d5f09f-dab6-5abd-b4a6-bd0314513428', 0, 'shirley.stevens', 'Shirley Stevens', 'shirley.stevens@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.fx_rates', 'Trading', 'Junior Trader', 'laura.carlson', 'acme_staff_photo:female_age20_latin_american_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '72c78390-6212-592c-a8a5-8aa4cd810fe8', 0, 'mark.reid', 'Mark Reid', 'mark.reid@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.middle_office', 'Operations', 'Head of Middle Office', 'david.reeves', 'acme_staff_photo:male_age20_east_asian_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '3782b923-2fcc-5e6c-a75a-5a50941e3322', 0, 'elizabeth.franklin', 'Elizabeth Franklin', 'elizabeth.franklin@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.middle_office', 'Viewer', 'Senior Analyst', 'mark.reid', 'acme_staff_photo:female_age20_south_asian_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ac95f738-7792-543c-8881-4f4d3d7b6764', 0, 'john.sullivan', 'John Sullivan', 'john.sullivan@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.middle_office', 'Viewer', 'Junior Analyst', 'mark.reid', 'acme_staff_photo:male_age25_european_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ddf6bfb9-b6ef-5873-a2d7-c22a4ebac9da', 0, 'stacy.lopez', 'Stacy Lopez', 'stacy.lopez@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.market_risk', 'Operations', 'Head of Market Risk', 'emily.sanford', 'acme_staff_photo:female_age30_african_03'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'fcf7f08e-1837-585a-9bf9-71b45fbb3610', 0, 'charles.nelson', 'Charles Nelson', 'charles.nelson@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.market_risk', 'Viewer', 'Senior Analyst', 'stacy.lopez', 'acme_staff_photo:male_age20_latin_american_03'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'fd30d4de-dac7-5a6e-823e-02512734222b', 0, 'ashley.moore', 'Ashley Moore', 'ashley.moore@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_us.market_risk', 'Viewer', 'Junior Analyst', 'stacy.lopez', 'acme_staff_photo:female_age20_east_asian_03');
end $$;
