/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_bank/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * Acme Bank ACME_US Business Units Artefact Population Script
 *
 * parent_business_unit_id is the artefact-space id (uuid) of the parent
 * unit's own row in this same dataset -- ores_refdata_publish_business_
 * units_from_dq_fn walks this self-referential chain breadth-first and
 * remaps it to newly-published ids. This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_us.business_units'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_us.business_units. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_business_units_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_business_units_artefact_tbl (
        dataset_id, tenant_id, id, version, unit_name,
        parent_business_unit_id, unit_code, business_centre_code, unit_type_code
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '4951bc79-5e32-5677-ad77-77deea521a90', 0, 'Global Markets', null, 'acme_us.global_markets', 'USNY', 'DIVISION'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '25523799-1194-5c84-b415-40b6cd952335', 0, 'IR Swaps New York', '4951bc79-5e32-5677-ad77-77deea521a90', 'acme_us.ir_swaps', 'USNY', 'DESK'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '4e9fdb9b-1d8e-5318-9c00-27a522595f6f', 0, 'Credit Trading New York', '4951bc79-5e32-5677-ad77-77deea521a90', 'acme_us.credit_trading', 'USNY', 'DESK'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '2075badb-b410-5488-98ea-4c63eca7b475', 0, 'FX Rates New York', '4951bc79-5e32-5677-ad77-77deea521a90', 'acme_us.fx_rates', 'USNY', 'DESK'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '8141f088-c156-5003-8a86-3811f0e7e251', 0, 'Middle Office New York', null, 'acme_us.middle_office', 'USNY', 'COST_CENTRE'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '369a24e9-5568-5903-a163-910ca818e3dd', 0, 'Market Risk New York', null, 'acme_us.market_risk', 'USNY', 'COST_CENTRE');
end $$;
