/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_bank/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * Acme Bank ACME_UK Accounts Artefact Population Script
 *
 * business_unit_code is a natural-key code, resolved to a business unit
 * id by the publish function (see the server-side-orchestration
 * follow-up task). This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_uk.accounts'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_uk.accounts. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_accounts_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_accounts_artefact_tbl (
        dataset_id, tenant_id, id, version, username,
        email, password_hash, account_type, business_unit_code, role
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '39ee5b7c-d3aa-5b6d-8bae-f0bf5c2dec2e', 0, 'clifford.shaw.acme_uk.0', 'clifford.shaw.0@acme_uk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.ir_swaps', 'Desk Head'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '36045c3c-34f1-52ad-906b-473966f4266e', 0, 'stanley.turnbull.acme_uk.1', 'stanley.turnbull.1@acme_uk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.ir_swaps', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '01f75129-7726-5eb1-97d8-e1537797a113', 0, 'harriet.walker.acme_uk.2', 'harriet.walker.2@acme_uk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.ir_swaps', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '57aa30e6-6aa0-5132-b3a5-e05787a568b1', 0, 'joseph.brown.acme_uk.3', 'joseph.brown.3@acme_uk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.credit_trading', 'Desk Head'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '3fe56468-140f-5ecd-a281-332045e9b104', 0, 'bradley.kay.acme_uk.4', 'bradley.kay.4@acme_uk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.credit_trading', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '086e6fd5-fc5f-5d78-8803-06e493eb9d08', 0, 'jamie.thomson.acme_uk.5', 'jamie.thomson.5@acme_uk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.credit_trading', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '246473d4-7624-555b-967b-db2f2a2fc81e', 0, 'ellie.jennings.acme_uk.6', 'ellie.jennings.6@acme_uk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.fx_rates', 'Desk Head'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '640d5004-a4ff-50c6-9f5a-561941bd3758', 0, 'catherine.butcher.acme_uk.7', 'catherine.butcher.7@acme_uk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.fx_rates', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'cb942781-a346-54cc-a0ad-981a5c77b462', 0, 'sally.quinn.acme_uk.8', 'sally.quinn.8@acme_uk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.fx_rates', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '371e1c48-a2d4-52ae-abca-0b796aeda3ae', 0, 'patrick.davies.acme_uk.9', 'patrick.davies.9@acme_uk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.middle_office', 'Manager'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '05f7b132-c481-5be1-9a67-772e3e173b9b', 0, 'lorraine.french.acme_uk.10', 'lorraine.french.10@acme_uk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.middle_office', 'Analyst'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '2da2a20b-d07a-55fb-8d22-f53251a0af3b', 0, 'lynn.collins.acme_uk.11', 'lynn.collins.11@acme_uk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.middle_office', 'Analyst'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '53d86c6b-5c3c-5ec5-bd11-337636453272', 0, 'donald.pugh.acme_uk.12', 'donald.pugh.12@acme_uk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.market_risk', 'Manager'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '2245a374-c564-595c-890a-e92f09d4c87f', 0, 'lynne.davis.acme_uk.13', 'lynne.davis.13@acme_uk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.market_risk', 'Analyst'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '82fba5e7-3dce-5aee-8a64-bb83a443cf34', 0, 'denise.haynes.acme_uk.14', 'denise.haynes.14@acme_uk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.market_risk', 'Analyst');
end $$;
