/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_corporation/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- (organisation data), generate_netting_data.py (netting agreements, sets and
-- CSAs) and/or generate_sql.py, then run the generators and generate_sql.py.
-- =============================================================================

/**
 * ACME Corporation US CSAs Artefact Population Script
 *
 * Each CSA names its netting set by code; the eligible currencies are a comma list, margin currency first. This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_us.csas'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_us.csas. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_csas_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_csas_artefact_tbl (
        dataset_id, tenant_id, netting_set_code, version, is_active, bilateral, csa_currency, index_name, threshold_pay, threshold_receive, minimum_transfer_amount_pay, minimum_transfer_amount_receive, independent_amount_held, independent_amount_type, call_frequency, post_frequency, margin_period_of_risk, collateral_compounding_spread_receive, collateral_compounding_spread_pay, apply_initial_margin, initial_margin_type, calculate_im_amount, calculate_vm_amount, non_exempt_im_regulations, eligible_currencies
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUS-JPM-VMIM', 0, true, 'Bilateral', 'USD', 'USD-SOFR', 0.0, 0.0, 500000.0, 500000.0, 0.0, 'FIXED', '1D', '1D', '10D', 0.0, 0.0, true, 'Bilateral', true, true, 'CFTC,PRUDENTIAL', 'USD,EUR,GBP'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUS-BOFA-VM', 0, true, 'Bilateral', 'USD', 'USD-SOFR', 0.0, 0.0, 250000.0, 250000.0, 0.0, 'FIXED', '1D', '1D', '10D', 0.0, 0.0, false, null, false, true, null, 'USD,EUR,GBP'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUS-CITI-VM', 0, true, 'Bilateral', 'USD', 'USD-SOFR', 0.0, 0.0, 250000.0, 250000.0, 0.0, 'FIXED', '1D', '1D', '10D', 0.0, 0.0, false, null, false, true, null, 'USD,EUR,GBP'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUS-ACUK-IC-VM', 0, true, 'Bilateral', 'USD', 'USD-SOFR', 0.0, 0.0, 0.0, 0.0, 0.0, 'FIXED', '1D', '1D', '10D', 0.0, 0.0, false, null, false, true, null, 'USD,EUR,GBP');
end $$;
