/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_corporation/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- (organisation data), generate_netting_data.py (netting agreements, sets and
-- CSAs) and/or generate_sql.py, then run the generators and generate_sql.py.
-- =============================================================================

/**
 * ACME Corporation ACME_GROUP Account Contact Informations Artefact
 * Population Script
 *
 * account_username identifies the owning account by username, resolved
 * to an account id by the publish function once the account itself has
 * been published (see the server-side-orchestration follow-up task).
 * This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_group.account_contact_informations'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_group.account_contact_informations. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_account_contact_informations_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_account_contact_informations_artefact_tbl (
        dataset_id, tenant_id, id, version, account_username,
        street_line_1, street_line_2, city, state, country_code,
        postal_code, phone, email, web_page
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'f2fbfa25-d92f-5e80-9e16-71e13170499d', 0, 'adrian.vance', '25 Old Broad Street', null, 'London', null, 'GB', 'EC2N 1HQ', '+44 20 7946 0000', 'adrian.vance@acmecorp.com', null);
end $$;
