/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_corporation/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- (organisation data), generate_netting_data.py (netting agreements, sets and
-- CSAs) and/or generate_sql.py, then run the generators and generate_sql.py.
-- =============================================================================

/**
 * ACME Corporation Group Netting Agreements Artefact Population Script
 *
 * The agreement number is unique within the entity; the counterparty is resolved by LEI at publish time, so a bank is the legal entity GLEIF holds. This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_group.netting_agreements'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_group.netting_agreements. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_netting_agreements_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_netting_agreements_artefact_tbl (
        dataset_id, tenant_id, agreement_number, version, counterparty_lei, agreement_type, governing_law, description
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACGR-HSBC-ISDA-2016', 0, 'MP6I5ZYZBEU3UXPYFY54', 'ISDA', 'English', 'ISDA 2002 Master Agreement between Acme Corporation Plc and HSBC Bank plc, English law, signed 2016'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACGR-JPM-ISDA-2015', 0, '7H6GLXDRUGQFU57RNE97', 'ISDA', 'New York', 'ISDA 2002 Master Agreement between Acme Corporation Plc and JPMorgan Chase Bank, National Association, New York law, signed 2015'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACGR-ACUK-ISDA-2018', 0, '9695ACMEUK0000000047', 'ISDA', 'English', 'ISDA 2002 Master Agreement between Acme Corporation Plc and ACME Corporation UK plc, English law, signed 2018'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACGR-ACUS-ISDA-2018', 0, '9695ACMEUS0000000043', 'ISDA', 'New York', 'ISDA 2002 Master Agreement between Acme Corporation Plc and ACME Corporation US Inc, New York law, signed 2018'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACGR-ACHK-ISDA-2018', 0, '9695ACMEHK0000000018', 'ISDA', 'English', 'ISDA 2002 Master Agreement between Acme Corporation Plc and ACME Corporation HK Ltd, English law, signed 2018');
end $$;
