/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_bank/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * Acme Bank LEI Relationships Artefact Population Script
 *
 * Populates ores_dq_lei_relationships_artefact_tbl with the parent/
 * subsidiary consolidation relationships linking each Acme Bank office to
 * the holding company. This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.lei_relationships'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.lei_relationships. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_lei_relationships_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_lei_relationships_artefact_tbl (
        dataset_id, tenant_id, relationship_start_node_node_id, version,
        relationship_start_node_node_id_type, relationship_end_node_node_id,
        relationship_end_node_node_id_type, relationship_relationship_type,
        relationship_relationship_status
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '9695ACMEUK0000000047', 0, 'LEI', '9695ACMEGROUP0000030', 'LEI', 'IS_DIRECTLY_CONSOLIDATED_BY', 'ACTIVE'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '9695ACMEUS0000000043', 0, 'LEI', '9695ACMEGROUP0000030', 'LEI', 'IS_DIRECTLY_CONSOLIDATED_BY', 'ACTIVE'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '9695ACMEHK0000000018', 0, 'LEI', '9695ACMEGROUP0000030', 'LEI', 'IS_DIRECTLY_CONSOLIDATED_BY', 'ACTIVE');
end $$;
