/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_bank/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * Acme Bank ACME_UK Account Contact Informations Artefact
 * Population Script
 *
 * account_username identifies the owning account by username, resolved
 * to an account id by the publish function once the account itself has
 * been published (see the server-side-orchestration follow-up task).
 * This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_uk.account_contact_informations'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_uk.account_contact_informations. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_account_contact_informations_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_account_contact_informations_artefact_tbl (
        dataset_id, tenant_id, id, version, account_username, full_name,
        street_line_1, street_line_2, city, state, country_code,
        postal_code, phone, email, web_page
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '4845555c-0612-5d7c-a477-f94644140eb9', 0, 'clifford.shaw.acme_uk.0', 'Clifford Shaw', null, null, null, null, null, null, null, 'clifford.shaw.0@acme_uk.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'cb2c4fa8-3bba-5779-b54b-cb3bd0f0d80a', 0, 'stanley.turnbull.acme_uk.1', 'Stanley Turnbull', null, null, null, null, null, null, null, 'stanley.turnbull.1@acme_uk.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'c7bf1375-f4eb-5ddf-93f4-0c1b62448811', 0, 'harriet.walker.acme_uk.2', 'Harriet Walker', null, null, null, null, null, null, null, 'harriet.walker.2@acme_uk.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '90fcfcc2-5ebe-554f-bd32-82690e226272', 0, 'joseph.brown.acme_uk.3', 'Joseph Brown', null, null, null, null, null, null, null, 'joseph.brown.3@acme_uk.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '616c5125-4768-5192-89f2-55bf594e608b', 0, 'bradley.kay.acme_uk.4', 'Bradley Kay', null, null, null, null, null, null, null, 'bradley.kay.4@acme_uk.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'f219b929-48c3-53eb-8eb9-7d10550ece1d', 0, 'jamie.thomson.acme_uk.5', 'Jamie Thomson', null, null, null, null, null, null, null, 'jamie.thomson.5@acme_uk.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '4b6cf248-97ad-5223-9253-0fc1219d244c', 0, 'ellie.jennings.acme_uk.6', 'Ellie Jennings', null, null, null, null, null, null, null, 'ellie.jennings.6@acme_uk.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'e478714f-0494-5023-bb7b-7d3065739a0c', 0, 'catherine.butcher.acme_uk.7', 'Catherine Butcher', null, null, null, null, null, null, null, 'catherine.butcher.7@acme_uk.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'c9d9c5f8-a8e2-5b2b-a108-82055531e28e', 0, 'sally.quinn.acme_uk.8', 'Sally Quinn', null, null, null, null, null, null, null, 'sally.quinn.8@acme_uk.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '462e8f5d-4cb6-56e0-bedc-390752066913', 0, 'patrick.davies.acme_uk.9', 'Patrick Davies', null, null, null, null, null, null, null, 'patrick.davies.9@acme_uk.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'a47efd2e-9c57-56c8-9b37-6e5347cf19e7', 0, 'lorraine.french.acme_uk.10', 'Lorraine French', null, null, null, null, null, null, null, 'lorraine.french.10@acme_uk.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ae31d791-a39d-5251-b9ae-92e4dc9176c1', 0, 'lynn.collins.acme_uk.11', 'Lynn Collins', null, null, null, null, null, null, null, 'lynn.collins.11@acme_uk.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'eb950fcc-a666-5824-8133-1b52a3499532', 0, 'donald.pugh.acme_uk.12', 'Donald Pugh', null, null, null, null, null, null, null, 'donald.pugh.12@acme_uk.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'c8962376-5ae4-5986-a9cf-2adac6baf6c6', 0, 'lynne.davis.acme_uk.13', 'Lynne Davis', null, null, null, null, null, null, null, 'lynne.davis.13@acme_uk.acmebank.example', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '365afa66-34a7-50bd-a4c7-90ffe759b583', 0, 'denise.haynes.acme_uk.14', 'Denise Haynes', null, null, null, null, null, null, null, 'denise.haynes.14@acme_uk.acmebank.example', null);
end $$;
