/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_bank/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * Acme Bank LEI Entities Artefact Population Script
 *
 * Populates ores_dq_lei_entities_artefact_tbl with Acme Bank's four legal
 * entities. This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.lei_entities'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.lei_entities. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_lei_entities_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_lei_entities_artefact_tbl (
        dataset_id, tenant_id, lei, version, entity_legal_name,
        entity_entity_category, entity_entity_sub_category, entity_entity_status,
        entity_legal_form_entity_legal_form_code, entity_legal_form_other_legal_form,
        entity_legal_jurisdiction, entity_legal_address_first_address_line,
        entity_legal_address_city, entity_legal_address_region, entity_legal_address_country,
        entity_legal_address_postal_code, entity_headquarters_address_first_address_line,
        entity_headquarters_address_city, entity_headquarters_address_region,
        entity_headquarters_address_country, entity_headquarters_address_postal_code
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '9695ACMEGROUP0000030', 0, 'Acme Bank Group plc', 'GENERAL', null, 'ACTIVE', null, null, 'GB', null, 'London', null, 'GB', null, null, 'London', null, 'GB', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '9695ACMEUK0000000047', 0, 'Acme Bank UK plc', 'GENERAL', null, 'ACTIVE', null, null, 'GB', '886 Deborah Radial', 'London', null, 'GB', null, '886 Deborah Radial', 'London', null, 'GB', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '9695ACMEUS0000000043', 0, 'Acme Bank US Inc', 'GENERAL', null, 'ACTIVE', null, null, 'US', '997 David Way', 'New York', null, 'US', null, '997 David Way', 'New York', null, 'US', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '9695ACMEHK0000000018', 0, 'Acme Bank HK Ltd', 'GENERAL', null, 'ACTIVE', null, null, 'HK', 'Wai Ming Building, Central', 'Hong Kong', null, 'HK', null, 'Wai Ming Building, Central', 'Hong Kong', null, 'HK', null);
end $$;
