/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_corporation/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * ACME Corporation ACME_HK Accounts Artefact Population Script
 *
 * business_unit_code is a natural-key code, resolved to a business unit
 * id by the publish function (see the server-side-orchestration
 * follow-up task). This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_hk.accounts'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_hk.accounts. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_accounts_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_accounts_artefact_tbl (
        dataset_id, tenant_id, id, version, username, full_name,
        email, password_hash, account_type, business_unit_code, role,
        job_title, reports_to_username, photo_key
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'b01cf539-d034-5743-8e46-a932569ae039', 0, 'wai.ming.chan', 'Wai Ming Chan', 'wai.ming.chan@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.global_markets', 'Operations', 'Country Head', 'adrian.vance', 'acme_staff_photo:female_age25_east_asian_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'c7f930b6-9c90-5b5e-9b78-ecbd84170055', 0, 'siu.fung.wong', 'Siu Fung Wong', 'siu.fung.wong@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.global_markets', 'Operations', 'COO', 'wai.ming.chan', 'acme_staff_photo:male_age20_southeast_asian_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '381a497c-91e1-5454-b94a-4936bea197d5', 0, 'ka.yee.lee', 'Ka Yee Lee', 'ka.yee.lee@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.global_markets', 'Operations', 'Head of Risk', 'wai.ming.chan', 'acme_staff_photo:female_age25_east_asian_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'c015ce8e-5e70-5b18-bf46-2af0d5bb94ab', 0, 'chi.wing.cheung', 'Chi Wing Cheung', 'chi.wing.cheung@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.global_markets', 'Trading', 'Head of Trading', 'wai.ming.chan', 'acme_staff_photo:male_age20_southeast_asian_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '4781e19a-b461-5c1f-bbbd-af4d0e6cfcf4', 0, 'man.yee.ng', 'Man Yee Ng', 'man.yee.ng@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.ir_swaps', 'Trading', 'Head of Desk', 'chi.wing.cheung', 'acme_staff_photo:female_age25_east_asian_03'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '3e0d1630-2663-5369-a324-4fdc238c11a8', 0, 'tsz.ching.lau', 'Tsz Ching Lau', 'tsz.ching.lau@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.ir_swaps', 'Trading', 'Senior Trader', 'man.yee.ng', 'acme_staff_photo:male_age20_southeast_asian_03'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '55d78ceb-a718-52cf-b1d3-ff44ebfc31a9', 0, 'ho.yin.tang', 'Ho Yin Tang', 'ho.yin.tang@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.ir_swaps', 'Trading', 'Junior Trader', 'man.yee.ng', 'acme_staff_photo:female_age30_east_asian_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '067ef312-b3b3-5223-bddb-1557f1e4f054', 0, 'ying.ying.lam', 'Ying Ying Lam', 'ying.ying.lam@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.credit_trading', 'Trading', 'Head of Desk', 'chi.wing.cheung', 'acme_staff_photo:male_age25_southeast_asian_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '3d374bbb-0308-5d02-9cda-1116ac02778d', 0, 'kwok.wing.yip', 'Kwok Wing Yip', 'kwok.wing.yip@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.credit_trading', 'Trading', 'Senior Trader', 'ying.ying.lam', 'acme_staff_photo:female_age30_east_asian_03'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '71650cfa-c86e-5a89-b4ce-a0453f2f5e1e', 0, 'suet.ying.ho', 'Suet Ying Ho', 'suet.ying.ho@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.credit_trading', 'Trading', 'Junior Trader', 'ying.ying.lam', 'acme_staff_photo:male_age25_southeast_asian_03'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'c8aac694-decf-509d-86dd-45d271d76ec4', 0, 'hoi.yan.chan', 'Hoi Yan Chan', 'hoi.yan.chan@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.fx_rates', 'Trading', 'Head of Desk', 'chi.wing.cheung', 'acme_staff_photo:female_age35_east_asian_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'b8980590-1147-591d-b106-1f27ee98533e', 0, 'chun.kit.wong', 'Chun Kit Wong', 'chun.kit.wong@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.fx_rates', 'Trading', 'Senior Trader', 'hoi.yan.chan', 'acme_staff_photo:male_age30_southeast_asian_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '6222f226-f58f-59f8-b23e-2ea34f52f818', 0, 'wai.ming.lee', 'Wai Ming Lee', 'wai.ming.lee@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.fx_rates', 'Trading', 'Junior Trader', 'hoi.yan.chan', 'acme_staff_photo:female_age35_east_asian_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '8a3c8d81-c5f2-5fdb-b671-b0b0c2d25190', 0, 'siu.fung.cheung', 'Siu Fung Cheung', 'siu.fung.cheung@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.middle_office', 'Operations', 'Head of Middle Office', 'siu.fung.wong', 'acme_staff_photo:male_age30_southeast_asian_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'df1da07d-8f41-5b0a-b593-a37bc8688e2d', 0, 'ka.yee.ng', 'Ka Yee Ng', 'ka.yee.ng@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.middle_office', 'Viewer', 'Senior Analyst', 'siu.fung.cheung', 'acme_staff_photo:female_age40_east_asian_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'b75a4473-3800-5cc2-a9c6-c1e6846fcc8b', 0, 'chi.wing.lau', 'Chi Wing Lau', 'chi.wing.lau@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.middle_office', 'Viewer', 'Junior Analyst', 'siu.fung.cheung', 'acme_staff_photo:male_age30_southeast_asian_03'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '56977b7f-36bd-5405-b347-443eabc78b7b', 0, 'man.yee.tang', 'Man Yee Tang', 'man.yee.tang@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.market_risk', 'Operations', 'Head of Market Risk', 'ka.yee.lee', 'acme_staff_photo:female_age40_east_asian_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'd2808ff6-4716-5b21-b754-f1061b0fb40b', 0, 'tsz.ching.lam', 'Tsz Ching Lam', 'tsz.ching.lam@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.market_risk', 'Viewer', 'Senior Analyst', 'man.yee.tang', 'acme_staff_photo:male_age35_southeast_asian_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '7db9a8b2-08d7-50a7-978d-299b73275a55', 0, 'ho.yin.yip', 'Ho Yin Yip', 'ho.yin.yip@acmecorp.hk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.market_risk', 'Viewer', 'Junior Analyst', 'man.yee.tang', 'acme_staff_photo:female_age40_east_asian_03');
end $$;
