/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_corporation/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * ACME Corporation ACME_GROUP Accounts Artefact Population Script
 *
 * business_unit_code is a natural-key code, resolved to a business unit
 * id by the publish function (see the server-side-orchestration
 * follow-up task). This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_group.accounts'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_group.accounts. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_accounts_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_accounts_artefact_tbl (
        dataset_id, tenant_id, id, version, username, full_name,
        email, password_hash, account_type, business_unit_code, role,
        job_title, reports_to_username, photo_key
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'd5124a10-9284-5243-a017-07abf0dc5a60', 0, 'adrian.vance', 'Adrian Vance', 'adrian.vance@acmecorp.com', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', null, 'Operations', 'Group Chief Executive Officer', null, 'acme_staff_photo:male_age20_european_01');
end $$;
