/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_corporation/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * ACME Corporation ACME_US Account Contact Informations Artefact
 * Population Script
 *
 * account_username identifies the owning account by username, resolved
 * to an account id by the publish function once the account itself has
 * been published (see the server-side-orchestration follow-up task).
 * This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_us.account_contact_informations'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_us.account_contact_informations. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_account_contact_informations_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_account_contact_informations_artefact_tbl (
        dataset_id, tenant_id, id, version, account_username,
        street_line_1, street_line_2, city, state, country_code,
        postal_code, phone, email, web_page
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '82d7968d-3d6e-53c7-ae2b-935375be98fe', 0, 'mindy.adams', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'mindy.adams@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '16ec96f8-d1cc-5777-8054-a66f518dcf83', 0, 'david.reeves', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'david.reeves@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '8ddbae0f-d39f-5201-bca4-96b9870544d8', 0, 'emily.sanford', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'emily.sanford@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '12ea185f-738b-5f3d-9553-8b578fa0ab82', 0, 'paul.armstrong', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'paul.armstrong@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '6e91b428-efc1-5e6e-8b1c-8e7b200a8739', 0, 'yesenia.choi', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'yesenia.choi@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'b732b040-f1f1-5f34-a770-1666ca4c60de', 0, 'timothy.adams', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'timothy.adams@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '9a1ba5b8-9b2a-525d-9365-b292a8099c82', 0, 'elizabeth.barrett', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'elizabeth.barrett@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '1a33b30e-8994-5d34-bd32-a4f3066169d8', 0, 'john.robinson', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'john.robinson@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '7575e752-c191-50d1-a9a3-e4142d2db0ae', 0, 'sandra.green', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'sandra.green@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'a5e37f2a-3a57-59c7-ac6c-4bb6711fd31b', 0, 'henry.jones', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'henry.jones@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '67930219-bd7b-5a56-8b82-1cebb3c21a3b', 0, 'laura.carlson', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'laura.carlson@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '5c3901a5-5ab3-5f6c-a15a-560be032a939', 0, 'corey.gross', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'corey.gross@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '82be961a-4926-5731-94e5-2f46580d6268', 0, 'shirley.stevens', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'shirley.stevens@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '1e14926a-ad3f-5e65-b719-c52086239f4e', 0, 'mark.reid', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'mark.reid@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '6fa09e02-52d1-526a-9ed8-41b70055f6e3', 0, 'elizabeth.franklin', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'elizabeth.franklin@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '1f2ece1a-3895-5d8e-adac-bd0ce8a2c0d9', 0, 'john.sullivan', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'john.sullivan@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '4bb59d80-131f-50f3-9dbc-e71ec949545c', 0, 'stacy.lopez', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'stacy.lopez@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'e31f6369-6454-56d2-a459-e171818eb3a1', 0, 'charles.nelson', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'charles.nelson@acmecorp.com', null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'bf0ee385-036e-5248-a063-9031fc1acfff', 0, 'ashley.moore', '200 Park Avenue', null, 'New York', 'NY', 'US', '10166', '+1 212 555 0148', 'ashley.moore@acmecorp.com', null);
end $$;
