/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_corporation/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * ACME Corporation US Netting Sets Artefact Population Script
 *
 * Each set names its agreement by number; the agreement is found among the same entity's agreements at publish time. This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_us.netting_sets'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_us.netting_sets. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_netting_sets_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_netting_sets_artefact_tbl (
        dataset_id, tenant_id, code, version, agreement_number, description
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUS-JPM-VMIM', 0, 'ACUS-JPM-ISDA-2015', 'OTC derivatives with JPMorgan Chase Bank, National Association under the 2016 Credit Support Annex for Variation Margin (New York law) and the 2018 Credit Support Annex for Initial Margin (New York law), variation and initial margin, margined daily'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUS-JPM-CMDTY-UNC', 0, 'ACUS-JPM-ISDA-2015', 'Commodity derivatives with JPMorgan Chase Bank, National Association outside the credit support annex, uncollateralised'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUS-BOFA-VM', 0, 'ACUS-BOFA-ISDA-2017', 'OTC derivatives with Bank of America, National Association under the 2016 Credit Support Annex for Variation Margin (New York law), variation margin only, margined daily'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUS-CITI-VM', 0, 'ACUS-CITI-ISDA-2016', 'OTC derivatives with Citibank, National Association under the 2016 Credit Support Annex for Variation Margin (New York law), variation margin only, margined daily'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUS-ACGR-IC-UNC', 0, 'ACGR-ACUS-ISDA-2018', 'Intragroup derivatives with Acme Corporation Plc, uncollateralised'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUS-ACUK-IC-VM', 0, 'ACUK-ACUS-ISDA-2019', 'Intragroup derivatives with ACME Corporation UK plc, variation margin only');
end $$;
