/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_bank/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * Acme Bank ACME_UK Portfolios Artefact Population Script
 *
 * parent_portfolio_id is the artefact-space id (uuid) of the parent
 * portfolio's own row in this dataset; owner_unit_id is the artefact-
 * space id of the owning row in the matching business_units dataset --
 * both self/cross-referential ids resolved by name at publish time (see
 * ores_refdata_publish_portfolios_from_dq_fn). This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_uk.portfolios'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_uk.portfolios. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_portfolios_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_portfolios_artefact_tbl (
        dataset_id, tenant_id, id, version, name,
        parent_portfolio_id, owner_unit_id, purpose_type, aggregation_ccy, is_virtual
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '93925bc5-1800-5c69-a18b-f683dae17f2e', 0, 'Acme Bank UK plc Global Markets', null, '57e8e604-dcb6-515a-a6bd-38f0be805480', 'Risk', 'GBP', 1),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '2e99eb72-bab9-5a7f-9b57-a194cc2e164b', 0, 'IR Swaps London Portfolio', '93925bc5-1800-5c69-a18b-f683dae17f2e', '1e719eee-612e-5927-8e71-4107008a1590', 'Risk', 'GBP', 0),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'e7f6b28c-f0b3-5c66-a9f9-bcc057369e3f', 0, 'Credit Trading London Portfolio', '93925bc5-1800-5c69-a18b-f683dae17f2e', 'aeb8a9e6-86a6-5382-b5eb-54c1b9577c32', 'Risk', 'GBP', 0),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '4ae8aa86-e0f2-56fc-9cf5-5a631ec54120', 0, 'FX Rates London Portfolio', '93925bc5-1800-5c69-a18b-f683dae17f2e', 'c3264d1e-2c3a-538c-b598-915a8b354dec', 'Risk', 'GBP', 0);
end $$;
