/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_corporation/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * ACME Corporation UK Netting Sets Artefact Population Script
 *
 * Each set names its agreement by number; the agreement is found among the same entity's agreements at publish time. This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_uk.netting_sets'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_uk.netting_sets. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_netting_sets_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_netting_sets_artefact_tbl (
        dataset_id, tenant_id, code, version, agreement_number, description
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUK-BARC-VMIM', 0, 'ACUK-BARC-ISDA-2014', 'OTC derivatives with Barclays Bank PLC under the 2016 Credit Support Annex for Variation Margin (English law, title transfer) and the 2016 Credit Support Deed for Initial Margin (English law, security interest), variation and initial margin, margined daily'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUK-BARC-CMDTY-UNC', 0, 'ACUK-BARC-ISDA-2014', 'Commodity derivatives with Barclays Bank PLC outside the credit support annex, uncollateralised'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUK-HSBC-VM', 0, 'ACUK-HSBC-ISDA-2016', 'OTC derivatives with HSBC Bank plc under the 2016 Credit Support Annex for Variation Margin (English law, title transfer), variation margin only, margined daily'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUK-DB-VM', 0, 'ACUK-DB-ISDA-2015', 'OTC derivatives with Deutsche Bank AG under the 2016 Credit Support Annex for Variation Margin (English law, title transfer), variation margin only, margined daily'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUK-BNPP-VM', 0, 'ACUK-BNPP-ISDA-2018', 'OTC derivatives with BNP Paribas under the 2016 Credit Support Annex for Variation Margin (English law, title transfer), variation margin only, margined daily'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUK-UBS-UNC', 0, 'ACUK-UBS-ISDA-2012', 'OTC derivatives with UBS AG, uncollateralised'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUK-ACGR-IC-UNC', 0, 'ACGR-ACUK-ISDA-2018', 'Intragroup derivatives with Acme Corporation Plc, uncollateralised'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ACUK-ACUS-IC-VM', 0, 'ACUK-ACUS-ISDA-2019', 'Intragroup derivatives with ACME Corporation US Inc, variation margin only');
end $$;
