/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_bank/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * Acme Bank ACME_UK Business Units Artefact Population Script
 *
 * parent_business_unit_id is the artefact-space id (uuid) of the parent
 * unit's own row in this same dataset -- ores_refdata_publish_business_
 * units_from_dq_fn walks this self-referential chain breadth-first and
 * remaps it to newly-published ids. This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_uk.business_units'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_uk.business_units. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_business_units_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_business_units_artefact_tbl (
        dataset_id, tenant_id, id, version, unit_name,
        parent_business_unit_id, unit_code, business_centre_code, unit_type_code
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '57e8e604-dcb6-515a-a6bd-38f0be805480', 0, 'Global Markets', null, 'acme_uk.global_markets', 'GBLO', 'DIVISION'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '1e719eee-612e-5927-8e71-4107008a1590', 0, 'IR Swaps London', '57e8e604-dcb6-515a-a6bd-38f0be805480', 'acme_uk.ir_swaps', 'GBLO', 'DESK'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'aeb8a9e6-86a6-5382-b5eb-54c1b9577c32', 0, 'Credit Trading London', '57e8e604-dcb6-515a-a6bd-38f0be805480', 'acme_uk.credit_trading', 'GBLO', 'DESK'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'c3264d1e-2c3a-538c-b598-915a8b354dec', 0, 'FX Rates London', '57e8e604-dcb6-515a-a6bd-38f0be805480', 'acme_uk.fx_rates', 'GBLO', 'DESK'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'a3c5e2ae-d25f-5f39-b334-e59d76ceff31', 0, 'Middle Office London', null, 'acme_uk.middle_office', 'GBLO', 'COST_CENTRE'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '648136b1-4548-59e8-80c7-2eb7639c4a89', 0, 'Market Risk London', null, 'acme_uk.market_risk', 'GBLO', 'COST_CENTRE');
end $$;
