/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_corporation/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * ACME Corporation ACME_UK Accounts Artefact Population Script
 *
 * business_unit_code is a natural-key code, resolved to a business unit
 * id by the publish function (see the server-side-orchestration
 * follow-up task). This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_uk.accounts'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_uk.accounts. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_accounts_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_accounts_artefact_tbl (
        dataset_id, tenant_id, id, version, username, full_name,
        email, password_hash, account_type, business_unit_code, role,
        job_title, reports_to_username, photo_key
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '45c825ea-4a56-5998-a3ab-e9090223a20c', 0, 'leanne.shaw', 'Leanne Shaw', 'leanne.shaw@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.global_markets', 'Operations', 'Country Head', null, 'acme_staff_photo:female_age20_european_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'f76254c9-b91d-5351-9d7a-8330c65acc6f', 0, 'sam.turnbull', 'Sam Turnbull', 'sam.turnbull@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.global_markets', 'Operations', 'COO', 'leanne.shaw', 'acme_staff_photo:male_age20_south_asian_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '280cdf7a-dac7-52da-bac7-a24a39c51a86', 0, 'vanessa.walker', 'Vanessa Walker', 'vanessa.walker@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.global_markets', 'Operations', 'Head of Risk', 'leanne.shaw', 'acme_staff_photo:female_age20_african_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'e49201d8-e4db-53ab-98a1-936172e1879f', 0, 'joshua.brown', 'Joshua Brown', 'joshua.brown@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.global_markets', 'Trading', 'Head of Trading', 'leanne.shaw', 'acme_staff_photo:male_age20_west_asian_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'a8c728f8-4c45-5d65-a3cf-d83d5d0157f1', 0, 'diane.kay', 'Diane Kay', 'diane.kay@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.rates_trading_emea', 'Trading', 'Head of Desk', 'joshua.brown', 'acme_staff_photo:female_age20_european_03'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'fa2fa964-4bb5-5201-8a2b-b5abafc515d3', 0, 'william.thomson', 'William Thomson', 'william.thomson@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.rates_trading_emea', 'Trading', 'Senior Trader', 'diane.kay', 'acme_staff_photo:male_age20_south_asian_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '26c47d5c-3aad-53b3-9338-65f02950e6c0', 0, 'hazel.jennings', 'Hazel Jennings', 'hazel.jennings@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.rates_trading_emea', 'Trading', 'Junior Trader', 'diane.kay', 'acme_staff_photo:female_age20_african_03'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '1dcea59a-bdf0-5406-8165-1170a28b12ba', 0, 'shane.butcher', 'Shane Butcher', 'shane.butcher@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.credit_trading_emea', 'Trading', 'Head of Desk', 'joshua.brown', 'acme_staff_photo:male_age20_west_asian_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '59bb6938-3145-5a92-b8e2-7a81f67154cc', 0, 'molly.quinn', 'Molly Quinn', 'molly.quinn@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.credit_trading_emea', 'Trading', 'Senior Trader', 'shane.butcher', 'acme_staff_photo:female_age25_european_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'e7b5aff0-e042-5ffb-bbb4-cf466200938a', 0, 'steven.davies', 'Steven Davies', 'steven.davies@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.credit_trading_emea', 'Trading', 'Junior Trader', 'shane.butcher', 'acme_staff_photo:male_age20_south_asian_03'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '36fc165f-dd0a-59d2-8040-fedf34aea3ef', 0, 'harriet.french', 'Harriet French', 'harriet.french@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.fx_trading_emea', 'Trading', 'Head of Desk', 'joshua.brown', 'acme_staff_photo:female_age25_african_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ee504aba-06d7-5b10-93b4-94dd7e70435f', 0, 'martyn.collins', 'Martyn Collins', 'martyn.collins@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.fx_trading_emea', 'Trading', 'Senior Trader', 'harriet.french', 'acme_staff_photo:male_age20_west_asian_03'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'db964e1c-899e-546f-a8d9-9c412d662890', 0, 'megan.pugh', 'Megan Pugh', 'megan.pugh@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.fx_trading_emea', 'Trading', 'Junior Trader', 'harriet.french', 'acme_staff_photo:female_age25_european_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '46cc3223-c38d-59da-9680-426fa6dff4d3', 0, 'lawrence.davis', 'Lawrence Davis', 'lawrence.davis@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.middle_office', 'Operations', 'Head of Middle Office', 'sam.turnbull', 'acme_staff_photo:male_age25_south_asian_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '868352f7-062a-5257-9ec3-5f307f47a9ef', 0, 'kathryn.haynes', 'Kathryn Haynes', 'kathryn.haynes@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.middle_office', 'Viewer', 'Senior Analyst', 'lawrence.davis', 'acme_staff_photo:female_age25_african_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '2d070c1a-0239-5781-9abb-0b18cf274a1e', 0, 'matthew.day', 'Matthew Day', 'matthew.day@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.middle_office', 'Viewer', 'Junior Analyst', 'lawrence.davis', 'acme_staff_photo:male_age25_west_asian_01'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'c035eec8-7125-5463-90cd-c99f731b0344', 0, 'eleanor.jackson', 'Eleanor Jackson', 'eleanor.jackson@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.market_risk', 'Operations', 'Head of Market Risk', 'vanessa.walker', 'acme_staff_photo:female_age25_european_03'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '8d98681b-ddaf-5979-9ae0-6581f8265b82', 0, 'howard.scott', 'Howard Scott', 'howard.scott@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.market_risk', 'Viewer', 'Senior Analyst', 'eleanor.jackson', 'acme_staff_photo:male_age25_south_asian_02'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '3410d3c4-110a-5b1e-a8f5-da60216f4312', 0, 'maureen.palmer', 'Maureen Palmer', 'maureen.palmer@acmecorp.co.uk', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_uk.market_risk', 'Viewer', 'Junior Analyst', 'eleanor.jackson', 'acme_staff_photo:female_age25_african_03');
end $$;
