/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_corporation/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * ACME Corporation ACME_HK Books Artefact Population Script
 *
 * parent_portfolio_id is the artefact-space id (uuid) of the owning row
 * in the matching portfolios dataset, resolved by name at publish time
 * (see ores_refdata_publish_books_from_dq_fn). This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_hk.books'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_hk.books. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_books_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_books_artefact_tbl (
        dataset_id, tenant_id, id, version, name,
        parent_portfolio_id, functional_currency, gl_account_ref, cost_center,
        book_status, regulatory_book_type, is_sweepable, rates_centre_code
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '10da1d97-1e96-53db-a3cc-6f6bf96b1cda', 0, 'JPY Rates Book', '9baf7c4a-7745-5271-8893-86db933a393c', 'HKD', null, null, 'Active', 'Trading', false, null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '3ee05afa-0fb2-5d9a-9bce-88a8b46777e7', 0, 'IG Credit APAC Book', '23a0b5ee-ee06-59aa-9bc6-e081187248aa', 'HKD', null, null, 'Active', 'Trading', false, null),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '92fb437d-12f9-5112-8d48-dd0c6a6ccfa5', 0, 'G10 FX APAC Book', '62ef27bf-b2a1-5802-98c8-d1d867087a56', 'HKD', null, null, 'Active', 'Trading', false, null);
end $$;
