/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

-- =============================================================================
-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
-- Generated by projects/ores.seeder/datasets/acme_bank/generate_sql.py from
-- the JSON files in that same directory. To modify, update generate_data.py
-- and/or generate_sql.py and regenerate both.
-- =============================================================================

/**
 * Acme Bank ACME_HK Accounts Artefact Population Script
 *
 * business_unit_code is a natural-key code, resolved to a business unit
 * id by the publish function (see the server-side-orchestration
 * follow-up task). This script is idempotent.
 */

DO $$
declare
    v_dataset_id uuid;
begin
    select id into v_dataset_id
    from ores_dq_datasets_tbl
    where code = 'acme.acme_hk.accounts'
      and valid_to = ores_utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: acme.acme_hk.accounts. Run acme_dataset_populate.sql first.';
    end if;

    delete from ores_dq_accounts_artefact_tbl
    where dataset_id = v_dataset_id;

    insert into ores_dq_accounts_artefact_tbl (
        dataset_id, tenant_id, id, version, username,
        email, password_hash, account_type, business_unit_code, role
    )
    values
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '4bea6ac0-baf8-5cac-bf3f-693667fde73a', 0, 'wai.ming.chan.acme_hk.0', 'wai.ming.chan.0@acme_hk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.ir_swaps', 'Desk Head'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '3d6c552e-6ea5-5792-8f89-477883bbc956', 0, 'siu.fung.wong.acme_hk.1', 'siu.fung.wong.1@acme_hk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.ir_swaps', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '8aa62145-0571-5292-b0a2-7b449cd10e81', 0, 'ka.yee.lee.acme_hk.2', 'ka.yee.lee.2@acme_hk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.ir_swaps', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ba4d60b9-4b9a-5ba9-a942-8dd888230c22', 0, 'chi.wing.cheung.acme_hk.3', 'chi.wing.cheung.3@acme_hk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.credit_trading', 'Desk Head'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'cd197edc-790c-50af-90ef-ef1a876f22ee', 0, 'man.yee.ng.acme_hk.4', 'man.yee.ng.4@acme_hk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.credit_trading', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'd750128f-f670-50f4-bbc8-1c09e67bdde7', 0, 'tsz.ching.lau.acme_hk.5', 'tsz.ching.lau.5@acme_hk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.credit_trading', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'e9ab56c6-2e44-5622-acf0-cf9b774098de', 0, 'ho.yin.tang.acme_hk.6', 'ho.yin.tang.6@acme_hk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.fx_rates', 'Desk Head'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'd6f24ba5-4c5e-5571-a03f-b0052b506152', 0, 'ying.ying.lam.acme_hk.7', 'ying.ying.lam.7@acme_hk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.fx_rates', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '6ecac9d8-7438-5ea9-9b24-4604f94e16ed', 0, 'kwok.wing.yip.acme_hk.8', 'kwok.wing.yip.8@acme_hk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.fx_rates', 'Trader'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'ee914258-fc98-5bb7-b6ee-0b3793e5c9eb', 0, 'suet.ying.ho.acme_hk.9', 'suet.ying.ho.9@acme_hk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.middle_office', 'Manager'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'aeaf0a73-4c88-5609-bc19-8eb1faf5b0d6', 0, 'hoi.yan.chan.acme_hk.10', 'hoi.yan.chan.10@acme_hk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.middle_office', 'Analyst'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '82ae32fa-8f58-5896-a5e5-bf7465674ca9', 0, 'chun.kit.wong.acme_hk.11', 'chun.kit.wong.11@acme_hk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.middle_office', 'Analyst'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'a8380aa1-d27e-5f29-833e-4dfc295eba80', 0, 'wai.ming.lee.acme_hk.12', 'wai.ming.lee.12@acme_hk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.market_risk', 'Manager'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), 'db12e986-300c-5898-81d6-82583e5f5b37', 0, 'siu.fung.cheung.acme_hk.13', 'siu.fung.cheung.13@acme_hk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.market_risk', 'Analyst'),
        (v_dataset_id, ores_utility_system_tenant_id_fn(), '113666f1-f2f7-58d7-a6e1-8476478a94d3', 0, 'ka.yee.ng.acme_hk.14', 'ka.yee.ng.14@acme_hk.acmebank.example', '$scrypt$ln=14,r=8,p=1$0h1vacFtQdXZd9nqj+0G/Q==$4zoqrV+ojPxe/IwWAMLDXGHZQYJQGYgU6270fCl4kcXYep+uLyganiEM9ARBGQa83MbfvyurLPH304ZTdy8msw==', 'user', 'acme_hk.market_risk', 'Analyst');
end $$;
