/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2025 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */
create schema if not exists oresdb;
create extension if not exists btree_gist;
set schema 'oresdb';

--
-- generated by sqlgen and manually adapted for temporal support.
--
create table if not exists "oresdb"."currencies" (
    "iso_code" text not null,
    "name" text not null,
    "numeric_code" text not null,
    "symbol" text not null,
    "fraction_symbol" text not null,
    "fractions_per_unit" integer not null,
    "rounding_type" text not null,
    "rounding_precision" integer not null,
    "format" text not null,
    "currency_type" text not null,
    "modified_by" text not null,
    "valid_from" timestamp with time zone not null,
    "valid_to" timestamp with time zone not null,
    primary key (iso_code, valid_from, valid_to),
    exclude using gist (
        iso_code WITH =,
        tstzrange(valid_from, valid_to) WITH &&
    )
);

create or replace function update_currencies()
returns trigger as $$
begin
    update "oresdb"."currencies"
    set valid_to = current_timestamp
    where iso_code = new.iso_code
    and valid_to = '9999-12-31 23:59:59'::timestamptz
    and valid_from < current_timestamp;

    new.valid_from = current_timestamp;
    new.valid_to = '9999-12-31 23:59:59'::timestamptz;
    new.modified_by = current_user;

    return new;
end;
$$ language plpgsql;

create or replace trigger  update_currencies_trigger
before insert on "oresdb"."currencies"
for each row
execute function update_currencies();

create or replace function delete_currencies()
returns trigger as $$
begin
    update "oresdb"."currencies"
    set valid_to = current_timestamp
    where iso_code = old.iso_code
    and valid_to = '9999-12-31 23:59:59'::timestamptz;

    return null;  -- Cancel the actual delete to preserve history
end;
$$ language plpgsql;

create or replace trigger delete_currencies_trigger
before delete on "oresdb"."currencies"
for each row
execute function delete_currencies();
