/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Cryptocurrency Reference Data Master Include File
 *
 * Auto-generated by crypto_generate_metadata_sql.py
 * Includes all cryptocurrency SQL files in the correct dependency order.
 */

-- =============================================================================
-- Cryptocurrency Catalog (must come first)
-- =============================================================================

\echo '--- Cryptocurrency Catalog ---'
\ir crypto_catalog_populate.sql

-- =============================================================================
-- Cryptocurrency Methodology
-- =============================================================================

\echo '--- Cryptocurrency Methodology ---'
\ir crypto_methodology_populate.sql

-- =============================================================================
-- Cryptocurrency Datasets
-- =============================================================================

\echo '--- Cryptocurrency Datasets ---'
\ir crypto_dataset_populate.sql

-- =============================================================================
-- Cryptocurrency Dataset Tags
-- =============================================================================

\echo '--- Cryptocurrency Dataset Tags ---'
\ir crypto_dataset_tag_populate.sql

-- =============================================================================
-- Cryptocurrency Dataset Dependencies
-- =============================================================================

\echo '--- Cryptocurrency Dataset Dependencies ---'
\ir crypto_dataset_dependency_populate.sql

-- =============================================================================
-- Cryptocurrency Images
-- =============================================================================

\echo '--- Cryptocurrency Images ---'
\ir crypto_images_artefact_populate.sql

-- =============================================================================
-- Publish to the System Tenant
-- =============================================================================

-- The images stage into the DQ artefact table above and must publish before
-- any cryptocurrency publish reads them, on the same terms as the flag icons.
\echo '--- Publishing Cryptocurrency Icons ---'
select * from ores_assets_publish_images_from_dq_fn(
    (select id from ores_dq_datasets_tbl
      where code = 'assets.crypto_icons'
        and valid_to = ores_utility_infinity_timestamp_fn()),
    ores_utility_system_tenant_id_fn(),
    'upsert'
);

-- =============================================================================
-- Cryptocurrency Currencies
-- =============================================================================

\echo '--- Cryptocurrency Currencies ---'
\ir crypto_currencies_small_artefact_populate.sql
\ir crypto_currencies_large_artefact_populate.sql
