/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Cryptocurrency Reference Data Master Include File
 *
 * Auto-generated by crypto_generate_metadata_sql.py
 * Includes all cryptocurrency SQL files in the correct dependency order.
 */

-- =============================================================================
-- Cryptocurrency Catalog (must come first)
-- =============================================================================

\echo '--- Cryptocurrency Catalog ---'
\ir crypto_catalog_populate.sql

-- =============================================================================
-- Cryptocurrency Methodology
-- =============================================================================

\echo '--- Cryptocurrency Methodology ---'
\ir crypto_methodology_populate.sql

-- =============================================================================
-- Cryptocurrency Datasets
-- =============================================================================

\echo '--- Cryptocurrency Datasets ---'
\ir crypto_dataset_populate.sql

-- =============================================================================
-- Cryptocurrency Dataset Tags
-- =============================================================================

\echo '--- Cryptocurrency Dataset Tags ---'
\ir crypto_dataset_tag_populate.sql

-- =============================================================================
-- Cryptocurrency Images
-- =============================================================================

\echo '--- Cryptocurrency Images ---'
\ir crypto_images_artefact_populate.sql

-- =============================================================================
-- Cryptocurrency Currencies
-- =============================================================================

\echo '--- Cryptocurrency Currencies ---'
\ir crypto_currencies_small_artefact_populate.sql
\ir crypto_currencies_large_artefact_populate.sql
