/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

/**
 * Cryptocurrency Currencies Population Script (Small - Top 100 Coins)
 *
 * Populates the dq_currencies_artefact_tbl with cryptocurrency data.
 * Links cryptocurrencies to their icons from the cryptocurrency-icons dataset.
 *
 * Generated by crypto_generate_sql.py
 * Source: external/crypto/cryptocurrencies/cryptocurrencies.json
 */

set schema 'ores';

DO $$
declare
    v_dataset_id uuid;
    v_icons_dataset_id uuid;
    v_placeholder_image_id uuid;
    v_count integer := 0;
begin
    -- Get the cryptocurrencies dataset ID
    select id into v_dataset_id
    from ores.dq_datasets_tbl
    where name = 'Cryptocurrencies Small'
      and subject_area_name = 'Cryptocurrencies'
      and domain_name = 'Reference Data'
      and valid_to = ores.utility_infinity_timestamp_fn();

    if v_dataset_id is null then
        raise exception 'Dataset not found: Cryptocurrencies Small';
    end if;

    -- Get the cryptocurrency icons dataset ID (for linking images)
    select id into v_icons_dataset_id
    from ores.dq_datasets_tbl
    where name = 'Cryptocurrency Icon Images'
      and subject_area_name = 'Cryptocurrencies'
      and domain_name = 'Reference Data'
      and valid_to = ores.utility_infinity_timestamp_fn();

    if v_icons_dataset_id is null then
        raise exception 'Dataset not found: Cryptocurrency Icon Images';
    end if;

    -- Get a placeholder image (use 'xx' flag from the flags dataset)
    select image_id into v_placeholder_image_id
    from ores.dq_images_artefact_tbl
    where key = 'xx'
    limit 1;

    if v_placeholder_image_id is null then
        raise warning 'Placeholder image (xx) not found - cryptocurrencies without icons will have NULL image_id';
    end if;

    -- Clear existing cryptocurrencies for this dataset (idempotency)
    delete from ores.dq_currencies_artefact_tbl
    where dataset_id = v_dataset_id;

    raise notice 'Populating cryptocurrencies for dataset: Cryptocurrencies Small';

    -- Insert cryptocurrencies with icon links
    insert into ores.dq_currencies_artefact_tbl (
        dataset_id, iso_code, version, name, numeric_code, symbol, fraction_symbol,
        fractions_per_unit, rounding_type, rounding_precision, format, currency_type, image_id
    )
    select
        v_dataset_id,
        c.iso_code,
        0,
        c.name,
        c.numeric_code,
        c.symbol,
        c.fraction_symbol,
        c.fractions_per_unit,
        c.rounding_type,
        c.rounding_precision,
        c.format,
        c.currency_type,
        coalesce(i.image_id, v_placeholder_image_id)
    from (values
        ('BTC', 'Bitcoin', '', '₿', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('ETH', 'Ethereum', '', 'Ξ', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('USDT', 'Tether', '', 'USDT', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('XRP', 'XRP', '', '✕', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('BNB', 'Binance Coin', '', 'BNB', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('SOL', 'Solana', '', 'SOL', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('USDC', 'USD Coin', '', 'USDC', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('DOGE', 'Dogecoin', '', 'Ð', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('ADA', 'Cardano', '', 'ADA', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('TRX', 'TRON', '', 'TRX', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('LINK', 'Chainlink', '', 'LINK', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('XLM', 'Stellar', '', 'XLM', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('HBAR', 'Hedera Hashgraph', '', 'HBAR', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('SUI', 'Sui', '', 'SUI', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('HYPE', 'Hype', '', 'HYPE', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('BCH', 'Bitcoin Cash', '', 'BCH', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('XMR', 'Monero', '', 'XMR', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('ZEC', 'ZCash', '', 'ZEC', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('PAXG', 'PAX Gold', '', 'PAXG', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('AVAX', 'Avalanche', '', 'AVAX', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.major'),
        ('TON', 'Tokamak Network', '', 'TON', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('SHIB', 'Shiba Inu', '', 'SHIB', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('DOT', 'Polkadot', '', 'DOT', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('LTC', 'Litecoin', '', 'Ł', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('UNI', 'Uniswap Protocol Token', '', 'UNI', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('LEO', 'LEO Token', '', 'LEO', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('DAI', 'Dai', '', 'DAI', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('NEAR', 'Near', '', 'NEAR', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('APT', 'Aptos', '', 'APT', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('ICP', 'Internet Computer', '', 'ICP', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('RNDR', 'Render Token', '', 'RNDR', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('POL', 'Polygon Ecosystem Token', '', 'POL', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('ETC', 'Ethereum Classic', '', 'ETC', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('TAO', 'Bittensor', '', 'TAO', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('AAVE', 'Aave', '', 'AAVE', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('VET', 'VeChain', '', 'VET', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('FET', 'Fetch.AI', '', 'FET', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('MNT', 'Mantle', '', 'MNT', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('FIL', 'FileCoin', '', 'FIL', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('ARB', 'Arbitrum', '', 'ARB', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('ATOM', 'Cosmos', '', 'ATOM', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('OP', 'Optimism', '', 'OP', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('KAS', 'Kaspa', '', 'KAS', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('INJ', 'Injective', '', 'INJ', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('IMX', 'Immutable X', '', 'IMX', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('STX', 'Stacks', '', 'STX', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('THETA', 'Theta Network', '', 'THETA', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('RUNE', 'Thorchain', '', 'RUNE', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('GRT', 'The Graph', '', 'GRT', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('SEI', 'Sei', '', 'SEI', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('FTM', 'Fantom', '', 'FTM', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('SAND', 'The Sandbox', '', 'SAND', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('MANA', 'Decentraland', '', 'MANA', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('ALGO', 'Algorand', '', 'ALGO', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('AXS', 'Axie Infinity Shards', '', 'AXS', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('FLOW', 'Flow', '', 'FLOW', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('CFX', 'Conflux Network', '', 'CFX', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('GALA', 'Gala', '', 'GALA', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('NEO', 'NEO', '', 'NEO', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('KAVA', 'Kava', '', 'KAVA', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('XTZ', 'Tezos', '', 'XTZ', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('EGLD', 'eGold', '', 'EGLD', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('ROSE', 'Oasis Labs', '', 'ROSE', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('LUNC', 'Terra Classic', '', 'LUNC', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('MIOTA', 'IOTA', '', 'MIOTA', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('CRO', 'Cronos', '', 'CRO', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('QNT', 'Quant', '', 'QNT', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('FLOKI', 'Floki Inu', '', 'FLOKI', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('SNX', 'Synthetix', '', 'SNX', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('CAKE', 'PancakeSwap', '', 'CAKE', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('ORDI', 'Ordinals', '', 'ORDI', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('CHZ', 'Chiliz', '', 'CHZ', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('PEPE', 'Pepe', '', 'PEPE', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('WIF', 'dogwifhat', '', 'WIF', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('BONK', 'Bonk', '', 'BONK', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('ENS', 'Ethereum Name Service', '', 'ENS', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('TUSD', 'True USD', '', 'TUSD', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('OSMO', 'Osmosis', '', 'OSMO', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('XEC', 'eCash', '', 'XEC', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('MINA', 'Mina Protocol', '', 'MINA', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('DASH', 'Dash', '', 'DASH', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('APE', 'ApeCoin', '', 'APE', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('BLUR', 'Blur', '', 'BLUR', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('CRV', 'Curve DAO Token', '', 'CRV', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('LDO', 'Lido DAO', '', 'LDO', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('MKR', 'Maker', '', 'MKR', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('COMP', 'Compound Governance Token', '', 'COMP', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('ZIL', 'Zilliqa', '', 'ZIL', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('ENJ', 'Enjin Coin', '', 'ENJ', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('BAT', 'Basic Attention Token', '', 'BAT', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('NEXO', 'NEXO', '', 'NEXO', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('1INCH', '1inch', '', '1INCH', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('WOO', 'WOO Network', '', 'WOO', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('GMT', 'STEPN', '', 'GMT', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('DYDX', 'dYdX', '', 'DYDX', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('AR', 'Arweave', '', 'AR', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('ASTR', 'Astar', '', 'ASTR', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('CELO', 'Celo', '', 'CELO', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('AGIX', 'SingularityNET', '', 'AGIX', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor'),
        ('OCEAN', 'Ocean Protocol', '', 'OCEAN', '', 100000000, 'Closest', 8, '#,##0.00000000', 'crypto.minor')
    ) as c(iso_code, name, numeric_code, symbol, fraction_symbol, fractions_per_unit, rounding_type, rounding_precision, format, currency_type)
    left join ores.dq_images_artefact_tbl i
        on i.dataset_id = v_icons_dataset_id
        and i.key = lower(c.iso_code);

    get diagnostics v_count = row_count;
    raise notice 'Successfully populated % cryptocurrencies for dataset: Cryptocurrencies Small', v_count;

    -- Report count of cryptocurrencies with icons
    raise notice 'Cryptocurrencies with matching icons: %', (
        select count(*)
        from ores.dq_currencies_artefact_tbl
        where dataset_id = v_dataset_id
          and image_id is not null
    );
end $$;

\echo ''
\echo '--- Cryptocurrency Summary (Cryptocurrencies Small) ---'

select 'Total Cryptocurrencies' as metric, count(*) as count
from ores.dq_currencies_artefact_tbl c
join ores.dq_datasets_tbl d on c.dataset_id = d.id
where d.name = 'Cryptocurrencies Small'
union all
select 'Major (crypto.major)', count(*)
from ores.dq_currencies_artefact_tbl c
join ores.dq_datasets_tbl d on c.dataset_id = d.id
where d.name = 'Cryptocurrencies Small'
  and c.currency_type = 'crypto.major'
union all
select 'Minor (crypto.minor)', count(*)
from ores.dq_currencies_artefact_tbl c
join ores.dq_datasets_tbl d on c.dataset_id = d.id
where d.name = 'Cryptocurrencies Small'
  and c.currency_type = 'crypto.minor'
union all
select 'With Icons', count(*)
from ores.dq_currencies_artefact_tbl c
join ores.dq_datasets_tbl d on c.dataset_id = d.id
where d.name = 'Cryptocurrencies Small'
  and c.image_id is not null;
