/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Flag Icons Reference Data Master Include File
 *
 * Auto-generated by flags_generate_metadata_sql.py
 * Includes all flag icon SQL files in the correct dependency order.
 */

-- =============================================================================
-- Visual Assets Catalog (must come first)
-- =============================================================================

\echo '--- Visual Assets Catalog ---'
\ir flags_catalog_populate.sql

-- =============================================================================
-- Flag Icons Methodology
-- =============================================================================

\echo '--- Flag Icons Methodology ---'
\ir flags_methodology_populate.sql

-- =============================================================================
-- Flag Icons Datasets
-- =============================================================================

\echo '--- Flag Icons Datasets ---'
\ir flags_dataset_populate.sql

-- =============================================================================
-- Flag Icons Dataset Tags
-- =============================================================================

\echo '--- Flag Icons Dataset Tags ---'
\ir flags_dataset_tag_populate.sql

-- =============================================================================
-- Flag Icons Dataset Dependencies
-- =============================================================================

\echo '--- Flag Icons Dataset Dependencies ---'
\ir flags_dataset_dependency_populate.sql

-- =============================================================================
-- Flag Icon Images
-- =============================================================================

\echo '--- Flag Icon Images ---'
\ir flags_images_artefact_populate.sql

-- =============================================================================
-- Publish to the System Tenant
-- =============================================================================

-- The images stage into the DQ artefact table above and must publish before
-- the ISO countries publish reads them. Without this step every country
-- resolves no flag and the publish warns once per country.
\echo '--- Publishing Flag Icons ---'
select * from ores_assets_publish_images_from_dq_fn(
    (select id from ores_dq_datasets_tbl
      where code = 'assets.country_flags'
        and valid_to = ores_utility_infinity_timestamp_fn()),
    ores_utility_system_tenant_id_fn(),
    'upsert'
);
