' -*- mode: plantuml; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
'
' Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
'
' This program is free software; you can redistribute it and/or modify it under
' the terms of the GNU General Public License as published by the Free Software
' Foundation; either version 3 of the License, or (at your option) any later
' version.
'
' This program is distributed in the hope that it will be useful, but WITHOUT
' ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
' FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with
' this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
' Street, Fifth Floor, Boston, MA 02110-1301, USA.
'
@startuml

salt
{
  <b>PROTECT MY ACCOUNT</b>
  --
  {#
    Password         | Value
    Current password | hidden
    New password     | enter
    Confirm password | enter
    Strength         | Strong
  }
  --
  {#
    Sign-in state   | Value
    Last sign-in    | 2 hours ago
    Failed attempts | 0
    Account status  | Open
    Reset required  | No
  }
  --
  {#
    Where my account is signed in
    Client | Address | Country | Started | Status
    Desktop app | 192.168.1.20 | GB | 09:14 | Active
    Web browser | 203.0.113.7 | GB | 08:02 | Active
    Phone | 198.51.100.4 | FR | Yesterday | Active
  }
  --
  [ Change password ] | [ Sign out ] | [ Cancel ]
}

@enduml
