' -*- mode: plantuml; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
'
' Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
'
' This program is free software; you can redistribute it and/or modify it under
' the terms of the GNU General Public License as published by the Free Software
' Foundation; either version 3 of the License, or (at your option) any later
' version.
'
' This program is distributed in the hope that it will be useful, but WITHOUT
' ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
' FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with
' this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
' Street, Fifth Floor, Boston, MA 02110-1301, USA.
'
@startuml

salt
{
  <b>RESCUE ACCESS</b>
  --
  {#
    Account   | Value
    Username  | jdoe
    Full name | Jane Doe
    Type      | User
    Email     | jane.doe@example.com
  }
  --
  {#
    Security state  | Value
    Locked          | No
    Failed attempts | 0
    Last sign-in    | 2 hours ago
    Reset required  | No
  }
  --
  {#
    Reset the password
    New password     | enter
    Confirm password | enter
    Require change on next sign-in | Yes
  }
  --
  {#
    Administrator actions      | State
    Reset the password         | Available
    Lock the account           | Available
    Unlock the account         | Available
    Activate or deactivate     | Not available
    Send a recovery link       | Not available
  }
  --
  [ Reset password ] | [ Lock ] | [ Unlock ] | [ Cancel ]
}

@enduml
