' -*- mode: plantuml; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
'
' Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
'
' This program is free software; you can redistribute it and/or modify it under
' the terms of the GNU General Public License as published by the Free Software
' Foundation; either version 3 of the License, or (at your option) any later
' version.
'
' This program is distributed in the hope that it will be useful, but WITHOUT
' ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
' FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with
' this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
' Street, Fifth Floor, Boston, MA 02110-1301, USA.
'
@startuml

title ores.http.core Component

set namespaceSeparator ::

namespace ores #F2F2F2 {
    namespace http #F2F2F2 {
        namespace server #F2F2F2 {
            namespace routes #F2F2F2 {
                class storage_routes {
                    -store_ : storage::filesystem::local_store
                    -auth_service_ : shared_ptr<iam::service::authorization_service>
                    +storage_routes(string storage_dir, shared_ptr<iam::service::authorization_service> auth_service)
                    +register_routes(shared_ptr<http::net::router> router, shared_ptr<http::openapi::endpoint_registry> registry) : void
                    -lg() : auto&
                    -check_auth(const http::domain::http_request& req, string_view required_permission, string_view operation_name) : expected<auth_result, http::domain::http_response>
                    -handle_put(const http::domain::http_request& req) : boost::asio::awaitable<http::domain::http_response>
                    -handle_get(const http::domain::http_request& req) : boost::asio::awaitable<http::domain::http_response>
                    -handle_head(const http::domain::http_request& req) : boost::asio::awaitable<http::domain::http_response>
                    -handle_delete(const http::domain::http_request& req) : boost::asio::awaitable<http::domain::http_response>
                    -handle_list(const http::domain::http_request& req) : boost::asio::awaitable<http::domain::http_response>
                }
                class variability_routes {
                    -ctx_ : database::context
                    -system_settings_ : shared_ptr<variability::service::system_settings_service>
                    -sessions_ : shared_ptr<iam::service::auth_session_service>
                    +variability_routes(database::context ctx, shared_ptr<variability::service::system_settings_service> system_settings, shared_ptr<iam::service::auth_session_service> sessions)
                    +register_routes(shared_ptr<http::net::router> router, shared_ptr<http::openapi::endpoint_registry> registry) : void
                    -lg() : auto&
                    -handle_list_system_settings(const http::domain::http_request& req) : boost::asio::awaitable<http::domain::http_response>
                }
            }
        }
    }
}

' --- manual: everything below this line is hand-authored; the script preserves it ---

' Local Variables:
' compile-command: "java -Djava.awt.headless=true -DPLANTUML_SECURITY_PROFILE=UNSECURE -DPLANTUML_LIMIT_SIZE=65535 -jar /usr/share/plantuml/plantuml.jar ores.http.core.puml"
' End:
@enduml
