#!/usr/bin/env bash

# -*- mode: sh; tab-width: 4; indent-tabs-mode: nil -*-
#
# Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#

# Start the development stack this checkout needs and leave it running.
#
# The C++ services are started one per process because each presents its own
# NATS client certificate; `compass services start` installs systemd units
# outside the checkout, which needs privileges this workspace does not have.
#
# The BFF serves the built browser bundle itself, so `start` needs no separate
# web server. `dev` adds the Vite dev server for hot reload, which proxies the
# API to the BFF.
#
# Usage:
#   scripts/dev-stack.sh start     start NATS, the services and the BFF
#   scripts/dev-stack.sh dev       start the stack plus the Vite dev server
#   scripts/dev-stack.sh stop      stop everything this script started
#   scripts/dev-stack.sh status    report what is listening
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$WORKSPACE/../.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
RUN_DIR="$WORKSPACE/.runtime/pids"
LOG_DIR="$WORKSPACE/.runtime/logs"

env_value() {
  sed -n "s/^$1=//p" "$ENV_FILE" | head -1
}

LABEL="$(env_value ORES_ENV_NAME)"
if [[ -z "$LABEL" ]]; then
  echo "no ORES_ENV_NAME in $ENV_FILE" >&2
  exit 1
fi

NATS_PORT="$(env_value ORES_NATS_PORT)"
NATS_PORT="${NATS_PORT:-4222}"
NATS_MONITOR_PORT="$(env_value ORES_NATS_MONITOR_PORT)"
NATS_MONITOR_PORT="${NATS_MONITOR_PORT:-8222}"
WEB_PORT="$(env_value ORES_WEB_PORT)"
WEB_PORT="${WEB_PORT:-8080}"
WEB_DEV_PORT="$(env_value ORES_WEB_DEV_PORT)"
WEB_DEV_PORT="${WEB_DEV_PORT:-5173}"
DB_PORT="$(env_value ORES_IAM_SERVICE_DB_PORT)"
DB_PORT="${DB_PORT:-5432}"

# The checkout's own NATS configuration is generated by `compass nats init` and
# carries the per-environment port, store and certificates. A locally generated
# config is the fallback for a checkout that has none.
NATS_CONF="$REPO_ROOT/build/config/nats-$LABEL.conf"
if [[ ! -r "$NATS_CONF" ]]; then
  NATS_CONF="$WORKSPACE/.runtime/nats/nats.conf"
fi

mkdir -p "$RUN_DIR" "$LOG_DIR"

# Long-lived children get their own process group so a stop cannot leave a
# half-killed service holding a port.
start_one() {
  local name="$1"
  shift
  if [[ -f "$RUN_DIR/$name.pid" ]] && kill -0 "$(cat "$RUN_DIR/$name.pid")" 2>/dev/null; then
    echo "  $name already running"
    return
  fi
  setsid "$@" >"$LOG_DIR/$name.out" 2>&1 &
  echo $! >"$RUN_DIR/$name.pid"
  echo "  $name started (pid $!)"
}

stop_one() {
  local name="$1"
  local pid_file="$RUN_DIR/$name.pid"
  if [[ ! -f "$pid_file" ]]; then
    return
  fi
  local pid
  pid="$(cat "$pid_file")"
  if kill -0 "$pid" 2>/dev/null; then
    # Negative pid targets the whole process group.
    kill -- "-$pid" 2>/dev/null || kill "$pid" 2>/dev/null || true
    echo "  $name stopped"
  fi
  rm -f "$pid_file"
}

wait_for_port() {
  local port="$1"
  local label="$2"
  for _ in $(seq 1 60); do
    if (exec 3<>"/dev/tcp/127.0.0.1/$port") 2>/dev/null; then
      exec 3<&- 3>&- || true
      echo "  $label is up on $port"
      return 0
    fi
    sleep 0.5
  done
  echo "  $label did not come up on $port" >&2
  return 1
}

# NATS, the two services the browser session needs, and the BFF.
start_stack() {
  if [[ ! -r "$NATS_CONF" ]]; then
    echo "no NATS configuration at $NATS_CONF; run 'compass nats init'" >&2
    exit 1
  fi

  echo "starting the stack"
  start_one nats nats-server -c "$NATS_CONF"
  wait_for_port "$NATS_PORT" nats

  start_one iam bash "$SCRIPT_DIR/run-service.sh" iam \
    --tenant ffffffff-ffff-ffff-ffff-ffffffffffff
  # The IAM service loads party summaries from refdata over the bus, and a
  # login that arrives first gets empty party names, so start refdata too.
  start_one refdata bash "$SCRIPT_DIR/run-service.sh" refdata
  wait_for_port "$DB_PORT" postgres

  # The BFF resolves its site configuration from the working directory, so it
  # starts in the package root rather than wherever this script was called from.
  start_one bff env -C "$WORKSPACE" npx tsx --env-file="$ENV_FILE" \
    packages/bff/src/main.ts
  wait_for_port "$WEB_PORT" bff
}

case "${1:-start}" in
  start)
    start_stack

    echo
    echo "open http://127.0.0.1:$WEB_PORT/"
    echo "logs in $LOG_DIR"
    ;;

  dev)
    start_stack

    # The dev server proxies /api to the BFF, so it needs the BFF's port as well
    # as its own; both come from the environment file.
    start_one web env -C "$WORKSPACE" \
      ORES_WEB_PORT="$WEB_PORT" ORES_WEB_DEV_PORT="$WEB_DEV_PORT" \
      npx vite --host 127.0.0.1 --port "$WEB_DEV_PORT" packages/web
    wait_for_port "$WEB_DEV_PORT" vite

    echo
    echo "open http://127.0.0.1:$WEB_DEV_PORT/ for hot reload"
    echo "the BFF serves the built bundle on http://127.0.0.1:$WEB_PORT/"
    echo "logs in $LOG_DIR"
    ;;

  stop)
    echo "stopping the stack"
    for name in web bff refdata iam nats; do
      stop_one "$name"
    done
    ;;

  status)
    echo "listening:"
    ss -ltn 2>/dev/null \
      | grep -E ":($NATS_PORT|$NATS_MONITOR_PORT|$WEB_PORT|$WEB_DEV_PORT|$DB_PORT)\b" \
      || echo "  nothing from this stack"
    ;;

  *)
    echo "usage: dev-stack.sh {start|dev|stop|status}" >&2
    exit 2
    ;;
esac
