# -*- mode: cmake; cmake-tab-width: 4; indent-tabs-mode: nil -*-
#
# Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# Template: cmake_component_files_src.mustache
# To modify, update the template and regenerate.
set(files
    "app/commands/refdata/asset_class_code_commands.cpp"
    "app/commands/refdata/book_commands.cpp"
    "app/commands/refdata/book_purpose_type_commands.cpp"
    "app/commands/refdata/book_status_commands.cpp"
    "app/commands/refdata/business_centre_commands.cpp"
    "app/commands/refdata/business_day_convention_type_commands.cpp"
    "app/commands/refdata/business_unit_commands.cpp"
    "app/commands/refdata/business_unit_type_commands.cpp"
    "app/commands/refdata/calendar_commands.cpp"
    "app/commands/refdata/calendar_date_commands.cpp"
    "app/commands/refdata/calendar_event_commands.cpp"
    "app/commands/refdata/calendar_exception_commands.cpp"
    "app/commands/refdata/calendar_rule_commands.cpp"
    "app/commands/refdata/calendar_type_commands.cpp"
    "app/commands/refdata/cds_convention_commands.cpp"
    "app/commands/refdata/contact_type_commands.cpp"
    "app/commands/refdata/counterparty_commands.cpp"
    "app/commands/refdata/counterparty_contact_information_commands.cpp"
    "app/commands/refdata/counterparty_identifier_commands.cpp"
    "app/commands/refdata/country_commands.cpp"
    "app/commands/refdata/crm_driver_pair_commands.cpp"
    "app/commands/refdata/crm_enabled_derived_pair_commands.cpp"
    "app/commands/refdata/crm_topology_config_commands.cpp"
    "app/commands/refdata/currency_calendar_commands.cpp"
    "app/commands/refdata/currency_commands.cpp"
    "app/commands/refdata/currency_country_commands.cpp"
    "app/commands/refdata/currency_currency_group_commands.cpp"
    "app/commands/refdata/currency_group_commands.cpp"
    "app/commands/refdata/currency_market_tier_commands.cpp"
    "app/commands/refdata/currency_pair_classification_commands.cpp"
    "app/commands/refdata/currency_pair_commands.cpp"
    "app/commands/refdata/currency_pair_convention_calendar_commands.cpp"
    "app/commands/refdata/currency_pair_convention_commands.cpp"
    "app/commands/refdata/curve_role_commands.cpp"
    "app/commands/refdata/day_count_fraction_type_commands.cpp"
    "app/commands/refdata/deposit_convention_commands.cpp"
    "app/commands/refdata/derivation_kind_commands.cpp"
    "app/commands/refdata/diary_entry_type_commands.cpp"
    "app/commands/refdata/floating_index_type_commands.cpp"
    "app/commands/refdata/fra_convention_commands.cpp"
    "app/commands/refdata/ibor_index_convention_commands.cpp"
    "app/commands/refdata/instrument_code_commands.cpp"
    "app/commands/refdata/ledger_feed_type_commands.cpp"
    "app/commands/refdata/leg_type_commands.cpp"
    "app/commands/refdata/monetary_nature_commands.cpp"
    "app/commands/refdata/ois_convention_commands.cpp"
    "app/commands/refdata/overnight_index_convention_commands.cpp"
    "app/commands/refdata/party_commands.cpp"
    "app/commands/refdata/party_contact_information_commands.cpp"
    "app/commands/refdata/party_counterparty_commands.cpp"
    "app/commands/refdata/party_country_commands.cpp"
    "app/commands/refdata/party_currency_commands.cpp"
    "app/commands/refdata/party_id_scheme_commands.cpp"
    "app/commands/refdata/party_identifier_commands.cpp"
    "app/commands/refdata/party_status_commands.cpp"
    "app/commands/refdata/party_type_commands.cpp"
    "app/commands/refdata/payment_frequency_commands.cpp"
    "app/commands/refdata/portfolio_commands.cpp"
    "app/commands/refdata/purpose_type_commands.cpp"
    "app/commands/refdata/regulatory_book_type_commands.cpp"
    "app/commands/refdata/rounding_type_commands.cpp"
    "app/commands/refdata/series_subclass_code_commands.cpp"
    "app/commands/refdata/swap_convention_commands.cpp"
    "app/commands/refdata/tenor_anchor_commands.cpp"
    "app/commands/refdata/tenor_commands.cpp"
    "app/commands/refdata/tenor_convention_commands.cpp"
    "app/commands/refdata/tenor_convention_resolution_commands.cpp"
    "app/commands/refdata/tenor_kind_commands.cpp"
    "app/commands/refdata/tenor_resolution_algorithm_commands.cpp"
    "app/commands/refdata/tenor_schedule_commands.cpp"
    "app/commands/refdata/tenor_unit_commands.cpp"
    "app/commands/refdata/zero_convention_commands.cpp"
)

# The headers are listed for the install and IDE targets.
set(HEADERS
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/asset_class_code_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/book_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/book_purpose_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/book_status_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/business_centre_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/business_day_convention_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/business_unit_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/business_unit_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/calendar_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/calendar_date_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/calendar_event_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/calendar_exception_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/calendar_rule_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/calendar_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/cds_convention_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/contact_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/counterparty_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/counterparty_contact_information_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/counterparty_identifier_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/country_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/crm_driver_pair_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/crm_enabled_derived_pair_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/crm_topology_config_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/currency_calendar_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/currency_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/currency_country_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/currency_currency_group_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/currency_group_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/currency_market_tier_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/currency_pair_classification_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/currency_pair_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/currency_pair_convention_calendar_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/currency_pair_convention_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/curve_role_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/day_count_fraction_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/deposit_convention_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/derivation_kind_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/diary_entry_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/floating_index_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/fra_convention_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/ibor_index_convention_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/instrument_code_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/ledger_feed_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/leg_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/monetary_nature_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/ois_convention_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/overnight_index_convention_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/party_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/party_contact_information_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/party_counterparty_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/party_country_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/party_currency_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/party_id_scheme_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/party_identifier_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/party_status_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/party_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/payment_frequency_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/portfolio_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/purpose_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/regulatory_book_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/rounding_type_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/series_subclass_code_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/swap_convention_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/tenor_anchor_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/tenor_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/tenor_convention_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/tenor_convention_resolution_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/tenor_kind_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/tenor_resolution_algorithm_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/tenor_schedule_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/tenor_unit_commands.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.shell/app/commands/refdata/zero_convention_commands.hpp"
)
