# -*- mode: cmake; cmake-tab-width: 4; indent-tabs-mode: nil -*-
#
# Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#

# The schema fingerprint: a hash of the SQL that compass db recreate reads.
#
# The inputs are every .sql file under create/, populate/ and instance/, and the
# .sql files at the top of projects/ores.sql. Each contributes the line
# "<path relative to projects/ores.sql> <sha256 of its bytes>"; the lines are
# sorted by path and joined with newlines, each line ending in one, and the
# fingerprint is the first sixteen hex digits of the sha256 of the result.
#
# compass_db.schema_fingerprint in projects/ores.compass computes the same
# value when it stamps a recreated database, and a compass test checks the two
# agree. Change both together.
#
# Script mode. Pass -DSQL_DIR=<projects/ores.sql> and either -DOUTPUT=<header>
# to write the header the database library compiles in, or -DPRINT=ON to print
# the fingerprint.

function(ores_schema_fingerprint_inputs sql_dir out_var)
    file(GLOB_RECURSE nested RELATIVE "${sql_dir}"
        "${sql_dir}/create/*.sql"
        "${sql_dir}/populate/*.sql"
        "${sql_dir}/instance/*.sql")
    file(GLOB top RELATIVE "${sql_dir}" "${sql_dir}/*.sql")
    set(inputs ${nested} ${top})
    list(SORT inputs)
    set(${out_var} ${inputs} PARENT_SCOPE)
endfunction()

function(ores_schema_fingerprint sql_dir out_var)
    ores_schema_fingerprint_inputs("${sql_dir}" inputs)
    set(lines "")
    foreach(relative IN LISTS inputs)
        file(SHA256 "${sql_dir}/${relative}" digest)
        string(APPEND lines "${relative} ${digest}\n")
    endforeach()
    string(SHA256 whole "${lines}")
    string(SUBSTRING "${whole}" 0 16 fingerprint)
    set(${out_var} ${fingerprint} PARENT_SCOPE)
endfunction()

if(CMAKE_SCRIPT_MODE_FILE AND DEFINED SQL_DIR)
    ores_schema_fingerprint("${SQL_DIR}" fingerprint)
    if(PRINT)
        message("${fingerprint}")
    endif()
    if(DEFINED OUTPUT)
        file(CONFIGURE OUTPUT "${OUTPUT}" CONTENT
"// Generated by projects/ores.sql/schema_fingerprint.cmake. Do not edit.
#ifndef ORES_DATABASE_SCHEMA_FINGERPRINT_HPP
#define ORES_DATABASE_SCHEMA_FINGERPRINT_HPP

#define ORES_SCHEMA_FINGERPRINT \"${fingerprint}\"

#endif
" @ONLY)
    endif()
endif()
