/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*- */
/*
* GENERATED FILE - Instance Database Teardown
*
* This file was generated by admin/admin_teardown_instances_generate.sql
* Review carefully before running teardown_all.sql
*
* For each instance database, this script:
* 1. Connects to the database
* 2. Runs drop/drop.sql to drop all schema objects
* 3. Connects back to postgres
* 4. Drops the database
*
* To regenerate:
* psql -U postgres -f admin/admin_teardown_instances_generate.sql
*/

-- Instance: ores_frosty_leaf
\echo 'Dropping schema objects in ores_frosty_leaf...'
\c ores_frosty_leaf
\ir drop/drop.sql
\c postgres
drop database if exists ores_frosty_leaf;

