/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*- */
/*
* GENERATED FILE - Instance Database Teardown
*
* This file was generated by admin/admin_teardown_instances_generate.sql
* Review carefully before running teardown_all.sql
*
* For each instance database, this script calls drop/drop_database.sql
* which handles the full teardown sequence (schema drops + database drop).
*
* To regenerate:
* psql -U postgres -f admin/admin_teardown_instances_generate.sql
*/

-- Instance: ores_dev_local2
\set db_name ores_dev_local2
\ir drop/drop_database.sql

-- Instance: ores_frosty_leaf
\set db_name ores_frosty_leaf
\ir drop/drop_database.sql

