/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

/**
 * Calendar Names Population Script
 *
 * Populates the calendar names ORE accepts: the literal names of the calendar
 * pattern in external/ore/xsd/ore_types.xsd, without the two open forms the
 * pattern also allows (a four-letter exchange code and a CUSTOM_ name), which
 * ores_refdata_validate_calendar_fn checks by form.
 *
 * This script is idempotent - uses INSERT ON CONFLICT.
 */

\echo '--- Calendar Names ---'

insert into ores_refdata_calendar_names_tbl (
    tenant_id, code, description, version,
    modified_by, performed_by, change_reason_code, change_commentary
)
values
    (ores_utility_system_tenant_id_fn(), 'TGT', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TARGET', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CN-IB', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'US-FED', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'US-GOV', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'US-NERC', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'US-NYSE', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'US-SET', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'US-SOFR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Australia', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Australia settlement', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Botswana', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Brazil', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Canada', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Denmark', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Hungary', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Japan', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Norway', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Switzerland', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Sweden', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Belgium', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Finland', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Luxembourg', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Spain', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Austria', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Romania', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Poland', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'New Zealand', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Cyprus', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Greece', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Ireland', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'FRA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CATO', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CHZU', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'JPTO', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GBLO', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SEST', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TRIS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'USNY', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'EUTA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BEBR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'AE', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'AT', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'AR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'AU', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BW', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CO', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CY', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CZ', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'DK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'FI', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'FR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'DE', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'HK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'HU', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'IE', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'IS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'IN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ID', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'IL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'IT', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'JE', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'JP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MX', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MY', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'NL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'NO', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'NZ', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'PE', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'PH', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'PL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'RO', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'RU', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SG', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ZA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'KR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SE', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CH', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TW', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TH', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'UA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GB', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'US', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BE', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'LU', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ES', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'AED', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'AFN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ALL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'AMD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ANG', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'AOA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ARS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'AUD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'AWG', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'AZN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BAM', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BBD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BDT', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BGN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BHD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BIF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BMD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BND', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BOB', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BOV', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BRL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BSD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BTN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BWP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BYN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BZD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CAD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CDF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CHE', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CHF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CHW', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CLF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CLP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CNH', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CNT', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CNY', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'COP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'COU', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CRC', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CUC', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CUP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CVE', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CYP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CZK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'DJF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'DKK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'DOP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'DZD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'EGP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ERN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ETB', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'EUR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'FJD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'FKP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GBP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GEL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GGP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GHS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GIP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GMD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GNF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GTQ', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GYD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'HKD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'HNL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'HRK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'HTG', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'HUF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'IDR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ILS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'IMP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'INR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'IQD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'IRR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ISK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'JEP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'JMD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'JOD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'JPY', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'KES', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'KGS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'KHR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'KID', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'KMF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'KPW', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'KRW', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'KWD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'KYD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'KZT', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'LAK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'LBP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'LKR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'LRD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'LSL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'LTL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'LVL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'LYD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MAD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MDL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MGA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MKD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MMK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MNT', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MOP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MRU', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MUR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MUS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MU', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MVR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MWK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MXN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MXV', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MYR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MZN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'NAD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'NGN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'NIO', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'NOK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'NPR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'NZD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'OMR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'PAB', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'PEN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'PGK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'PHP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'PKR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'PLN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'PYG', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'QAR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'RON', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'RSD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'RUB', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'RWF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SAR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SBD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SCR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SDG', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SEK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SGD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SHP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SLL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SKK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SOS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SRD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SSP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'STN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SVC', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SYP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SZL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'THB', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TJS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TMT', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TND', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TOP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TRY', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TTD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TWD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TZS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'UAH', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'UGX', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'USD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'USN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'UYI', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'UYU', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'UYW', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'UZS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'VES', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'VND', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'VUV', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'WST', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XAF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XAG', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XAU', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XCD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XOF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XPD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XPF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XPT', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XSU', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XUA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'YER', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ZAR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ZMW', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ZWL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XBT', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BTC', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ETH', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ETC', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BCH', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XRP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'LTC', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ZUR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ZUG', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GBp', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GBX', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ILa', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ILA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ILX', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ILs', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'KWf', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ZAc', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ZAC', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ZAX', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'USc', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ARE', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ARG', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'AUS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BWA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BRA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CAN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CHL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CHN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'COL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CZE', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'DNK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'FIN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GRC', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'DEU', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'HKG', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'HUN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ISL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'IND', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'IDN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ISR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ITA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'JPN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MEX', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MYS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'NLD', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'NOR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'NZL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'PER', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'PHL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'POL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ROU', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'RUS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SAU', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SGP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ZAF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'KOR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SWE', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TWN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'THA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TUR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'UKR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'GBR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'USA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BEL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'LUX', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ESP', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'AUT', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'FRF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'IRL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ITL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BEF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'LUF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ATS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XASX', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BVMF', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XTSE', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XSHG', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XFRA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XDUB', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XPAR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XETR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ECAG', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'EUWA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XJKT', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XIDX', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XTAE', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XMIL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'MISX', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XKRX', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XSWX', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XLON', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XLME', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'XNYS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'DEN', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TSX', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Australia exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'BOVESPA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Euwax', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CME Group', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Eurex', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Xetra', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Frankfurt stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'French settlement', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'German settlement', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Paris stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Telbor', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'National Stock Exchange of India', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'London stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'LNB', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'London metals exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Iceland stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'New York stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Italian settlement', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Santiago Stock Exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Ukrainian stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'NGL', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'NYB', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SA', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SYB', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TKB', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'TRB', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'UK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'UK settlement', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Jakarta stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'US settlement', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Belgian settlement', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'US with Libor impact', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'US government bond market', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'North American Energy Reliability Council', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Federal Reserve Bankwire System', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SOFR fixing calendar', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'WMR', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ZUB', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE_FuturesUS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE_FuturesUS_1', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE_FuturesUS_2', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE_FuturesEU', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE_FuturesEU_1', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE_EndexEnergy', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE_EndexEquities', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE_SwapTradeUS', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE Futures U.S.', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE Futures U.S. 1', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE Futures U.S. 2', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE Futures Europe', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE Futures Europe 1', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE Endex Energy', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE Endex Equities', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE Swap Trade U.S.', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE Swap Trade U.K.', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE Futures Singapore', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE_SwapTradeUK', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'ICE_FuturesSingapore', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'CME', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Thailand stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Turkey', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Milan stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Taiwan stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'South-Korean settlement', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'South-Korea exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'South Africa', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Bratislava stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Moscow exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Mexican stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Russian settlement', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Spanish settlement', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Luxembourgish settlement', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Dutch settlement', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Austrian settlement', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Tadawul', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Tel Aviv stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Bucharest stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Singapore exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Hong Kong stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Vienna stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Prague stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'China inter bank market', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Shanghai stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Colombia Stock Exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Buenos Aires stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Philippine stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Lima stock exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'SIX Swiss Exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Malaysia Stock Exchange', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Thomson Reuters WM/Reuters Spot', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Israel Telbor Implementation', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'WeekendsOnly', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'weekends only', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'IslamicWeekendsOnly', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'islamic weekends only', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Islamic weekends only', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'UNMAPPED', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'Null', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names'),
    (ores_utility_system_tenant_id_fn(), 'NullCalendar', null, 0,
     current_user, current_user, 'system.initial_load', 'Initial population of calendar names')
on conflict (tenant_id, code)
where valid_to = ores_utility_infinity_timestamp_fn()
do nothing;

-- Summary
select 'refdata_calendar_names' as entity, count(*) as count
from ores_refdata_calendar_names_tbl
where tenant_id = ores_utility_system_tenant_id_fn()
  and valid_to = ores_utility_infinity_timestamp_fn();
