/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

/**
 * Instrument Codes Population Script
 *
 * Populates the full product/trade-type catalogue -- one row per
 * oreTradeType enumeration value in external/ore/xsd/instruments.xsd
 * (the authoritative source of truth), plus one ORE Studio-specific
 * addition: 'DEPO' (ORE has no distinct money-market-deposit trade
 * type -- a deposit is mathematically a single-period Swap, and ORE
 * doesn't model it separately -- 'DEPO' is added here purely so the
 * IR Curve Template can label a short-end entry accordingly; its
 * pricing still derives from the same discount_factor()-based
 * par-rate formula as a single-period Swap would).
 *
 * 'code' is deliberately NOT ORE's own oreTradeType spelling -- it is
 * a short, FIX-inspired mnemonic (e.g. 'FRA', 'IRS', 'CDS', 'FXBAR')
 * chosen so a trader can type it quickly. The literal oreTradeType
 * string, where one exists, is preserved in 'ore_trade_type' (null
 * only for 'DEPO') for future ORE trade-file interop.
 *
 * This script is idempotent - uses INSERT ON CONFLICT.
 */

\echo '--- Instrument Codes ---'

insert into ores_refdata_instrument_codes_tbl (
    tenant_id, code, version, name, description, asset_class, ore_trade_type, curve_role, display_order,
    modified_by, performed_by, change_reason_code, change_commentary
)
values
    (ores_utility_system_tenant_id_fn(), 'COMPOSITE', 0, 'Composite Trade',
     'CompositeTrade: a wrapper trade type that bundles two or more other ORE trades (of any type or asset class) into a single logical position for pricing, netting, and reporting purposes -- for example a swap and its associated cap hedge -- without requiring a bespoke combined pricing engine for every possible pairing.',
     'cross_asset', 'CompositeTrade', 'NONE', 1, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'ASCOT', 0, 'Ascot',
     'Ascot (Asset Swapped Convertible Option Transaction): a package that strips a convertible bond''s embedded equity option away from its fixed-income component, letting the credit/rates leg and the equity-option leg be held, hedged, or traded separately rather than only as a single convertible bond position.',
     'cross_asset', 'Ascot', 'NONE', 2, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'TRS', 0, 'Total Return Swap',
     'TotalReturnSwap: a swap in which one party pays the total return (price appreciation plus any income, such as dividends or coupons) of a reference asset, and receives a financing leg (typically a floating rate plus a spread) in return, without ever taking legal ownership of the reference asset itself.',
     'cross_asset', 'TotalReturnSwap', 'NONE', 3, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CFD', 0, 'Contract For Difference',
     'ContractForDifference (CFD): a cash-settled agreement to exchange the difference between the current price of an underlying and its price at contract close, giving synthetic long or short exposure without taking delivery or legal ownership of the underlying -- economically similar to a Total Return Swap but typically a simpler, uncollateralized retail-style structure.',
     'cross_asset', 'ContractForDifference', 'NONE', 4, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CBO', 0, 'Collateralized Bond Obligation',
     'CBO (Collateralized Bond Obligation): a structured credit security backed by a diversified pool of bonds, tranched into multiple classes of notes with differing seniority and loss-absorption priority -- the bond-collateral counterpart to a Synthetic CDO''s derivative-referenced credit pool.',
     'cross_asset', 'CBO', 'NONE', 5, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'MLOPT', 0, 'Multi-Leg Option',
     'MultiLegOption: a generic ORE trade type for option structures composed of several individual option legs (e.g. spreads, straddles, strangles, collars) priced and risk-managed as a single combined position, rather than requiring a bespoke trade type for every possible leg combination.',
     'cross_asset', 'MultiLegOption', 'NONE', 6, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FAILED', 0, 'Failed',
     'Failed: an internal ORE trade type used to represent a trade that failed to build or price (e.g. due to invalid input data or an unsupported configuration), letting the failure surface as an ordinary row in the trade population for reporting rather than aborting the entire portfolio load.',
     'cross_asset', 'Failed', 'NONE', 7, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'SCRIPT', 0, 'Scripted Trade',
     'ScriptedTrade: ORE''s generic payoff-scripting trade type, letting an arbitrary structured payoff be defined via a small domain-specific scripting language and priced by ORE''s script engine, rather than requiring a bespoke, hand-coded pricing engine for every new exotic payoff structure.',
     'cross_asset', 'ScriptedTrade', 'NONE', 8, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'RPA', 0, 'Risk Participation Agreement',
     'RiskParticipationAgreement: an agreement under which one party (the participant) assumes a share of the credit or other risk of an underlying trade or loan held by another party (the originator), in exchange for a participation fee, without formally assigning or novating the underlying contract itself.',
     'cross_asset', 'RiskParticipationAgreement', 'NONE', 9, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'AUTOCALL', 0, 'Autocallable',
     'Autocallable_01: ORE''s reference implementation of a common autocallable note structure -- a structured note that redeems early (is ''called'') with a coupon if the underlying is at or above a barrier on a scheduled observation date, and otherwise continues to the next observation, with principal at risk at final maturity if the underlying has fallen below a downside barrier.',
     'cross_asset', 'Autocallable_01', 'NONE', 10, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'DBLDIG', 0, 'Double Digital Option',
     'DoubleDigitalOption: a binary option whose fixed payout is conditional on two separate digital (in-or-out) conditions both being satisfied simultaneously -- for example a joint condition on two different underlyings, or two separate strike levels on the same underlying -- rather than a single digital condition as in a plain Digital Option.',
     'cross_asset', 'DoubleDigitalOption', 'NONE', 11, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EUROBAR', 0, 'European Barrier Option (Generic)',
     'EuropeanOptionBarrier: a barrier-option variant in which the barrier condition, like the option''s exercise itself, is evaluated only at expiry (European-style monitoring) rather than continuously through the option''s life -- ORE''s more general counterpart to the asset-class-specific European Barrier Option trade types (e.g. FxEuropeanBarrierOption).',
     'cross_asset', 'EuropeanOptionBarrier', 'NONE', 12, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'PERFOPT', 0, 'Performance Option',
     'PerformanceOption_01: ORE''s reference implementation of a performance-linked structured option, whose payoff is driven by the underlying''s realized performance (return) over the option''s life relative to one or more reference levels, rather than its absolute terminal price alone.',
     'cross_asset', 'PerformanceOption_01', 'NONE', 13, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CASHPOS', 0, 'Cash Position',
     'CashPosition: a simple holding of cash (or a cash-equivalent balance) in a given currency, recorded as a position for valuation, collateral, and reporting purposes rather than as a traded derivative contract.',
     'cross_asset', 'CashPosition', 'NONE', 14, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'XCCY', 0, 'Cross-Currency Swap',
     'CrossCurrencySwap: a swap exchanging principal and periodic interest payments denominated in two different currencies, typically used to convert funding raised in one currency into exposure in another while managing the associated FX and cross-currency basis risk; a core building block for multi-currency discounting curves.',
     'rates', 'CrossCurrencySwap', 'NONE', 15, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'IRS', 0, 'Interest Rate Swap',
     'Swap: the generic ORE trade type for a vanilla interest rate swap exchanging a fixed-rate leg against a floating-rate leg (or, more generally, two legs of any supported leg type) referencing a single currency''s yield curve. The most fundamental instrument for both hedging interest-rate exposure and bootstrapping the discounting/forward curve itself.',
     'rates', 'Swap', 'SWAP', 16, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'SWPTN', 0, 'Swaption',
     'Swaption: an option granting the right, but not the obligation, to enter into an underlying interest rate Swap at a pre-agreed fixed rate on a future exercise date -- priced using a rates volatility model (e.g. a SABR or Black volatility surface quoted by expiry and swap tenor) layered on top of the underlying swap''s forward rate.',
     'rates', 'Swaption', 'NONE', 17, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FRA', 0, 'Forward Rate Agreement',
     'ForwardRateAgreement (FRA): a forward contract to exchange a fixed interest rate against a floating reference rate (e.g. SOFR, ESTR) over a single future period, cash-settled at the start of that period. The simplest building block for the mid-curve segment of a yield curve, sitting between short-end deposits and longer swap-implied rates.',
     'rates', 'ForwardRateAgreement', 'FRA', 18, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CAPFLR', 0, 'Cap/Floor',
     'CapFloor: a strip of interest rate caplets (or floorlets), each an option on a single floating-rate reset paying off if the rate is above (cap) or below (floor) a strike, combined into a single instrument covering a schedule of periods -- used to hedge a floating-rate exposure against rates rising (cap) or falling (floor) beyond a threshold.',
     'rates', 'CapFloor', 'NONE', 19, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FLEXSWP', 0, 'Flexi Swap',
     'FlexiSwap: an interest rate swap that allows the notional profile (or, in some variants, the exercise of embedded optionality) to be adjusted according to a pre-agreed schedule or embedded flexibility, rather than following the fixed, fully-specified amortization of a plain vanilla Swap.',
     'rates', 'FlexiSwap', 'NONE', 20, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'BGS', 0, 'Balance Guaranteed Swap',
     'BalanceGuaranteedSwap: an amortizing interest rate swap whose notional schedule tracks the outstanding balance of an underlying pool of amortizing assets (e.g. a mortgage pool) subject to uncertain prepayment, rather than a pre-agreed deterministic amortization schedule as in a standard Swap.',
     'rates', 'BalanceGuaranteedSwap', 'NONE', 21, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CALLSWP', 0, 'Callable Swap',
     'CallableSwap: an interest rate swap in which one party holds the right to terminate (call) the swap early on one or more pre-specified dates -- priced as a vanilla Swap with an embedded cancellation option, closely related to a Swaption struck at the swap''s own fixed rate.',
     'rates', 'CallableSwap', 'NONE', 22, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'KOSWP', 0, 'Knock-Out Swap',
     'KnockOutSwap: an interest rate swap that terminates early (is ''knocked out'') if a specified reference rate or index crosses a barrier level, combining the periodic cashflow exchange of a vanilla Swap with the early-termination mechanics of a barrier option.',
     'rates', 'KnockOutSwap', 'NONE', 23, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'DEPO', 0, 'Deposit',
     'Deposit: an ORE Studio-specific addition (not a native ORE oreTradeType) representing a short-dated money-market deposit paying a simple interest rate over a single period. ORE itself models a deposit as a degenerate single-period Swap; Deposit is added here purely to give the IR Curve Template a distinct, recognizable label for its short end, with pricing still derived from the same discount_factor()-based par-rate formula a single-period Swap would use.',
     'rates', null, 'DEPOSIT', 24, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CDX', 0, 'Index Credit Default Swap',
     'IndexCreditDefaultSwap: a CDS written on a standardized index of reference entities (e.g. CDX or iTraxx) rather than a single name, paying protection on a pro-rata basis across the index constituents and typically more liquid than the equivalent basket of single-name CDS.',
     'credit', 'IndexCreditDefaultSwap', 'NONE', 25, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CDXOPT', 0, 'Index Credit Default Swap Option',
     'IndexCreditDefaultSwapOption: an option to enter into an Index Credit Default Swap at a pre-agreed spread on a future exercise date, used to take a view on the future level of index credit spreads (or index volatility) without committing to the underlying index CDS position today.',
     'credit', 'IndexCreditDefaultSwapOption', 'NONE', 26, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CDO', 0, 'Synthetic Collateralized Debt Obligation',
     'SyntheticCDO (Synthetic Collateralized Debt Obligation): a structured credit security whose reference pool is a portfolio of CDS (rather than physical bonds, as in a CBO), tranched into classes with differing subordination -- each tranche absorbing losses from the reference pool''s defaults in a fixed order of priority.',
     'credit', 'SyntheticCDO', 'NONE', 27, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CLS', 0, 'Credit Linked Swap',
     'CreditLinkedSwap: a swap whose cashflows (and possibly notional) are contingent on the credit performance of one or more reference entities, combining swap-style periodic exchange of cashflows with the loss-triggering mechanics of a credit default swap.',
     'credit', 'CreditLinkedSwap', 'NONE', 28, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CDS', 0, 'Credit Default Swap',
     'CreditDefaultSwap (CDS): the fundamental single-name credit derivative, under which the protection buyer pays a periodic spread to the protection seller in exchange for a contingent payment if the reference entity experiences a defined credit event (default, restructuring). The primary instrument used to bootstrap hazard-rate/survival-probability curves.',
     'credit', 'CreditDefaultSwap', 'NONE', 29, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CDSOPT', 0, 'Credit Default Swap Option',
     'CreditDefaultSwapOption: an option to enter into an underlying single-name Credit Default Swap at a pre-agreed spread on a future exercise date, used to take a view on the future level of that name''s credit spread (or its volatility) without committing to the CDS position today.',
     'credit', 'CreditDefaultSwapOption', 'NONE', 30, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'INFSWP', 0, 'Inflation Swap',
     'InflationSwap: a swap exchanging a fixed (or floating nominal) leg against a leg indexed to a published inflation index (e.g. CPI, RPI, HICP), in either zero-coupon (single payment at maturity) or year-on-year (periodic) form, used to hedge or take a view on future realized inflation.',
     'inflation', 'InflationSwap', 'NONE', 31, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CONVBOND', 0, 'Convertible Bond',
     'ConvertibleBond: a corporate bond that gives the holder the right to convert the bond''s principal into a fixed number of the issuer''s equity shares, instead of (or in addition to) redemption in cash. Priced as a bond-plus-embedded-equity-option hybrid, combining a credit-risky discount curve with an equity conversion option.',
     'bond', 'ConvertibleBond', 'NONE', 32, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CALLBOND', 0, 'Callable Bond',
     'CallableBond: a bond that gives the issuer the right to redeem the bond early, at one or more pre-specified call dates and prices, before its scheduled maturity -- typically to refinance at a lower coupon if rates fall. Priced as a bond with an embedded issuer call option, which the bondholder is implicitly short.',
     'bond', 'CallableBond', 'NONE', 33, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'BONDPOS', 0, 'Bond Position',
     'BondPosition: a simple, unlevered holding of a bond, recorded as a position rather than a new bond purchase trade -- used to represent existing bond inventory for valuation, risk, and reporting.',
     'bond', 'BondPosition', 'NONE', 34, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'BONDOPT', 0, 'Bond Option',
     'BondOption: an option granting the right, but not the obligation, to buy (call) or sell (put) a specified bond at a fixed strike price on or before a future exercise date -- priced off a yield-curve/credit-spread model for the underlying bond together with an interest-rate or spread volatility assumption.',
     'bond', 'BondOption', 'NONE', 35, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'BONDTRS', 0, 'Bond Total Return Swap',
     'BondTRS (Bond Total Return Swap): a Total Return Swap whose reference asset is a specific bond (or bond basket), letting the total-return receiver gain the bond''s price appreciation and coupon income while paying a financing rate, without funding the bond''s purchase outright.',
     'bond', 'BondTRS', 'NONE', 36, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'REPO', 0, 'Bond Repurchase Agreement',
     'BondRepo (Bond Repurchase Agreement): a short-term collateralized borrowing transaction in which one party sells a bond and simultaneously agrees to repurchase it at a later date for a pre-agreed price, with the price difference representing the implied repo financing rate on the bond used as collateral.',
     'bond', 'BondRepo', 'NONE', 37, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'BOND', 0, 'Bond',
     'Bond: the generic ORE trade type for a fixed-income security paying a defined schedule of coupons (fixed or floating) and a principal redemption at maturity -- priced off a discount curve plus an issuer-specific credit/liquidity spread, and a primary source instrument for bootstrapping government yield curves.',
     'bond', 'Bond', 'NONE', 38, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FWDBOND', 0, 'Forward Bond',
     'ForwardBond: a forward contract to buy or sell a bond at a fixed price (or yield) on a future settlement date, rather than for immediate (spot) settlement -- used to hedge or express a view on a bond''s future price without funding the purchase today.',
     'bond', 'ForwardBond', 'NONE', 39, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'BONDFUT', 0, 'Bond Future',
     'BondFuture: an exchange-traded futures contract on a notional bond (settled by delivery of one of several eligible bonds from a specified basket, chosen by the seller as the cheapest-to-deliver) -- widely used to hedge government bond portfolios and to express duration views with exchange-cleared, standardized liquidity.',
     'bond', 'BondFuture', 'NONE', 40, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXAVGFWD', 0, 'FX Average Forward',
     'FxAverageForward: an FX forward whose settlement rate is the average of the spot FX rate sampled over a series of dates, rather than a single rate fixed at maturity -- used by corporates hedging a stream of foreign-currency cashflows (e.g. monthly revenue) who want to hedge the average rate they''ll actually realize rather than a single point-in-time rate.',
     'fx', 'FxAverageForward', 'NONE', 41, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXFWD', 0, 'FX Forward',
     'FxForward: an over-the-counter agreement to exchange two currencies at a fixed rate on a future date, the most basic FX derivative and the building block from which forward points (and, in turn, the FX forward curve) are derived from the interest-rate differential between the two currencies.',
     'fx', 'FxForward', 'NONE', 42, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXOPT', 0, 'FX Option',
     'FxOption: a vanilla option granting the right, but not the obligation, to exchange one currency for another at a fixed strike rate on or before a future expiry date -- priced off the FX volatility surface (typically quoted by delta and tenor) for the given currency pair.',
     'fx', 'FxOption', 'NONE', 43, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXASN', 0, 'FX Asian Option',
     'FX Asian Option: an option whose payoff is based on the average of the FX rate sampled over a set of dates during the option''s life, rather than the single terminal value used by a vanilla option. Averaging reduces sensitivity to manipulation or a single-day price spike near expiry, which is why Asian structures are common on less liquid or more easily-moved underlyings.',
     'fx', 'FxAsianOption', 'NONE', 44, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXBAR', 0, 'FX Barrier Option',
     'FX Barrier Option: a vanilla option on the exchange rate between the pair''s two currencies that is knocked in or knocked out if the FX rate touches a specified barrier level at any point during the option''s life (continuously monitored, American-style, as opposed to the discretely-monitored Window Barrier variant). ORE supports up/down and in/out combinations sharing this single trade type.',
     'fx', 'FxBarrierOption', 'NONE', 45, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXDBAR', 0, 'FX Double Barrier Option',
     'FX Double Barrier Option: a barrier option with two barrier levels (an upper and a lower), knocked in or out if the FX rate touches either barrier at any point during the option''s life. Used to express range-bound views with a cheaper premium than a single-barrier equivalent, at the cost of two-sided knock risk.',
     'fx', 'FxDoubleBarrierOption', 'NONE', 46, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXSWP', 0, 'FX Swap',
     'FxSwap: a pair of simultaneous FX transactions -- a near-leg exchange of two currencies (often at spot) combined with a far-leg reversal at a different, forward rate -- used primarily to roll or fund an existing FX position rather than to take a fresh directional view.',
     'fx', 'FxSwap', 'NONE', 47, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXDIG', 0, 'FX Digital Option',
     'FX Digital Option: a binary option on the exchange rate between the pair''s two currencies that pays a fixed cash (or asset) amount if the FX rate is above (call) or below (put) a strike at expiry, and nothing otherwise. Priced off the FX rate''s implied volatility surface via a replicating call/put spread rather than a closed-form Black-Scholes vanilla formula.',
     'fx', 'FxDigitalOption', 'NONE', 48, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXEBAR', 0, 'FX European Barrier Option',
     'FX European Barrier Option: a barrier option whose barrier is only monitored once, at expiry, rather than continuously through the option''s life (unlike the standard FX Barrier Option, which is monitored American-style). This removes intra-life knock risk in exchange for the barrier condition being judged solely on the terminal FX rate.',
     'fx', 'FxEuropeanBarrierOption', 'NONE', 49, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXKIKO', 0, 'FX Knock-In-Knock-Out Barrier Option',
     'FxKIKOBarrierOption (Knock-In-Knock-Out): a double-barrier FX option combining a knock-in condition on one barrier with a knock-out condition on the other, so the option must be activated by touching the knock-in barrier before it can exist, and is then extinguished if the knock-out barrier is subsequently touched.',
     'fx', 'FxKIKOBarrierOption', 'NONE', 50, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXTOUCH', 0, 'FX Touch Option',
     'FX Touch Option: a one-touch binary option that pays a fixed amount as soon as the FX rate touches a specified barrier level at any time before expiry (a no-touch variant pays only if the barrier is never touched). Unlike a Digital Option, the payoff condition is monitored continuously through the option''s life, not just at expiry.',
     'fx', 'FxTouchOption', 'NONE', 51, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXDTOUCH', 0, 'FX Double Touch Option',
     'FX Double Touch Option: a touch option with two barrier levels, paying out if the FX rate touches either barrier (double-one-touch) or paying out only if neither barrier is ever touched (double-no-touch) before expiry.',
     'fx', 'FxDoubleTouchOption', 'NONE', 52, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXDIGBAR', 0, 'FX Digital Barrier Option',
     'FX Digital Barrier Option: a digital option whose fixed payout is additionally conditional on a barrier level being touched (or not touched) during the option''s life, combining the binary payoff structure of a Digital Option with the knock-in/knock-out mechanics of a Barrier Option.',
     'fx', 'FxDigitalBarrierOption', 'NONE', 53, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXVS', 0, 'FX Variance Swap',
     'FX Variance Swap: a swap that pays the difference between the realized variance of the FX rate over the swap''s life and a variance strike agreed at trade inception, settled in cash. Used to take a pure view on future realized volatility (or hedge a volatility exposure) without taking directional exposure to the FX rate itself.',
     'fx', 'FxVarianceSwap', 'NONE', 54, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXPVS', 0, 'FX Pairwise Variance Swap',
     'FX Pairwise Variance Swap: a variance swap struck on the realized variance of the spread (or ratio) between two correlated FX rates rather than a single one, used to trade the relative-volatility relationship between the pair directly.',
     'fx', 'FxPairwiseVarianceSwap', 'NONE', 55, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXBVS', 0, 'FX Basket Variance Swap',
     'FX Basket Variance Swap: a variance swap struck on the realized variance of a weighted basket of FX rates rather than a single one, giving exposure to the basket''s blended volatility (which is also sensitive to the realized correlation between the basket''s constituents).',
     'fx', 'FxBasketVarianceSwap', 'NONE', 56, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXTARF', 0, 'FX Target Redemption Forward',
     'FX TaRF (Target Redemption Forward): a strip of forward contracts on the FX rate that terminates early once the cumulative payoff to one side reaches a pre-agreed target, capping that side''s gain in exchange for a more favorable rate than a plain forward on each individual fixing.',
     'fx', 'FxTaRF', 'NONE', 57, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXWORST', 0, 'FX Worst-Of Basket Swap',
     'FX Worst Of Basket Swap: a swap whose payoff is linked to the worst-performing FX rate among a specified basket, commonly used to structure autocallable or coupon-bearing notes where the coupon or redemption depends on every constituent staying above a barrier.',
     'fx', 'FxWorstOfBasketSwap', 'NONE', 58, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXBESTENT', 0, 'FX Best Entry Option',
     'FX Best Entry Option: an option whose effective strike is set to the most favorable (lowest, for a call) level the FX rate reaches over a specified entry-observation window, rather than being fixed at trade inception -- giving the holder the benefit of optimal-entry timing without needing to actually time the market.',
     'fx', 'FxBestEntryOption', 'NONE', 59, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXACC', 0, 'FX Accumulator',
     'FX Accumulator: a structured trade under which the holder accumulates (buys or sells) the FX rate at a fixed strike on a series of scheduled dates, typically subject to a knock-out barrier that terminates the accumulation early and a leverage feature (e.g. doubling the accumulated quantity) if the FX rate trades below the strike on an observation date.',
     'fx', 'FxAccumulator', 'NONE', 60, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXWINBAR', 0, 'FX Window Barrier Option',
     'FX Window Barrier Option: a barrier option whose knock-in/knock-out condition is only monitored during a specified window of time within the option''s life (e.g. the final month before expiry), rather than continuously from trade date to expiry as in the standard FX Barrier Option.',
     'fx', 'FxWindowBarrierOption', 'NONE', 61, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXGENBAR', 0, 'FX Generic Barrier Option',
     'FX Generic Barrier Option: a flexible barrier-option trade type in ORE covering the general family of knock-in/knock-out structures (single or double barrier, continuous or discrete monitoring) via configurable schedule and event parameters, rather than the more narrowly-specified FX Barrier Option/Double Barrier Option/Window Barrier Option trade types.',
     'fx', 'FxGenericBarrierOption', 'NONE', 62, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXBSKT', 0, 'FX Basket Option',
     'FX Basket Option: an option whose payoff depends on a weighted basket of FX rates rather than a single one, typically struck on the basket''s average or weighted-sum performance at expiry. Cheaper than a strip of options on each constituent individually because the basket''s volatility benefits from imperfect correlation between its members.',
     'fx', 'FxBasketOption', 'NONE', 63, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXRNBW', 0, 'FX Rainbow Option',
     'FX Rainbow Option: a multi-asset option whose payoff depends on the best- or worst-performing (or a ranked combination) of several FX rates, rather than their combined basket value. Distinct from a Basket Option in that the payoff is driven by the relative ranking of the constituents, not their weighted sum.',
     'fx', 'FxRainbowOption', 'NONE', 64, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FXRESET', 0, 'FX Strike Resettable Option',
     'FX Strike Resettable Option: an option whose strike is reset to (or relative to) the FX rate''s prevailing level on one or more specified reset dates during the option''s life, rather than being fixed at trade inception -- used to structure cliquet-like or ratchet payoffs that lock in favorable moves.',
     'fx', 'FxStrikeResettableOption', 'NONE', 65, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQPOS', 0, 'Equity Position',
     'EquityPosition: a simple, unlevered holding of shares in a single equity, recorded as a position rather than a forward or derivative contract -- the equity-asset-class analogue of a spot cash holding, used as the underlying leg for hedges, baskets, or reporting rather than a priced derivative in its own right.',
     'equity', 'EquityPosition', 'NONE', 66, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQOPOS', 0, 'Equity Option Position',
     'EquityOptionPosition: a held position in a previously-transacted equity option (rather than a newly-struck option contract), used to represent option inventory -- for example options acquired via an exercise, assignment, or portfolio transfer -- for valuation and risk purposes.',
     'equity', 'EquityOptionPosition', 'NONE', 67, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQOPT', 0, 'Equity Option',
     'EquityOption: a vanilla option granting the right, but not the obligation, to buy (call) or sell (put) a single stock or equity index at a fixed strike price on or before a future expiry date -- priced off the equity''s implied volatility surface together with its dividend/borrow-cost forward curve.',
     'equity', 'EquityOption', 'NONE', 68, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQFUTOPT', 0, 'Equity Future Option',
     'EquityFutureOption: an option whose underlying is an equity future (rather than the equity spot or index level directly), settled by delivery of (or cash reference to) the underlying future''s price -- separating the option''s volatility exposure from the future''s own basis to the cash index.',
     'equity', 'EquityFutureOption', 'NONE', 69, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQASN', 0, 'Equity Asian Option',
     'Equity Asian Option: an option whose payoff is based on the average of the equity sampled over a set of dates during the option''s life, rather than the single terminal value used by a vanilla option. Averaging reduces sensitivity to manipulation or a single-day price spike near expiry, which is why Asian structures are common on less liquid or more easily-moved underlyings.',
     'equity', 'EquityAsianOption', 'NONE', 70, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQBAR', 0, 'Equity Barrier Option',
     'Equity Barrier Option: a vanilla option on a single stock, basket of stocks, or an equity index that is knocked in or knocked out if the equity touches a specified barrier level at any point during the option''s life (continuously monitored, American-style, as opposed to the discretely-monitored Window Barrier variant). ORE supports up/down and in/out combinations sharing this single trade type.',
     'equity', 'EquityBarrierOption', 'NONE', 71, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQDBAR', 0, 'Equity Double Barrier Option',
     'Equity Double Barrier Option: a barrier option with two barrier levels (an upper and a lower), knocked in or out if the equity touches either barrier at any point during the option''s life. Used to express range-bound views with a cheaper premium than a single-barrier equivalent, at the cost of two-sided knock risk.',
     'equity', 'EquityDoubleBarrierOption', 'NONE', 72, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQEBAR', 0, 'Equity European Barrier Option',
     'Equity European Barrier Option: a barrier option whose barrier is only monitored once, at expiry, rather than continuously through the option''s life (unlike the standard Equity Barrier Option, which is monitored American-style). This removes intra-life knock risk in exchange for the barrier condition being judged solely on the terminal equity value.',
     'equity', 'EquityEuropeanBarrierOption', 'NONE', 73, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQTOUCH', 0, 'Equity Touch Option',
     'Equity Touch Option: a one-touch binary option that pays a fixed amount as soon as the equity touches a specified barrier level at any time before expiry (a no-touch variant pays only if the barrier is never touched). Unlike a Digital Option, the payoff condition is monitored continuously through the option''s life, not just at expiry.',
     'equity', 'EquityTouchOption', 'NONE', 74, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQDTOUCH', 0, 'Equity Double Touch Option',
     'Equity Double Touch Option: a touch option with two barrier levels, paying out if the equity touches either barrier (double-one-touch) or paying out only if neither barrier is ever touched (double-no-touch) before expiry.',
     'equity', 'EquityDoubleTouchOption', 'NONE', 75, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQDIG', 0, 'Equity Digital Option',
     'Equity Digital Option: a binary option on a single stock, basket of stocks, or an equity index that pays a fixed cash (or asset) amount if the equity is above (call) or below (put) a strike at expiry, and nothing otherwise. Priced off the equity''s implied volatility surface via a replicating call/put spread rather than a closed-form Black-Scholes vanilla formula.',
     'equity', 'EquityDigitalOption', 'NONE', 76, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQFWD', 0, 'Equity Forward',
     'EquityForward: an over-the-counter agreement to buy or sell a single stock or equity index at a fixed price on a future date, the equity-asset-class analogue of an FX Forward, priced off the equity''s dividend/borrow-cost forward curve rather than an FX interest-rate differential.',
     'equity', 'EquityForward', 'NONE', 77, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQSWP', 0, 'Equity Swap',
     'EquitySwap: a swap exchanging the total return of a single stock or equity index (price appreciation plus dividends) against a floating financing leg, functionally the equity-asset-class instance of a Total Return Swap, commonly used to gain synthetic equity exposure without direct share ownership.',
     'equity', 'EquitySwap', 'NONE', 78, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQVS', 0, 'Equity Variance Swap',
     'Equity Variance Swap: a swap that pays the difference between the realized variance of the equity over the swap''s life and a variance strike agreed at trade inception, settled in cash. Used to take a pure view on future realized volatility (or hedge a volatility exposure) without taking directional exposure to the equity itself.',
     'equity', 'EquityVarianceSwap', 'NONE', 79, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQCLIQ', 0, 'Equity Cliquet Option',
     'EquityCliquetOption (ratchet option): a series of forward-starting options on the same equity underlying, each period''s strike reset to the prevailing spot at the start of that period, with the total payoff typically the sum (or average) of each period''s locked-in return -- used to monetize periodic volatility rather than a single terminal move.',
     'equity', 'EquityCliquetOption', 'NONE', 80, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQOUTPERF', 0, 'Equity Outperformance Option',
     'EquityOutperformanceOption: an option whose payoff depends on the relative outperformance of one equity (or index) against another, rather than either underlying''s absolute level -- used to take a pure relative-value view between two stocks or indices, immunized against a common market-wide move affecting both.',
     'equity', 'EquityOutperformanceOption', 'NONE', 81, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQPVS', 0, 'Equity Pairwise Variance Swap',
     'Equity Pairwise Variance Swap: a variance swap struck on the realized variance of the spread (or ratio) between two correlated equities rather than a single one, used to trade the relative-volatility relationship between the pair directly.',
     'equity', 'EquityPairwiseVarianceSwap', 'NONE', 82, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQBVS', 0, 'Equity Basket Variance Swap',
     'Equity Basket Variance Swap: a variance swap struck on the realized variance of a weighted basket of equities rather than a single one, giving exposure to the basket''s blended volatility (which is also sensitive to the realized correlation between the basket''s constituents).',
     'equity', 'EquityBasketVarianceSwap', 'NONE', 83, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQTARF', 0, 'Equity Target Redemption Forward',
     'Equity TaRF (Target Redemption Forward): a strip of forward contracts on the equity that terminates early once the cumulative payoff to one side reaches a pre-agreed target, capping that side''s gain in exchange for a more favorable rate than a plain forward on each individual fixing.',
     'equity', 'EquityTaRF', 'NONE', 84, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQWORST', 0, 'Equity Worst-Of Basket Swap',
     'Equity Worst Of Basket Swap: a swap whose payoff is linked to the worst-performing equity among a specified basket, commonly used to structure autocallable or coupon-bearing notes where the coupon or redemption depends on every constituent staying above a barrier.',
     'equity', 'EquityWorstOfBasketSwap', 'NONE', 85, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQBESTENT', 0, 'Equity Best Entry Option',
     'Equity Best Entry Option: an option whose effective strike is set to the most favorable (lowest, for a call) level the equity reaches over a specified entry-observation window, rather than being fixed at trade inception -- giving the holder the benefit of optimal-entry timing without needing to actually time the market.',
     'equity', 'EquityBestEntryOption', 'NONE', 86, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQACC', 0, 'Equity Accumulator',
     'Equity Accumulator: a structured trade under which the holder accumulates (buys or sells) the equity at a fixed strike on a series of scheduled dates, typically subject to a knock-out barrier that terminates the accumulation early and a leverage feature (e.g. doubling the accumulated quantity) if the equity trades below the strike on an observation date.',
     'equity', 'EquityAccumulator', 'NONE', 87, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQWINBAR', 0, 'Equity Window Barrier Option',
     'Equity Window Barrier Option: a barrier option whose knock-in/knock-out condition is only monitored during a specified window of time within the option''s life (e.g. the final month before expiry), rather than continuously from trade date to expiry as in the standard Equity Barrier Option.',
     'equity', 'EquityWindowBarrierOption', 'NONE', 88, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQGENBAR', 0, 'Equity Generic Barrier Option',
     'Equity Generic Barrier Option: a flexible barrier-option trade type in ORE covering the general family of knock-in/knock-out structures (single or double barrier, continuous or discrete monitoring) via configurable schedule and event parameters, rather than the more narrowly-specified Equity Barrier Option/Double Barrier Option/Window Barrier Option trade types.',
     'equity', 'EquityGenericBarrierOption', 'NONE', 89, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQBSKT', 0, 'Equity Basket Option',
     'Equity Basket Option: an option whose payoff depends on a weighted basket of equities rather than a single one, typically struck on the basket''s average or weighted-sum performance at expiry. Cheaper than a strip of options on each constituent individually because the basket''s volatility benefits from imperfect correlation between its members.',
     'equity', 'EquityBasketOption', 'NONE', 90, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQRNBW', 0, 'Equity Rainbow Option',
     'Equity Rainbow Option: a multi-asset option whose payoff depends on the best- or worst-performing (or a ranked combination) of several equities, rather than their combined basket value. Distinct from a Basket Option in that the payoff is driven by the relative ranking of the constituents, not their weighted sum.',
     'equity', 'EquityRainbowOption', 'NONE', 91, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EQRESET', 0, 'Equity Strike Resettable Option',
     'Equity Strike Resettable Option: an option whose strike is reset to (or relative to) the equity''s prevailing level on one or more specified reset dates during the option''s life, rather than being fixed at trade inception -- used to structure cliquet-like or ratchet payoffs that lock in favorable moves.',
     'equity', 'EquityStrikeResettableOption', 'NONE', 92, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMFWD', 0, 'Commodity Forward',
     'CommodityForward: an over-the-counter agreement to buy or sell a physical commodity (or commodity index/future reference) at a fixed price on a future date, the commodity-asset-class analogue of an FX/Equity Forward, priced off the commodity''s forward curve which reflects storage cost and convenience yield rather than pure interest-rate parity.',
     'commodity', 'CommodityForward', 'NONE', 93, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMOPT', 0, 'Commodity Option',
     'CommodityOption: a vanilla option granting the right, but not the obligation, to buy (call) or sell (put) a physical commodity (or commodity future) at a fixed strike price on or before a future expiry date -- priced off the commodity''s volatility surface, typically quoted per delivery point and contract month.',
     'commodity', 'CommodityOption', 'NONE', 94, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMDAPO', 0, 'Commodity Digital Average Price Option',
     'CommodityDigitalAveragePriceOption: a binary option that pays a fixed amount if the average of the commodity''s price over a set of observation dates is above (call) or below (put) a strike, combining the averaging feature of an Average Price Option with the fixed, all-or-nothing payoff of a Digital Option.',
     'commodity', 'CommodityDigitalAveragePriceOption', 'NONE', 95, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMDIG', 0, 'Commodity Digital Option',
     'Commodity Digital Option: a binary option on a physical commodity or commodity future that pays a fixed cash (or asset) amount if the commodity price is above (call) or below (put) a strike at expiry, and nothing otherwise. Priced off the commodity price''s implied volatility surface via a replicating call/put spread rather than a closed-form Black-Scholes vanilla formula.',
     'commodity', 'CommodityDigitalOption', 'NONE', 96, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMASN', 0, 'Commodity Asian Option',
     'Commodity Asian Option: an option whose payoff is based on the average of the commodity price sampled over a set of dates during the option''s life, rather than the single terminal value used by a vanilla option. Averaging reduces sensitivity to manipulation or a single-day price spike near expiry, which is why Asian structures are common on less liquid or more easily-moved underlyings.',
     'commodity', 'CommodityAsianOption', 'NONE', 97, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMSWP', 0, 'Commodity Swap',
     'CommoditySwap: a swap exchanging a fixed price (or rate) against a floating commodity reference price over a schedule of periods, used by producers and consumers to hedge commodity price exposure without taking physical delivery.',
     'commodity', 'CommoditySwap', 'NONE', 98, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMSWPTN', 0, 'Commodity Swaption',
     'CommoditySwaption: an option granting the right, but not the obligation, to enter into an underlying Commodity Swap at a pre-agreed fixed price on a future exercise date -- priced using a commodity volatility model layered on top of the underlying swap''s forward price.',
     'commodity', 'CommoditySwaption', 'NONE', 99, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMSPD', 0, 'Commodity Spread Option',
     'CommoditySpreadOption: an option whose payoff depends on the price spread between two related commodities (e.g. the crack spread between crude oil and refined products, or a locational/calendar spread within the same commodity), rather than either commodity''s absolute level.',
     'commodity', 'CommoditySpreadOption', 'NONE', 100, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMAPO', 0, 'Commodity Average Price Option',
     'CommodityAveragePriceOption (Asian-style commodity option): an option whose payoff is based on the average of the commodity''s price sampled over a set of dates, rather than a single terminal value -- common in commodity markets where daily settlement prices, not a single expiry fixing, are the natural hedge target.',
     'commodity', 'CommodityAveragePriceOption', 'NONE', 101, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMSTRIP', 0, 'Commodity Option Strip',
     'CommodityOptionStrip: a series of individual commodity options across consecutive delivery periods (e.g. one option per month for a year), combined into a single instrument -- used to hedge a rolling commodity exposure across many periods without booking each period''s option separately.',
     'commodity', 'CommodityOptionStrip', 'NONE', 102, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMPOS', 0, 'Commodity Position',
     'CommodityPosition: a simple, unlevered holding of a physical commodity or commodity future, recorded as a position rather than a forward or option contract -- used to represent existing commodity inventory for valuation and risk purposes.',
     'commodity', 'CommodityPosition', 'NONE', 103, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMVS', 0, 'Commodity Variance Swap',
     'Commodity Variance Swap: a swap that pays the difference between the realized variance of the commodity price over the swap''s life and a variance strike agreed at trade inception, settled in cash. Used to take a pure view on future realized volatility (or hedge a volatility exposure) without taking directional exposure to the commodity price itself.',
     'commodity', 'CommodityVarianceSwap', 'NONE', 104, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMPVS', 0, 'Commodity Pairwise Variance Swap',
     'Commodity Pairwise Variance Swap: a variance swap struck on the realized variance of the spread (or ratio) between two correlated commodity prices rather than a single one, used to trade the relative-volatility relationship between the pair directly.',
     'commodity', 'CommodityPairwiseVarianceSwap', 'NONE', 105, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMBVS', 0, 'Commodity Basket Variance Swap',
     'Commodity Basket Variance Swap: a variance swap struck on the realized variance of a weighted basket of commodity prices rather than a single one, giving exposure to the basket''s blended volatility (which is also sensitive to the realized correlation between the basket''s constituents).',
     'commodity', 'CommodityBasketVarianceSwap', 'NONE', 106, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMTARF', 0, 'Commodity Target Redemption Forward',
     'Commodity TaRF (Target Redemption Forward): a strip of forward contracts on the commodity price that terminates early once the cumulative payoff to one side reaches a pre-agreed target, capping that side''s gain in exchange for a more favorable rate than a plain forward on each individual fixing.',
     'commodity', 'CommodityTaRF', 'NONE', 107, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMWORST', 0, 'Commodity Worst-Of Basket Swap',
     'Commodity Worst Of Basket Swap: a swap whose payoff is linked to the worst-performing commodity price among a specified basket, commonly used to structure autocallable or coupon-bearing notes where the coupon or redemption depends on every constituent staying above a barrier.',
     'commodity', 'CommodityWorstOfBasketSwap', 'NONE', 108, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMBESTENT', 0, 'Commodity Best Entry Option',
     'Commodity Best Entry Option: an option whose effective strike is set to the most favorable (lowest, for a call) level the commodity price reaches over a specified entry-observation window, rather than being fixed at trade inception -- giving the holder the benefit of optimal-entry timing without needing to actually time the market.',
     'commodity', 'CommodityBestEntryOption', 'NONE', 109, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMACC', 0, 'Commodity Accumulator',
     'Commodity Accumulator: a structured trade under which the holder accumulates (buys or sells) the commodity price at a fixed strike on a series of scheduled dates, typically subject to a knock-out barrier that terminates the accumulation early and a leverage feature (e.g. doubling the accumulated quantity) if the commodity price trades below the strike on an observation date.',
     'commodity', 'CommodityAccumulator', 'NONE', 110, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMWINBAR', 0, 'Commodity Window Barrier Option',
     'Commodity Window Barrier Option: a barrier option whose knock-in/knock-out condition is only monitored during a specified window of time within the option''s life (e.g. the final month before expiry), rather than continuously from trade date to expiry as in the standard Commodity Barrier Option.',
     'commodity', 'CommodityWindowBarrierOption', 'NONE', 111, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMGENBAR', 0, 'Commodity Generic Barrier Option',
     'Commodity Generic Barrier Option: a flexible barrier-option trade type in ORE covering the general family of knock-in/knock-out structures (single or double barrier, continuous or discrete monitoring) via configurable schedule and event parameters, rather than the more narrowly-specified Commodity Barrier Option/Double Barrier Option/Window Barrier Option trade types.',
     'commodity', 'CommodityGenericBarrierOption', 'NONE', 112, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMBSKT', 0, 'Commodity Basket Option',
     'Commodity Basket Option: an option whose payoff depends on a weighted basket of commodity prices rather than a single one, typically struck on the basket''s average or weighted-sum performance at expiry. Cheaper than a strip of options on each constituent individually because the basket''s volatility benefits from imperfect correlation between its members.',
     'commodity', 'CommodityBasketOption', 'NONE', 113, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMRNBW', 0, 'Commodity Rainbow Option',
     'Commodity Rainbow Option: a multi-asset option whose payoff depends on the best- or worst-performing (or a ranked combination) of several commodity prices, rather than their combined basket value. Distinct from a Basket Option in that the payoff is driven by the relative ranking of the constituents, not their weighted sum.',
     'commodity', 'CommodityRainbowOption', 'NONE', 114, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'COMMRESET', 0, 'Commodity Strike Resettable Option',
     'Commodity Strike Resettable Option: an option whose strike is reset to (or relative to) the commodity price''s prevailing level on one or more specified reset dates during the option''s life, rather than being fixed at trade inception -- used to structure cliquet-like or ratchet payoffs that lock in favorable moves.',
     'commodity', 'CommodityStrikeResettableOption', 'NONE', 115, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes')
on conflict (tenant_id, code)
where valid_to = ores_utility_infinity_timestamp_fn()
do nothing;

-- Summary
select 'refdata_instrument_codes' as entity, count(*) as count
from ores_refdata_instrument_codes_tbl;
