/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

/**
 * Instrument Codes Population Script
 *
 * Populates the full ORE product/trade-type catalogue -- one row per
 * oreTradeType enumeration value in external/ore/xsd/instruments.xsd
 * (the authoritative source of truth), tagged with its asset class,
 * plus one ORE Studio-specific addition: 'Deposit'. ORE's oreTradeType
 * has no distinct money-market-deposit trade type (a deposit is
 * mathematically a single-period Swap, and ORE doesn't model it
 * separately) -- 'Deposit' is added here purely so the IR Curve
 * Template can label a short-end entry accordingly; its pricing still
 * derives from the same discount_factor()-based par-rate formula as a
 * single-period Swap would.
 *
 * This script is idempotent - uses INSERT ON CONFLICT.
 */

\echo '--- Instrument Codes ---'

insert into ores_refdata_instrument_codes_tbl (
    tenant_id, code, version, name, description, asset_class, display_order,
    modified_by, performed_by, change_reason_code, change_commentary
)
values
    (ores_utility_system_tenant_id_fn(), 'CompositeTrade', 0, 'Composite Trade',
     'ORE trade type CompositeTrade.',
     'cross_asset', 1, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'ConvertibleBond', 0, 'Convertible Bond',
     'ORE trade type ConvertibleBond.',
     'bond', 2, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CallableBond', 0, 'Callable Bond',
     'ORE trade type CallableBond.',
     'bond', 3, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'Ascot', 0, 'Ascot',
     'ORE trade type Ascot.',
     'cross_asset', 4, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'TotalReturnSwap', 0, 'Total Return Swap',
     'ORE trade type TotalReturnSwap.',
     'cross_asset', 5, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'ContractForDifference', 0, 'Contract For Difference',
     'ORE trade type ContractForDifference.',
     'cross_asset', 6, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CBO', 0, 'CBO',
     'ORE trade type CBO.',
     'cross_asset', 7, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityPosition', 0, 'Equity Position',
     'ORE trade type EquityPosition.',
     'equity', 8, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityOptionPosition', 0, 'Equity Option Position',
     'ORE trade type EquityOptionPosition.',
     'equity', 9, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'BondPosition', 0, 'Bond Position',
     'ORE trade type BondPosition.',
     'bond', 10, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'MultiLegOption', 0, 'Multi Leg Option',
     'ORE trade type MultiLegOption.',
     'cross_asset', 11, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'IndexCreditDefaultSwap', 0, 'Index Credit Default Swap',
     'ORE trade type IndexCreditDefaultSwap.',
     'credit', 12, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'IndexCreditDefaultSwapOption', 0, 'Index Credit Default Swap Option',
     'ORE trade type IndexCreditDefaultSwapOption.',
     'credit', 13, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'SyntheticCDO', 0, 'Synthetic CDO',
     'ORE trade type SyntheticCDO.',
     'credit', 14, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'BondOption', 0, 'Bond Option',
     'ORE trade type BondOption.',
     'bond', 15, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'BondTRS', 0, 'Bond TRS',
     'ORE trade type BondTRS.',
     'bond', 16, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'BondRepo', 0, 'Bond Repo',
     'ORE trade type BondRepo.',
     'bond', 17, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CreditLinkedSwap', 0, 'Credit Linked Swap',
     'ORE trade type CreditLinkedSwap.',
     'credit', 18, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CrossCurrencySwap', 0, 'Cross Currency Swap',
     'ORE trade type CrossCurrencySwap.',
     'rates', 19, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'InflationSwap', 0, 'Inflation Swap',
     'ORE trade type InflationSwap.',
     'inflation', 20, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'Swap', 0, 'Swap',
     'ORE trade type Swap.',
     'rates', 21, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'Swaption', 0, 'Swaption',
     'ORE trade type Swaption.',
     'rates', 22, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'ForwardRateAgreement', 0, 'Forward Rate Agreement',
     'ORE trade type ForwardRateAgreement.',
     'rates', 23, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxAverageForward', 0, 'Fx Average Forward',
     'ORE trade type FxAverageForward.',
     'fx', 24, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxForward', 0, 'Fx Forward',
     'ORE trade type FxForward.',
     'fx', 25, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxOption', 0, 'Fx Option',
     'ORE trade type FxOption.',
     'fx', 26, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxAsianOption', 0, 'Fx Asian Option',
     'ORE trade type FxAsianOption.',
     'fx', 27, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxBarrierOption', 0, 'Fx Barrier Option',
     'ORE trade type FxBarrierOption.',
     'fx', 28, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxDoubleBarrierOption', 0, 'Fx Double Barrier Option',
     'ORE trade type FxDoubleBarrierOption.',
     'fx', 29, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxSwap', 0, 'Fx Swap',
     'ORE trade type FxSwap.',
     'fx', 30, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxDigitalOption', 0, 'Fx Digital Option',
     'ORE trade type FxDigitalOption.',
     'fx', 31, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxEuropeanBarrierOption', 0, 'Fx European Barrier Option',
     'ORE trade type FxEuropeanBarrierOption.',
     'fx', 32, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxKIKOBarrierOption', 0, 'Fx KIKO Barrier Option',
     'ORE trade type FxKIKOBarrierOption.',
     'fx', 33, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxTouchOption', 0, 'Fx Touch Option',
     'ORE trade type FxTouchOption.',
     'fx', 34, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxDoubleTouchOption', 0, 'Fx Double Touch Option',
     'ORE trade type FxDoubleTouchOption.',
     'fx', 35, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxDigitalBarrierOption', 0, 'Fx Digital Barrier Option',
     'ORE trade type FxDigitalBarrierOption.',
     'fx', 36, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxVarianceSwap', 0, 'Fx Variance Swap',
     'ORE trade type FxVarianceSwap.',
     'fx', 37, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CapFloor', 0, 'Cap Floor',
     'ORE trade type CapFloor.',
     'rates', 38, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityOption', 0, 'Equity Option',
     'ORE trade type EquityOption.',
     'equity', 39, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityFutureOption', 0, 'Equity Future Option',
     'ORE trade type EquityFutureOption.',
     'equity', 40, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityAsianOption', 0, 'Equity Asian Option',
     'ORE trade type EquityAsianOption.',
     'equity', 41, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityBarrierOption', 0, 'Equity Barrier Option',
     'ORE trade type EquityBarrierOption.',
     'equity', 42, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityDoubleBarrierOption', 0, 'Equity Double Barrier Option',
     'ORE trade type EquityDoubleBarrierOption.',
     'equity', 43, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityEuropeanBarrierOption', 0, 'Equity European Barrier Option',
     'ORE trade type EquityEuropeanBarrierOption.',
     'equity', 44, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityTouchOption', 0, 'Equity Touch Option',
     'ORE trade type EquityTouchOption.',
     'equity', 45, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityDoubleTouchOption', 0, 'Equity Double Touch Option',
     'ORE trade type EquityDoubleTouchOption.',
     'equity', 46, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityDigitalOption', 0, 'Equity Digital Option',
     'ORE trade type EquityDigitalOption.',
     'equity', 47, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityForward', 0, 'Equity Forward',
     'ORE trade type EquityForward.',
     'equity', 48, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquitySwap', 0, 'Equity Swap',
     'ORE trade type EquitySwap.',
     'equity', 49, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityVarianceSwap', 0, 'Equity Variance Swap',
     'ORE trade type EquityVarianceSwap.',
     'equity', 50, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityCliquetOption', 0, 'Equity Cliquet Option',
     'ORE trade type EquityCliquetOption.',
     'equity', 51, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityForward', 0, 'Commodity Forward',
     'ORE trade type CommodityForward.',
     'commodity', 52, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityOption', 0, 'Commodity Option',
     'ORE trade type CommodityOption.',
     'commodity', 53, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityDigitalAveragePriceOption', 0, 'Commodity Digital Average Price Option',
     'ORE trade type CommodityDigitalAveragePriceOption.',
     'commodity', 54, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityDigitalOption', 0, 'Commodity Digital Option',
     'ORE trade type CommodityDigitalOption.',
     'commodity', 55, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityAsianOption', 0, 'Commodity Asian Option',
     'ORE trade type CommodityAsianOption.',
     'commodity', 56, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommoditySwap', 0, 'Commodity Swap',
     'ORE trade type CommoditySwap.',
     'commodity', 57, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommoditySwaption', 0, 'Commodity Swaption',
     'ORE trade type CommoditySwaption.',
     'commodity', 58, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommoditySpreadOption', 0, 'Commodity Spread Option',
     'ORE trade type CommoditySpreadOption.',
     'commodity', 59, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityAveragePriceOption', 0, 'Commodity Average Price Option',
     'ORE trade type CommodityAveragePriceOption.',
     'commodity', 60, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityOptionStrip', 0, 'Commodity Option Strip',
     'ORE trade type CommodityOptionStrip.',
     'commodity', 61, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityPosition', 0, 'Commodity Position',
     'ORE trade type CommodityPosition.',
     'commodity', 62, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityVarianceSwap', 0, 'Commodity Variance Swap',
     'ORE trade type CommodityVarianceSwap.',
     'commodity', 63, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'Bond', 0, 'Bond',
     'ORE trade type Bond.',
     'bond', 64, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'ForwardBond', 0, 'Forward Bond',
     'ORE trade type ForwardBond.',
     'bond', 65, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'BondFuture', 0, 'Bond Future',
     'ORE trade type BondFuture.',
     'bond', 66, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CreditDefaultSwap', 0, 'Credit Default Swap',
     'ORE trade type CreditDefaultSwap.',
     'credit', 67, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CreditDefaultSwapOption', 0, 'Credit Default Swap Option',
     'ORE trade type CreditDefaultSwapOption.',
     'credit', 68, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'Failed', 0, 'Failed',
     'ORE trade type Failed.',
     'cross_asset', 69, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FlexiSwap', 0, 'Flexi Swap',
     'ORE trade type FlexiSwap.',
     'rates', 70, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'BalanceGuaranteedSwap', 0, 'Balance Guaranteed Swap',
     'ORE trade type BalanceGuaranteedSwap.',
     'rates', 71, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CallableSwap', 0, 'Callable Swap',
     'ORE trade type CallableSwap.',
     'rates', 72, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityOutperformanceOption', 0, 'Equity Outperformance Option',
     'ORE trade type EquityOutperformanceOption.',
     'equity', 73, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityPairwiseVarianceSwap', 0, 'Equity Pairwise Variance Swap',
     'ORE trade type EquityPairwiseVarianceSwap.',
     'equity', 74, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxPairwiseVarianceSwap', 0, 'Fx Pairwise Variance Swap',
     'ORE trade type FxPairwiseVarianceSwap.',
     'fx', 75, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityPairwiseVarianceSwap', 0, 'Commodity Pairwise Variance Swap',
     'ORE trade type CommodityPairwiseVarianceSwap.',
     'commodity', 76, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'ScriptedTrade', 0, 'Scripted Trade',
     'ORE trade type ScriptedTrade.',
     'cross_asset', 77, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityBasketVarianceSwap', 0, 'Equity Basket Variance Swap',
     'ORE trade type EquityBasketVarianceSwap.',
     'equity', 78, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxBasketVarianceSwap', 0, 'Fx Basket Variance Swap',
     'ORE trade type FxBasketVarianceSwap.',
     'fx', 79, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityBasketVarianceSwap', 0, 'Commodity Basket Variance Swap',
     'ORE trade type CommodityBasketVarianceSwap.',
     'commodity', 80, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'RiskParticipationAgreement', 0, 'Risk Participation Agreement',
     'ORE trade type RiskParticipationAgreement.',
     'cross_asset', 81, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'Autocallable_01', 0, 'Autocallable 1',
     'ORE trade type Autocallable_01.',
     'cross_asset', 82, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'DoubleDigitalOption', 0, 'Double Digital Option',
     'ORE trade type DoubleDigitalOption.',
     'cross_asset', 83, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EuropeanOptionBarrier', 0, 'European Option Barrier',
     'ORE trade type EuropeanOptionBarrier.',
     'cross_asset', 84, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'PerformanceOption_01', 0, 'Performance Option 1',
     'ORE trade type PerformanceOption_01.',
     'cross_asset', 85, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxTaRF', 0, 'Fx TaRF',
     'ORE trade type FxTaRF.',
     'fx', 86, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityTaRF', 0, 'Equity TaRF',
     'ORE trade type EquityTaRF.',
     'equity', 87, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityTaRF', 0, 'Commodity TaRF',
     'ORE trade type CommodityTaRF.',
     'commodity', 88, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxWorstOfBasketSwap', 0, 'Fx Worst Of Basket Swap',
     'ORE trade type FxWorstOfBasketSwap.',
     'fx', 89, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityWorstOfBasketSwap', 0, 'Equity Worst Of Basket Swap',
     'ORE trade type EquityWorstOfBasketSwap.',
     'equity', 90, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityWorstOfBasketSwap', 0, 'Commodity Worst Of Basket Swap',
     'ORE trade type CommodityWorstOfBasketSwap.',
     'commodity', 91, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityBestEntryOption', 0, 'Equity Best Entry Option',
     'ORE trade type EquityBestEntryOption.',
     'equity', 92, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxBestEntryOption', 0, 'Fx Best Entry Option',
     'ORE trade type FxBestEntryOption.',
     'fx', 93, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityBestEntryOption', 0, 'Commodity Best Entry Option',
     'ORE trade type CommodityBestEntryOption.',
     'commodity', 94, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxAccumulator', 0, 'Fx Accumulator',
     'ORE trade type FxAccumulator.',
     'fx', 95, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityAccumulator', 0, 'Equity Accumulator',
     'ORE trade type EquityAccumulator.',
     'equity', 96, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityAccumulator', 0, 'Commodity Accumulator',
     'ORE trade type CommodityAccumulator.',
     'commodity', 97, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxWindowBarrierOption', 0, 'Fx Window Barrier Option',
     'ORE trade type FxWindowBarrierOption.',
     'fx', 98, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityWindowBarrierOption', 0, 'Equity Window Barrier Option',
     'ORE trade type EquityWindowBarrierOption.',
     'equity', 99, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityWindowBarrierOption', 0, 'Commodity Window Barrier Option',
     'ORE trade type CommodityWindowBarrierOption.',
     'commodity', 100, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxGenericBarrierOption', 0, 'Fx Generic Barrier Option',
     'ORE trade type FxGenericBarrierOption.',
     'fx', 101, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityGenericBarrierOption', 0, 'Equity Generic Barrier Option',
     'ORE trade type EquityGenericBarrierOption.',
     'equity', 102, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityGenericBarrierOption', 0, 'Commodity Generic Barrier Option',
     'ORE trade type CommodityGenericBarrierOption.',
     'commodity', 103, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxBasketOption', 0, 'Fx Basket Option',
     'ORE trade type FxBasketOption.',
     'fx', 104, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityBasketOption', 0, 'Equity Basket Option',
     'ORE trade type EquityBasketOption.',
     'equity', 105, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityBasketOption', 0, 'Commodity Basket Option',
     'ORE trade type CommodityBasketOption.',
     'commodity', 106, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxRainbowOption', 0, 'Fx Rainbow Option',
     'ORE trade type FxRainbowOption.',
     'fx', 107, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityRainbowOption', 0, 'Equity Rainbow Option',
     'ORE trade type EquityRainbowOption.',
     'equity', 108, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityRainbowOption', 0, 'Commodity Rainbow Option',
     'ORE trade type CommodityRainbowOption.',
     'commodity', 109, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'KnockOutSwap', 0, 'Knock Out Swap',
     'ORE trade type KnockOutSwap.',
     'rates', 110, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CashPosition', 0, 'Cash Position',
     'ORE trade type CashPosition.',
     'cross_asset', 111, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'CommodityStrikeResettableOption', 0, 'Commodity Strike Resettable Option',
     'ORE trade type CommodityStrikeResettableOption.',
     'commodity', 112, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'FxStrikeResettableOption', 0, 'Fx Strike Resettable Option',
     'ORE trade type FxStrikeResettableOption.',
     'fx', 113, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    (ores_utility_system_tenant_id_fn(), 'EquityStrikeResettableOption', 0, 'Equity Strike Resettable Option',
     'ORE trade type EquityStrikeResettableOption.',
     'equity', 114, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes'),
    -- ORE Studio-specific addition, not a native oreTradeType -- see header comment.
    (ores_utility_system_tenant_id_fn(), 'Deposit', 0, 'Deposit',
     'Short-dated money-market deposit; simple rate over a single period. Not a native ORE trade type -- ORE models this as a single-period Swap; added here as a distinct short-end label for the IR Curve Template.',
     'rates', 115, current_user, current_user, 'system.initial_load', 'Initial population of instrument codes')
on conflict (tenant_id, code)
where valid_to = ores_utility_infinity_timestamp_fn()
do nothing;

-- Summary
select 'refdata_instrument_codes' as entity, count(*) as count
from ores_refdata_instrument_codes_tbl;
