;;; ores-env.el --- .env file support for ORE Studio. -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:
;;
;; Provides .env file loading for ORE Studio checkouts.
;;
;; The .env file lives at the project root (as returned by `project-current')
;; and is generated by build/scripts/init-environment.sh.  It contains all
;; credentials and configuration for a single checkout and is never committed.
;;
;; Public API:
;;
;;   `ores/dotenv-file'  - path to the .env file
;;   `ores/load-dotenv'  - parse .env -> alist of (KEY . VALUE)

;;; Code:

(require 'project)

;; ---------------------------------------------------------------------------
;; Checkout root and .env location
;; ---------------------------------------------------------------------------

(defun ores/checkout-root ()
  "Return the absolute path to the current checkout root directory."
  (expand-file-name (project-root (project-current t))))

(defun ores/dotenv-file ()
  "Return the absolute path to the .env file at the checkout root."
  (expand-file-name ".env" (ores/checkout-root)))

;; ---------------------------------------------------------------------------
;; Parser
;; ---------------------------------------------------------------------------

(defun ores/load-dotenv ()
  "Parse the checkout .env file and return an alist of (KEY . VALUE) pairs.

Skips blank lines and comment lines (starting with #).
Handles KEY=VALUE and KEY=unquoted value forms.
Unescapes \\\\n sequences to real newlines (used for the PEM key)."
  (let ((path (ores/dotenv-file)))
    (unless (file-exists-p path)
      (user-error "No .env file found at %s — run init-environment.sh first" path))
    (with-temp-buffer
      (insert-file-contents path)
      (ores/--parse-dotenv-buffer))))

(defun ores/--parse-dotenv-buffer ()
  "Parse the current buffer as a dotenv file, returning an alist."
  (let (result)
    (goto-char (point-min))
    (while (not (eobp))
      (let ((line (buffer-substring-no-properties
                   (line-beginning-position)
                   (line-end-position))))
        (when (and (not (string-match-p "^[[:space:]]*$" line))
                   (not (string-match-p "^[[:space:]]*#" line))
                   (string-match "^\\([A-Za-z_][A-Za-z0-9_]*\\)=\\(.*\\)$" line))
          (let* ((key (match-string 1 line))
                 (raw (match-string 2 line))
                 (value (ores/--dotenv-unescape raw)))
            (push (cons key value) result))))
      (forward-line 1))
    (nreverse result)))

(defun ores/--dotenv-unescape (raw)
  "Strip optional surrounding double-quotes and unescape \\\\n in RAW."
  (let ((v (if (and (> (length raw) 1)
                    (string-prefix-p "\"" raw)
                    (string-suffix-p "\"" raw))
               (substring raw 1 -1)
             raw)))
    (replace-regexp-in-string "\\\\n" "\n" v)))

(provide 'ores-env)
;;; ores-env.el ends here
