drop rule if exists ores_analytics_pricing_model_products_delete_rule on "ores_analytics_pricing_model_products_tbl";
drop trigger if exists ores_analytics_pricing_model_products_insert_trg on "ores_analytics_pricing_model_products_tbl";
drop function if exists ores_analytics_pricing_model_products_insert_fn;
drop table if exists "ores_analytics_pricing_model_products_tbl";
