drop rule if exists ores_analytics_pricing_engine_types_delete_rule on "ores_analytics_pricing_engine_types_tbl";
drop trigger if exists ores_analytics_pricing_engine_types_insert_trg on "ores_analytics_pricing_engine_types_tbl";
drop function if exists ores_analytics_pricing_engine_types_insert_fn;
drop function if exists ores_analytics_validate_pricing_engine_type_fn;
drop table if exists "ores_analytics_pricing_engine_types_tbl";
