/*
 * Minimal org-mode parser for ORE Studio agile documents.
 *
 * The agile docs are generated by ores.codegen and follow a rigid
 * structure: a :PROPERTIES: drawer, a block of #+keyword: lines, then
 * level-1..3 sections containing prose, lists, and org tables. This
 * parser targets exactly that shape rather than full org-mode.
 */

/** Parse a `[[target][desc]]` or `[[target]]` org link. */
const LINK_RE = /\[\[([^\]]+)\]\(?\]?\[?([^\]]*)\]?\]/g;

/** Strip org links to their description (or target when bare). */
export function linkText(s) {
  return s.replace(/\[\[([^\]]*)\]\[([^\]]*)\]\]/g, '$2')
          .replace(/\[\[([^\]]*)\]\]/g, '$1')
          .trim();
}

/** Extract the first id: link target from a string, or null. */
export function idLink(s) {
  const m = s.match(/\[\[id:([0-9A-Fa-f-]+)\]/);
  return m ? m[1].toUpperCase() : null;
}

/** Parse one org table row into trimmed cells. */
function parseRow(line) {
  // | a | b | -> ['a', 'b']
  const inner = line.trim().replace(/^\|/, '').replace(/\|$/, '');
  return inner.split('|').map(c => c.trim());
}

/**
 * Parse the lines of a section body, extracting tables and list items
 * while keeping the prose.
 */
function parseBody(lines) {
  const tables = [];
  const items = [];
  const prose = [];
  let table = null;

  for (const line of lines) {
    const t = line.trim();
    if (t.startsWith('|')) {
      if (/^\|[-+]+\|?$/.test(t.replace(/\s/g, ''))) continue; // separator
      if (!table) { table = { header: null, rows: [] }; tables.push(table); }
      const cells = parseRow(t);
      if (!table.header) table.header = cells;
      else table.rows.push(cells);
      continue;
    }
    table = null;
    if (t.startsWith('- ')) { items.push(t.slice(2)); continue; }
    if (t.startsWith('#+')) continue; // attr lines etc.
    if (t.length) prose.push(t);
  }
  return { tables, items, prose };
}

/**
 * Parse an org document into:
 *   { id, keywords: {title, type, ...}, filetags: [],
 *     sections: [{ level, title, path, ...body }] }
 */
export function parseOrg(text) {
  const lines = text.split('\n');
  const doc = { id: null, keywords: {}, filetags: [], sections: [] };

  let i = 0;
  // :PROPERTIES: drawer.
  if (lines[i] && lines[i].trim() === ':PROPERTIES:') {
    i++;
    while (i < lines.length && lines[i].trim() !== ':END:') {
      const m = lines[i].match(/^:([A-Za-z_]+):\s*(.*)$/);
      if (m && m[1].toUpperCase() === 'ID') doc.id = m[2].trim().toUpperCase();
      i++;
    }
    i++; // skip :END:
  }

  // #+keyword: lines and preamble prose until the first heading.
  const headingAt = n => lines[n] && /^\*+ /.test(lines[n]);
  const preamble = [];
  for (; i < lines.length && !headingAt(i); i++) {
    const kw = lines[i].match(/^#\+([A-Za-z_]+):\s*(.*)$/);
    if (kw) {
      const key = kw[1].toLowerCase();
      const val = kw[2].trim();
      if (key === 'filetags') {
        doc.filetags = val.split(':').map(s => s.trim()).filter(Boolean);
      } else {
        doc.keywords[key] = val;
      }
      continue;
    }
    if (lines[i].trim().length) preamble.push(lines[i].trim());
  }
  doc.preamble = preamble.join(' ');

  // Sections: track the heading path so nested headings stay addressable.
  const stack = [];
  let current = null;
  for (; i < lines.length; i++) {
    const h = lines[i].match(/^(\*+) (.*)$/);
    if (h) {
      const level = h[1].length;
      const title = h[2].trim();
      while (stack.length >= level) stack.pop();
      stack.push(title);
      current = { level, title, path: stack.join(' / '), lines: [] };
      doc.sections.push(current);
      continue;
    }
    if (current) current.lines.push(lines[i]);
  }
  for (const s of doc.sections) {
    Object.assign(s, parseBody(s.lines));
    delete s.lines;
  }
  return doc;
}

/** Find the first section whose title matches (case-insensitive). */
export function section(doc, title) {
  const t = title.toLowerCase();
  return doc.sections.find(s => s.title.toLowerCase() === t) || null;
}

/**
 * Read a two-column field table (`| Field | Value |`) into an object
 * keyed by lower-cased field name.
 */
export function fieldTable(doc, sectionTitle) {
  const s = section(doc, sectionTitle);
  if (!s || !s.tables.length) return {};
  const out = {};
  const tbl = s.tables[0];
  const all = tbl.header ? [tbl.header, ...tbl.rows] : tbl.rows;
  for (const row of all) {
    if (row.length >= 2 && row[0]) out[row[0].toLowerCase()] = row[1];
  }
  return out;
}
