:PROPERTIES:
:ID: C4E8A2F1-D7B3-4A9C-8E6F-5B1D9C0A3E7F
:END:
#+title: SQL Recipes
#+author: Marco Craveiro
#+startup: inlineimages
#+options: <:nil c:nil todo:nil ^:nil d:nil date:nil author:nil toc:nil html-postamble:nil

SQL recipes for directly querying and managing the [[id:B7E9F3A1-C8D2-4E6B-A1F5-9D3C7E8B2A4F][ORES Database Schema]].

* Initial Setup
  :PROPERTIES:
  :header-args: :exports both
  :header-args+: :results raw
  :header-args+: :engine postgresql
  :header-args+: :dbhost localhost
  :header-args+: :dbuser postgres
  :header-args+: :dbpassword (auth-source-pick-first-password :host "localhost" :user "postgres")
  :header-args+: :var project_sql_dir=(concat (project-root (project-current)) "projects/sql")
  :END:

These recipes must be run *in order* using the =postgres= superuser to bootstrap
the ORES database infrastructure. Run each step once when setting up a new
PostgreSQL server.

** Step 1: Setup password for user =postgres=

If you have not yet added a password to =postgres=, login as
that user and in psql:

#+begin_src sql
alter user postgres password 'SECURE PASSWORD';
#+end_src

To generate a secure password:

#+begin_src sh :wrap example
pwgen -c 25 | head -n1
#+end_src

#+RESULTS:
#+begin_example
ohzo4cohmoof1Cai2Xaxohsie
#+end_example

Then add the secure password to your =authinfo.gpg=, e.g.:

#+begin_src authinfo
machine localhost login postgres password ohzo4cohmoof1Cai2Xaxohsie
#+end_src

** Step 2: Clean Slate

To make sure you do not have any remnants of a previous install, do:

#+begin_src sql :database template1 :wrap example
\ir '$project_sql_dir'/clean_slate.sql
#+end_src

#+RESULTS:
#+begin_example
UPDATE 1
DROP DATABASE
DROP DATABASE
DROP DATABASE
DROP DATABASE
DROP ROLE
#+end_example

This will drop *all* databases related to ores.

** Step 3: Install Extensions

Installs required PostgreSQL extensions (btree_gist, TimescaleDB). TimescaleDB
must be installed on your system. For Debian, as root:

#+begin_src sh
curl -s https://packagecloud.io/install/repositories/timescale/timescaledb/script.deb.sh | sudo bash
apt-get install postgresql-18-timescaledb
#+end_src

It then must be added to =shared_preload_libraries= in =postgresql.conf=:

#+begin_src conf
shared_preload_libraries = 'timescaledb'
#+end_src

Restart PostgreSQL after modifying the config, then run:

#+begin_src sql :database template1 :wrap example
\ir '$project_sql_dir'/setup_extensions.sql
#+end_src

#+RESULTS:
#+begin_example
CREATE EXTENSION
DO
extname	extversion
btree_gist	1.8
timescaledb	2.24.0
#+end_example

You may need to enable community edition if available. At present it's not
available for Postgres 18 on Debian.

#+begin_src sql :database template1 :wrap example
alter system set timescaledb.license = 'timescale';
select pg_reload_conf();
show timescaledb.license;
#+end_src

#+RESULTS:
#+begin_example
#+end_example

** Step 4: Create ORES User

Creates the =ores= application user. Generate a secure password first:

#+begin_src sh :wrap example
pwgen -c 25 1
#+end_src

Then run the script with the password as a variable. From the command line:

#+begin_src sh
psql -U postgres -v ores_password='YOUR_SECURE_PASSWORD' -f projects/sql/setup_user.sql
#+end_src

Add the password to your =authinfo.gpg=:

#+begin_src authinfo
machine localhost login ores password YOUR_SECURE_PASSWORD
#+end_src

** Step 5: Create Admin Database

Creates =ores_admin= with cluster-level utilities (name generation, cleanup):

#+begin_src sql :database template1 :wrap example
\ir '$project_sql_dir'/admin/setup_admin.sql
#+end_src

#+RESULTS:
#+begin_example
CREATE DATABASE
GRANT
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE VIEW
CREATE VIEW
CREATE VIEW
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
#+end_example

** Step 4: Create Template Database

Creates =ores_template= with the complete application schema and reference data:

#+begin_src sql :database template1 :wrap example
\ir '$project_sql_dir'/setup_template.sql
#+end_src

#+RESULTS:
#+begin_example
CREATE DATABASE
GRANT
CREATE EXTENSION
DO
extname	extversion
btree_gist	1.8
timescaledb	2.24.0
CREATE SCHEMA
CREATE EXTENSION
GRANT
GRANT
SET
CREATE FUNCTION
SET
CREATE TABLE
CREATE INDEX
CREATE FUNCTION
CREATE TRIGGER
CREATE RULE
CREATE FUNCTION
CREATE TRIGGER
SET
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE FUNCTION
CREATE TRIGGER
CREATE FUNCTION
CREATE TRIGGER
SET
CREATE TABLE
CREATE INDEX
CREATE FUNCTION
CREATE TRIGGER
SET
CREATE TABLE
CREATE INDEX
CREATE INDEX
SET
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
DO
SET
DO
CREATE FUNCTION
CREATE FUNCTION
SET
CREATE TABLE
CREATE INDEX
CREATE FUNCTION
CREATE TRIGGER
CREATE RULE
SET
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE FUNCTION
CREATE TRIGGER
CREATE RULE
SET
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE FUNCTION
CREATE TRIGGER
CREATE RULE
SET
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE FUNCTION
CREATE TRIGGER
CREATE RULE
SET
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
SET
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE FUNCTION
CREATE TRIGGER
CREATE RULE
SET
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE FUNCTION
CREATE TRIGGER
CREATE RULE
SET
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE FUNCTION
CREATE TRIGGER
CREATE RULE
SET
CREATE TABLE
CREATE INDEX
CREATE FUNCTION
CREATE TRIGGER
CREATE RULE
SET
CREATE TABLE
CREATE INDEX
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
INSERT 0 1
CREATE FUNCTION
SET
load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

load_flag

SET
INSERT 0 158
SET
INSERT 0 158
GRANT
GRANT
ALTER DEFAULT PRIVILEGES
ALTER DEFAULT PRIVILEGES
UPDATE 1
#+end_example

If you need to drop to recreate:

#+begin_src sql :database template1 :wrap example
update pg_database set datistemplate = false where datname = 'ores_template';
drop database if exists ores_template;
#+end_src

#+RESULTS:
#+begin_example
UPDATE 1
DROP DATABASE
#+end_example


** Step 5: Create Database Instance

Creates a new database instance from the template. Run this each time you need a
new database (development, testing, production, etc.).

*** With Auto-Generated Whimsical Name

#+begin_src sql :database template1 :results output :wrap example
\ir '$project_sql_dir'/create_instance.sql
#+end_src

#+RESULTS:
#+begin_example
CREATE DATABASE
GRANT
SET
DO
SET
DO
name	enabled	description	modified_by
system.disable_password_validation	0	When enabled (1), disables strict password validation. FOR TESTING/DEVELOPMENT ONLY.	system
database_created
ores_bold_mountain
#+end_example

*** With Specific Name

#+begin_src sh :wrap example
psql -U postgres -v db_name='my_ores_db' -f projects/sql/create_instance.sql
#+end_src

* Recipes
  :PROPERTIES:
  :header-args: :exports both
  :header-args+: :results raw
  :header-args+: :engine postgresql
  :header-args+: :dbhost localhost
  :header-args+: :dbuser ores
  :header-args+: :dbpassword (auth-source-pick-first-password :host "localhost" :user "ores")
  :header-args+: :var project_sql_dir=(concat (project-root (project-current)) "projects/sql")
  :END:

Day-to-day recipes for querying and managing ORES databases. These use the
=ores= application user.

** Database Management

These recipes require the initial setup (Steps 1-3) to be completed first.

*** List All ORES Databases

List all databases created from the ORES template:

#+begin_src sql :database ores_admin
select * from ores_databases;
#+end_src

*** List Test Databases

List databases created by automated tests (=ores_test_*=, =oresdb_test_*=):

#+begin_src sql :database ores_admin
select * from test_databases;
#+end_src

*** List Instance Databases

List instance databases only (excludes test and template):

#+begin_src sql :database ores_admin
select * from ores_instance_databases;
#+end_src

*** Delete All Test Databases

Delete all test databases. Uses =\gexec= because =DROP DATABASE= cannot run
inside a transaction block:

#+begin_src sql :database ores_admin
select format('DROP DATABASE IF EXISTS %I;', database_name)
from test_databases \gexec
#+end_src

*** Delete All ORES Databases

*WARNING*: This deletes ALL ORES databases (instances, templates, test). Use
with caution!

#+begin_src sql :database ores_admin
select format('DROP DATABASE IF EXISTS %I;', database_name)
from ores_databases \gexec
#+end_src

*** Delete All Instance Databases

Delete all instance databases (preserves templates and test databases):

#+begin_src sql :database ores_admin
select format('DROP DATABASE IF EXISTS %I;', database_name)
from ores_instance_databases \gexec
#+end_src

*** Preview Cleanup SQL

Generate cleanup SQL without executing (for review):

#+begin_src sql :database ores_admin
select generate_cleanup_test_databases_sql();
#+end_src

*** Generate Whimsical Database Name

Generate a unique whimsical name for a new database:

#+begin_src sql :database ores_admin
select generate_unique_database_name_from_server();
#+end_src

** Accounts

*** List All Current Accounts

Get all currently active accounts (where =valid_to= is infinity):

#+begin_src sql
select id, username, email, version, valid_from
from ores.accounts
where valid_to = '9999-12-31 23:59:59'::timestamptz
order by username;
#+end_src

*** List All Account Versions

View the complete temporal history of an account:

#+begin_src sql
select id, username, email, version, valid_from, valid_to
from ores.accounts
where username = 'admin'
order by valid_from;
#+end_src

*** Get Account by Username

#+begin_src sql
select id, username, email, version, valid_from
from ores.accounts
where username = 'admin'
  and valid_to = '9999-12-31 23:59:59'::timestamptz;
#+end_src

*** Get Account by UUID

#+begin_src sql
select id, username, email, version, valid_from
from ores.accounts
where id = 'your-uuid-here'
  and valid_to = '9999-12-31 23:59:59'::timestamptz;
#+end_src

*** Count Active Accounts

#+begin_src sql
select count(*) as active_accounts
from ores.accounts
where valid_to = '9999-12-31 23:59:59'::timestamptz;
#+end_src

** Login Info

*** List All Login Info

View login tracking for all accounts:

#+begin_src sql
select li.account_id, a.username, li.last_login, li.failed_logins,
       li.locked, li.online, li.last_ip
from ores.login_info li
join ores.accounts a on a.id = li.account_id
  and a.valid_to = '9999-12-31 23:59:59'::timestamptz
order by li.last_login desc nulls last;
#+end_src

*** Find Locked Accounts

#+begin_src sql
select li.account_id, a.username, li.failed_logins, li.last_attempt_ip
from ores.login_info li
join ores.accounts a on a.id = li.account_id
  and a.valid_to = '9999-12-31 23:59:59'::timestamptz
where li.locked = 1;
#+end_src

*** Find Online Users

#+begin_src sql
select a.username, li.last_login, li.last_ip
from ores.login_info li
join ores.accounts a on a.id = li.account_id
  and a.valid_to = '9999-12-31 23:59:59'::timestamptz
where li.online = 1;
#+end_src

** Sessions

*** List Recent Sessions

#+begin_src sql
select s.id, a.username, s.start_time, s.end_time,
       s.client_ip, s.country_code, s.city
from ores.sessions s
join ores.accounts a on a.id = s.account_id
  and a.valid_to = '9999-12-31 23:59:59'::timestamptz
order by s.start_time desc
limit 20;
#+end_src

*** Session Statistics by User

#+begin_src sql
select a.username,
       count(*) as total_sessions,
       sum(s.bytes_sent) as total_bytes_sent,
       sum(s.bytes_received) as total_bytes_received
from ores.sessions s
join ores.accounts a on a.id = s.account_id
  and a.valid_to = '9999-12-31 23:59:59'::timestamptz
group by a.username
order by total_sessions desc;
#+end_src

** RBAC (Roles and Permissions)

*** List All Roles

#+begin_src sql
select id, name, description, version
from ores.roles
where valid_to = '9999-12-31 23:59:59'::timestamptz
order by name;
#+end_src

*** List All Permissions

#+begin_src sql
select id, code, description
from ores.permissions
where valid_to = '9999-12-31 23:59:59'::timestamptz
order by code;
#+end_src

*** Get Permissions for a Role

#+begin_src sql
select r.name as role_name, p.code as permission_code, p.description
from ores.role_permissions rp
join ores.roles r on r.id = rp.role_id
  and r.valid_to = '9999-12-31 23:59:59'::timestamptz
join ores.permissions p on p.id = rp.permission_id
  and p.valid_to = '9999-12-31 23:59:59'::timestamptz
where rp.valid_to = '9999-12-31 23:59:59'::timestamptz
  and r.name = 'admin'
order by p.code;
#+end_src

*** Get Roles for an Account

#+begin_src sql
select a.username, r.name as role_name, ar.assigned_at, ar.assigned_by
from ores.account_roles ar
join ores.accounts a on a.id = ar.account_id
  and a.valid_to = '9999-12-31 23:59:59'::timestamptz
join ores.roles r on r.id = ar.role_id
  and r.valid_to = '9999-12-31 23:59:59'::timestamptz
where ar.valid_to = '9999-12-31 23:59:59'::timestamptz
  and a.username = 'admin'
order by r.name;
#+end_src

*** Get All Permissions for an Account (via Roles)

#+begin_src sql
select distinct a.username, p.code as permission_code
from ores.accounts a
join ores.account_roles ar on ar.account_id = a.id
  and ar.valid_to = '9999-12-31 23:59:59'::timestamptz
join ores.role_permissions rp on rp.role_id = ar.role_id
  and rp.valid_to = '9999-12-31 23:59:59'::timestamptz
join ores.permissions p on p.id = rp.permission_id
  and p.valid_to = '9999-12-31 23:59:59'::timestamptz
where a.valid_to = '9999-12-31 23:59:59'::timestamptz
  and a.username = 'admin'
order by p.code;
#+end_src

*** Check if Account Has Permission

Uses the built-in RBAC function:

#+begin_src sql
select ores.account_has_permission('admin', 'accounts:create') as has_permission;
#+end_src

** Currencies

*** List All Currencies

#+begin_src sql
select iso_code, name, symbol, numeric_code, currency_type
from ores.currencies
where valid_to = '9999-12-31 23:59:59'::timestamptz
order by iso_code;
#+end_src

*** Get Currency Details

#+begin_src sql
select iso_code, name, symbol, fraction_symbol,
       fractions_per_unit, rounding_type, rounding_precision, format
from ores.currencies
where iso_code = 'USD'
  and valid_to = '9999-12-31 23:59:59'::timestamptz;
#+end_src

*** Count Currencies by Type

#+begin_src sql
select currency_type, count(*) as count
from ores.currencies
where valid_to = '9999-12-31 23:59:59'::timestamptz
group by currency_type
order by count desc;
#+end_src

*** Get Currency with Flag Image

#+begin_src sql
select c.iso_code, c.name, c.symbol, i.key as flag_key
from ores.currencies c
left join ores.currency_images ci on ci.iso_code = c.iso_code
  and ci.valid_to = '9999-12-31 23:59:59'::timestamptz
left join ores.images i on i.image_id = ci.image_id
  and i.valid_to = '9999-12-31 23:59:59'::timestamptz
where c.valid_to = '9999-12-31 23:59:59'::timestamptz
  and c.iso_code = 'GBP';
#+end_src

** Feature Flags

*** List All Feature Flags

#+begin_src sql
select name, enabled, description, version
from ores.feature_flags
where valid_to = '9999-12-31 23:59:59'::timestamptz
order by name;
#+end_src

*** Check Feature Flag Status

#+begin_src sql
select name, enabled
from ores.feature_flags
where name = 'bootstrap_mode'
  and valid_to = '9999-12-31 23:59:59'::timestamptz;
#+end_src

*** List Enabled Features

#+begin_src sql
select name, description
from ores.feature_flags
where enabled = 1
  and valid_to = '9999-12-31 23:59:59'::timestamptz
order by name;
#+end_src

** Images and Tags

*** List All Images

#+begin_src sql
select image_id, key, description, version
from ores.images
where valid_to = '9999-12-31 23:59:59'::timestamptz
order by key
limit 20;
#+end_src

*** List All Tags

#+begin_src sql
select tag_id, name, description
from ores.tags
where valid_to = '9999-12-31 23:59:59'::timestamptz
order by name;
#+end_src

*** Get Images by Tag

#+begin_src sql
select i.key, i.description
from ores.images i
join ores.image_tags it on it.image_id = i.image_id
  and it.valid_to = '9999-12-31 23:59:59'::timestamptz
join ores.tags t on t.tag_id = it.tag_id
  and t.valid_to = '9999-12-31 23:59:59'::timestamptz
where i.valid_to = '9999-12-31 23:59:59'::timestamptz
  and t.name = 'flag'
order by i.key
limit 20;
#+end_src

** Temporal Queries

*** View Entity History

See all versions of an entity over time:

#+begin_src sql
select id, username, email, version, valid_from, valid_to,
       case when valid_to = '9999-12-31 23:59:59'::timestamptz
            then 'current' else 'historical' end as status
from ores.accounts
where username = 'admin'
order by valid_from;
#+end_src

*** Point-in-Time Query

Get the state of an entity at a specific point in time:

#+begin_src sql
select id, username, email, version
from ores.accounts
where username = 'admin'
  and valid_from <= '2025-01-15 12:00:00'::timestamptz
  and valid_to > '2025-01-15 12:00:00'::timestamptz;
#+end_src

*** Count Entity Versions

#+begin_src sql
select username, count(*) as version_count
from ores.accounts
group by username
having count(*) > 1
order by version_count desc;
#+end_src

** Administrative

*** Database Size

#+begin_src sql
select pg_size_pretty(pg_database_size(current_database())) as database_size;
#+end_src

*** Table Sizes

#+begin_src sql
select schemaname, tablename,
       pg_size_pretty(pg_total_relation_size(schemaname || '.' || tablename)) as size
from pg_tables
where schemaname = 'ores'
order by pg_total_relation_size(schemaname || '.' || tablename) desc;
#+end_src

*** Row Counts per Table

Uses PostgreSQL statistics for all tables in the schema:

#+begin_src sql
select relname as table_name, n_live_tup as rows
from pg_stat_user_tables
where schemaname = 'ores'
order by n_live_tup desc;
#+end_src

| Previous: [[id:46F5ED07-9E63-77B4-2783-E0147EFF45D0][Recipes]] | Schema: [[id:B7E9F3A1-C8D2-4E6B-A1F5-9D3C7E8B2A4F][SQL Schema]] |
