# -*- mode: cmake; cmake-tab-width: 4; indent-tabs-mode: nil -*-
#
# Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
set(files
    "asset_class_code_eventing_integration_tests.cpp"
    "book_eventing_integration_tests.cpp"
    "book_purpose_type_eventing_integration_tests.cpp"
    "book_status_eventing_integration_tests.cpp"
    "business_centre_eventing_integration_tests.cpp"
    "business_day_convention_type_eventing_integration_tests.cpp"
    "business_unit_eventing_integration_tests.cpp"
    "business_unit_type_eventing_integration_tests.cpp"
    "calendar_event_eventing_integration_tests.cpp"
    "calendar_eventing_integration_tests.cpp"
    "calendar_exception_eventing_integration_tests.cpp"
    "calendar_rule_eventing_integration_tests.cpp"
    "calendar_type_eventing_integration_tests.cpp"
    "cds_convention_eventing_integration_tests.cpp"
    "contact_type_eventing_integration_tests.cpp"
    "counterparty_contact_information_eventing_integration_tests.cpp"
    "counterparty_eventing_integration_tests.cpp"
    "counterparty_identifier_eventing_integration_tests.cpp"
    "country_eventing_integration_tests.cpp"
    "crm_driver_pair_eventing_integration_tests.cpp"
    "crm_enabled_derived_pair_eventing_integration_tests.cpp"
    "crm_topology_config_eventing_integration_tests.cpp"
    "currency_eventing_integration_tests.cpp"
    "currency_group_eventing_integration_tests.cpp"
    "currency_market_tier_eventing_integration_tests.cpp"
    "currency_pair_classification_eventing_integration_tests.cpp"
    "currency_pair_convention_eventing_integration_tests.cpp"
    "currency_pair_eventing_integration_tests.cpp"
    "curve_role_eventing_integration_tests.cpp"
    "day_count_fraction_type_eventing_integration_tests.cpp"
    "deposit_convention_eventing_integration_tests.cpp"
    "derivation_kind_eventing_integration_tests.cpp"
    "diary_entry_type_eventing_integration_tests.cpp"
    "floating_index_type_eventing_integration_tests.cpp"
    "fra_convention_eventing_integration_tests.cpp"
    "ibor_index_convention_eventing_integration_tests.cpp"
    "instrument_code_eventing_integration_tests.cpp"
    "ledger_feed_type_eventing_integration_tests.cpp"
    "leg_type_eventing_integration_tests.cpp"
    "main.cpp"
    "monetary_nature_eventing_integration_tests.cpp"
    "ois_convention_eventing_integration_tests.cpp"
    "overnight_index_convention_eventing_integration_tests.cpp"
    "party_contact_information_eventing_integration_tests.cpp"
    "party_eventing_integration_tests.cpp"
    "party_id_scheme_eventing_integration_tests.cpp"
    "party_identifier_eventing_integration_tests.cpp"
    "party_rls_isolation_tests.cpp"
    "party_status_eventing_integration_tests.cpp"
    "party_type_eventing_integration_tests.cpp"
    "payment_frequency_eventing_integration_tests.cpp"
    "portfolio_eventing_integration_tests.cpp"
    "presentation_currency_history_field_mapper_tests.cpp"
    "purpose_type_eventing_integration_tests.cpp"
    "regulatory_book_type_eventing_integration_tests.cpp"
    "repository_book_status_repository_tests.cpp"
    "repository_business_unit_repository_tests.cpp"
    "repository_business_unit_type_repository_tests.cpp"
    "repository_cds_convention_workspace_inheritance_tests.cpp"
    "repository_contact_type_repository_tests.cpp"
    "repository_counterparty_contact_information_repository_tests.cpp"
    "repository_counterparty_identifier_repository_tests.cpp"
    "repository_counterparty_repository_tests.cpp"
    "repository_country_repository_tests.cpp"
    "repository_currency_calendar_repository_tests.cpp"
    "repository_currency_country_repository_tests.cpp"
    "repository_currency_market_tier_repository_tests.cpp"
    "repository_currency_pair_convention_calendar_repository_tests.cpp"
    "repository_currency_repository_tests.cpp"
    "repository_monetary_nature_repository_tests.cpp"
    "repository_party_contact_information_repository_tests.cpp"
    "repository_party_counterparty_repository_tests.cpp"
    "repository_party_country_repository_tests.cpp"
    "repository_party_currency_repository_tests.cpp"
    "repository_party_id_scheme_repository_tests.cpp"
    "repository_party_identifier_repository_tests.cpp"
    "repository_party_repository_tests.cpp"
    "repository_party_status_repository_tests.cpp"
    "repository_party_type_repository_tests.cpp"
    "repository_regulatory_book_type_repository_tests.cpp"
    "repository_rounding_type_repository_tests.cpp"
    "rounding_type_eventing_integration_tests.cpp"
    "service_calendar_materialisation_service_tests.cpp"
    "swap_convention_eventing_integration_tests.cpp"
    "tenor_anchor_eventing_integration_tests.cpp"
    "tenor_convention_eventing_integration_tests.cpp"
    "tenor_eventing_integration_tests.cpp"
    "tenor_kind_eventing_integration_tests.cpp"
    "tenor_resolution_algorithm_eventing_integration_tests.cpp"
    "tenor_schedule_eventing_integration_tests.cpp"
    "tenor_unit_eventing_integration_tests.cpp"
    "zero_convention_eventing_integration_tests.cpp"
)
