' -*- mode: plantuml; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
'
' Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
'
' This program is free software; you can redistribute it and/or modify it under
' the terms of the GNU General Public License as published by the Free Software
' Foundation; either version 3 of the License, or (at your option) any later
' version.
'
' This program is distributed in the hope that it will be useful, but WITHOUT
' ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
' FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with
' this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
' Street, Fifth Floor, Boston, MA 02110-1301, USA.
'
@startuml

title ores.qt.party Component

set namespaceSeparator ::

namespace ores #F2F2F2 {
    namespace qt #F2F2F2 {
        class BusinessCentreController {
            +parent : QObject*
            -imageCache_ : ImageCache*
            -listWindow_ : BusinessCentreMdiWindow*
            -listMdiSubWindow_ : DetachableMdiSubWindow*
        }
        class BusinessCentreDetailDialog {
            -ui_ : Ui::BusinessCentreDetailDialog*
            -clientManager_ : ClientManager*
            -username_ : string
            -business_centre_ : refdata::domain::business_centre
            -pending_country_ : string
        }
        class BusinessCentreHistoryDialog {
            +parent : QWidget*
            -ui_ : Ui::BusinessCentreHistoryDialog*
            -code_ : QString
            -clientManager_ : ClientManager*
            -versions_ : vector<refdata::domain::business_centre>
            -toolbar_ : QToolBar*
            -openVersionAction_ : QAction*
            -revertAction_ : QAction*
        }
        class BusinessCentreMdiWindow {
            +parent : QWidget*
            -clientManager_ : ClientManager*
            -imageCache_ : ImageCache*
            -username_ : QString
            -toolbar_ : QToolBar*
            -tableView_ : QTableView*
            -pagination_widget_ : PaginationWidget*
            -model_ : ClientBusinessCentreModel*
            -proxyModel_ : QSortFilterProxyModel*
            -reloadAction_ : QAction*
            -addAction_ : QAction*
            -editAction_ : QAction*
            -deleteAction_ : QAction*
            -historyAction_ : QAction*
        }
        class unit_type_entry <<struct>> {
            +id : boost::uuids::uuid
            +name : string
            +level : int
        }
        class BusinessUnitDetailDialog {
            -ui_ : Ui::BusinessUnitDetailDialog*
            -clientManager_ : ClientManager*
            -username_ : string
            -business_unit_ : refdata::domain::business_unit
            -unit_type_entries_ : vector<unit_type_entry>
        }
        class BusinessUnitHistoryDialog {
            +parent : QWidget*
            -ui_ : Ui::BusinessUnitHistoryDialog*
            -id_ : boost::uuids::uuid
            -code_ : QString
            -clientManager_ : ClientManager*
            -versions_ : vector<refdata::domain::business_unit>
            -toolbar_ : QToolBar*
            -openVersionAction_ : QAction*
            -revertAction_ : QAction*
        }
        class BusinessUnitMdiWindow {
            +parent : QWidget*
            -clientManager_ : ClientManager*
            -imageCache_ : ImageCache*
            -username_ : QString
            -badgeCache_ : BadgeCache*
            -toolbar_ : QToolBar*
            -tableView_ : QTableView*
            -model_ : ClientBusinessUnitModel*
            -proxyModel_ : QSortFilterProxyModel*
            -paginationWidget_ : PaginationWidget*
            -reloadAction_ : QAction*
            -addAction_ : QAction*
            -editAction_ : QAction*
            -deleteAction_ : QAction*
            -historyAction_ : QAction*
        }
        class BusinessUnitTypeController {
            +parent : QObject*
            -listWindow_ : BusinessUnitTypeMdiWindow*
            -listMdiSubWindow_ : DetachableMdiSubWindow*
        }
        class BusinessUnitTypeDetailDialog {
            -ui_ : Ui::BusinessUnitTypeDetailDialog*
            -clientManager_ : ClientManager*
            -username_ : string
            -type_ : refdata::domain::business_unit_type
        }
        class BusinessUnitTypeHistoryDialog {
            +parent : QWidget*
            -ui_ : Ui::BusinessUnitTypeHistoryDialog*
            -id_ : boost::uuids::uuid
            -code_ : QString
            -clientManager_ : ClientManager*
            -versions_ : vector<refdata::domain::business_unit_type>
            -toolbar_ : QToolBar*
            -openVersionAction_ : QAction*
            -revertAction_ : QAction*
        }
        class BusinessUnitTypeMdiWindow {
            +parent : QWidget*
            -clientManager_ : ClientManager*
            -username_ : QString
            -toolbar_ : QToolBar*
            -tableView_ : QTableView*
            -model_ : ClientBusinessUnitTypeModel*
            -proxyModel_ : QSortFilterProxyModel*
            -paginationWidget_ : PaginationWidget*
            -reloadAction_ : QAction*
            -addAction_ : QAction*
            -editAction_ : QAction*
            -deleteAction_ : QAction*
            -historyAction_ : QAction*
        }
        class ClientBusinessCentreModel {
            +parent : QObject*
            +role : int
            -clientManager_ : ClientManager*
            -imageCache_ : ImageCache*
            -business_centres_ : vector<refdata::domain::business_centre>
            -watcher_ : QFutureWatcher<FetchResult>*
            -recencyTracker_ : RecencyTracker<refdata::domain::business_centre, BusinessCentreKeyExtractor>
            -pulseManager_ : RecencyPulseManager*
        }
        class ClientBusinessUnitModel {
            +parent : QObject*
            +role : int
            -clientManager_ : ClientManager*
            -imageCache_ : ImageCache*
            -business_units_ : vector<refdata::domain::business_unit>
            -watcher_ : QFutureWatcher<FetchResult>*
            -recencyTracker_ : RecencyTracker<refdata::domain::business_unit, BusinessUnitKeyExtractor>
            -pulseManager_ : RecencyPulseManager*
        }
        class ClientBusinessUnitTypeModel {
            +parent : QObject*
            +role : int
            -clientManager_ : ClientManager*
            -types_ : vector<refdata::domain::business_unit_type>
            -watcher_ : QFutureWatcher<FetchResult>*
            -recencyTracker_ : BusinessUnitTypeKeyExtractor>
            -pulseManager_ : RecencyPulseManager*
        }
        class ClientContactTypeModel {
            +parent : QObject*
            +role : int
            -clientManager_ : ClientManager*
            -types_ : vector<refdata::domain::contact_type>
            -watcher_ : QFutureWatcher<FetchResult>*
            -recencyTracker_ : RecencyTracker<refdata::domain::contact_type, ContactTypeKeyExtractor>
            -pulseManager_ : RecencyPulseManager*
        }
        class ClientCounterpartyModel {
            +parent : QObject*
            +role : int
            -clientManager_ : ClientManager*
            -imageCache_ : ImageCache*
            -counterparties_ : vector<refdata::domain::counterparty>
            -watcher_ : QFutureWatcher<FetchResult>*
            -recencyTracker_ : RecencyTracker<refdata::domain::counterparty, CounterpartyKeyExtractor>
            -pulseManager_ : RecencyPulseManager*
            -bc_code_to_image_id_ : unordered_map<string, string>
        }
        class ClientPartyIdSchemeModel {
            +parent : QObject*
            +role : int
            -clientManager_ : ClientManager*
            -schemes_ : vector<refdata::domain::party_id_scheme>
            -watcher_ : QFutureWatcher<FetchResult>*
            -recencyTracker_ : RecencyTracker<refdata::domain::party_id_scheme, PartyIdSchemeKeyExtractor>
            -pulseManager_ : RecencyPulseManager*
        }
        class ClientPartyModel {
            +parent : QObject*
            +role : int
            -clientManager_ : ClientManager*
            -imageCache_ : ImageCache*
            -parties_ : vector<refdata::domain::party>
            -watcher_ : QFutureWatcher<FetchResult>*
            -recencyTracker_ : RecencyTracker<refdata::domain::party, PartyKeyExtractor>
            -pulseManager_ : RecencyPulseManager*
            -bc_code_to_image_id_ : unordered_map<string, string>
        }
        class ClientPartyStatusModel {
            +parent : QObject*
            +role : int
            -clientManager_ : ClientManager*
            -statuses_ : vector<refdata::domain::party_status>
            -watcher_ : QFutureWatcher<FetchResult>*
            -recencyTracker_ : RecencyTracker<refdata::domain::party_status, PartyStatusKeyExtractor>
            -pulseManager_ : RecencyPulseManager*
        }
        class ClientPartyTypeModel {
            +parent : QObject*
            +role : int
            -clientManager_ : ClientManager*
            -types_ : vector<refdata::domain::party_type>
            -watcher_ : QFutureWatcher<FetchResult>*
            -recencyTracker_ : RecencyTracker<refdata::domain::party_type, PartyTypeKeyExtractor>
            -pulseManager_ : RecencyPulseManager*
        }
        class ContactTypeController {
            +parent : QObject*
            -listWindow_ : ContactTypeMdiWindow*
            -listMdiSubWindow_ : DetachableMdiSubWindow*
        }
        class ContactTypeDetailDialog {
            -ui_ : Ui::ContactTypeDetailDialog*
            -clientManager_ : ClientManager*
            -username_ : string
            -type_ : refdata::domain::contact_type
        }
        class ContactTypeHistoryDialog {
            +parent : QWidget*
            -ui_ : Ui::ContactTypeHistoryDialog*
            -code_ : QString
            -clientManager_ : ClientManager*
            -versions_ : vector<refdata::domain::contact_type>
            -toolbar_ : QToolBar*
            -openVersionAction_ : QAction*
            -revertAction_ : QAction*
        }
        class ContactTypeMdiWindow {
            +parent : QWidget*
            -clientManager_ : ClientManager*
            -username_ : QString
            -toolbar_ : QToolBar*
            -tableView_ : QTableView*
            -model_ : ClientContactTypeModel*
            -proxyModel_ : QSortFilterProxyModel*
            -paginationWidget_ : PaginationWidget*
            -reloadAction_ : QAction*
            -addAction_ : QAction*
            -editAction_ : QAction*
            -deleteAction_ : QAction*
            -historyAction_ : QAction*
        }
        class CounterpartyController {
            +parent : QObject*
            -imageCache_ : ImageCache*
            -changeReasonCache_ : ChangeReasonCache*
            -badgeCache_ : BadgeCache*
            -listWindow_ : CounterpartyMdiWindow*
            -listMdiSubWindow_ : DetachableMdiSubWindow*
        }
        class counterparty_detail_operations {
        }
        class CounterpartyHistoryDialog {
            +parent : QWidget*
            -ui_ : Ui::CounterpartyHistoryDialog*
            -id_ : boost::uuids::uuid
            -code_ : QString
            -clientManager_ : ClientManager*
            -versions_ : vector<refdata::domain::counterparty>
            -toolbar_ : QToolBar*
            -openVersionAction_ : QAction*
            -revertAction_ : QAction*
        }
        class CounterpartyMdiWindow {
            +parent : QWidget*
            -clientManager_ : ClientManager*
            -imageCache_ : ImageCache*
            -username_ : QString
            -badgeCache_ : BadgeCache*
            -toolbar_ : QToolBar*
            -tableView_ : QTableView*
            -pagination_widget_ : PaginationWidget*
            -model_ : ClientCounterpartyModel*
            -proxyModel_ : QSortFilterProxyModel*
            -reloadAction_ : QAction*
            -addAction_ : QAction*
            -editAction_ : QAction*
            -deleteAction_ : QAction*
            -historyAction_ : QAction*
        }
        class PartyController {
            +parent : QObject*
            -imageCache_ : ImageCache*
            -changeReasonCache_ : ChangeReasonCache*
            -badgeCache_ : BadgeCache*
            -listWindow_ : PartyMdiWindow*
            -listMdiSubWindow_ : DetachableMdiSubWindow*
        }
        class party_detail_operations {
        }
        class PartyHistoryDialog {
            +parent : QWidget*
            -ui_ : Ui::PartyHistoryDialog*
            -id_ : boost::uuids::uuid
            -code_ : QString
            -clientManager_ : ClientManager*
            -versions_ : vector<refdata::domain::party>
            -toolbar_ : QToolBar*
            -openVersionAction_ : QAction*
            -revertAction_ : QAction*
        }
        class PartyIdSchemeController {
            +parent : QObject*
            -listWindow_ : PartyIdSchemeMdiWindow*
            -listMdiSubWindow_ : DetachableMdiSubWindow*
        }
        class PartyIdSchemeDetailDialog {
            -ui_ : Ui::PartyIdSchemeDetailDialog*
            -clientManager_ : ClientManager*
            -username_ : string
            -scheme_ : refdata::domain::party_id_scheme
        }
        class PartyIdSchemeHistoryDialog {
            +parent : QWidget*
            -ui_ : Ui::PartyIdSchemeHistoryDialog*
            -code_ : QString
            -clientManager_ : ClientManager*
            -versions_ : vector<refdata::domain::party_id_scheme>
            -toolbar_ : QToolBar*
            -openVersionAction_ : QAction*
            -revertAction_ : QAction*
        }
        class PartyIdSchemeMdiWindow {
            +parent : QWidget*
            -clientManager_ : ClientManager*
            -username_ : QString
            -toolbar_ : QToolBar*
            -tableView_ : QTableView*
            -model_ : ClientPartyIdSchemeModel*
            -proxyModel_ : QSortFilterProxyModel*
            -paginationWidget_ : PaginationWidget*
            -reloadAction_ : QAction*
            -addAction_ : QAction*
            -editAction_ : QAction*
            -deleteAction_ : QAction*
            -historyAction_ : QAction*
        }
        class PartyMdiWindow {
            +parent : QWidget*
            -clientManager_ : ClientManager*
            -imageCache_ : ImageCache*
            -username_ : QString
            -badgeCache_ : BadgeCache*
            -toolbar_ : QToolBar*
            -tableView_ : QTableView*
            -model_ : ClientPartyModel*
            -proxyModel_ : QSortFilterProxyModel*
            -pagination_widget_ : PaginationWidget*
            -reloadAction_ : QAction*
            -addAction_ : QAction*
            -editAction_ : QAction*
            -deleteAction_ : QAction*
            -historyAction_ : QAction*
        }
        class PartyPlugin {
            -ctx_ : plugin_context
            -partyTypeController_ : unique_ptr<PartyTypeController>
            -partyStatusController_ : unique_ptr<PartyStatusController>
            -partyIdSchemeController_ : unique_ptr<PartyIdSchemeController>
            -contactTypeController_ : unique_ptr<ContactTypeController>
            -partyController_ : unique_ptr<PartyController>
            -counterpartyController_ : unique_ptr<CounterpartyController>
            -businessCentreController_ : unique_ptr<BusinessCentreController>
            -businessUnitController_ : unique_ptr<BusinessUnitController>
            -businessUnitTypeController_ : unique_ptr<BusinessUnitTypeController>
        }
        class PartyStatusController {
            +parent : QObject*
            -listWindow_ : PartyStatusMdiWindow*
            -listMdiSubWindow_ : DetachableMdiSubWindow*
        }
        class PartyStatusDetailDialog {
            -ui_ : Ui::PartyStatusDetailDialog*
            -clientManager_ : ClientManager*
            -username_ : string
            -status_ : refdata::domain::party_status
        }
        class PartyStatusHistoryDialog {
            +parent : QWidget*
            -ui_ : Ui::PartyStatusHistoryDialog*
            -code_ : QString
            -clientManager_ : ClientManager*
            -versions_ : vector<refdata::domain::party_status>
            -toolbar_ : QToolBar*
            -openVersionAction_ : QAction*
            -revertAction_ : QAction*
        }
        class PartyStatusMdiWindow {
            +parent : QWidget*
            -clientManager_ : ClientManager*
            -username_ : QString
            -toolbar_ : QToolBar*
            -tableView_ : QTableView*
            -model_ : ClientPartyStatusModel*
            -proxyModel_ : QSortFilterProxyModel*
            -paginationWidget_ : PaginationWidget*
            -reloadAction_ : QAction*
            -addAction_ : QAction*
            -editAction_ : QAction*
            -deleteAction_ : QAction*
            -historyAction_ : QAction*
        }
        class PartyTypeController {
            +parent : QObject*
            -listWindow_ : PartyTypeMdiWindow*
            -listMdiSubWindow_ : DetachableMdiSubWindow*
        }
        class PartyTypeDetailDialog {
            -ui_ : Ui::PartyTypeDetailDialog*
            -clientManager_ : ClientManager*
            -username_ : string
            -type_ : refdata::domain::party_type
        }
        class PartyTypeHistoryDialog {
            +parent : QWidget*
            -ui_ : Ui::PartyTypeHistoryDialog*
            -code_ : QString
            -clientManager_ : ClientManager*
            -versions_ : vector<refdata::domain::party_type>
            -toolbar_ : QToolBar*
            -openVersionAction_ : QAction*
            -revertAction_ : QAction*
        }
        class PartyTypeMdiWindow {
            +parent : QWidget*
            -clientManager_ : ClientManager*
            -username_ : QString
            -toolbar_ : QToolBar*
            -tableView_ : QTableView*
            -model_ : ClientPartyTypeModel*
            -proxyModel_ : QSortFilterProxyModel*
            -paginationWidget_ : PaginationWidget*
            -reloadAction_ : QAction*
            -addAction_ : QAction*
            -editAction_ : QAction*
            -deleteAction_ : QAction*
            -historyAction_ : QAction*
        }
    }
}

' --- manual: everything below this line is hand-authored; the script preserves it ---

' Local Variables:
' compile-command: "java -Djava.awt.headless=true -DPLANTUML_SECURITY_PROFILE=UNSECURE -DPLANTUML_LIMIT_SIZE=65535 -jar /usr/share/plantuml/plantuml.jar ores.qt.party.puml"
' End:
@enduml
