#!/usr/bin/env python3
"""
ore_domain_roundtrip_check.py — Thing 3: ORE domain roundtrip check.

Compares committed roundtrip outputs (assets/test_data/domain_roundtrip/)
against the upstream ORE originals (external/ore/examples/) and reports
per-file and per-entity fidelity for all supported ORE XML document types:
  - Portfolio       (entities keyed by Trade @id)
  - CurrencyConfig  (entities keyed by <ISOCode>)
  - CalendarAdjustments (entities keyed by <Calendar name="...">)
  - Conventions     (entities keyed by <Id> within each convention element)

The roundtrip outputs are generated by:
  ores.cli ore roundtrip external/ore/examples \\
      --output-dir assets/test_data/domain_roundtrip

Usage:
  python3 scripts/ore_domain_roundtrip_check.py [--repo-root <path>] [--strict]

  --strict: exit with code 1 on any partial or missing outputs.

Exit codes:
  0 — all outputs full (or non-strict mode)
  1 — partial/missing found and --strict was specified
"""

import argparse
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path


# ---------------------------------------------------------------------------
# XML helpers
# ---------------------------------------------------------------------------

def collect_element_names(elem) -> set:
    """Recursively collect all element tag names under an XML element."""
    names = set()
    for node in elem.iter():
        tag = node.tag
        if "}" in tag:
            tag = tag.split("}", 1)[1]
        names.add(tag)
    return names


def parse_xml_safe(path: Path):
    """Return (root, None) on success, (None, error_str) on failure."""
    try:
        return ET.parse(path).getroot(), None
    except ET.ParseError as e:
        return None, str(e)


# ---------------------------------------------------------------------------
# File type detection
# ---------------------------------------------------------------------------

def detect_file_type(path: Path) -> str:
    """Return 'portfolio', 'currency_config', 'calendar_adjustments',
    'conventions', or 'unknown' based on first 4 KiB."""
    try:
        with path.open("rb") as fh:
            chunk = fh.read(4096)
        if b"<Portfolio>" in chunk:
            return "portfolio"
        if b"<CurrencyConfig>" in chunk:
            return "currency_config"
        if b"<CalendarAdjustments>" in chunk:
            return "calendar_adjustments"
        if b"<Conventions>" in chunk:
            return "conventions"
    except OSError:
        pass
    return "unknown"


# ---------------------------------------------------------------------------
# Entity extraction — one dict {entity_key: element} per file type
# ---------------------------------------------------------------------------

def get_trade_entities(root) -> dict:
    """Return {trade_id: <Trade element>} for all <Trade> children."""
    entities = {}
    if root is None:
        return entities
    for trade in root.findall("Trade"):
        tid = trade.get("id")
        if tid:
            entities[tid] = trade
    return entities


def get_currency_entities(root) -> dict:
    """Return {iso_code: <Currency element>} for all <Currency> children."""
    entities = {}
    if root is None:
        return entities
    for currency in root.findall("Currency"):
        iso = currency.findtext("ISOCode")
        if iso:
            entities[iso.strip()] = currency
    return entities


def get_calendar_entities(root) -> dict:
    """Return {name: <Calendar element>} for all <Calendar> children."""
    entities = {}
    if root is None:
        return entities
    for cal in root.findall("Calendar"):
        name = cal.get("name")
        if name:
            entities[name.strip()] = cal
    return entities


def get_convention_entities(root) -> dict:
    """Return {type:id: <element>} for all convention elements with <Id>."""
    entities = {}
    if root is None:
        return entities
    for child in root:
        tag = child.tag
        if "}" in tag:
            tag = tag.split("}", 1)[1]
        id_elem = child.find("Id")
        if id_elem is not None and id_elem.text:
            key = f"{tag}:{id_elem.text.strip()}"
            entities[key] = child
    return entities


# ---------------------------------------------------------------------------
# Fidelity analysis — generic entity comparison
# ---------------------------------------------------------------------------

def trade_type(trade_elem) -> str:
    """Extract <TradeType> text from a <Trade> element, or 'Unknown'."""
    tt = trade_elem.find("TradeType")
    return tt.text.strip() if tt is not None and tt.text else "Unknown"


def analyse_entities(orig_path: Path, out_path: Path,
                     get_entities_fn, label_fn=None) -> list:
    """
    Compare entities from orig_path against out_path using get_entities_fn.

    Returns list of dicts:
      {
        "entity_id":   str,
        "entity_type": str,
        "fidelity":    float,   # 0.0–1.0; -1.0 means absent in output
        "missing":     set[str],
      }
    """
    orig_root, err = parse_xml_safe(orig_path)
    if err:
        return []

    out_root, _ = parse_xml_safe(out_path)
    orig_entities = get_entities_fn(orig_root)
    out_entities  = get_entities_fn(out_root) if out_root is not None else {}

    results = []
    for eid, orig_elem in orig_entities.items():
        orig_elems = collect_element_names(orig_elem)
        etype = label_fn(orig_elem) if label_fn else (
            orig_elem.tag.split("}")[-1] if "}" in orig_elem.tag else orig_elem.tag)

        if eid not in out_entities:
            results.append({
                "entity_id":   eid,
                "entity_type": etype,
                "fidelity":    -1.0,
                "missing":     orig_elems,
            })
            continue

        out_elems = collect_element_names(out_entities[eid])
        missing   = orig_elems - out_elems
        fidelity  = (len(orig_elems) - len(missing)) / len(orig_elems) \
                    if orig_elems else 1.0

        results.append({
            "entity_id":   eid,
            "entity_type": etype,
            "fidelity":    fidelity,
            "missing":     missing,
        })

    return results


# ---------------------------------------------------------------------------
# Reporting helpers
# ---------------------------------------------------------------------------

def pct(n, d):
    return f"{n / d * 100:.1f}%" if d else "n/a"


def print_entity_section(label: str, full: list, partial: list,
                         passthrough: list, missing_files: list):
    """Print a summary section for one file type."""
    total = len(full) + len(partial) + len(passthrough)
    print(f"\n--- {label} ---")
    print(f"  Missing output files: {len(missing_files)}")
    print(f"  Entities analysed:    {total}")
    if total:
        print(f"    Full     (100%):  {len(full)}"
              f"  ({pct(len(full), total)})")
        print(f"    Partial  (<100%): {len(partial)}"
              f"  ({pct(len(partial), total)})")
        if passthrough:
            print(f"    Absent in output: {len(passthrough)}"
                  f"  ({pct(len(passthrough), total)})")

    if partial:
        by_type: dict[str, list] = defaultdict(list)
        for r in partial:
            by_type[r["entity_type"]].append(r)
        print(f"  Partial detail:")
        for etype in sorted(by_type):
            entries = by_type[etype]
            avg_fid = sum(e["fidelity"] for e in entries) / len(entries)
            print(f"    {etype}  ({len(entries)}, avg {avg_fid * 100:.0f}%)")
            for e in entries[:3]:
                print(f"      [{e['entity_id']}]  {e['fidelity'] * 100:.0f}%")
                miss = sorted(e["missing"])[:8]
                print(f"        missing: {', '.join(miss)}"
                      + ("..." if len(e["missing"]) > 8 else ""))
            if len(entries) > 3:
                print(f"      ... and {len(entries) - 3} more")

    if missing_files:
        for rel in missing_files[:10]:
            print(f"  MISSING: {rel}")
        if len(missing_files) > 10:
            print(f"  ... and {len(missing_files) - 10} more")


# ---------------------------------------------------------------------------
# Main check
# ---------------------------------------------------------------------------

def run_check(repo_root: Path, strict: bool) -> int:
    orig_root = repo_root / "external" / "ore" / "examples"
    out_root  = repo_root / "assets" / "test_data" / "domain_roundtrip"

    if not orig_root.exists():
        print(f"ERROR: ORE examples not found: {orig_root}", file=sys.stderr)
        return 1

    # Classify all XML files by root element.
    portfolio_files:   list[Path] = []
    currency_files:    list[Path] = []
    calendar_files:    list[Path] = []
    convention_files:  list[Path] = []

    for p in sorted(orig_root.rglob("*.xml")):
        ft = detect_file_type(p)
        if ft == "portfolio":
            portfolio_files.append(p)
        elif ft == "currency_config":
            currency_files.append(p)
        elif ft == "calendar_adjustments":
            calendar_files.append(p)
        elif ft == "conventions":
            convention_files.append(p)

    # Collect output files present.
    out_files_present: set[Path] = set()
    if out_root.exists():
        out_files_present = {p for p in out_root.rglob("*.xml")}

    # ----- Portfolio -----
    full_trades:        list[dict] = []
    partial_trades:     list[dict] = []
    passthrough_trades: list[dict] = []
    missing_portfolio:  list[Path] = []

    for orig_path in portfolio_files:
        rel      = orig_path.relative_to(orig_root)
        out_path = out_root / rel
        if out_path not in out_files_present:
            missing_portfolio.append(rel)
            continue
        for r in analyse_entities(orig_path, out_path,
                                  get_trade_entities,
                                  label_fn=trade_type):
            r["rel"] = str(rel)
            if r["fidelity"] < 0:
                passthrough_trades.append(r)
            elif r["fidelity"] >= 1.0:
                full_trades.append(r)
            else:
                partial_trades.append(r)

    # ----- CurrencyConfig -----
    full_curr:    list[dict] = []
    partial_curr: list[dict] = []
    absent_curr:  list[dict] = []
    missing_curr: list[Path] = []

    for orig_path in currency_files:
        rel      = orig_path.relative_to(orig_root)
        out_path = out_root / rel
        if out_path not in out_files_present:
            missing_curr.append(rel)
            continue
        for r in analyse_entities(orig_path, out_path, get_currency_entities):
            r["rel"] = str(rel)
            if r["fidelity"] < 0:
                absent_curr.append(r)
            elif r["fidelity"] >= 1.0:
                full_curr.append(r)
            else:
                partial_curr.append(r)

    # ----- CalendarAdjustments -----
    full_cal:    list[dict] = []
    partial_cal: list[dict] = []
    absent_cal:  list[dict] = []
    missing_cal: list[Path] = []

    for orig_path in calendar_files:
        rel      = orig_path.relative_to(orig_root)
        out_path = out_root / rel
        if out_path not in out_files_present:
            missing_cal.append(rel)
            continue
        for r in analyse_entities(orig_path, out_path, get_calendar_entities):
            r["rel"] = str(rel)
            if r["fidelity"] < 0:
                absent_cal.append(r)
            elif r["fidelity"] >= 1.0:
                full_cal.append(r)
            else:
                partial_cal.append(r)

    # ----- Conventions -----
    full_conv:    list[dict] = []
    partial_conv: list[dict] = []
    absent_conv:  list[dict] = []
    missing_conv: list[Path] = []

    for orig_path in convention_files:
        rel      = orig_path.relative_to(orig_root)
        out_path = out_root / rel
        if out_path not in out_files_present:
            missing_conv.append(rel)
            continue
        for r in analyse_entities(orig_path, out_path, get_convention_entities):
            r["rel"] = str(rel)
            if r["fidelity"] < 0:
                absent_conv.append(r)
            elif r["fidelity"] >= 1.0:
                full_conv.append(r)
            else:
                partial_conv.append(r)

    # ----- Summary report -----
    total_orig = (len(portfolio_files) + len(currency_files)
                  + len(calendar_files) + len(convention_files))
    total_missing = (len(missing_portfolio) + len(missing_curr)
                     + len(missing_cal) + len(missing_conv))

    print()
    print("=== ORE Domain Roundtrip Report ===")
    print(f"Original files:         {total_orig}")
    print(f"  Portfolio:            {len(portfolio_files)}")
    print(f"  CurrencyConfig:       {len(currency_files)}")
    print(f"  CalendarAdjustments:  {len(calendar_files)}")
    print(f"  Conventions:          {len(convention_files)}")
    print(f"Missing outputs:        {total_missing}")

    # Portfolio trades section (keep original detail level).
    total_trades = len(full_trades) + len(partial_trades) + len(passthrough_trades)
    print()
    print(f"Total trades analysed:  {total_trades}")
    print("Trade fidelity:")
    print(f"  Full     (100%):      {len(full_trades)}"
          f"  ({pct(len(full_trades), total_trades)})")
    print(f"  Partial  (<100%):     {len(partial_trades)}"
          f"  ({pct(len(partial_trades), total_trades)})")
    print(f"  Passthrough:          {len(passthrough_trades)}"
          f"  ({pct(len(passthrough_trades), total_trades)})")

    if partial_trades:
        by_type: dict[str, list] = defaultdict(list)
        for r in partial_trades:
            by_type[r["entity_type"]].append(r)

        print()
        print(f"--- Partial fidelity detail ({len(partial_trades)} trades) ---")
        for tt in sorted(by_type):
            entries = by_type[tt]
            avg_fid = sum(e["fidelity"] for e in entries) / len(entries)
            print(f"  {tt}  ({len(entries)} trade(s), avg {avg_fid * 100:.0f}%)")
            for r in entries[:5]:
                print(f"    {r['rel']}  [{r['entity_id']}]  {r['fidelity'] * 100:.0f}%")
                print(f"      missing: {', '.join(sorted(r['missing'])[:10])}"
                      + ("..." if len(r["missing"]) > 10 else ""))
            if len(entries) > 5:
                print(f"    ... and {len(entries) - 5} more")

    if missing_portfolio:
        print()
        print(f"--- Missing portfolio output files ({len(missing_portfolio)}) ---")
        for rel in missing_portfolio[:20]:
            print(f"  MISSING: {rel}")
        if len(missing_portfolio) > 20:
            print(f"  ... and {len(missing_portfolio) - 20} more")

    # Non-portfolio sections.
    print_entity_section("CurrencyConfig",
                         full_curr, partial_curr, absent_curr, missing_curr)
    print_entity_section("CalendarAdjustments",
                         full_cal, partial_cal, absent_cal, missing_cal)
    print_entity_section("Conventions",
                         full_conv, partial_conv, absent_conv, missing_conv)

    print()

    has_problems = bool(
        partial_trades or missing_portfolio
        or partial_curr or missing_curr or absent_curr
        or partial_cal  or missing_cal  or absent_cal
        or partial_conv or missing_conv or absent_conv
    )
    if has_problems and strict:
        print("STRICT MODE: partial or missing outputs found — exiting with code 1",
              file=sys.stderr)
        return 1
    return 0


def main():
    parser = argparse.ArgumentParser(
        description="ORE domain roundtrip check (Thing 3)")
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).parent.parent,
        help="Path to the repository root (default: parent of scripts/)")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit with code 1 on any partial or missing outputs")
    args = parser.parse_args()

    return run_check(args.repo_root, args.strict)


if __name__ == "__main__":
    sys.exit(main())
