#!/usr/bin/env python3
"""
ore_domain_roundtrip_check.py — Thing 3: ORE domain roundtrip check.

Compares committed roundtrip outputs (assets/test_data/domain_roundtrip/)
against the upstream ORE originals (external/ore/examples/) and reports
per-file and per-trade-type fidelity.

The roundtrip outputs are generated by:
  ores.cli ore roundtrip external/ore/examples \\
      --output-dir assets/test_data/domain_roundtrip

Usage:
  python3 scripts/ore_domain_roundtrip_check.py [--repo-root <path>] [--strict]

  --strict: exit with code 1 on any partial or missing outputs.

Exit codes:
  0 — all outputs full (or non-strict mode)
  1 — partial/missing found and --strict was specified
"""

import argparse
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path


# ---------------------------------------------------------------------------
# XML helpers
# ---------------------------------------------------------------------------

def collect_element_names(elem) -> set:
    """Recursively collect all element tag names under an XML element."""
    names = set()
    for node in elem.iter():
        tag = node.tag
        if "}" in tag:
            tag = tag.split("}", 1)[1]
        names.add(tag)
    return names


def parse_xml_safe(path: Path):
    """Return (root, None) on success, (None, error_str) on failure."""
    try:
        return ET.parse(path).getroot(), None
    except ET.ParseError as e:
        return None, str(e)


def get_trades_by_id(root) -> dict:
    """Return {trade_id: <Trade element>} for all <Trade> children of root."""
    trades = {}
    if root is None:
        return trades
    for trade in root.findall("Trade"):
        tid = trade.get("id")
        if tid:
            trades[tid] = trade
    return trades


# ---------------------------------------------------------------------------
# Fidelity analysis
# ---------------------------------------------------------------------------

def trade_type(trade_elem) -> str:
    """Extract <TradeType> text from a <Trade> element, or 'Unknown'."""
    tt = trade_elem.find("TradeType")
    return tt.text.strip() if tt is not None and tt.text else "Unknown"


def analyse_file(orig_path: Path, out_path: Path) -> list:
    """
    Compare one original portfolio file against its roundtrip output.

    Returns a list of dicts, one per trade in the original:
      {
        "trade_id":   str,
        "trade_type": str,
        "fidelity":   float,          # 0.0–1.0; -1.0 means trade absent in output
        "missing":    set[str],       # element names in original but not in output
      }
    """
    orig_root, err = parse_xml_safe(orig_path)
    if err:
        return []

    out_root, err = parse_xml_safe(out_path)
    # out_root may be None if the file is missing; handled below

    orig_trades = get_trades_by_id(orig_root)
    out_trades  = get_trades_by_id(out_root) if out_root is not None else {}

    results = []
    for tid, orig_trade in orig_trades.items():
        orig_elems = collect_element_names(orig_trade)
        tt = trade_type(orig_trade)

        if tid not in out_trades:
            results.append({
                "trade_id":   tid,
                "trade_type": tt,
                "fidelity":   -1.0,          # absent from output
                "missing":    orig_elems,
            })
            continue

        out_elems = collect_element_names(out_trades[tid])
        missing   = orig_elems - out_elems
        fidelity  = (len(orig_elems) - len(missing)) / len(orig_elems) \
                    if orig_elems else 1.0

        results.append({
            "trade_id":   tid,
            "trade_type": tt,
            "fidelity":   fidelity,
            "missing":    missing,
        })

    return results


# ---------------------------------------------------------------------------
# Main check
# ---------------------------------------------------------------------------

def run_check(repo_root: Path, strict: bool) -> int:
    orig_root = repo_root / "external" / "ore" / "examples"
    out_root  = repo_root / "assets" / "test_data" / "domain_roundtrip"

    if not orig_root.exists():
        print(f"ERROR: ORE examples not found: {orig_root}", file=sys.stderr)
        return 1

    # Collect all original portfolio XML files (files containing <Portfolio>).
    # Read only the first 4 KiB — enough to find the root tag without loading
    # large files into memory.
    orig_files: list[Path] = []
    for p in sorted(orig_root.rglob("*.xml")):
        try:
            with p.open("rb") as fh:
                chunk = fh.read(4096)
            if b"<Portfolio>" in chunk:
                orig_files.append(p)
        except OSError:
            pass

    # Collect output files that exist.
    out_files_present: set[Path] = set()
    if out_root.exists():
        out_files_present = {p for p in out_root.rglob("*.xml")}

    total_orig = len(orig_files)
    missing_outputs: list[Path] = []

    # Per-trade stats
    full_trades:        list[tuple[str, str, str]] = []   # (rel_path, trade_id, trade_type)
    partial_trades:     list[tuple[str, str, str, float, set]] = []
    passthrough_trades: list[tuple[str, str, str]] = []

    for orig_path in orig_files:
        rel = orig_path.relative_to(orig_root)
        out_path = out_root / rel

        if out_path not in out_files_present:
            missing_outputs.append(rel)
            continue

        results = analyse_file(orig_path, out_path)
        for r in results:
            rel_str = str(rel)
            if r["fidelity"] < 0:
                passthrough_trades.append((rel_str, r["trade_id"], r["trade_type"]))
            elif r["fidelity"] >= 1.0:
                full_trades.append((rel_str, r["trade_id"], r["trade_type"]))
            else:
                partial_trades.append(
                    (rel_str, r["trade_id"], r["trade_type"],
                     r["fidelity"], r["missing"]))

    total_out  = total_orig - len(missing_outputs)
    total_trades = len(full_trades) + len(partial_trades) + len(passthrough_trades)

    def pct(n, d):
        return f"{n / d * 100:.1f}%" if d else "n/a"

    print()
    print("=== ORE Domain Roundtrip Report ===")
    print(f"Original files:         {total_orig}")
    print(f"Output files:           {total_out}")
    print(f"Missing outputs:        {len(missing_outputs)}"
          "  (non-portfolio or skipped)")
    print()
    print(f"Total trades analysed:  {total_trades}")
    print("Trade fidelity:")
    print(f"  Full     (100%):      {len(full_trades)}"
          f"  ({pct(len(full_trades), total_trades)})")
    print(f"  Partial  (<100%):     {len(partial_trades)}"
          f"  ({pct(len(partial_trades), total_trades)})")
    print(f"  Passthrough:          {len(passthrough_trades)}"
          f"  ({pct(len(passthrough_trades), total_trades)})")

    if partial_trades:
        # Group by trade type for a concise summary.
        by_type: dict[str, list] = defaultdict(list)
        for rel, tid, tt, fid, miss in partial_trades:
            by_type[tt].append((rel, tid, fid, miss))

        print()
        print(f"--- Partial fidelity detail ({len(partial_trades)} trades) ---")
        for tt in sorted(by_type):
            entries = by_type[tt]
            avg_fid = sum(e[2] for e in entries) / len(entries)
            print(f"  {tt}  ({len(entries)} trade(s), avg {avg_fid * 100:.0f}%)")
            # Show up to 5 examples per type.
            for rel, tid, fid, miss in entries[:5]:
                print(f"    {rel}  [{tid}]  {fid * 100:.0f}%")
                print(f"      missing: {', '.join(sorted(miss)[:10])}"
                      + ("..." if len(miss) > 10 else ""))
            if len(entries) > 5:
                print(f"    ... and {len(entries) - 5} more")

    if missing_outputs:
        print()
        print(f"--- Missing output files ({len(missing_outputs)}) ---")
        for rel in missing_outputs[:20]:
            print(f"  MISSING: {rel}")
        if len(missing_outputs) > 20:
            print(f"  ... and {len(missing_outputs) - 20} more")

    print()

    # Passthrough trades are intentionally unmapped trade types whose instruments
    # are not yet handled by any mapper (monostate).  They are expected and do
    # not constitute a CI failure; only partial coverage and missing output files
    # are considered regressions that --strict should catch.
    has_problems = bool(partial_trades or missing_outputs)
    if has_problems and strict:
        print("STRICT MODE: partial or missing outputs found — exiting with code 1",
              file=sys.stderr)
        return 1
    return 0


def main():
    parser = argparse.ArgumentParser(
        description="ORE domain roundtrip check (Thing 3)")
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).parent.parent,
        help="Path to the repository root (default: parent of scripts/)")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit with code 1 on any partial or missing outputs")
    args = parser.parse_args()

    return run_check(args.repo_root, args.strict)


if __name__ == "__main__":
    sys.exit(main())
