/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

/**
 * Trade Types Population Script
 *
 * Seeds the database with all ORE instrument type codes.
 * The list is derived from the oreTradeType enum in domain.hpp / domain.cpp.
 * This script is idempotent.
 */

\echo '--- Trade Types ---'

insert into ores_trading_trade_types_tbl (
    code, tenant_id, version, description,
    product_type, has_options, has_extension,
    modified_by, change_reason_code, change_commentary
) values
    -- Composite / Structured
    ('CompositeTrade',                    ores_iam_system_tenant_id_fn(), 0, 'Composite Trade',
     'composite', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('MultiLegOption',                    ores_iam_system_tenant_id_fn(), 0, 'Multi-Leg Option',
     'composite', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    -- Rates
    ('Swap',                              ores_iam_system_tenant_id_fn(), 0, 'Interest Rate Swap',
     'swap', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CrossCurrencySwap',                 ores_iam_system_tenant_id_fn(), 0, 'Cross Currency Swap',
     'swap', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('ForwardRateAgreement',              ores_iam_system_tenant_id_fn(), 0, 'Forward Rate Agreement',
     'swap', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CapFloor',                          ores_iam_system_tenant_id_fn(), 0, 'Cap or Floor',
     'swap', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('Swaption',                          ores_iam_system_tenant_id_fn(), 0, 'Swaption',
     'swap', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FlexiSwap',                         ores_iam_system_tenant_id_fn(), 0, 'Flexi Swap',
     'swap', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('BalanceGuaranteedSwap',             ores_iam_system_tenant_id_fn(), 0, 'Balance Guaranteed Swap',
     'swap', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CallableSwap',                      ores_iam_system_tenant_id_fn(), 0, 'Callable Swap',
     'swap', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('KnockOutSwap',                      ores_iam_system_tenant_id_fn(), 0, 'Knock-Out Swap',
     'swap', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('RiskParticipationAgreement',        ores_iam_system_tenant_id_fn(), 0, 'Risk Participation Agreement',
     'swap', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    -- Inflation
    ('InflationSwap',                     ores_iam_system_tenant_id_fn(), 0, 'Inflation Swap',
     'swap', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    -- FX
    ('FxForward',                         ores_iam_system_tenant_id_fn(), 0, 'FX Forward',
     'fx', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxSwap',                            ores_iam_system_tenant_id_fn(), 0, 'FX Swap',
     'fx', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxOption',                          ores_iam_system_tenant_id_fn(), 0, 'FX Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxDigitalOption',                   ores_iam_system_tenant_id_fn(), 0, 'FX Digital Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxAverageForward',                  ores_iam_system_tenant_id_fn(), 0, 'FX Average Forward',
     'fx', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxAsianOption',                     ores_iam_system_tenant_id_fn(), 0, 'FX Asian Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxBarrierOption',                   ores_iam_system_tenant_id_fn(), 0, 'FX Barrier Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxDoubleBarrierOption',             ores_iam_system_tenant_id_fn(), 0, 'FX Double Barrier Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxEuropeanBarrierOption',           ores_iam_system_tenant_id_fn(), 0, 'FX European Barrier Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxWindowBarrierOption',             ores_iam_system_tenant_id_fn(), 0, 'FX Window Barrier Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxGenericBarrierOption',            ores_iam_system_tenant_id_fn(), 0, 'FX Generic Barrier Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxKIKOBarrierOption',               ores_iam_system_tenant_id_fn(), 0, 'FX Knock-In Knock-Out Barrier Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxTouchOption',                     ores_iam_system_tenant_id_fn(), 0, 'FX Touch Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxDoubleTouchOption',               ores_iam_system_tenant_id_fn(), 0, 'FX Double Touch Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxDigitalBarrierOption',            ores_iam_system_tenant_id_fn(), 0, 'FX Digital Barrier Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxVarianceSwap',                    ores_iam_system_tenant_id_fn(), 0, 'FX Variance Swap',
     'fx', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxPairwiseVarianceSwap',            ores_iam_system_tenant_id_fn(), 0, 'FX Pairwise Variance Swap',
     'fx', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxBasketVarianceSwap',              ores_iam_system_tenant_id_fn(), 0, 'FX Basket Variance Swap',
     'fx', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxAccumulator',                     ores_iam_system_tenant_id_fn(), 0, 'FX Accumulator',
     'fx', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxTaRF',                            ores_iam_system_tenant_id_fn(), 0, 'FX Target Redemption Forward',
     'fx', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxWorstOfBasketSwap',               ores_iam_system_tenant_id_fn(), 0, 'FX Worst-Of Basket Swap',
     'fx', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxBestEntryOption',                 ores_iam_system_tenant_id_fn(), 0, 'FX Best Entry Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxBasketOption',                    ores_iam_system_tenant_id_fn(), 0, 'FX Basket Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxRainbowOption',                   ores_iam_system_tenant_id_fn(), 0, 'FX Rainbow Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('FxStrikeResettableOption',          ores_iam_system_tenant_id_fn(), 0, 'FX Strike Resettable Option',
     'fx', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    -- Credit
    ('CreditDefaultSwap',                 ores_iam_system_tenant_id_fn(), 0, 'Credit Default Swap',
     'credit', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CreditDefaultSwapOption',           ores_iam_system_tenant_id_fn(), 0, 'Credit Default Swap Option',
     'credit', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('IndexCreditDefaultSwap',            ores_iam_system_tenant_id_fn(), 0, 'Index Credit Default Swap',
     'credit', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('IndexCreditDefaultSwapOption',      ores_iam_system_tenant_id_fn(), 0, 'Index Credit Default Swap Option',
     'credit', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('SyntheticCDO',                      ores_iam_system_tenant_id_fn(), 0, 'Synthetic CDO',
     'credit', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CreditLinkedSwap',                  ores_iam_system_tenant_id_fn(), 0, 'Credit Linked Swap',
     'credit', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CBO',                               ores_iam_system_tenant_id_fn(), 0, 'Collateralised Bond Obligation',
     'credit', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    -- Fixed Income / Bond
    ('Bond',                              ores_iam_system_tenant_id_fn(), 0, 'Fixed Income Bond',
     'bond', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('ForwardBond',                       ores_iam_system_tenant_id_fn(), 0, 'Forward Bond',
     'bond', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('BondFuture',                        ores_iam_system_tenant_id_fn(), 0, 'Bond Future',
     'bond', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('BondOption',                        ores_iam_system_tenant_id_fn(), 0, 'Bond Option',
     'bond', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('BondRepo',                          ores_iam_system_tenant_id_fn(), 0, 'Bond Repo',
     'bond', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('BondTRS',                           ores_iam_system_tenant_id_fn(), 0, 'Bond Total Return Swap',
     'bond', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('BondPosition',                      ores_iam_system_tenant_id_fn(), 0, 'Bond Position',
     'bond', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CallableBond',                      ores_iam_system_tenant_id_fn(), 0, 'Callable Bond',
     'bond', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('ConvertibleBond',                   ores_iam_system_tenant_id_fn(), 0, 'Convertible Bond',
     'bond', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('Ascot',                             ores_iam_system_tenant_id_fn(), 0, 'Asset Swapped Convertible Option Transaction',
     'bond', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    -- Equity
    ('EquityOption',                      ores_iam_system_tenant_id_fn(), 0, 'Equity Option',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityFutureOption',                ores_iam_system_tenant_id_fn(), 0, 'Equity Future Option',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityAsianOption',                 ores_iam_system_tenant_id_fn(), 0, 'Equity Asian Option',
     'equity', true, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityBarrierOption',               ores_iam_system_tenant_id_fn(), 0, 'Equity Barrier Option',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityDoubleBarrierOption',         ores_iam_system_tenant_id_fn(), 0, 'Equity Double Barrier Option',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityEuropeanBarrierOption',       ores_iam_system_tenant_id_fn(), 0, 'Equity European Barrier Option',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityWindowBarrierOption',         ores_iam_system_tenant_id_fn(), 0, 'Equity Window Barrier Option',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityGenericBarrierOption',        ores_iam_system_tenant_id_fn(), 0, 'Equity Generic Barrier Option',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityTouchOption',                 ores_iam_system_tenant_id_fn(), 0, 'Equity Touch Option',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityDoubleTouchOption',           ores_iam_system_tenant_id_fn(), 0, 'Equity Double Touch Option',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityDigitalOption',               ores_iam_system_tenant_id_fn(), 0, 'Equity Digital Option',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityForward',                     ores_iam_system_tenant_id_fn(), 0, 'Equity Forward',
     'equity', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquitySwap',                        ores_iam_system_tenant_id_fn(), 0, 'Equity Swap',
     'equity', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityVarianceSwap',                ores_iam_system_tenant_id_fn(), 0, 'Equity Variance Swap',
     'equity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityPairwiseVarianceSwap',        ores_iam_system_tenant_id_fn(), 0, 'Equity Pairwise Variance Swap',
     'equity', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityBasketVarianceSwap',          ores_iam_system_tenant_id_fn(), 0, 'Equity Basket Variance Swap',
     'equity', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityCliquetOption',               ores_iam_system_tenant_id_fn(), 0, 'Equity Cliquet Option',
     'equity', true, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityAccumulator',                 ores_iam_system_tenant_id_fn(), 0, 'Equity Accumulator',
     'equity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityTaRF',                        ores_iam_system_tenant_id_fn(), 0, 'Equity Target Redemption Forward',
     'equity', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityWorstOfBasketSwap',           ores_iam_system_tenant_id_fn(), 0, 'Equity Worst-Of Basket Swap',
     'equity', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityBestEntryOption',             ores_iam_system_tenant_id_fn(), 0, 'Equity Best Entry Option',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityBasketOption',                ores_iam_system_tenant_id_fn(), 0, 'Equity Basket Option',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityRainbowOption',               ores_iam_system_tenant_id_fn(), 0, 'Equity Rainbow Option',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityOutperformanceOption',        ores_iam_system_tenant_id_fn(), 0, 'Equity Outperformance Option',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityStrikeResettableOption',      ores_iam_system_tenant_id_fn(), 0, 'Equity Strike Resettable Option',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('TotalReturnSwap',                   ores_iam_system_tenant_id_fn(), 0, 'Total Return Swap',
     'equity', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('ContractForDifference',             ores_iam_system_tenant_id_fn(), 0, 'Contract for Difference',
     'equity', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityPosition',                    ores_iam_system_tenant_id_fn(), 0, 'Equity Position',
     'equity', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EquityOptionPosition',              ores_iam_system_tenant_id_fn(), 0, 'Equity Option Position',
     'equity', true, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    -- Commodity
    ('CommodityForward',                  ores_iam_system_tenant_id_fn(), 0, 'Commodity Forward',
     'commodity', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityOption',                   ores_iam_system_tenant_id_fn(), 0, 'Commodity Option',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityDigitalOption',            ores_iam_system_tenant_id_fn(), 0, 'Commodity Digital Option',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityDigitalAveragePriceOption', ores_iam_system_tenant_id_fn(), 0, 'Commodity Digital Average Price Option',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityAsianOption',              ores_iam_system_tenant_id_fn(), 0, 'Commodity Asian Option',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityAveragePriceOption',       ores_iam_system_tenant_id_fn(), 0, 'Commodity Average Price Option',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommoditySpreadOption',             ores_iam_system_tenant_id_fn(), 0, 'Commodity Spread Option',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityOptionStrip',              ores_iam_system_tenant_id_fn(), 0, 'Commodity Option Strip',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommoditySwap',                     ores_iam_system_tenant_id_fn(), 0, 'Commodity Swap',
     'commodity', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommoditySwaption',                 ores_iam_system_tenant_id_fn(), 0, 'Commodity Swaption',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityVarianceSwap',             ores_iam_system_tenant_id_fn(), 0, 'Commodity Variance Swap',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityPairwiseVarianceSwap',     ores_iam_system_tenant_id_fn(), 0, 'Commodity Pairwise Variance Swap',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityBasketVarianceSwap',       ores_iam_system_tenant_id_fn(), 0, 'Commodity Basket Variance Swap',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityAccumulator',              ores_iam_system_tenant_id_fn(), 0, 'Commodity Accumulator',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityTaRF',                     ores_iam_system_tenant_id_fn(), 0, 'Commodity Target Redemption Forward',
     'commodity', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityWorstOfBasketSwap',        ores_iam_system_tenant_id_fn(), 0, 'Commodity Worst-Of Basket Swap',
     'commodity', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityBestEntryOption',          ores_iam_system_tenant_id_fn(), 0, 'Commodity Best Entry Option',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityWindowBarrierOption',      ores_iam_system_tenant_id_fn(), 0, 'Commodity Window Barrier Option',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityGenericBarrierOption',     ores_iam_system_tenant_id_fn(), 0, 'Commodity Generic Barrier Option',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityBasketOption',             ores_iam_system_tenant_id_fn(), 0, 'Commodity Basket Option',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityRainbowOption',            ores_iam_system_tenant_id_fn(), 0, 'Commodity Rainbow Option',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityStrikeResettableOption',   ores_iam_system_tenant_id_fn(), 0, 'Commodity Strike Resettable Option',
     'commodity', false, true,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('CommodityPosition',                 ores_iam_system_tenant_id_fn(), 0, 'Commodity Position',
     'commodity', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    -- Generic / Positions
    ('CashPosition',                      ores_iam_system_tenant_id_fn(), 0, 'Cash Position',
     'equity', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    -- Scripted / Exotic payoffs
    ('ScriptedTrade',                     ores_iam_system_tenant_id_fn(), 0, 'Scripted Trade (ORE generic payoff engine)',
     'scripted', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('Autocallable_01',                   ores_iam_system_tenant_id_fn(), 0, 'Autocallable (variant 01)',
     'scripted', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('DoubleDigitalOption',               ores_iam_system_tenant_id_fn(), 0, 'Double Digital Option',
     'scripted', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('EuropeanOptionBarrier',             ores_iam_system_tenant_id_fn(), 0, 'European Option with Barrier',
     'scripted', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types'),
    ('PerformanceOption_01',              ores_iam_system_tenant_id_fn(), 0, 'Performance Option (variant 01)',
     'scripted', false, false,
     'ores_trading_service', 'system.initial_load', 'Seed trade types')
on conflict (tenant_id, code)
where valid_to = ores_utility_infinity_timestamp_fn()
do nothing;

select 'Trade Types' as entity, count(*) as count
from ores_trading_trade_types_tbl
where valid_to = ores_utility_infinity_timestamp_fn();
