#ifndef ORES_WORKFLOW_API_EXPORT_HPP
#define ORES_WORKFLOW_API_EXPORT_HPP

#include <boost/config.hpp>

#ifdef ORES_WORKFLOW_API_LIBRARY
#    define ORES_WORKFLOW_API_EXPORT BOOST_SYMBOL_EXPORT
#else
#    define ORES_WORKFLOW_API_EXPORT BOOST_SYMBOL_IMPORT
#endif

#endif
