/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * Copyright (C) 2025 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

/**
 * Generate Teardown Instances Script
 *
 * Queries the admin database for all instance databases and generates
 * an explicit teardown script that can be reviewed and committed to git.
 *
 * The generated script will:
 *   1. Connect to each instance database
 *   2. Run drop/drop.sql to drop all schema objects (validates drop logic)
 *   3. Connect back to postgres
 *   4. Drop the database
 *
 * USAGE:
 *   cd projects/ores.sql
 *   psql -U postgres -f admin/admin_teardown_instances_generate.sql
 *
 * OUTPUT:
 *   Creates/overwrites teardown_instances.sql with explicit teardown sequences.
 *
 * WORKFLOW:
 *   1. Run this script to generate teardown_instances.sql
 *   2. Review the generated file
 *   3. Commit to git (for production traceability)
 *   4. Run teardown_all.sql which will execute it
 *
 * PREREQUISITES:
 *   - ores_admin database must exist
 *   - Run from projects/ores.sql directory
 */

\set ON_ERROR_STOP on

\echo ''
\echo 'Generating teardown_instances.sql...'
\echo ''

-- Connect to admin database to query instance list
\c ores_admin

-- Configure output formatting
\pset tuples_only on
\pset format unaligned

-- Write to teardown_instances.sql
\o teardown_instances.sql

\qecho /* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*- */
\qecho /*
\qecho  * GENERATED FILE - Instance Database Teardown
\qecho  *
\qecho  * This file was generated by admin/admin_teardown_instances_generate.sql
\qecho  * Review carefully before running teardown_all.sql
\qecho  *
\qecho  * For each instance database, this script:
\qecho  *   1. Connects to the database
\qecho  *   2. Runs drop/drop.sql to drop all schema objects
\qecho  *   3. Connects back to postgres
\qecho  *   4. Drops the database
\qecho  *
\qecho  * To regenerate:
\qecho  *   psql -U postgres -f admin/admin_teardown_instances_generate.sql
\qecho  */
\qecho

select format(E'-- Instance: %s\n\\echo ''Dropping schema objects in %s...''\n\\c %I\n\\ir drop/drop.sql\n\\c postgres\ndrop database if exists %I;\n',
    database_name, database_name, database_name, database_name)
from admin_ores_instance_databases_view
order by database_name;

-- Close output file
\o

-- Reset formatting
\pset tuples_only off
\pset format aligned

-- Show what was generated
\echo 'Generated teardown_instances.sql with the following databases:'
\echo ''

select database_name from admin_ores_instance_databases_view order by database_name;

\echo ''
\echo '=============================================='
\echo 'teardown_instances.sql generated successfully!'
\echo '=============================================='
\echo ''
\echo 'Next steps:'
\echo '  1. Review: cat teardown_instances.sql'
\echo '  2. Commit: git add teardown_instances.sql && git commit'
\echo '  3. Execute: psql -U postgres -f teardown_all.sql'
\echo ''
