' -*- mode: plantuml; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
'
' Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
'
' This program is free software; you can redistribute it and/or modify it under
' the terms of the GNU General Public License as published by the Free Software
' Foundation; either version 3 of the License, or (at your option) any later
' version.
'
' This program is distributed in the hope that it will be useful, but WITHOUT
' ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
' FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with
' this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
' Street, Fifth Floor, Boston, MA 02110-1301, USA.
'
@startuml

title Client Credentials: the token provider inside one service


hide empty description
[*] --> waiting : the service starts
waiting : the service subscribes\nits own subjects first
waiting --> logging_in : subscriptions ready
logging_in --> valid : IAM returns a token
logging_in --> backing_off : IAM unreachable
backing_off --> logging_in : after a delay
logging_in --> refused : bad account or password
refused --> [*] : log an error;\nthe work that needs it does not start
valid --> renewing : 80% of the lifetime used
valid --> renewing : a call answered token_expired
renewing --> valid : a new token
renewing --> backing_off : IAM unreachable
valid --> valid : a call uses the token
@enduml
