/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * Copyright (C) 2025 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */
#ifndef ORES_TELEMETRY_DOMAIN_TELEMETRY_SOURCE_HPP
#define ORES_TELEMETRY_DOMAIN_TELEMETRY_SOURCE_HPP

#include <string_view>

namespace ores::telemetry::domain {

/**
 * @brief Source type for telemetry log entries.
 *
 * Distinguishes between logs submitted by clients (via the binary protocol)
 * and logs generated by the server itself.
 */
enum class telemetry_source {
    /**
     * @brief Log entry from a client application.
     *
     * Examples: ores.qt, ores.comms.shell
     */
    client = 0,

    /**
     * @brief Log entry from the server itself.
     *
     * Example: ores.comms.service
     */
    server = 1
};

/**
 * @brief Converts a telemetry_source to its string representation.
 */
[[nodiscard]] constexpr std::string_view to_string(telemetry_source s) {
    switch (s) {
        case telemetry_source::client: return "client";
        case telemetry_source::server: return "server";
        default: return "unknown";
    }
}

/**
 * @brief Converts a string to telemetry_source.
 */
[[nodiscard]] constexpr telemetry_source
telemetry_source_from_string(std::string_view s) {
    if (s == "client") return telemetry_source::client;
    if (s == "server") return telemetry_source::server;
    return telemetry_source::client; // Default fallback
}

}

#endif
