# -*- mode: cmake; cmake-tab-width: 4; indent-tabs-mode: nil -*-
#
# Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
set(files
    "BadgeCache.cpp"
    "BadgeComboHelper.cpp"
    "BadgeLabelUtils.cpp"
    "CalendarAssignmentWidget.cpp"
    "ChangeReasonCache.cpp"
    "ChangeReasonDialog.cpp"
    "ChildEntityTableWidget.cpp"
    "ClientDatasetBundleModel.cpp"
    "ClientManager.cpp"
    "ClientManagerExportPortfolio.cpp"
    "ClientManagerTradeInstrument.cpp"
    "ClientManagerTrades.cpp"
    "ClientResultItemDelegate.cpp"
    "ClientResultModel.cpp"
    "ColourSwatchHelper.cpp"
    "CronEditorDialog.cpp"
    "CronExpressionWidget.cpp"
    "DelegatePaintUtils.cpp"
    "DetachableMdiSubWindow.cpp"
    "DetailDialogBase.cpp"
    "EntityController.cpp"
    "EntityItemDelegate.cpp"
    "EntityListMdiWindow.cpp"
    "FlagIconHelper.cpp"
    "FlagSelectorDialog.cpp"
    "HierarchyTreeWidget.cpp"
    "HistoryDialog.cpp"
    "HistoryDialogBase.cpp"
    "HostDisplayNameCache.cpp"
    "IconUtils.cpp"
    "ImageCache.cpp"
    "ImportEntityDialog.cpp"
    "LeiEntityPicker.cpp"
    "LookupFetcher.cpp"
    "MdiAreaWithBackground.cpp"
    "MdiUtils.cpp"
    "MessageBoxHelper.cpp"
    "OreBadgeComboBox.cpp"
    "OreCalendarComboBox.cpp"
    "OreCurrencyComboBox.cpp"
    "OrgDocViewerWindow.cpp"
    "PaginationWidget.cpp"
    "PartyPickerDialog.cpp"
    "PasswordMatchIndicator.cpp"
    "PluginBase.cpp"
    "PluginRegistry.cpp"
    "ProvenanceWidget.cpp"
    "QaValidationRunnerWidget.cpp"
    "RecencyPulseManager.cpp"
    "RelativeTimeHelper.cpp"
    "SettingGatedActionController.cpp"
    "TimestampFormat.cpp"
    "UiPersistence.cpp"
    "WorkspaceSelector.cpp"
)

# Headers must be listed for AUTOMOC to find Q_OBJECT declarations.
set(HEADERS
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/AbstractClientModel.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/BadgeCache.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/BadgeComboHelper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/BadgeLabelUtils.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/BoolYesNoLabel.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/CalendarAssignmentWidget.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/ChangeReasonCache.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/ChangeReasonDialog.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/ChildEntityTableWidget.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/ClientDatasetBundleModel.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/ClientManager.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/ClientResultItemDelegate.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/ClientResultModel.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/ColorConstants.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/ColourSwatchHelper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/ColumnMetadata.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/CronEditorDialog.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/CronExpressionWidget.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/CronFieldWidget.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/DelegatePaintUtils.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/DetachableMdiSubWindow.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/DetailDialogBase.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/DialogStyles.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/DynamicComboSetup.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/EntityController.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/EntityItemDelegate.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/EntityListMdiWindow.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/ExceptionHelper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/FlagIconHelper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/FlagSelectorDialog.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/HierarchyTreeWidget.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/HistoryDialog.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/HistoryDialogBase.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/HostDisplayNameCache.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/IBusinessUnitBrowser.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/IPlugin.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/IconUtils.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/ImageCache.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/ImportEntityDialog.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/LeiEntityPicker.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/LookupFetcher.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/MdiAreaWithBackground.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/MdiUtils.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/MessageBoxHelper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/OreBadgeComboBox.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/OreCalendarComboBox.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/OreCurrencyComboBox.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/OrgDocViewerWindow.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/PaginationWidget.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/PartyPickerDialog.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/PasswordMatchIndicator.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/PluginBase.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/PluginRegistry.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/ProvenanceWidget.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/QaValidationRunnerWidget.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/RecencyPulseManager.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/RecencyTracker.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/RelativeTimeHelper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/SettingGatedActionController.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/TextUtils.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/TimestampFormat.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/UiPersistence.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/WatermarkChartView.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/WidgetUtils.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/WorkspaceContext.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/WorkspaceSelector.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/export.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.qt/plugin_context.hpp"
)
