/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */
#include "ores.refdata.core/messaging/registrar.hpp"
#include "ores.nats/service/client.hpp"
#include "ores.security/jwt/jwt_authenticator.hpp"

// Per-entity sub-registrars (generated by the nats-sub-registrar facet).
#include "ores.refdata.core/messaging/asset_class_code_registrar.hpp"
#include "ores.refdata.core/messaging/book_purpose_type_registrar.hpp"
#include "ores.refdata.core/messaging/book_registrar.hpp"
#include "ores.refdata.core/messaging/book_status_registrar.hpp"
#include "ores.refdata.core/messaging/business_day_convention_type_registrar.hpp"
#include "ores.refdata.core/messaging/business_unit_registrar.hpp"
#include "ores.refdata.core/messaging/cds_convention_registrar.hpp"
#include "ores.refdata.core/messaging/contact_type_registrar.hpp"
#include "ores.refdata.core/messaging/counterparty_identifier_registrar.hpp"
#include "ores.refdata.core/messaging/counterparty_registrar.hpp"
#include "ores.refdata.core/messaging/country_registrar.hpp"
#include "ores.refdata.core/messaging/crm_driver_pair_registrar.hpp"
#include "ores.refdata.core/messaging/crm_enabled_derived_pair_registrar.hpp"
#include "ores.refdata.core/messaging/crm_topology_config_registrar.hpp"
#include "ores.refdata.core/messaging/currency_market_tier_registrar.hpp"
#include "ores.refdata.core/messaging/currency_pair_classification_registrar.hpp"
#include "ores.refdata.core/messaging/currency_pair_convention_registrar.hpp"
#include "ores.refdata.core/messaging/currency_pair_registrar.hpp"
#include "ores.refdata.core/messaging/currency_registrar.hpp"
#include "ores.refdata.core/messaging/day_count_fraction_type_registrar.hpp"
#include "ores.refdata.core/messaging/instrument_code_registrar.hpp"
#include "ores.refdata.core/messaging/deposit_convention_registrar.hpp"
#include "ores.refdata.core/messaging/fra_convention_registrar.hpp"
#include "ores.refdata.core/messaging/ibor_index_convention_registrar.hpp"
#include "ores.refdata.core/messaging/ledger_feed_type_registrar.hpp"
#include "ores.refdata.core/messaging/monetary_nature_registrar.hpp"
#include "ores.refdata.core/messaging/ois_convention_registrar.hpp"
#include "ores.refdata.core/messaging/overnight_index_convention_registrar.hpp"
#include "ores.refdata.core/messaging/party_id_scheme_registrar.hpp"
#include "ores.refdata.core/messaging/party_identifier_registrar.hpp"
#include "ores.refdata.core/messaging/party_registrar.hpp"
#include "ores.refdata.core/messaging/party_status_registrar.hpp"
#include "ores.refdata.core/messaging/party_type_registrar.hpp"
#include "ores.refdata.core/messaging/portfolio_registrar.hpp"
#include "ores.refdata.core/messaging/purpose_type_registrar.hpp"
#include "ores.refdata.core/messaging/regulatory_book_type_registrar.hpp"
#include "ores.refdata.core/messaging/rounding_type_registrar.hpp"
#include "ores.refdata.core/messaging/swap_convention_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_anchor_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_convention_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_kind_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_resolution_algorithm_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_unit_registrar.hpp"
#include "ores.refdata.core/messaging/zero_convention_registrar.hpp"

// tenor_convention_resolution is a junction: codegen doesn't generate a
// service/protocol/handler/sub-registrar for it (see the story on adding
// junction C++ support). Hand-authored, read-only (list only), wired
// inline below alongside the other no-sub-registrar entities.
#include "ores.refdata.api/messaging/tenor_convention_resolution_protocol.hpp"
#include "ores.refdata.core/messaging/tenor_convention_resolution_handler.hpp"

// Entities without a per-entity sub-registrar: asset_class, business_centre
// and business_unit_type have no codegen model; party_contact /
// counterparty_contact use *_contact_handler against *_contact_information
// protocols (name mismatch); publish_from_dq is a bespoke multi-subject
// workflow handler. These stay wired inline below.
#include "ores.refdata.api/messaging/asset_class_protocol.hpp"
#include "ores.refdata.api/messaging/business_centre_protocol.hpp"
#include "ores.refdata.api/messaging/business_unit_type_protocol.hpp"
#include "ores.refdata.api/messaging/counterparty_contact_information_protocol.hpp"
#include "ores.refdata.api/messaging/party_contact_information_protocol.hpp"
#include "ores.refdata.core/messaging/asset_class_handler.hpp"
#include "ores.refdata.core/messaging/business_centre_handler.hpp"
#include "ores.refdata.core/messaging/business_unit_type_handler.hpp"
#include "ores.refdata.core/messaging/counterparty_contact_handler.hpp"
#include "ores.refdata.core/messaging/party_contact_handler.hpp"
#include "ores.refdata.core/messaging/publish_from_dq_handler.hpp"

// Generic history.v1.get subject.
#include "ores.history.api/service/version_builder.hpp"
#include "ores.history.core/messaging/registrar.hpp"
#include "ores.history.core/service/dispatch_registry.hpp"
#include "ores.refdata.api/domain/country.hpp"
#include "ores.refdata.api/domain/currency.hpp"
#include "ores.refdata.api/domain/book.hpp"
#include "ores.refdata.api/domain/book_purpose_type.hpp"
#include "ores.refdata.api/domain/book_status.hpp"
#include "ores.refdata.api/domain/business_centre.hpp"
#include "ores.refdata.api/domain/business_day_convention_type.hpp"
#include "ores.refdata.api/domain/calendar.hpp"
#include "ores.refdata.api/domain/cds_convention.hpp"
#include "ores.refdata.api/domain/contact_type.hpp"
#include "ores.refdata.api/domain/crm_driver_pair.hpp"
#include "ores.refdata.api/domain/crm_enabled_derived_pair.hpp"
#include "ores.refdata.api/domain/crm_topology_config.hpp"
#include "ores.refdata.api/domain/currency_group.hpp"
#include "ores.refdata.api/domain/currency_pair.hpp"
#include "ores.refdata.api/domain/currency_pair_classification.hpp"
#include "ores.refdata.api/domain/deposit_convention.hpp"
#include "ores.refdata.api/domain/fra_convention.hpp"
#include "ores.refdata.api/domain/ibor_index_convention.hpp"
#include "ores.refdata.api/domain/ois_convention.hpp"
#include "ores.refdata.api/domain/overnight_index_convention.hpp"
#include "ores.refdata.api/domain/swap_convention.hpp"
#include "ores.refdata.api/domain/tenor.hpp"
#include "ores.refdata.api/domain/tenor_convention.hpp"
#include "ores.refdata.api/domain/zero_convention.hpp"
#include "ores.refdata.core/presentation/book_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/book_purpose_type_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/book_status_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/business_centre_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/business_day_convention_type_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/calendar_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/cds_convention_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/contact_type_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/country_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/crm_driver_pair_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/crm_enabled_derived_pair_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/crm_topology_config_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/currency_group_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/currency_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/currency_pair_classification_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/currency_pair_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/deposit_convention_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/fra_convention_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/ibor_index_convention_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/ois_convention_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/overnight_index_convention_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/swap_convention_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/tenor_convention_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/tenor_history_field_mapper.hpp"
#include "ores.refdata.core/presentation/zero_convention_history_field_mapper.hpp"
#include "ores.refdata.core/service/book_purpose_type_service.hpp"
#include "ores.refdata.core/service/book_service.hpp"
#include "ores.refdata.core/service/book_status_service.hpp"
#include "ores.refdata.core/service/business_centre_service.hpp"
#include "ores.refdata.core/service/business_day_convention_type_service.hpp"
#include "ores.refdata.core/service/calendar_service.hpp"
#include "ores.refdata.core/service/cds_convention_service.hpp"
#include "ores.refdata.core/service/contact_type_service.hpp"
#include "ores.refdata.core/service/country_service.hpp"
#include "ores.refdata.core/service/crm_driver_pair_service.hpp"
#include "ores.refdata.core/service/crm_enabled_derived_pair_service.hpp"
#include "ores.refdata.core/service/crm_topology_config_service.hpp"
#include "ores.refdata.core/service/currency_group_service.hpp"
#include "ores.refdata.core/service/currency_pair_classification_service.hpp"
#include "ores.refdata.core/service/currency_pair_service.hpp"
#include "ores.refdata.core/service/currency_service.hpp"
#include "ores.refdata.core/service/deposit_convention_service.hpp"
#include "ores.refdata.core/service/fra_convention_service.hpp"
#include "ores.refdata.core/service/ibor_index_convention_service.hpp"
#include "ores.refdata.core/service/ois_convention_service.hpp"
#include "ores.refdata.core/service/overnight_index_convention_service.hpp"
#include "ores.refdata.core/service/swap_convention_service.hpp"
#include "ores.refdata.core/service/tenor_convention_service.hpp"
#include "ores.refdata.core/service/tenor_service.hpp"
#include "ores.refdata.core/service/zero_convention_service.hpp"
#include <array>
#include <iterator>
#include <memory>
#include <optional>

namespace ores::refdata::messaging {

namespace {
static constexpr std::string_view queue_group = "ores.refdata.service";

// Function-local static: must outlive the history.v1.get subscription
// (see ores::history::messaging::register_history_handlers's doc), and
// register_handlers is only ever called once per service process.
ores::history::service::dispatch_registry& history_registry() {
    static ores::history::service::dispatch_registry instance;
    return instance;
}
} // namespace

std::vector<ores::nats::service::subscription>
registrar::register_handlers(ores::nats::service::client& nats,
                             ores::database::context ctx,
                             std::optional<ores::security::jwt::jwt_authenticator> verifier) {
    std::vector<ores::nats::service::subscription> subs;

    // ----------------------------------------------------------------
    // Per-entity sub-registrars. Each register_<entity>_handlers() wires
    // that entity's subjects to its own handler and returns the resulting
    // subscriptions, which we take ownership of here.
    // ----------------------------------------------------------------
    const auto append = [&subs](std::vector<ores::nats::service::subscription> s) {
        subs.insert(
            subs.end(), std::make_move_iterator(s.begin()), std::make_move_iterator(s.end()));
    };

    append(register_asset_class_code_handlers(nats, ctx, verifier));
    append(register_book_handlers(nats, ctx, verifier));
    append(register_book_purpose_type_handlers(nats, ctx, verifier));
    append(register_book_status_handlers(nats, ctx, verifier));
    append(register_business_day_convention_type_handlers(nats, ctx, verifier));
    append(register_business_unit_handlers(nats, ctx, verifier));
    append(register_cds_convention_handlers(nats, ctx, verifier));
    append(register_contact_type_handlers(nats, ctx, verifier));
    append(register_counterparty_handlers(nats, ctx, verifier));
    append(register_counterparty_identifier_handlers(nats, ctx, verifier));
    append(register_country_handlers(nats, ctx, verifier));
    append(register_crm_driver_pair_handlers(nats, ctx, verifier));
    append(register_crm_enabled_derived_pair_handlers(nats, ctx, verifier));
    append(register_crm_topology_config_handlers(nats, ctx, verifier));
    append(register_currency_handlers(nats, ctx, verifier));
    append(register_currency_market_tier_handlers(nats, ctx, verifier));
    append(register_currency_pair_classification_handlers(nats, ctx, verifier));
    append(register_currency_pair_convention_handlers(nats, ctx, verifier));
    append(register_currency_pair_handlers(nats, ctx, verifier));
    append(register_day_count_fraction_type_handlers(nats, ctx, verifier));
    append(register_instrument_code_handlers(nats, ctx, verifier));
    append(register_deposit_convention_handlers(nats, ctx, verifier));
    append(register_fra_convention_handlers(nats, ctx, verifier));
    append(register_ibor_index_convention_handlers(nats, ctx, verifier));
    append(register_ledger_feed_type_handlers(nats, ctx, verifier));
    append(register_monetary_nature_handlers(nats, ctx, verifier));
    append(register_ois_convention_handlers(nats, ctx, verifier));
    append(register_overnight_index_convention_handlers(nats, ctx, verifier));
    append(register_party_handlers(nats, ctx, verifier));
    append(register_party_id_scheme_handlers(nats, ctx, verifier));
    append(register_party_identifier_handlers(nats, ctx, verifier));
    append(register_party_status_handlers(nats, ctx, verifier));
    append(register_party_type_handlers(nats, ctx, verifier));
    append(register_portfolio_handlers(nats, ctx, verifier));
    append(register_purpose_type_handlers(nats, ctx, verifier));
    append(register_regulatory_book_type_handlers(nats, ctx, verifier));
    append(register_rounding_type_handlers(nats, ctx, verifier));
    append(register_swap_convention_handlers(nats, ctx, verifier));
    append(register_tenor_handlers(nats, ctx, verifier));
    append(register_tenor_anchor_handlers(nats, ctx, verifier));
    append(register_tenor_convention_handlers(nats, ctx, verifier));
    append(register_tenor_kind_handlers(nats, ctx, verifier));
    append(register_tenor_unit_handlers(nats, ctx, verifier));
    append(register_tenor_resolution_algorithm_handlers(nats, ctx, verifier));
    append(register_zero_convention_handlers(nats, ctx, verifier));

    // ----------------------------------------------------------------
    // Tenor convention resolutions (junction — no codegen-generated
    // service/protocol/handler/sub-registrar; hand-authored, read-only).
    // ----------------------------------------------------------------
    {
        auto h = std::make_shared<tenor_convention_resolution_handler>(nats, ctx, verifier);
        subs.push_back(
            nats.queue_subscribe(get_tenor_convention_resolutions_request::nats_subject,
                                 queue_group,
                                 [h](ores::nats::message msg) { h->list(std::move(msg)); }));
    }

    // ----------------------------------------------------------------
    // Party contacts (party_contact_handler serves the
    // party_contact_information protocol — no matching sub-registrar).
    // ----------------------------------------------------------------
    {
        auto h = std::make_shared<party_contact_handler>(nats, ctx, verifier);
        subs.push_back(
            nats.queue_subscribe(get_party_contact_informations_request::nats_subject,
                                 queue_group,
                                 [h](ores::nats::message msg) { h->list(std::move(msg)); }));
        subs.push_back(
            nats.queue_subscribe(save_party_contact_information_request::nats_subject,
                                 queue_group,
                                 [h](ores::nats::message msg) { h->save(std::move(msg)); }));
        subs.push_back(
            nats.queue_subscribe(delete_party_contact_information_request::nats_subject,
                                 queue_group,
                                 [h](ores::nats::message msg) { h->remove(std::move(msg)); }));
    }

    // ----------------------------------------------------------------
    // Counterparty contacts (counterparty_contact_handler serves the
    // counterparty_contact_information protocol — no matching sub-registrar).
    // ----------------------------------------------------------------
    {
        auto h = std::make_shared<counterparty_contact_handler>(nats, ctx, verifier);
        subs.push_back(
            nats.queue_subscribe(get_counterparty_contact_informations_request::nats_subject,
                                 queue_group,
                                 [h](ores::nats::message msg) { h->list(std::move(msg)); }));
        subs.push_back(
            nats.queue_subscribe(save_counterparty_contact_information_request::nats_subject,
                                 queue_group,
                                 [h](ores::nats::message msg) { h->save(std::move(msg)); }));
        subs.push_back(
            nats.queue_subscribe(delete_counterparty_contact_information_request::nats_subject,
                                 queue_group,
                                 [h](ores::nats::message msg) { h->remove(std::move(msg)); }));
    }

    // ----------------------------------------------------------------
    // Business unit types (no codegen model).
    // ----------------------------------------------------------------
    {
        auto h = std::make_shared<business_unit_type_handler>(nats, ctx, verifier);
        subs.push_back(
            nats.queue_subscribe(get_business_unit_types_request::nats_subject,
                                 queue_group,
                                 [h](ores::nats::message msg) { h->list(std::move(msg)); }));
        subs.push_back(
            nats.queue_subscribe(save_business_unit_type_request::nats_subject,
                                 queue_group,
                                 [h](ores::nats::message msg) { h->save(std::move(msg)); }));
        subs.push_back(
            nats.queue_subscribe(delete_business_unit_type_request::nats_subject,
                                 queue_group,
                                 [h](ores::nats::message msg) { h->remove(std::move(msg)); }));
        subs.push_back(
            nats.queue_subscribe(get_business_unit_type_history_request::nats_subject,
                                 queue_group,
                                 [h](ores::nats::message msg) { h->history(std::move(msg)); }));
    }

    // ----------------------------------------------------------------
    // Business centres (no codegen model).
    // ----------------------------------------------------------------
    {
        auto h = std::make_shared<business_centre_handler>(nats, ctx, verifier);
        subs.push_back(nats.queue_subscribe(
            get_business_centres_request::nats_subject, queue_group, [h](ores::nats::message msg) {
                h->list(std::move(msg));
            }));
        subs.push_back(nats.queue_subscribe(
            save_business_centre_request::nats_subject, queue_group, [h](ores::nats::message msg) {
                h->save(std::move(msg));
            }));
        subs.push_back(
            nats.queue_subscribe(delete_business_centre_request::nats_subject,
                                 queue_group,
                                 [h](ores::nats::message msg) { h->remove(std::move(msg)); }));
        subs.push_back(
            nats.queue_subscribe(get_business_centre_history_request::nats_subject,
                                 queue_group,
                                 [h](ores::nats::message msg) { h->history(std::move(msg)); }));
    }

    // ----------------------------------------------------------------
    // Asset classes (no codegen model; list-only).
    // ----------------------------------------------------------------
    {
        auto h = std::make_shared<asset_class_handler>(nats, ctx, verifier);
        subs.push_back(nats.queue_subscribe(
            get_asset_classes_request::nats_subject, queue_group, [h](ores::nats::message msg) {
                h->list(std::move(msg));
            }));
    }

    // ----------------------------------------------------------------
    // Publish-from-DQ workflow step handlers (24 subjects, one handler).
    // ----------------------------------------------------------------
    {
        auto h = std::make_shared<publish_from_dq_handler>(nats, ctx);
        static constexpr std::array publish_subjects{
            "refdata.v1.account-types.publish-from-dq",
            "refdata.v1.asset-classes.publish-from-dq",
            "refdata.v1.asset-measures.publish-from-dq",
            "refdata.v1.benchmark-rates.publish-from-dq",
            "refdata.v1.books.publish-from-dq",
            "refdata.v1.business-centres.publish-from-dq",
            "refdata.v1.business-processes.publish-from-dq",
            "refdata.v1.business-units.publish-from-dq",
            "refdata.v1.calendar-types.publish-from-dq",
            "refdata.v1.calendars.publish-from-dq",
            "refdata.v1.cashflow-types.publish-from-dq",
            "refdata.v1.countries.publish-from-dq",
            "refdata.v1.crm-topology-bundles.publish-from-dq",
            "refdata.v1.currencies.publish-from-dq",
            "refdata.v1.currency-pairs.publish-from-dq",
            "refdata.v1.currency-pair-conventions.publish-from-dq",
            "refdata.v1.entity-classifications.publish-from-dq",
            "refdata.v1.lei-counterparties.publish-from-dq",
            "refdata.v1.lei-parties.publish-from-dq",
            "refdata.v1.local-jurisdictions.publish-from-dq",
            "refdata.v1.party-relationships.publish-from-dq",
            "refdata.v1.party-roles.publish-from-dq",
            "refdata.v1.person-roles.publish-from-dq",
            "refdata.v1.portfolios.publish-from-dq",
            "refdata.v1.regulatory-corporate-sectors.publish-from-dq",
            "refdata.v1.reporting-regimes.publish-from-dq",
            "refdata.v1.supervisory-bodies.publish-from-dq",
        };
        for (const auto subject : publish_subjects) {
            subs.push_back(nats.queue_subscribe(
                subject, queue_group, [h](ores::nats::message msg) { h->handle(std::move(msg)); }));
        }
    }

    // ----------------------------------------------------------------
    // Generic history.v1.get subject. The registrar resolves each
    // request into a scoped context exactly like every other subject
    // (make_request_context), so a provider sees the same
    // tenant/party/roles/workspace visibility any other handler in
    // this file would.
    // ----------------------------------------------------------------
    {
        auto& hist_registry = history_registry();
        hist_registry.register_history_provider(
            "ores.refdata.currency",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::currency_service svc(scoped_ctx);
                auto versions = svc.get_currency_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_currency_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.country",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::country_service svc(scoped_ctx);
                auto versions = svc.get_country_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_country_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.book",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::book_service svc(scoped_ctx);
                auto versions = svc.get_book_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_book_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.book_purpose_type",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::book_purpose_type_service svc(scoped_ctx);
                auto versions = svc.get_type_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_book_purpose_type_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.book_status",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::book_status_service svc(scoped_ctx);
                auto versions = svc.get_status_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_book_status_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.business_centre",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::business_centre_service svc(scoped_ctx);
                auto versions = svc.get_centre_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_business_centre_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.business_day_convention_type",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::business_day_convention_type_service svc(scoped_ctx);
                auto versions = svc.get_type_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_business_day_convention_type_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.calendar",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::calendar_service svc(scoped_ctx);
                auto versions = svc.get_calendar_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_calendar_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.contact_type",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::contact_type_service svc(scoped_ctx);
                auto versions = svc.get_type_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_contact_type_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.cds_convention",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::cds_convention_service svc(scoped_ctx);
                auto versions = svc.get_cds_convention_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_cds_convention_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.crm_driver_pair",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::crm_driver_pair_service svc(scoped_ctx);
                auto versions = svc.get_crm_driver_pair_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_crm_driver_pair_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.crm_enabled_derived_pair",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::crm_enabled_derived_pair_service svc(scoped_ctx);
                auto versions = svc.get_crm_enabled_derived_pair_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_crm_enabled_derived_pair_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.crm_topology_config",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::crm_topology_config_service svc(scoped_ctx);
                auto versions = svc.get_crm_topology_config_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_crm_topology_config_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.currency_group",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::currency_group_service svc(scoped_ctx);
                auto versions = svc.get_group_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_currency_group_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.currency_pair",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::currency_pair_service svc(scoped_ctx);
                auto versions = svc.get_pair_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_currency_pair_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.currency_pair_classification",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::currency_pair_classification_service svc(scoped_ctx);
                auto versions = svc.get_classification_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_currency_pair_classification_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.deposit_convention",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::deposit_convention_service svc(scoped_ctx);
                auto versions = svc.get_deposit_convention_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_deposit_convention_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.fra_convention",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::fra_convention_service svc(scoped_ctx);
                auto versions = svc.get_fra_convention_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_fra_convention_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.ibor_index_convention",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::ibor_index_convention_service svc(scoped_ctx);
                auto versions = svc.get_ibor_index_convention_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_ibor_index_convention_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.ois_convention",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::ois_convention_service svc(scoped_ctx);
                auto versions = svc.get_ois_convention_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_ois_convention_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.overnight_index_convention",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::overnight_index_convention_service svc(scoped_ctx);
                auto versions = svc.get_overnight_index_convention_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_overnight_index_convention_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.swap_convention",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::swap_convention_service svc(scoped_ctx);
                auto versions = svc.get_swap_convention_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_swap_convention_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.zero_convention",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::zero_convention_service svc(scoped_ctx);
                auto versions = svc.get_zero_convention_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_zero_convention_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.tenor",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::tenor_service svc(scoped_ctx);
                auto versions = svc.get_tenor_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_tenor_fields);
            });

        hist_registry.register_history_provider(
            "ores.refdata.tenor_convention",
            [](const ores::database::context& scoped_ctx, const std::string& entity_id) {
                service::tenor_convention_service svc(scoped_ctx);
                auto versions = svc.get_convention_history(entity_id);
                return ores::history::service::build_entity_history_versions(
                    versions, presentation::render_tenor_convention_fields);
            });

        subs.push_back(ores::history::messaging::register_history_handlers(
            nats, hist_registry, queue_group, ctx, verifier));
    }

    return subs;
}

} // namespace ores::refdata::messaging
