/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */
#include "ores.refdata.core/messaging/registrar.hpp"
#include "ores.database/domain/context.hpp"
#include "ores.nats/domain/message.hpp"
#include "ores.nats/service/client.hpp"
#include "ores.nats/service/subscription.hpp"
#include "ores.security/jwt/jwt_authenticator.hpp"

// Per-entity sub-registrars (generated by the nats-sub-registrar facet).
#include "ores.refdata.core/messaging/asset_class_code_registrar.hpp"
#include "ores.refdata.core/messaging/book_change_registrar.hpp"
#include "ores.refdata.core/messaging/book_purpose_type_registrar.hpp"
#include "ores.refdata.core/messaging/book_registrar.hpp"
#include "ores.refdata.core/messaging/book_status_registrar.hpp"
#include "ores.refdata.core/messaging/business_centre_registrar.hpp"
#include "ores.refdata.core/messaging/business_day_convention_type_registrar.hpp"
#include "ores.refdata.core/messaging/business_unit_registrar.hpp"
#include "ores.refdata.core/messaging/business_unit_type_registrar.hpp"
#include "ores.refdata.core/messaging/calendar_adjustment_registrar.hpp"
#include "ores.refdata.core/messaging/calendar_date_registrar.hpp"
#include "ores.refdata.core/messaging/calendar_event_registrar.hpp"
#include "ores.refdata.core/messaging/calendar_materialisation_registrar.hpp"
#include "ores.refdata.core/messaging/calendar_name_registrar.hpp"
#include "ores.refdata.core/messaging/calendar_registrar.hpp"
#include "ores.refdata.core/messaging/calendar_type_registrar.hpp"
#include "ores.refdata.core/messaging/cds_convention_registrar.hpp"
#include "ores.refdata.core/messaging/configuration_document_registrar.hpp"
#include "ores.refdata.core/messaging/contact_type_registrar.hpp"
#include "ores.refdata.core/messaging/counterparty_contact_information_registrar.hpp"
#include "ores.refdata.core/messaging/counterparty_identifier_registrar.hpp"
#include "ores.refdata.core/messaging/counterparty_registrar.hpp"
#include "ores.refdata.core/messaging/country_registrar.hpp"
#include "ores.refdata.core/messaging/crm_driver_pair_registrar.hpp"
#include "ores.refdata.core/messaging/crm_enabled_derived_pair_registrar.hpp"
#include "ores.refdata.core/messaging/crm_topology_config_registrar.hpp"
#include "ores.refdata.core/messaging/csa_eligible_currency_registrar.hpp"
#include "ores.refdata.core/messaging/csa_registrar.hpp"
#include "ores.refdata.core/messaging/currency_calendar_registrar.hpp"
#include "ores.refdata.core/messaging/currency_country_registrar.hpp"
#include "ores.refdata.core/messaging/currency_currency_group_registrar.hpp"
#include "ores.refdata.core/messaging/currency_group_registrar.hpp"
#include "ores.refdata.core/messaging/currency_market_tier_registrar.hpp"
#include "ores.refdata.core/messaging/currency_pair_classification_registrar.hpp"
#include "ores.refdata.core/messaging/currency_pair_convention_calendar_registrar.hpp"
#include "ores.refdata.core/messaging/currency_pair_convention_registrar.hpp"
#include "ores.refdata.core/messaging/currency_pair_registrar.hpp"
#include "ores.refdata.core/messaging/currency_registrar.hpp"
#include "ores.refdata.core/messaging/curve_role_registrar.hpp"
#include "ores.refdata.core/messaging/day_count_fraction_type_registrar.hpp"
#include "ores.refdata.core/messaging/day_counter_registrar.hpp"
#include "ores.refdata.core/messaging/deposit_convention_registrar.hpp"
#include "ores.refdata.core/messaging/diary_entry_type_registrar.hpp"
#include "ores.refdata.core/messaging/floating_index_type_registrar.hpp"
#include "ores.refdata.core/messaging/fra_convention_registrar.hpp"
#include "ores.refdata.core/messaging/ibor_index_convention_registrar.hpp"
#include "ores.refdata.core/messaging/instrument_code_registrar.hpp"
#include "ores.refdata.core/messaging/ir_curve_bootstrap_config_registrar.hpp"
#include "ores.refdata.core/messaging/ir_curve_bootstrap_pillar_registrar.hpp"
#include "ores.refdata.core/messaging/ledger_feed_type_registrar.hpp"
#include "ores.refdata.core/messaging/leg_type_registrar.hpp"
#include "ores.refdata.core/messaging/monetary_nature_registrar.hpp"
#include "ores.refdata.core/messaging/netting_agreement_registrar.hpp"
#include "ores.refdata.core/messaging/netting_set_identifier_registrar.hpp"
#include "ores.refdata.core/messaging/netting_set_registrar.hpp"
#include "ores.refdata.core/messaging/ois_convention_registrar.hpp"
#include "ores.refdata.core/messaging/overnight_index_convention_registrar.hpp"
#include "ores.refdata.core/messaging/party_contact_information_registrar.hpp"
#include "ores.refdata.core/messaging/party_counterparty_registrar.hpp"
#include "ores.refdata.core/messaging/party_country_registrar.hpp"
#include "ores.refdata.core/messaging/party_currency_registrar.hpp"
#include "ores.refdata.core/messaging/party_id_scheme_registrar.hpp"
#include "ores.refdata.core/messaging/party_identifier_registrar.hpp"
#include "ores.refdata.core/messaging/party_registrar.hpp"
#include "ores.refdata.core/messaging/party_status_registrar.hpp"
#include "ores.refdata.core/messaging/party_type_registrar.hpp"
#include "ores.refdata.core/messaging/payment_frequency_registrar.hpp"
#include "ores.refdata.core/messaging/portfolio_registrar.hpp"
#include "ores.refdata.core/messaging/portfolio_right_registrar.hpp"
#include "ores.refdata.core/messaging/producer_kind_registrar.hpp"
#include "ores.refdata.core/messaging/purpose_type_registrar.hpp"
#include "ores.refdata.core/messaging/regulatory_book_type_registrar.hpp"
#include "ores.refdata.core/messaging/rounding_type_registrar.hpp"
#include "ores.refdata.core/messaging/sandbox_member_registrar.hpp"
#include "ores.refdata.core/messaging/sandbox_registrar.hpp"
#include "ores.refdata.core/messaging/series_subclass_code_registrar.hpp"
#include "ores.refdata.core/messaging/swap_convention_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_anchor_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_convention_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_convention_resolution_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_kind_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_resolution_algorithm_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_schedule_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_unit_registrar.hpp"
#include "ores.refdata.core/messaging/zero_convention_registrar.hpp"

// Wired inline rather than through a generated sub-registrar: asset_class
// is an operation protocol and publish_from_dq is a bespoke multi-subject
// workflow handler.
#include "ores.refdata.api/messaging/asset_class_protocol.hpp"
#include "ores.refdata.core/messaging/asset_class_handler.hpp"
#include "ores.refdata.core/messaging/publish_from_dq_handler.hpp"

// Generic history.v1.get subject.
#include "ores.history.core/messaging/registrar.hpp"
#include "ores.history.core/service/dispatch_registry.hpp"

// Per-entity history-provider registrars (generated by the
// history-provider-registrar facet).
#include "ores.refdata.core/messaging/asset_class_code_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/average_ois_convention_registrar.hpp"
#include "ores.refdata.core/messaging/base_correlation_config_registrar.hpp"
#include "ores.refdata.core/messaging/bma_basis_swap_convention_registrar.hpp"
#include "ores.refdata.core/messaging/bond_future_volatility_config_registrar.hpp"
#include "ores.refdata.core/messaging/bond_yield_convention_registrar.hpp"
#include "ores.refdata.core/messaging/book_change_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/book_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/book_purpose_type_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/book_status_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/business_centre_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/business_day_convention_type_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/business_unit_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/business_unit_type_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/calendar_event_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/calendar_exception_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/calendar_exception_registrar.hpp"
#include "ores.refdata.core/messaging/calendar_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/calendar_name_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/calendar_rule_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/calendar_rule_registrar.hpp"
#include "ores.refdata.core/messaging/calendar_type_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/cap_floor_volatility_config_registrar.hpp"
#include "ores.refdata.core/messaging/cds_convention_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/cds_volatility_config_registrar.hpp"
#include "ores.refdata.core/messaging/cds_volatility_term_registrar.hpp"
#include "ores.refdata.core/messaging/cms_spread_option_convention_registrar.hpp"
#include "ores.refdata.core/messaging/commodity_curve_config_registrar.hpp"
#include "ores.refdata.core/messaging/commodity_forward_convention_registrar.hpp"
#include "ores.refdata.core/messaging/commodity_future_convention_registrar.hpp"
#include "ores.refdata.core/messaging/commodity_price_segment_registrar.hpp"
#include "ores.refdata.core/messaging/commodity_volatility_config_registrar.hpp"
#include "ores.refdata.core/messaging/contact_type_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/counterparty_contact_information_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/counterparty_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/counterparty_identifier_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/country_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/crm_driver_pair_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/crm_enabled_derived_pair_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/crm_topology_config_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/cross_currency_basis_convention_registrar.hpp"
#include "ores.refdata.core/messaging/cross_currency_fix_float_convention_registrar.hpp"
#include "ores.refdata.core/messaging/csa_eligible_currency_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/csa_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/currency_group_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/currency_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/currency_market_tier_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/currency_pair_classification_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/currency_pair_convention_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/currency_pair_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/curve_bootstrap_config_registrar.hpp"
#include "ores.refdata.core/messaging/curve_configuration_registrar.hpp"
#include "ores.refdata.core/messaging/curve_configuration_section_registrar.hpp"
#include "ores.refdata.core/messaging/curve_correlation_config_registrar.hpp"
#include "ores.refdata.core/messaging/curve_definition_registrar.hpp"
#include "ores.refdata.core/messaging/curve_global_report_registrar.hpp"
#include "ores.refdata.core/messaging/curve_parametric_smile_parameter_registrar.hpp"
#include "ores.refdata.core/messaging/curve_parametric_smile_registrar.hpp"
#include "ores.refdata.core/messaging/curve_quote_registrar.hpp"
#include "ores.refdata.core/messaging/curve_report_configuration_registrar.hpp"
#include "ores.refdata.core/messaging/curve_role_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/curve_section_registrar.hpp"
#include "ores.refdata.core/messaging/curve_security_config_registrar.hpp"
#include "ores.refdata.core/messaging/curve_segment_curve_registrar.hpp"
#include "ores.refdata.core/messaging/curve_segment_registrar.hpp"
#include "ores.refdata.core/messaging/curve_segment_type_registrar.hpp"
#include "ores.refdata.core/messaging/curve_volatility_config_registrar.hpp"
#include "ores.refdata.core/messaging/day_count_fraction_type_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/day_counter_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/default_curve_config_registrar.hpp"
#include "ores.refdata.core/messaging/default_curve_configuration_registrar.hpp"
#include "ores.refdata.core/messaging/deposit_convention_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/derivation_kind_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/derivation_kind_registrar.hpp"
#include "ores.refdata.core/messaging/diary_entry_type_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/equity_curve_config_registrar.hpp"
#include "ores.refdata.core/messaging/equity_volatility_config_registrar.hpp"
#include "ores.refdata.core/messaging/floating_index_type_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/fra_convention_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/future_convention_registrar.hpp"
#include "ores.refdata.core/messaging/fx_option_convention_registrar.hpp"
#include "ores.refdata.core/messaging/fx_volatility_config_registrar.hpp"
#include "ores.refdata.core/messaging/ibor_index_convention_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/inflation_cap_floor_volatility_config_registrar.hpp"
#include "ores.refdata.core/messaging/inflation_curve_config_registrar.hpp"
#include "ores.refdata.core/messaging/inflation_seasonality_factor_registrar.hpp"
#include "ores.refdata.core/messaging/inflation_swap_convention_registrar.hpp"
#include "ores.refdata.core/messaging/instrument_code_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/intraday_power_curve_config_registrar.hpp"
#include "ores.refdata.core/messaging/intraday_power_load_convention_registrar.hpp"
#include "ores.refdata.core/messaging/ir_curve_bootstrap_config_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/ir_curve_bootstrap_pillar_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/ledger_feed_type_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/leg_type_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/monetary_nature_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/netting_agreement_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/netting_set_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/netting_set_identifier_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/ois_convention_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/overnight_index_convention_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/party_contact_information_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/party_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/party_id_scheme_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/party_identifier_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/party_status_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/party_type_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/payment_frequency_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/portfolio_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/portfolio_right_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/producer_kind_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/purpose_type_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/regulatory_book_type_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/rounding_type_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/sandbox_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/sandbox_member_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/series_subclass_code_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/swap_convention_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/swap_index_convention_registrar.hpp"
#include "ores.refdata.core/messaging/swaption_volatility_config_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_anchor_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_basis_swap_convention_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_basis_two_swap_convention_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_convention_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_kind_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_resolution_algorithm_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_schedule_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/tenor_unit_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/yield_curve_config_registrar.hpp"
#include "ores.refdata.core/messaging/yield_volatility_config_registrar.hpp"
#include "ores.refdata.core/messaging/zero_convention_history_provider_registrar.hpp"
#include "ores.refdata.core/messaging/zero_inflation_index_convention_registrar.hpp"
#include <array>
#include <iterator>
#include <memory>
#include <optional>
#include <string_view>
#include <utility>
#include <vector>

namespace ores::refdata::messaging {

namespace {
static constexpr std::string_view queue_group = "ores.refdata.service";

// Function-local static: must outlive the history.v1.get subscription
// (see ores::history::messaging::register_history_handlers's doc), and
// register_handlers is only ever called once per service process.
ores::history::service::dispatch_registry& history_registry() {
    static ores::history::service::dispatch_registry instance;
    return instance;
}
} // namespace

std::vector<ores::nats::service::subscription>
registrar::register_handlers(ores::nats::service::client& nats,
                             ores::database::context ctx,
                             std::optional<ores::security::jwt::jwt_authenticator> verifier) {
    std::vector<ores::nats::service::subscription> subs;

    // ----------------------------------------------------------------
    // Per-entity sub-registrars. Each register_<entity>_handlers() wires
    // that entity's subjects to its own handler and returns the resulting
    // subscriptions, which we take ownership of here.
    // ----------------------------------------------------------------
    const auto append = [&subs](std::vector<ores::nats::service::subscription> s) {
        subs.insert(
            subs.end(), std::make_move_iterator(s.begin()), std::make_move_iterator(s.end()));
    };

    append(register_asset_class_code_handlers(nats, ctx, verifier));
    append(register_book_handlers(nats, ctx, verifier));
    append(register_book_change_handlers(nats, ctx, verifier));
    append(register_book_purpose_type_handlers(nats, ctx, verifier));
    append(register_book_status_handlers(nats, ctx, verifier));
    append(register_business_centre_handlers(nats, ctx, verifier));
    append(register_business_day_convention_type_handlers(nats, ctx, verifier));
    append(register_business_unit_handlers(nats, ctx, verifier));
    append(register_business_unit_type_handlers(nats, ctx, verifier));
    append(register_calendar_handlers(nats, ctx, verifier));
    append(register_calendar_date_handlers(nats, ctx, verifier));
    append(register_calendar_materialisation_handlers(nats, ctx, verifier));
    append(register_configuration_document_handlers(nats, ctx, verifier));
    append(register_calendar_adjustment_handlers(nats, ctx, verifier));
    append(register_calendar_event_handlers(nats, ctx, verifier));
    append(register_calendar_name_handlers(nats, ctx, verifier));
    append(register_calendar_type_handlers(nats, ctx, verifier));
    append(register_cds_convention_handlers(nats, ctx, verifier));
    append(register_contact_type_handlers(nats, ctx, verifier));
    append(register_counterparty_handlers(nats, ctx, verifier));
    append(register_counterparty_contact_information_handlers(nats, ctx, verifier));
    append(register_counterparty_identifier_handlers(nats, ctx, verifier));
    append(register_csa_handlers(nats, ctx, verifier));
    append(register_csa_eligible_currency_handlers(nats, ctx, verifier));
    append(register_country_handlers(nats, ctx, verifier));
    append(register_crm_driver_pair_handlers(nats, ctx, verifier));
    append(register_crm_enabled_derived_pair_handlers(nats, ctx, verifier));
    append(register_crm_topology_config_handlers(nats, ctx, verifier));
    append(register_currency_handlers(nats, ctx, verifier));
    append(register_currency_calendar_handlers(nats, ctx, verifier));
    append(register_currency_country_handlers(nats, ctx, verifier));
    append(register_currency_currency_group_handlers(nats, ctx, verifier));
    append(register_currency_group_handlers(nats, ctx, verifier));
    append(register_currency_market_tier_handlers(nats, ctx, verifier));
    append(register_currency_pair_classification_handlers(nats, ctx, verifier));
    append(register_currency_pair_convention_calendar_handlers(nats, ctx, verifier));
    append(register_currency_pair_convention_handlers(nats, ctx, verifier));
    append(register_currency_pair_handlers(nats, ctx, verifier));
    append(register_day_counter_handlers(nats, ctx, verifier));
    append(register_day_count_fraction_type_handlers(nats, ctx, verifier));
    append(register_diary_entry_type_handlers(nats, ctx, verifier));
    append(register_instrument_code_handlers(nats, ctx, verifier));
    append(register_deposit_convention_handlers(nats, ctx, verifier));
    append(register_floating_index_type_handlers(nats, ctx, verifier));
    append(register_fra_convention_handlers(nats, ctx, verifier));
    append(register_ibor_index_convention_handlers(nats, ctx, verifier));
    append(register_ir_curve_bootstrap_config_handlers(nats, ctx, verifier));
    append(register_ir_curve_bootstrap_pillar_handlers(nats, ctx, verifier));
    append(register_ledger_feed_type_handlers(nats, ctx, verifier));
    append(register_leg_type_handlers(nats, ctx, verifier));
    append(register_monetary_nature_handlers(nats, ctx, verifier));
    append(register_netting_agreement_handlers(nats, ctx, verifier));
    append(register_netting_set_handlers(nats, ctx, verifier));
    append(register_netting_set_identifier_handlers(nats, ctx, verifier));
    append(register_ois_convention_handlers(nats, ctx, verifier));
    append(register_overnight_index_convention_handlers(nats, ctx, verifier));
    append(register_party_handlers(nats, ctx, verifier));
    append(register_party_contact_information_handlers(nats, ctx, verifier));
    append(register_party_counterparty_handlers(nats, ctx, verifier));
    append(register_party_country_handlers(nats, ctx, verifier));
    append(register_party_currency_handlers(nats, ctx, verifier));
    append(register_party_id_scheme_handlers(nats, ctx, verifier));
    append(register_payment_frequency_handlers(nats, ctx, verifier));
    append(register_party_identifier_handlers(nats, ctx, verifier));
    append(register_party_status_handlers(nats, ctx, verifier));
    append(register_party_type_handlers(nats, ctx, verifier));
    append(register_portfolio_handlers(nats, ctx, verifier));
    append(register_portfolio_right_handlers(nats, ctx, verifier));
    append(register_sandbox_handlers(nats, ctx, verifier));
    append(register_sandbox_member_handlers(nats, ctx, verifier));
    append(register_purpose_type_handlers(nats, ctx, verifier));
    append(register_regulatory_book_type_handlers(nats, ctx, verifier));
    append(register_rounding_type_handlers(nats, ctx, verifier));
    append(register_series_subclass_code_handlers(nats, ctx, verifier));
    append(register_swap_convention_handlers(nats, ctx, verifier));
    append(register_tenor_handlers(nats, ctx, verifier));
    append(register_tenor_anchor_handlers(nats, ctx, verifier));
    append(register_tenor_convention_handlers(nats, ctx, verifier));
    append(register_tenor_convention_resolution_handlers(nats, ctx, verifier));
    append(register_tenor_kind_handlers(nats, ctx, verifier));
    append(register_curve_role_handlers(nats, ctx, verifier));
    append(register_tenor_unit_handlers(nats, ctx, verifier));
    append(register_tenor_resolution_algorithm_handlers(nats, ctx, verifier));
    append(register_tenor_schedule_handlers(nats, ctx, verifier));
    append(register_zero_convention_handlers(nats, ctx, verifier));
    append(register_calendar_exception_handlers(nats, ctx, verifier));
    append(register_calendar_rule_handlers(nats, ctx, verifier));
    append(register_derivation_kind_handlers(nats, ctx, verifier));
    append(register_producer_kind_handlers(nats, ctx, verifier));
    append(register_average_ois_convention_handlers(nats, ctx, verifier));
    append(register_base_correlation_config_handlers(nats, ctx, verifier));
    append(register_bma_basis_swap_convention_handlers(nats, ctx, verifier));
    append(register_bond_future_volatility_config_handlers(nats, ctx, verifier));
    append(register_bond_yield_convention_handlers(nats, ctx, verifier));
    append(register_cap_floor_volatility_config_handlers(nats, ctx, verifier));
    append(register_cds_volatility_config_handlers(nats, ctx, verifier));
    append(register_cds_volatility_term_handlers(nats, ctx, verifier));
    append(register_cms_spread_option_convention_handlers(nats, ctx, verifier));
    append(register_commodity_curve_config_handlers(nats, ctx, verifier));
    append(register_commodity_forward_convention_handlers(nats, ctx, verifier));
    append(register_commodity_future_convention_handlers(nats, ctx, verifier));
    append(register_commodity_price_segment_handlers(nats, ctx, verifier));
    append(register_commodity_volatility_config_handlers(nats, ctx, verifier));
    append(register_cross_currency_basis_convention_handlers(nats, ctx, verifier));
    append(register_cross_currency_fix_float_convention_handlers(nats, ctx, verifier));
    append(register_curve_bootstrap_config_handlers(nats, ctx, verifier));
    append(register_curve_configuration_handlers(nats, ctx, verifier));
    append(register_curve_configuration_section_handlers(nats, ctx, verifier));
    append(register_curve_correlation_config_handlers(nats, ctx, verifier));
    append(register_curve_definition_handlers(nats, ctx, verifier));
    append(register_curve_global_report_handlers(nats, ctx, verifier));
    append(register_curve_parametric_smile_handlers(nats, ctx, verifier));
    append(register_curve_parametric_smile_parameter_handlers(nats, ctx, verifier));
    append(register_curve_quote_handlers(nats, ctx, verifier));
    append(register_curve_report_configuration_handlers(nats, ctx, verifier));
    append(register_curve_section_handlers(nats, ctx, verifier));
    append(register_curve_security_config_handlers(nats, ctx, verifier));
    append(register_curve_segment_curve_handlers(nats, ctx, verifier));
    append(register_curve_segment_handlers(nats, ctx, verifier));
    append(register_curve_segment_type_handlers(nats, ctx, verifier));
    append(register_curve_volatility_config_handlers(nats, ctx, verifier));
    append(register_default_curve_config_handlers(nats, ctx, verifier));
    append(register_default_curve_configuration_handlers(nats, ctx, verifier));
    append(register_equity_curve_config_handlers(nats, ctx, verifier));
    append(register_equity_volatility_config_handlers(nats, ctx, verifier));
    append(register_future_convention_handlers(nats, ctx, verifier));
    append(register_fx_option_convention_handlers(nats, ctx, verifier));
    append(register_fx_volatility_config_handlers(nats, ctx, verifier));
    append(register_inflation_cap_floor_volatility_config_handlers(nats, ctx, verifier));
    append(register_inflation_curve_config_handlers(nats, ctx, verifier));
    append(register_inflation_seasonality_factor_handlers(nats, ctx, verifier));
    append(register_inflation_swap_convention_handlers(nats, ctx, verifier));
    append(register_intraday_power_curve_config_handlers(nats, ctx, verifier));
    append(register_intraday_power_load_convention_handlers(nats, ctx, verifier));
    append(register_swap_index_convention_handlers(nats, ctx, verifier));
    append(register_swaption_volatility_config_handlers(nats, ctx, verifier));
    append(register_tenor_basis_swap_convention_handlers(nats, ctx, verifier));
    append(register_tenor_basis_two_swap_convention_handlers(nats, ctx, verifier));
    append(register_yield_curve_config_handlers(nats, ctx, verifier));
    append(register_yield_volatility_config_handlers(nats, ctx, verifier));
    append(register_zero_inflation_index_convention_handlers(nats, ctx, verifier));

    // ----------------------------------------------------------------
    // Asset classes (no codegen model; list-only).
    // ----------------------------------------------------------------
    {
        auto h = std::make_shared<asset_class_handler>(nats, ctx, verifier);
        subs.push_back(nats.queue_subscribe(
            get_asset_classes_request::nats_subject, queue_group, [h](ores::nats::message msg) {
                h->list(std::move(msg));
            }));
    }

    // ----------------------------------------------------------------
    // Publish-from-DQ workflow step handlers (42 subjects, one handler).
    // ----------------------------------------------------------------
    {
        auto h = std::make_shared<publish_from_dq_handler>(nats, ctx);
        static constexpr std::array publish_subjects{
            "refdata.v1.ops.publish_account_types_from_dq",
            "refdata.v1.ops.publish_asset_classes_from_dq",
            "refdata.v1.ops.publish_asset_measures_from_dq",
            "refdata.v1.ops.publish_benchmark_rates_from_dq",
            "refdata.v1.ops.publish_books_from_dq",
            "refdata.v1.ops.publish_business_centres_from_dq",
            "refdata.v1.ops.publish_business_processes_from_dq",
            "refdata.v1.ops.publish_business_units_from_dq",
            "refdata.v1.ops.publish_calendar_events_from_dq",
            "refdata.v1.ops.publish_calendar_types_from_dq",
            "refdata.v1.ops.publish_calendars_from_dq",
            "refdata.v1.ops.publish_cashflow_types_from_dq",
            "refdata.v1.ops.publish_conventions_from_dq",
            "refdata.v1.ops.publish_counterparty_aliases_from_dq",
            "refdata.v1.ops.publish_countries_from_dq",
            "refdata.v1.ops.publish_crm_topology_bundles_from_dq",
            "refdata.v1.ops.publish_csas_from_dq",
            "refdata.v1.ops.publish_currencies_from_dq",
            "refdata.v1.ops.publish_currency_groups_from_dq",
            "refdata.v1.ops.publish_currency_currency_groups_from_dq",
            "refdata.v1.ops.publish_currency_pairs_from_dq",
            "refdata.v1.ops.publish_currency_pair_conventions_from_dq",
            "refdata.v1.ops.publish_currency_calendars_from_dq",
            "refdata.v1.ops.publish_currency_countries_from_dq",
            "refdata.v1.ops.publish_currency_pair_convention_calendars_from_dq",
            "refdata.v1.ops.publish_entity_classifications_from_dq",
            "refdata.v1.ops.publish_lei_counterparties_from_dq",
            "refdata.v1.ops.publish_lei_parties_from_dq",
            "refdata.v1.ops.publish_local_jurisdictions_from_dq",
            "refdata.v1.ops.publish_sandbox_portfolios_from_dq",
            "refdata.v1.ops.publish_netting_agreements_from_dq",
            "refdata.v1.ops.publish_netting_set_aliases_from_dq",
            "refdata.v1.ops.publish_netting_sets_from_dq",
            "refdata.v1.ops.publish_party_relationships_from_dq",
            "refdata.v1.ops.publish_party_roles_from_dq",
            "refdata.v1.ops.publish_payment_frequencies_from_dq",
            "refdata.v1.ops.publish_person_roles_from_dq",
            "refdata.v1.ops.publish_portfolios_from_dq",
            "refdata.v1.ops.publish_regulatory_corporate_sectors_from_dq",
            "refdata.v1.ops.publish_reporting_regimes_from_dq",
            "refdata.v1.ops.publish_supervisory_bodies_from_dq",
            "refdata.v1.ops.publish_tenor_schedules_from_dq",
        };
        for (const auto subject : publish_subjects) {
            subs.push_back(nats.queue_subscribe(
                subject, queue_group, [h](ores::nats::message msg) { h->handle(std::move(msg)); }));
        }
    }

    // ----------------------------------------------------------------
    // Generic history.v1.get subject. The registrar resolves each
    // request into a scoped context exactly like every other subject
    // (make_request_context), so a provider sees the same
    // tenant/party/roles visibility any other handler in
    // this file would.
    // ----------------------------------------------------------------
    {
        auto& hist_registry = history_registry();
        // Per-entity history providers (generated by the
        // history-provider-registrar facet).
        register_asset_class_code_history_provider(hist_registry);
        register_book_history_provider(hist_registry);
        register_book_change_history_provider(hist_registry);
        register_book_purpose_type_history_provider(hist_registry);
        register_book_status_history_provider(hist_registry);
        register_business_centre_history_provider(hist_registry);
        register_business_day_convention_type_history_provider(hist_registry);
        register_business_unit_history_provider(hist_registry);
        register_business_unit_type_history_provider(hist_registry);
        register_calendar_history_provider(hist_registry);
        register_calendar_event_history_provider(hist_registry);
        register_cds_convention_history_provider(hist_registry);
        register_contact_type_history_provider(hist_registry);
        register_counterparty_history_provider(hist_registry);
        register_country_history_provider(hist_registry);
        register_crm_driver_pair_history_provider(hist_registry);
        register_crm_enabled_derived_pair_history_provider(hist_registry);
        register_crm_topology_config_history_provider(hist_registry);
        register_currency_history_provider(hist_registry);
        register_currency_group_history_provider(hist_registry);
        register_currency_market_tier_history_provider(hist_registry);
        register_currency_pair_history_provider(hist_registry);
        register_currency_pair_classification_history_provider(hist_registry);
        register_currency_pair_convention_history_provider(hist_registry);
        register_curve_role_history_provider(hist_registry);
        register_day_counter_history_provider(hist_registry);
        register_day_count_fraction_type_history_provider(hist_registry);
        register_deposit_convention_history_provider(hist_registry);
        register_diary_entry_type_history_provider(hist_registry);
        register_floating_index_type_history_provider(hist_registry);
        register_fra_convention_history_provider(hist_registry);
        register_ibor_index_convention_history_provider(hist_registry);
        register_ledger_feed_type_history_provider(hist_registry);
        register_leg_type_history_provider(hist_registry);
        register_monetary_nature_history_provider(hist_registry);
        register_netting_agreement_history_provider(hist_registry);
        register_netting_set_history_provider(hist_registry);
        register_netting_set_identifier_history_provider(hist_registry);
        register_ois_convention_history_provider(hist_registry);
        register_overnight_index_convention_history_provider(hist_registry);
        register_party_history_provider(hist_registry);
        register_party_id_scheme_history_provider(hist_registry);
        register_party_status_history_provider(hist_registry);
        register_party_type_history_provider(hist_registry);
        register_payment_frequency_history_provider(hist_registry);
        register_portfolio_history_provider(hist_registry);
        register_portfolio_right_history_provider(hist_registry);
        register_sandbox_history_provider(hist_registry);
        register_sandbox_member_history_provider(hist_registry);
        register_purpose_type_history_provider(hist_registry);
        register_regulatory_book_type_history_provider(hist_registry);
        register_rounding_type_history_provider(hist_registry);
        register_series_subclass_code_history_provider(hist_registry);
        register_swap_convention_history_provider(hist_registry);
        register_tenor_history_provider(hist_registry);
        register_tenor_anchor_history_provider(hist_registry);
        register_tenor_convention_history_provider(hist_registry);
        register_tenor_kind_history_provider(hist_registry);
        register_tenor_resolution_algorithm_history_provider(hist_registry);
        register_tenor_schedule_history_provider(hist_registry);
        register_tenor_unit_history_provider(hist_registry);
        register_zero_convention_history_provider(hist_registry);
        register_calendar_exception_history_provider(hist_registry);
        register_calendar_rule_history_provider(hist_registry);
        register_calendar_name_history_provider(hist_registry);
        register_calendar_type_history_provider(hist_registry);
        register_counterparty_contact_information_history_provider(hist_registry);
        register_counterparty_identifier_history_provider(hist_registry);
        register_csa_history_provider(hist_registry);
        register_csa_eligible_currency_history_provider(hist_registry);
        register_derivation_kind_history_provider(hist_registry);
        register_producer_kind_history_provider(hist_registry);
        register_instrument_code_history_provider(hist_registry);
        register_ir_curve_bootstrap_config_history_provider(hist_registry);
        register_ir_curve_bootstrap_pillar_history_provider(hist_registry);
        register_party_contact_information_history_provider(hist_registry);
        register_party_identifier_history_provider(hist_registry);

        subs.push_back(ores::history::messaging::register_history_handlers(
            nats, hist_registry, "refdata", queue_group, ctx, verifier));
    }

    return subs;
}

} // namespace ores::refdata::messaging
