# -*- mode: cmake; cmake-tab-width: 4; indent-tabs-mode: nil -*-
#
# Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
set(files
    "messaging/app_registrar.cpp"
    "messaging/app_version_platform_registrar.cpp"
    "messaging/app_version_registrar.cpp"
    "messaging/batch_registrar.cpp"
    "messaging/host_registrar.cpp"
    "messaging/registrar.cpp"
    "messaging/report_submit_handler.cpp"
    "messaging/result_registrar.cpp"
    "messaging/workunit_registrar.cpp"
    "presentation/app_history_field_mapper.cpp"
    "presentation/app_version_history_field_mapper.cpp"
    "presentation/batch_history_field_mapper.cpp"
    "presentation/host_history_field_mapper.cpp"
    "presentation/result_history_field_mapper.cpp"
    "presentation/workunit_history_field_mapper.cpp"
    "repository/app_entity.cpp"
    "repository/app_mapper.cpp"
    "repository/app_repository.cpp"
    "repository/app_version_entity.cpp"
    "repository/app_version_mapper.cpp"
    "repository/app_version_platform_entity.cpp"
    "repository/app_version_platform_mapper.cpp"
    "repository/app_version_platform_repository.cpp"
    "repository/app_version_repository.cpp"
    "repository/batch_entity.cpp"
    "repository/batch_mapper.cpp"
    "repository/batch_repository.cpp"
    "repository/compute_telemetry_repository.cpp"
    "repository/host_entity.cpp"
    "repository/host_mapper.cpp"
    "repository/host_repository.cpp"
    "repository/platform_entity.cpp"
    "repository/platform_repository.cpp"
    "repository/result_entity.cpp"
    "repository/result_mapper.cpp"
    "repository/result_repository.cpp"
    "repository/workflow_batch_link_repository.cpp"
    "repository/workunit_entity.cpp"
    "repository/workunit_mapper.cpp"
    "repository/workunit_repository.cpp"
    "service/app_service.cpp"
    "service/app_version_platform_service.cpp"
    "service/app_version_service.cpp"
    "service/batch_service.cpp"
    "service/host_service.cpp"
    "service/result_service.cpp"
    "service/workunit_service.cpp"
)

# Headers must be listed for AUTOMOC to find Q_OBJECT declarations.
set(HEADERS
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/export.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/app_handler.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/app_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/app_version_handler.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/app_version_platform_handler.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/app_version_platform_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/app_version_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/batch_handler.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/batch_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/host_handler.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/host_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/platform_handler.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/report_submit_handler.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/result_handler.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/result_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/telemetry_handler.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/work_handler.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/workunit_handler.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/messaging/workunit_registrar.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/ores.compute.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/presentation/app_history_field_mapper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/presentation/app_version_history_field_mapper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/presentation/batch_history_field_mapper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/presentation/host_history_field_mapper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/presentation/result_history_field_mapper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/presentation/workunit_history_field_mapper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/app_entity.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/app_mapper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/app_repository.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/app_version_entity.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/app_version_mapper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/app_version_platform_entity.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/app_version_platform_mapper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/app_version_platform_repository.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/app_version_repository.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/batch_entity.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/batch_mapper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/batch_repository.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/compute_telemetry_repository.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/grid_sample_entity.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/host_entity.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/host_mapper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/host_repository.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/node_sample_entity.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/platform_entity.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/platform_repository.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/result_entity.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/result_mapper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/result_repository.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/workflow_batch_link_entity.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/workflow_batch_link_repository.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/workunit_entity.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/workunit_mapper.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/repository/workunit_repository.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/service/app_service.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/service/app_version_platform_service.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/service/app_version_service.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/service/batch_service.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/service/host_service.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/service/result_service.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../include/ores.compute.core/service/workunit_service.hpp"
)
