/* -*- sql-product: postgres; tab-width: 4; indent-tabs-mode: nil -*-
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Template: sql_batch_execute.mustache
 * To modify, update the template and regenerate.
 *
 * solvaris Reference Data Master Include File
 *
 * Auto-generated by generator.py from models/slovaris/model.json
 * Includes all solvaris SQL files in the correct dependency order.
 */

-- =============================================================================
-- Catalogs data for Slovaris
-- =============================================================================

\echo '--- Catalogs data for Slovaris ---'
\ir solvaris_catalog_populate.sql

-- =============================================================================
-- Methodologies data for Slovaris
-- =============================================================================

\echo '--- Methodologies data for Slovaris ---'
\ir solvaris_methodology_populate.sql

-- =============================================================================
-- Datasets data for Slovaris
-- =============================================================================

\echo '--- Datasets data for Slovaris ---'
\ir solvaris_dataset_populate.sql

-- =============================================================================
-- Dataset dependencies for Slovaris
-- =============================================================================

\echo '--- Dataset dependencies for Slovaris ---'
\ir solvaris_dataset_dependency_populate.sql

-- =============================================================================
-- Tags data for Slovaris
-- =============================================================================

\echo '--- Tags data for Slovaris ---'
\ir solvaris_tag_populate.sql

-- =============================================================================
-- Flags data for Slovaris
-- =============================================================================

\echo '--- Flags data for Slovaris ---'
\ir solvaris_flag_populate.sql

-- =============================================================================
-- Currencies data for Slovaris
-- =============================================================================

\echo '--- Currencies data for Slovaris ---'
\ir solvaris_currency_populate.sql

-- =============================================================================
-- Countries data for Slovaris
-- =============================================================================

\echo '--- Countries data for Slovaris ---'
\ir solvaris_country_populate.sql

