/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */
#ifndef ORES_EVENTING_CORE_SERVICE_CACHE_PARTITIONED_CACHE_HPP
#define ORES_EVENTING_CORE_SERVICE_CACHE_PARTITIONED_CACHE_HPP

#include <functional>
#include <immer/atom.hpp>
#include <immer/map.hpp>
#include <immer/map_transient.hpp>
#include <optional>
#include <utility>
#include <variant>

namespace ores::eventing::service::cache {

/**
 * @brief A generic, thread-safe, entity-agnostic in-process cache
 * partitioned by an outer key (typically a tenant id), mirroring another
 * service's entity and kept fresh via eventing.
 *
 * Storage is @c immer::atom<immer::map<PartitionKey, partition>>. Reads
 * (@c get, @c snapshot) take a wait-free atomic load of the whole
 * structure and are never blocked by -- or block -- a concurrent
 * @c replace_partition. Replacing a partition goes through the atom's
 * compare-and-swap @c update(), not a blind @c store(), so concurrently
 * replacing two different partitions never races into a lost update, and
 * structural sharing means only the touched partition's map path is ever
 * copied -- other partitions' entries are neither copied nor touched.
 *
 * @c AuxIndex lets a caller attach a derived structure alongside the
 * primary key/value entries (e.g. a parent-to-children index built from
 * the same source data) without the primitive itself knowing anything
 * about the entity's shape; entities with no derived structure leave it
 * defaulted.
 *
 * This is Layer A of the entity-mirror cache design: a hand-written,
 * reusable primitive that any per-entity consumer-side cache -- whether
 * hand-instantiated or, eventually, generated by the nats-event-cache
 * facet -- is built on, so no consumer ever hand-writes atom/map
 * concurrency code again.
 */
template <typename PartitionKey,
         typename Key,
         typename Value,
         typename AuxIndex = std::monostate,
         typename KeyHash = std::hash<Key>,
         typename PartitionKeyHash = std::hash<PartitionKey>>
class partitioned_cache {
public:
    using entries_map = immer::map<Key, Value, KeyHash>;
    using aux_type = AuxIndex;

    struct partition {
        entries_map entries;
        AuxIndex aux{};
    };

    partitioned_cache() = default;

    /// immer::atom disallows copy/move.
    partitioned_cache(const partitioned_cache&) = delete;
    partitioned_cache& operator=(const partitioned_cache&) = delete;
    partitioned_cache(partitioned_cache&&) = delete;
    partitioned_cache& operator=(partitioned_cache&&) = delete;

    /**
     * @brief Atomically replace one partition's entries (and, optionally,
     * its derived aux index) with a new snapshot. Other partitions are
     * untouched. Safe to call concurrently for different partitions;
     * concurrent calls for the *same* partition are safe too (last
     * writer wins, no torn state), though callers reloading from an
     * authoritative source on each event should not normally race
     * themselves.
     */
    void replace_partition(const PartitionKey& partition_key,
                           entries_map entries,
                           AuxIndex aux = AuxIndex{}) {
        // update()'s callback may be invoked more than once if the
        // compare-and-swap loses a race and retries -- so it must not
        // consume `data` by move (a second invocation would then move
        // from an already-moved-from value). `data` is captured by
        // reference and .set() copies it fresh on every attempt; immer
        // types make that cheap (structural sharing), not a deep copy.
        const partition data{std::move(entries), std::move(aux)};
        cache_.update([&](partition_map m) {
            return std::move(m).set(partition_key, data);
        });
    }

    /// Wait-free lookup of a single entry. Never blocks on, or is
    /// blocked by, a concurrent replace_partition.
    [[nodiscard]] std::optional<Value> get(const PartitionKey& partition_key,
                                           const Key& key) const {
        const auto snap = cache_.load().get();
        const auto* part = snap.find(partition_key);
        if (!part)
            return std::nullopt;
        const auto* value = part->entries.find(key);
        if (!value)
            return std::nullopt;
        return *value;
    }

    /// Wait-free snapshot of a whole partition (entries + aux index),
    /// for callers that need more than a single-key lookup (e.g. reading
    /// the aux index directly).
    [[nodiscard]] std::optional<partition>
    snapshot(const PartitionKey& partition_key) const {
        const auto snap = cache_.load().get();
        const auto* part = snap.find(partition_key);
        if (!part)
            return std::nullopt;
        return *part;
    }

private:
    using partition_map = immer::map<PartitionKey, partition, PartitionKeyHash>;

    immer::atom<partition_map> cache_;
};

} // namespace ores::eventing::service::cache

#endif
