' -*- mode: plantuml; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
'
' Copyright (C) 2026 Marco Craveiro <marco.craveiro@gmail.com>
'
' This program is free software; you can redistribute it and/or modify it under
' the terms of the GNU General Public License as published by the Free Software
' Foundation; either version 3 of the License, or (at your option) any later
' version.
'
' This program is distributed in the hope that it will be useful, but WITHOUT
' ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
' FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with
' this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
' Street, Fifth Floor, Boston, MA 02110-1301, USA.
'
@startuml

title ores.connections Component

set namespaceSeparator ::

namespace ores #F2F2F2 {
    namespace connections #F2F2F2 {
        namespace domain #F2F2F2 {
            class connection <<struct>> {
                +id : boost::uuids::uuid
                +folder_id : optional<boost::uuids::uuid>
                +environment_id : optional<boost::uuids::uuid>
                +name : string
                +host : optional<string>
                +port : optional<int>
                +username : string
                +encrypted_password : string
                +description : string
            }
            class connection_tag <<struct>> {
                +connection_id : boost::uuids::uuid
                +tag_id : boost::uuids::uuid
            }
            class environment <<struct>> {
                +id : boost::uuids::uuid
                +folder_id : optional<boost::uuids::uuid>
                +name : string
                +host : string
                +description : string
                +subject_prefix : string
            }
            class environment_tag <<struct>> {
                +environment_id : boost::uuids::uuid
                +tag_id : boost::uuids::uuid
            }
            class folder <<struct>> {
                +id : boost::uuids::uuid
                +name : string
                +parent_id : optional<boost::uuids::uuid>
                +description : string
            }
            class recent_party <<struct>> {
                +party_id : boost::uuids::uuid
                +party_name : string
                +last_selected_at : string
            }
            class tag <<struct>> {
                +id : boost::uuids::uuid
                +name : string
            }
        }
        namespace repository #F2F2F2 {
            class connection_entity <<struct>> {
                +tablename : constexpr static const char*
                +id : sqlgen::PrimaryKey<string>
                +folder_id : optional<string>
                +environment_id : optional<string>
                +name : string
                +host : optional<string>
                +port : optional<int>
                +username : string
                +encrypted_password : string
                +description : string
            }
            class connection_mapper {
            }
            class connection_repository {
                -ctx_ : sqlite_context&
            }
            class connection_tag_entity <<struct>> {
                +tablename : constexpr static const char*
                +connection_id : string
                +tag_id : string
            }
            class connection_tag_mapper {
            }
            class connection_tag_repository {
                -ctx_ : sqlite_context&
            }
            class environment_entity <<struct>> {
                +tablename : constexpr static const char*
                +id : sqlgen::PrimaryKey<string>
                +folder_id : optional<string>
                +name : string
                +host : string
                +description : string
                +subject_prefix : string
            }
            class environment_mapper {
            }
            class environment_repository {
                -ctx_ : sqlite_context&
            }
            class environment_tag_entity <<struct>> {
                +tablename : constexpr static const char*
                +environment_id : string
                +tag_id : string
            }
            class environment_tag_mapper {
            }
            class environment_tag_repository {
                -ctx_ : sqlite_context&
            }
            class folder_entity <<struct>> {
                +tablename : constexpr static const char*
                +id : sqlgen::PrimaryKey<string>
                +name : string
                +parent_id : optional<string>
                +description : optional<string>
            }
            class folder_mapper {
            }
            class folder_repository {
                -ctx_ : sqlite_context&
            }
            class recent_party_entity <<struct>> {
                +tablename : constexpr static const char*
                +party_id : sqlgen::PrimaryKey<string>
                +party_name : string
                +last_selected_at : string
            }
            class recent_party_mapper {
            }
            class recent_party_repository {
                -ctx_ : sqlite_context&
            }
            class sqlite_context {
                -db_path_ : filesystem::path
            }
            class tag_entity <<struct>> {
                +tablename : constexpr static const char*
                +id : sqlgen::PrimaryKey<string>
                +name : string
            }
            class tag_mapper {
            }
            class tag_repository {
                -ctx_ : sqlite_context&
            }
        }
        namespace service #F2F2F2 {
            class connection_manager {
                -ctx_ : repository::sqlite_context
                -folder_repo_ : repository::folder_repository
                -tag_repo_ : repository::tag_repository
                -conn_repo_ : repository::connection_repository
                -conn_tag_repo_ : repository::connection_tag_repository
                -env_repo_ : repository::environment_repository
                -env_tag_repo_ : repository::environment_tag_repository
                -recent_party_repo_ : repository::recent_party_repository
                -master_password_ : string
            }
        }
    }
}

' --- manual: everything below this line is hand-authored; the script preserves it ---

' Local Variables:
' compile-command: "java -Djava.awt.headless=true -DPLANTUML_SECURITY_PROFILE=UNSECURE -DPLANTUML_LIMIT_SIZE=65535 -jar /usr/share/plantuml/plantuml.jar ores.connections.puml"
' End:
@enduml
